In [4]:
import numpy as np
import pandas as pd

df = pd.DataFrame(
    [[0, 0, 0],
     [0, 1, 1],
     [1, 0, 1],
     [1, 1, 0]],
     columns=["A", "B", "C"]
)

L = np.c_[np.c_[df, df].reshape(-1, df.shape[1]),
          np.mod(np.arange(df.shape[0] * 2), 2)]

L = np.c_[L, np.c_[[c ^ L.T[-1] for c in L.T[:-1]]].T]

df = pd.DataFrame(L)
df.columns = (df.columns + 65).map(chr)
df

   A  B  C  D  E  F  G
0  0  0  0  0  0  0  0
1  0  0  0  1  1  1  1
2  0  1  1  0  0  1  1
3  0  1  1  1  1  0  0
4  1  0  1  0  1  0  1
5  1  0  1  1  0  1  0
6  1  1  0  0  1  1  0
7  1  1  0  1  0  0  1

In [1]:
import numpy as np
import pandas as pd

df = pd.DataFrame(
    [[0, 0, 0],
     [0, 1, 1],
     [1, 0, 1],
     [1, 1, 0]],
     columns=["A", "B", "C"]
)
df

   A  B  C
0  0  0  0
1  0  1  1
2  1  0  1
3  1  1  0

In [2]:
np.c_[df, df]

array([[0, 0, 0, 0, 0, 0],
       [0, 1, 1, 0, 1, 1],
       [1, 0, 1, 1, 0, 1],
       [1, 1, 0, 1, 1, 0]])

In [3]:
np.c_[df, df].reshape(-1, df.shape[1])

array([[0, 0, 0],
       [0, 0, 0],
       [0, 1, 1],
       [0, 1, 1],
       [1, 0, 1],
       [1, 0, 1],
       [1, 1, 0],
       [1, 1, 0]])

In [4]:
df.shape

(4, 3)

In [5]:
df.shape[0]

4

In [6]:
df.shape[1]

3

In [7]:
np.mod(np.arange(df.shape[0] *2), 2)

array([0, 1, 0, 1, 0, 1, 0, 1])

In [8]:
L = np.c_[np.c_[df, df].reshape(-1, df.shape[1]),
          np.mod(np.arange(df.shape[0] * 2), 2)]

In [9]:
L

array([[0, 0, 0, 0],
       [0, 0, 0, 1],
       [0, 1, 1, 0],
       [0, 1, 1, 1],
       [1, 0, 1, 0],
       [1, 0, 1, 1],
       [1, 1, 0, 0],
       [1, 1, 0, 1]])

In [10]:
[c ^ L.T[-1] for c in L.T[:-1]]

[array([0, 1, 0, 1, 1, 0, 1, 0]),
 array([0, 1, 1, 0, 0, 1, 1, 0]),
 array([0, 1, 1, 0, 1, 0, 0, 1])]

In [11]:
L = np.c_[L, np.c_[[c ^ L.T[-1] for c in L.T[:-1]]].T]
L

array([[0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 1, 1, 1],
       [0, 1, 1, 0, 0, 1, 1],
       [0, 1, 1, 1, 1, 0, 0],
       [1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 1, 0, 1, 0],
       [1, 1, 0, 0, 1, 1, 0],
       [1, 1, 0, 1, 0, 0, 1]])

In [14]:
df = pd.DataFrame(L)
df.columns = (df.columns + 65).map(chr)
df

   A  B  C  D  E  F  G
0  0  0  0  0  0  0  0
1  0  0  0  1  1  1  1
2  0  1  1  0  0  1  1
3  0  1  1  1  1  0  0
4  1  0  1  0  1  0  1
5  1  0  1  1  0  1  0
6  1  1  0  0  1  1  0
7  1  1  0  1  0  0  1

In [15]:
# 次のコードを書いて、右端の [0,1,0,1,...] の列だけ表示してください。
# 条件：
# 元の df は問題文と同じ
# 結果を変数 last_col に入れる

import numpy as np
import pandas as pd

df = pd.DataFrame(
    [[0, 0, 0],
     [0, 1, 1],
     [1, 0, 1],
     [1, 1, 0]],
    columns=["A", "B", "C"]
)
last_col = np.mod(np.arange(df.shape[0] * 2), 2)
last_col

array([0, 1, 0, 1, 0, 1, 0, 1])

In [17]:
# 問題2
# 次のコードを書いて、L.T[-1] の中身を表示してください。

import numpy as np
import pandas as pd

df = pd.DataFrame(
    [[0, 0, 0],
     [0, 1, 1],
     [1, 0, 1],
     [1, 1, 0]],
     columns=["A", "B", "C"]
)

L = np.c_[np.c_[df, df].reshape(-1, df.shape[1]),
          np.mod(np.arange(df.shape[0] * 2), 2)]
L.T[-1]

array([0, 1, 0, 1, 0, 1, 0, 1])

In [19]:
# 問題3
# 次のコードを書いて、XOR の結果として作られる3列だけを表示してください。
import numpy as np
import pandas as pd

df = pd.DataFrame(
    [[0, 0, 0],
     [0, 1, 1],
     [1, 0, 1],
     [1, 1, 0]],
     columns=["A", "B", "C"]
)

L = np.c_[np.c_[df, df].reshape(-1, df.shape[1]),
          np.mod(np.arange(df.shape[0] * 2), 2)]

xor_cols = np.c_[[c ^ L.T[-1] for c in L.T[:-1]]].T
xor_cols

array([[0, 0, 0],
       [1, 1, 1],
       [0, 1, 1],
       [1, 0, 0],
       [1, 0, 1],
       [0, 1, 0],
       [1, 1, 0],
       [0, 0, 1]])