###### 129_1_quality_rate_check_practice

In [1]:
#cell1

import pandas as pd

In [2]:

#cell2

df = pd.DataFrame(
    [
        ["Q001", "J69P", "MELMB", "Line1", 1200, 3],
        ["Q002", "J69P", "WSE", "Line2", 980, -2],
        ["Q003", "310D", "GSE", "Line1", -500, 1],
        ["Q004", "310D", "ISE", "Line2", 760, 0],
        ["Q005", "J69P", "MELMB", "Line1", 1100, 5],
        ["Q006", "310D", "WSE", "Line2", 850, -1],
        ["Q007", "J69P", "GSE", "Line1", 920, 2],
        ["Q008", "310D", "MELMB", "Line2", 0, 1],
        ["Q009", "J69P", "ISE", "Line1", 1500, 8],
        ["Q010", "310D", "GSE", "Line2", 1300, 2],
    ],
    columns=[
        "check_id",
        "project",
        "site",
        "line",
        "inspection_qty",
        "defect_qty",
    ],
)
df

  check_id project   site   line  inspection_qty  defect_qty
0     Q001    J69P  MELMB  Line1            1200           3
1     Q002    J69P    WSE  Line2             980          -2
2     Q003    310D    GSE  Line1            -500           1
3     Q004    310D    ISE  Line2             760           0
4     Q005    J69P  MELMB  Line1            1100           5
5     Q006    310D    WSE  Line2             850          -1
6     Q007    J69P    GSE  Line1             920           2
7     Q008    310D  MELMB  Line2               0           1
8     Q009    J69P    ISE  Line1            1500           8
9     Q010    310D    GSE  Line2            1300           2

In [3]:
df["defect_qty_fixed"] = df["defect_qty"].where(
    df["defect_qty"] >= 0,
    0,
)
df

  check_id project   site   line  inspection_qty  defect_qty  defect_qty_fixed
0     Q001    J69P  MELMB  Line1            1200           3                 3
1     Q002    J69P    WSE  Line2             980          -2                 0
2     Q003    310D    GSE  Line1            -500           1                 1
3     Q004    310D    ISE  Line2             760           0                 0
4     Q005    J69P  MELMB  Line1            1100           5                 5
5     Q006    310D    WSE  Line2             850          -1                 0
6     Q007    J69P    GSE  Line1             920           2                 2
7     Q008    310D  MELMB  Line2               0           1                 1
8     Q009    J69P    ISE  Line1            1500           8                 8
9     Q010    310D    GSE  Line2            1300           2                 2

In [4]:
df["inspection_qty_fixed"] = df["inspection_qty"].where(
    df["inspection_qty"] >= 0,
    0,
)
df

,check_id,project,site,line,inspection_qty,defect_qty,defect_qty_fixed,inspection_qty_fixed
0,Q001,J69P,MELMB,Line1,1200,3,3,1200
1,Q002,J69P,WSE,Line2,980,-2,0,980
2,Q003,310D,GSE,Line1,-500,1,1,0
3,Q004,310D,ISE,Line2,760,0,0,760
4,Q005,J69P,MELMB,Line1,1100,5,5,1100
5,Q006,310D,WSE,Line2,850,-1,0,850
6,Q007,J69P,GSE,Line1,920,2,2,920
7,Q008,310D,MELMB,Line2,0,1,1,0
8,Q009,J69P,ISE,Line1,1500,8,8,1500
9,Q010,310D,GSE,Line2,1300,2,2,1300

In [15]:
df["defect_rate_safe"] = (
    df["defect_qty_fixed"] / df["inspection_qty_fixed"]
).where(
    df["inspection_qty_fixed"] > 0,
    0,
)
df

,check_id,project,site,line,inspection_qty,defect_qty,defect_qty_fixed,inspection_qty_fixed,defect_rate_safe,check_result
0,Q001,J69P,MELMB,Line1,1200,3,3,1200,0.002500,通常
1,Q002,J69P,WSE,Line2,980,-2,0,980,0.000000,通常
2,Q003,310D,GSE,Line1,-500,1,1,0,0.000000,通常
3,Q004,310D,ISE,Line2,760,0,0,760,0.000000,通常
4,Q005,J69P,MELMB,Line1,1100,5,5,1100,0.004545,通常
5,Q006,310D,WSE,Line2,850,-1,0,850,0.000000,通常
6,Q007,J69P,GSE,Line1,920,2,2,920,0.002174,通常
7,Q008,310D,MELMB,Line2,0,1,1,0,0.000000,通常
8,Q009,J69P,ISE,Line1,1500,8,8,1500,0.005333,通常
9,Q010,310D,GSE,Line2,1300,2,2,1300,0.001538,通常

In [17]:
df["check_result"] = "通常"

df["check_result"] = df["check_result"].where(
    df["defect_rate_safe"] <= 0.003,
    "要確認",
)
df

,check_id,project,site,line,inspection_qty,defect_qty,defect_qty_fixed,inspection_qty_fixed,defect_rate_safe,check_result
0,Q001,J69P,MELMB,Line1,1200,3,3,1200,0.002500,通常
1,Q002,J69P,WSE,Line2,980,-2,0,980,0.000000,通常
2,Q003,310D,GSE,Line1,-500,1,1,0,0.000000,通常
3,Q004,310D,ISE,Line2,760,0,0,760,0.000000,通常
4,Q005,J69P,MELMB,Line1,1100,5,5,1100,0.004545,要確認
5,Q006,310D,WSE,Line2,850,-1,0,850,0.000000,通常
6,Q007,J69P,GSE,Line1,920,2,2,920,0.002174,通常
7,Q008,310D,MELMB,Line2,0,1,1,0,0.000000,通常
8,Q009,J69P,ISE,Line1,1500,8,8,1500,0.005333,要確認
9,Q010,310D,GSE,Line2,1300,2,2,1300,0.001538,通常