In [1]:
import pandas as pd

anime_xlsx = "dataset/anime.xlsx"

df = pd.read_excel(anime_xlsx, index_col=0)
df.head()

,anime_id,name,genre,type,episodes,rating,members
9,15417,Gintama&#039;: Enchousen,"Action, Comedy, Historical, Parody, Samurai, S...",TV,13,9.11,81109
15,199,Sen to Chihiro no Kamikakushi,"Adventure, Drama, Supernatural",Movie,1,8.93,466254
18,12355,Ookami Kodomo no Ame to Yuki,"Fantasy, Slice of Life",Movie,1,8.84,226193
23,30276,One Punch Man,"Action, Comedy, Parody, Sci-Fi, Seinen, Super ...",TV,12,8.82,552458
31,32983,Natsume Yuujinchou Go,"Drama, Fantasy, Shoujo, Slice of Life, Superna...",TV,13,8.76,38865

In [2]:
df.mean(numeric_only=True)

anime_id    15047.053410
rating          6.476230
members     18528.328088
dtype: float64

In [3]:
df["rating"].mean()

np.float64(6.476229985443959)

In [7]:
df["members"].median()

np.float64(1139.0)

In [5]:
df.describe().round(1)

       anime_id  rating   members
count    2097.0  2061.0    2097.0
mean    15047.1     6.5   18528.3
std     11538.8     1.1   57745.3
min        19.0     2.7      13.0
25%      3935.0     5.8     158.0
50%     12279.0     6.6    1139.0
75%     26103.0     7.2    8491.0
max     34514.0    10.0  624055.0

## 練習問題

In [8]:
import pandas as pd

anime_xlsx = "dataset/anime.xlsx"
df = pd.read_excel(anime_xlsx, index_col=0)
df.head()

,anime_id,name,genre,type,episodes,rating,members
9,15417,Gintama&#039;: Enchousen,"Action, Comedy, Historical, Parody, Samurai, S...",TV,13,9.11,81109
15,199,Sen to Chihiro no Kamikakushi,"Adventure, Drama, Supernatural",Movie,1,8.93,466254
18,12355,Ookami Kodomo no Ame to Yuki,"Fantasy, Slice of Life",Movie,1,8.84,226193
23,30276,One Punch Man,"Action, Comedy, Parody, Sci-Fi, Seinen, Super ...",TV,12,8.82,552458
31,32983,Natsume Yuujinchou Go,"Drama, Fantasy, Shoujo, Slice of Life, Superna...",TV,13,8.76,38865

In [9]:
df.mean(numeric_only=True)

anime_id    15047.053410
rating          6.476230
members     18528.328088
dtype: float64

In [10]:
df["rating"].mean()

np.float64(6.476229985443959)

In [11]:
df["members"].median()

np.float64(1139.0)

In [12]:
df.describe().round(2)

       anime_id   rating    members
count   2097.00  2061.00    2097.00
mean   15047.05     6.48   18528.33
std    11538.85     1.07   57745.34
min       19.00     2.67      13.00
25%     3935.00     5.83     158.00
50%    12279.00     6.58    1139.00
75%    26103.00     7.22    8491.00
max    34514.00    10.00  624055.00

## 練習問題2

In [13]:
import pandas as pd

ax = "dataset/anime.xlsx"
df = pd.read_excel(ax, index_col=0)
df.head()

,anime_id,name,genre,type,episodes,rating,members
9,15417,Gintama&#039;: Enchousen,"Action, Comedy, Historical, Parody, Samurai, S...",TV,13,9.11,81109
15,199,Sen to Chihiro no Kamikakushi,"Adventure, Drama, Supernatural",Movie,1,8.93,466254
18,12355,Ookami Kodomo no Ame to Yuki,"Fantasy, Slice of Life",Movie,1,8.84,226193
23,30276,One Punch Man,"Action, Comedy, Parody, Sci-Fi, Seinen, Super ...",TV,12,8.82,552458
31,32983,Natsume Yuujinchou Go,"Drama, Fantasy, Shoujo, Slice of Life, Superna...",TV,13,8.76,38865

In [14]:
df["rating"].mean()

np.float64(6.476229985443959)

In [15]:
df["rating"].median()

np.float64(6.58)