###### 128_5_real_quality_cross_tab_practice

In [2]:
import pandas as pd

In [3]:
df_defect = pd.DataFrame(
    [
        ["D001", "MELMB", "LCM-A", "J69P", "コイル", "RH Lo不灯", "2026-06-01"],
        ["D002", "MELMB", "LCM-A", "J69P", "コイル", "RH Hi/Lo不灯", "2026-06-02"],
        ["D003", "MELMB", "LCM-B", "J69P", "Buck-IC", "RH Lo不灯", "2026-06-03"],
        ["D004", "MELMB", "LCM-C", "310D", "NTF", "再現せず", "2026-06-03"],
        ["D005", "MELMB", "LCM-B", "310D", "はんだ", "点灯不安定", "2026-06-04"],
        ["D006", "MELMB", "LCM-A", "J69P", "コイル", "RH Lo不灯", "2026-06-05"],

        ["D007", "WSE", "LCM-A", "J69P", "コイル", "RH Lo不灯", "2026-06-01"],
        ["D008", "WSE", "LCM-B", "J69P", "Buck-IC", "全灯火不点灯", "2026-06-02"],
        ["D009", "WSE", "LCM-B", "J69P", "Buck-IC", "RH Lo不灯", "2026-06-03"],
        ["D010", "WSE", "LCM-C", "310D", "異物", "点灯不安定", "2026-06-04"],
        ["D011", "WSE", "LCM-C", "310D", "異物", "点灯不安定", "2026-06-05"],
        ["D012", "WSE", "LCM-D", "310D", "NTF", "再現せず", "2026-06-06"],

        ["D013", "GSE", "LCM-A", "J69P", "コイル", "RH Hi/Lo不灯", "2026-06-01"],
        ["D014", "GSE", "LCM-A", "J69P", "コイル", "RH Lo不灯", "2026-06-02"],
        ["D015", "GSE", "LCM-B", "J69P", "Buck-IC", "全灯火不点灯", "2026-06-03"],
        ["D016", "GSE", "LCM-C", "310D", "NTF", "再現せず", "2026-06-04"],
        ["D017", "GSE", "LCM-C", "310D", "NTF", "再現せず", "2026-06-05"],
        ["D018", "GSE", "LCM-D", "310D", "異物", "点灯不安定", "2026-06-06"],

        ["D019", "ISE", "LCM-A", "J69P", "コイル", "RH Lo不灯", "2026-06-01"],
        ["D020", "ISE", "LCM-B", "310D", "はんだ", "点灯不安定", "2026-06-02"],
        ["D021", "ISE", "LCM-B", "310D", "はんだ", "点灯不安定", "2026-06-03"],
        ["D022", "ISE", "LCM-C", "310D", "NTF", "再現せず", "2026-06-04"],
        ["D023", "ISE", "LCM-D", "310D", "異物", "点灯不安定", "2026-06-05"],
        ["D024", "ISE", "LCM-D", "310D", "異物", "点灯不安定", "2026-06-06"],

        ["D025", "MELMB", "LCM-A", "J69P", "コイル", "RH Lo不灯", "2026-06-07"],
        ["D026", "MELMB", "LCM-A", "J69P", "コイル", "RH Hi/Lo不灯", "2026-06-08"],
        ["D027", "WSE", "LCM-B", "J69P", "Buck-IC", "RH Lo不灯", "2026-06-08"],
        ["D028", "GSE", "LCM-A", "J69P", "コイル", "RH Lo不灯", "2026-06-09"],
        ["D029", "ISE", "LCM-D", "310D", "異物", "点灯不安定", "2026-06-09"],
        ["D030", "WSE", "LCM-C", "310D", "異物", "点灯不安定", "2026-06-10"],
    ],
    columns=[
        "defect_id",
        "site",
        "product",
        "project",
        "defect_category",
        "symptom",
        "occ_data",
    ],
)
df_defect.head()

  defect_id   site product project defect_category     symptom    occ_data
0      D001  MELMB   LCM-A    J69P             コイル     RH Lo不灯  2026-06-01
1      D002  MELMB   LCM-A    J69P             コイル  RH Hi/Lo不灯  2026-06-02
2      D003  MELMB   LCM-B    J69P         Buck-IC     RH Lo不灯  2026-06-03
3      D004  MELMB   LCM-C    310D             NTF        再現せず  2026-06-03
4      D005  MELMB   LCM-B    310D             はんだ       点灯不安定  2026-06-04

In [4]:
df_site_master = pd.DataFrame(
    [
        ["MELMB", "メルモビ", "品質保証1課", "重点監視"],
        ["WSE", "中国WSE", "品質保証2課", "重点監視"],
        ["GSE", "中国GSE", "品質保証2課", "通常監視"],
        ["ISE", "日本ISE", "品質保証1課", "通常監視"],
    ],
    columns=[
        "site",
        "site_name",
        "owner_department",
        "monitoring_level",
    ],
)
df_site_master.head()

    site site_name owner_department monitoring_level
0  MELMB      メルモビ           品質保証1課             重点監視
1    WSE     中国WSE           品質保証2課             重点監視
2    GSE     中国GSE           品質保証2課             通常監視
3    ISE     日本ISE           品質保証1課             通常監視

In [5]:
df_cross = df_defect.pivot_table(
    values="defect_id",
    index="site",
    columns="defect_category",
    aggfunc="count",
    fill_value=0,
)
df_cross

defect_category  Buck-IC  NTF  はんだ  コイル  異物
site
GSE                    1    2    0    3   1
ISE                    0    1    2    1   3
MELMB                  1    1    1    5   0
WSE                    3    1    0    1   3

In [8]:
df_cross = df_cross[
    [
        "Buck-IC",
        "NTF",
        "はんだ",
        "コイル",
        "異物",
    ]
]
df_cross

defect_category  Buck-IC  NTF  はんだ  コイル  異物
site
GSE                    1    2    0    3   1
ISE                    0    1    2    1   3
MELMB                  1    1    1    5   0
WSE                    3    1    0    1   3

In [10]:
df_cross["total"] = df_cross.sum(axis=1)
df_cross

defect_category  Buck-IC  NTF  はんだ  コイル  異物  total
site
GSE                    1    2    0    3   1     14
ISE                    0    1    2    1   3     14
MELMB                  1    1    1    5   0     16
WSE                    3    1    0    1   3     16

In [12]:
df_cross_sort = df_cross.sort_values(
    "total",
    ascending=False,
)
df_cross_sort

defect_category  Buck-IC  NTF  はんだ  コイル  異物  total
site
WSE                    3    1    0    1   3     16
MELMB                  1    1    1    5   0     16
ISE                    0    1    2    1   3     14
GSE                    1    2    0    3   1     14

In [13]:
df_cross_sort = df_cross_sort.reset_index()

In [14]:
df_cross_sort

defect_category   site  Buck-IC  NTF  はんだ  コイル  異物  total
0                  WSE        3    1    0    1   3     16
1                MELMB        1    1    1    5   0     16
2                  ISE        0    1    2    1   3     14
3                  GSE        1    2    0    3   1     14

In [15]:
df_merge = df_cross_sort.merge(
    df_site_master,
    on="site",
)

In [16]:
df_merge

,site,Buck-IC,NTF,はんだ,コイル,異物,total,site_name,owner_department,monitoring_level
0,WSE,3,1,0,1,3,16,中国WSE,品質保証2課,重点監視
1,MELMB,1,1,1,5,0,16,メルモビ,品質保証1課,重点監視
2,ISE,0,1,2,1,3,14,日本ISE,品質保証1課,通常監視
3,GSE,1,2,0,3,1,14,中国GSE,品質保証2課,通常監視

In [18]:
df_report = df_merge[
    [
        "owner_department",
        "site_name",
        "site",
        "monitoring_level",
        "Buck-IC",
        "NTF",
        "はんだ",
        "コイル",
        "異物",
        "total",
    ]
].copy()

In [24]:
df_report
df_report["check_level"] = "通常確認"
df_report

df_report.loc[
    df_report["コイル"] >= 4,
    "check_level",
] = "コイル重点確認"
df_report

df_report.loc[
    df_report["Buck-IC"] >= 3,
    "check_level",
] = "Buck-IC重点確認"
df_report

df_report.loc[
    df_report["異物"] >= 3,
    "check_level",
] = "異物重点確認"
df_report

,owner_department,site_name,site,monitoring_level,Buck-IC,NTF,はんだ,コイル,異物,total,check_level
0,品質保証2課,中国WSE,WSE,重点監視,3,1,0,1,3,16,異物重点確認
1,品質保証1課,メルモビ,MELMB,重点監視,1,1,1,5,0,16,コイル重点確認
2,品質保証1課,日本ISE,ISE,通常監視,0,1,2,1,3,14,異物重点確認
3,品質保証2課,中国GSE,GSE,通常監視,1,2,0,3,1,14,通常確認

In [25]:
df_priority = df_report[
    df_report["check_level"] != "通常確認"
]

In [26]:
df_priority

,owner_department,site_name,site,monitoring_level,Buck-IC,NTF,はんだ,コイル,異物,total,check_level
0,品質保証2課,中国WSE,WSE,重点監視,3,1,0,1,3,16,異物重点確認
1,品質保証1課,メルモビ,MELMB,重点監視,1,1,1,5,0,16,コイル重点確認
2,品質保証1課,日本ISE,ISE,通常監視,0,1,2,1,3,14,異物重点確認

In [27]:
df_defect_with_master = df_defect.merge(
    df_site_master,
    on="site",
)

In [29]:
df_defect_with_master.head()

,defect_id,site,product,project,defect_category,symptom,occ_data,site_name,owner_department,monitoring_level
0,D001,MELMB,LCM-A,J69P,コイル,RH Lo不灯,2026-06-01,メルモビ,品質保証1課,重点監視
1,D002,MELMB,LCM-A,J69P,コイル,RH Hi/Lo不灯,2026-06-02,メルモビ,品質保証1課,重点監視
2,D003,MELMB,LCM-B,J69P,Buck-IC,RH Lo不灯,2026-06-03,メルモビ,品質保証1課,重点監視
3,D004,MELMB,LCM-C,310D,NTF,再現せず,2026-06-03,メルモビ,品質保証1課,重点監視
4,D005,MELMB,LCM-B,310D,はんだ,点灯不安定,2026-06-04,メルモビ,品質保証1課,重点監視

In [30]:
df_dept_cross = df_defect_with_master.pivot_table(
    values="defect_id",
    index="owner_department",
    columns="defect_category",
    aggfunc="count",
    fill_value=0
)
df_dept_cross

defect_category   Buck-IC  NTF  はんだ  コイル  異物
owner_department
品質保証1課                  1    2    3    6   3
品質保証2課                  4    3    0    4   4

In [32]:
df_dept_cross = df_dept_cross[
    [
        "Buck-IC",
        "NTF",
        "はんだ",
        "コイル",
        "異物",
    ]
]

In [33]:
df_dept_cross["total"] = df_dept_cross.sum(axis=1)

In [34]:
df_dept_cross

defect_category   Buck-IC  NTF  はんだ  コイル  異物  total
owner_department
品質保証1課                  1    2    3    6   3     15
品質保証2課                  4    3    0    4   4     15