In [3]:
!head -n 5 dataset/review.tsv

'head' �́A�����R�}���h�܂��͊O���R�}���h�A
����\�ȃv���O�����܂��̓o�b�` �t�@�C���Ƃ��ĔF������Ă��܂���B

In [4]:
import pandas as pd

df = pd.read_csv("dataset/review.tsv", encoding="shift_jis", sep="\t")
df.head()

       製品  レビュアー  評価
0   yq310    655   4
1  py-110    115   5
2  PY-220     26   2
3   PY220    760   3
4   YQ330    282   2

In [5]:
df.shape

(300, 3)

In [6]:
df.isna().sum()

製品       0
レビュアー    0
評価       0
dtype: int64

In [7]:
df.isna()

        製品  レビュアー     評価
0    False  False  False
1    False  False  False
2    False  False  False
3    False  False  False
4    False  False  False
..     ...    ...    ...
295  False  False  False
296  False  False  False
297  False  False  False
298  False  False  False
299  False  False  False

[300 rows x 3 columns]

In [8]:
df.isna().sum()

製品       0
レビュアー    0
評価       0
dtype: int64

In [9]:
df.describe()

            レビュアー          評価
count  300.000000  300.000000
mean   511.386667    3.780000
std    296.740358    1.201281
min      1.000000    1.000000
25%    242.750000    3.000000
50%    541.500000    4.000000
75%    760.750000    5.000000
max    998.000000    5.000000

In [11]:
df["製品"].value_counts()

製品
YQ110     29
PY220     22
PY330     21
YQ330     21
PY310     19
PY110     18
YQ220     18
YQ-310    12
YQ310     11
yq110      9
PY-220     9
yq310      9
yq-110     9
py-110     8
py110      7
YQ-110     7
py330      6
PY-330     6
py220      6
PY-310     6
YQ-220     6
yq330      6
py310      6
yq220      5
YQ-330     5
yq-310     3
py-330     3
py-310     3
yq-220     3
PY-110     3
yq-330     2
py-220     2
Name: count, dtype: int64

In [12]:
valid_names = {
    "PY110",
    "PY220",
    "PY310",
    "PY330",
    "YQ110",
    "YQ220",
    "YQ310",
    "YQ330",
}

In [15]:
invalid_df = df[~df["製品"].isin(valid_names)]
invalid_df.shape

(141, 3)

In [19]:
df[~df["製品"].isin(valid_names)]

         製品  レビュアー  評価
0     yq310    655   4
1    py-110    115   5
2    PY-220     26   2
5    yq-330    251   3
6     yq330    229   5
..      ...    ...  ..
291  yq-110    249   4
292   py110    708   5
296  YQ-220    945   4
297  YQ-110    675   4
299   py330    363   4

[141 rows x 3 columns]

In [21]:
invalid_df["製品"].unique()

array(['yq310', 'py-110', 'PY-220', 'yq-330', 'yq330', 'py-220', 'py-330',
       'py-310', 'yq110', 'yq-110', 'YQ-220', 'PY-310', 'py310', 'yq220',
       'YQ-310', 'py330', 'PY-330', 'YQ-110', 'yq-310', 'yq-220',
       'YQ-330', 'py110', 'py220', 'PY-110'], dtype=object)

In [23]:
import pandas as pd
df = pd.read_csv("dataset/review.tsv", encoding="shift_jis", sep="\t")
df.head()

       製品  レビュアー  評価
0   yq310    655   4
1  py-110    115   5
2  PY-220     26   2
3   PY220    760   3
4   YQ330    282   2

In [24]:
df.shape

(300, 3)

In [25]:
df.isna()

        製品  レビュアー     評価
0    False  False  False
1    False  False  False
2    False  False  False
3    False  False  False
4    False  False  False
..     ...    ...    ...
295  False  False  False
296  False  False  False
297  False  False  False
298  False  False  False
299  False  False  False

[300 rows x 3 columns]

In [26]:
df.isna().sum()

製品       0
レビュアー    0
評価       0
dtype: int64

In [27]:
df.describe()

            レビュアー          評価
count  300.000000  300.000000
mean   511.386667    3.780000
std    296.740358    1.201281
min      1.000000    1.000000
25%    242.750000    3.000000
50%    541.500000    4.000000
75%    760.750000    5.000000
max    998.000000    5.000000

In [28]:
df["製品"].value_counts()

製品
YQ110     29
PY220     22
PY330     21
YQ330     21
PY310     19
PY110     18
YQ220     18
YQ-310    12
YQ310     11
yq110      9
PY-220     9
yq310      9
yq-110     9
py-110     8
py110      7
YQ-110     7
py330      6
PY-330     6
py220      6
PY-310     6
YQ-220     6
yq330      6
py310      6
yq220      5
YQ-330     5
yq-310     3
py-330     3
py-310     3
yq-220     3
PY-110     3
yq-330     2
py-220     2
Name: count, dtype: int64

In [29]:
valid_names = {
    "PY110",
    "PY220",
    "PY310",
    "PY330",
    "YQ110",
    "YQ220",
    "YQ310",
    "YQ330",
}

In [30]:
invalid_df = df[~df["製品"].isin(valid_names)]
invalid_df.shape

(141, 3)

In [31]:
invalid_df["製品"].unique()

array(['yq310', 'py-110', 'PY-220', 'yq-330', 'yq330', 'py-220', 'py-330',
       'py-310', 'yq110', 'yq-110', 'YQ-220', 'PY-310', 'py310', 'yq220',
       'YQ-310', 'py330', 'PY-330', 'YQ-110', 'yq-310', 'yq-220',
       'YQ-330', 'py110', 'py220', 'PY-110'], dtype=object)