In [3]:
import pandas as pd
df = pd.read_table("dataset/review_after.tsv", encoding="shift_jis")
grouped = df.groupby(["シリーズ名", "バージョン番号"])
agg_df = grouped["評価"].agg(["mean", "size"])
agg_df = agg_df.rename(columns={"mean":"評価の平均", "size":"レビュー件数"})
agg_df["全体順位"] = agg_df["評価の平均"].rank(ascending=False)
agg_df

                  評価の平均  レビュー件数  全体順位
シリーズ名 バージョン番号
PY    110      4.112245      98   1.0
      220      3.598291     117   6.0
      310      3.767045     176   3.0
      330      3.246914      81   8.0
YQ    110      3.694611     167   5.0
      220      3.760618     259   4.0
      310      3.474576     177   7.0
      330      4.007194     139   2.0

In [4]:
import pandas as pd
df = pd.read_table("dataset/review_after.tsv", encoding="shift_jis")
df.head()

      製品  レビュアー  評価 シリーズ名  バージョン番号
0  PY110      1   4    PY      110
1  PY110      2   4    PY      110
2  PY110      3   4    PY      110
3  PY110      4   4    PY      110
4  PY110      5   4    PY      110

In [6]:
grouped  = df.groupby(["シリーズ名", "バージョン番号"])
grouped

In [7]:
agg_df = grouped["評価"].agg(["mean", "size"])
agg_df

                   mean  size
シリーズ名 バージョン番号
PY    110      4.112245    98
      220      3.598291   117
      310      3.767045   176
      330      3.246914    81
YQ    110      3.694611   167
      220      3.760618   259
      310      3.474576   177
      330      4.007194   139

In [8]:
agg_df = agg_df.rename(columns={"mean": "評価の平均", "size": "レビュー"})
agg_df

                  評価の平均  レビュー
シリーズ名 バージョン番号
PY    110      4.112245    98
      220      3.598291   117
      310      3.767045   176
      330      3.246914    81
YQ    110      3.694611   167
      220      3.760618   259
      310      3.474576   177
      330      4.007194   139

In [10]:
agg_df["全体順位"] = agg_df["評価の平均"].rank(ascending=False)
agg_df

                  評価の平均  レビュー  全体順位
シリーズ名 バージョン番号
PY    110      4.112245    98   1.0
      220      3.598291   117   6.0
      310      3.767045   176   3.0
      330      3.246914    81   8.0
YQ    110      3.694611   167   5.0
      220      3.760618   259   4.0
      310      3.474576   177   7.0
      330      4.007194   139   2.0

In [11]:
import pandas as pd
df = pd.read_table("dataset/review_after.tsv", encoding="shift_jis")
df.head()

      製品  レビュアー  評価 シリーズ名  バージョン番号
0  PY110      1   4    PY      110
1  PY110      2   4    PY      110
2  PY110      3   4    PY      110
3  PY110      4   4    PY      110
4  PY110      5   4    PY      110

In [13]:
grouped = df.groupby(["シリーズ名","バージョン番号"])
grouped

In [14]:
agg_df = grouped["評価"].agg(["mean", "size"])
agg_df

                   mean  size
シリーズ名 バージョン番号
PY    110      4.112245    98
      220      3.598291   117
      310      3.767045   176
      330      3.246914    81
YQ    110      3.694611   167
      220      3.760618   259
      310      3.474576   177
      330      4.007194   139

In [15]:
agg_df = agg_df.rename(columns={"mean": "評価の平均", "size": "レビュー件数"})
agg_df

                  評価の平均  レビュー件数
シリーズ名 バージョン番号
PY    110      4.112245      98
      220      3.598291     117
      310      3.767045     176
      330      3.246914      81
YQ    110      3.694611     167
      220      3.760618     259
      310      3.474576     177
      330      4.007194     139

In [16]:
agg_df["全体順位"] = agg_df["評価の平均"].rank(ascending=False)
agg_df

                  評価の平均  レビュー件数  全体順位
シリーズ名 バージョン番号
PY    110      4.112245      98   1.0
      220      3.598291     117   6.0
      310      3.767045     176   3.0
      330      3.246914      81   8.0
YQ    110      3.694611     167   5.0
      220      3.760618     259   4.0
      310      3.474576     177   7.0
      330      4.007194     139   2.0

In [17]:
agg_df2 = grouped["評価"].agg(["mean", "size", "sum"])
agg_df2

                   mean  size  sum
シリーズ名 バージョン番号
PY    110      4.112245    98  403
      220      3.598291   117  421
      310      3.767045   176  663
      330      3.246914    81  263
YQ    110      3.694611   167  617
      220      3.760618   259  974
      310      3.474576   177  615
      330      4.007194   139  557

In [18]:
agg_df["件数順位"] = agg_df["レビュー件数"].rank(ascending=False)
agg_df

                  評価の平均  レビュー件数  全体順位  件数順位
シリーズ名 バージョン番号
PY    110      4.112245      98   1.0   7.0
      220      3.598291     117   6.0   6.0
      310      3.767045     176   3.0   3.0
      330      3.246914      81   8.0   8.0
YQ    110      3.694611     167   5.0   4.0
      220      3.760618     259   4.0   1.0
      310      3.474576     177   7.0   2.0
      330      4.007194     139   2.0   5.0

In [19]:
series_df = df.groupby("シリーズ名")["評価"].mean()
series_df

シリーズ名
PY    3.707627
YQ    3.723720
Name: 評価, dtype: float64

In [20]:
agg_df["全体順位_int"] = agg_df["全体順位"].astype(int)
agg_df

                  評価の平均  レビュー件数  全体順位  件数順位  全体順位_int
シリーズ名 バージョン番号
PY    110      4.112245      98   1.0   7.0         1
      220      3.598291     117   6.0   6.0         6
      310      3.767045     176   3.0   3.0         3
      330      3.246914      81   8.0   8.0         8
YQ    110      3.694611     167   5.0   4.0         5
      220      3.760618     259   4.0   1.0         4
      310      3.474576     177   7.0   2.0         7
      330      4.007194     139   2.0   5.0         2