In [4]:
import pandas as pd
#　データの読み込み
df = pd.read_table("dataset/review.tsv", encoding="shift_jis")
df.shape
# ---------------------------
# （1）表記揺れの修正
# ---------------------------
df["製品"] = df["製品"].str.upper()
df["製品"] = df["製品"].str.replace("-", "", regex=False)
df

        製品  レビュアー  評価
0    YQ310    655   4
1    PY110    115   5
2    PY220     26   2
3    PY220    760   3
4    YQ330    282   2
..     ...    ...  ..
295  PY310     97   2
296  YQ220    945   4
297  YQ110    675   4
298  PY220    442   5
299  PY330    363   4

[300 rows x 3 columns]

In [5]:
valid_names = {
    "PY110",
    "PY220",
    "PY310",
    "PY330",
    "YQ110",
    "YQ220",
    "YQ310",
    "YQ330",
}

In [6]:
invalid_df = df[~df["製品"].isin(valid_names)]

In [7]:
df["シリーズ名"] = df["製品"].str[:2]

In [8]:
df["バージョン番号"] = df["製品"].str[2:]

In [9]:
df.head()

      製品  レビュアー  評価 シリーズ名 バージョン番号
0  YQ310    655   4    YQ     310
1  PY110    115   5    PY     110
2  PY220     26   2    PY     220
3  PY220    760   3    PY     220
4  YQ330    282   2    YQ     330

In [10]:
import pandas as pd
df = pd.read_table("dataset/review.tsv", encoding="shift_jis")
df.head()

       製品  レビュアー  評価
0   yq310    655   4
1  py-110    115   5
2  PY-220     26   2
3   PY220    760   3
4   YQ330    282   2

In [14]:
df["製品"] = df["製品"].str.upper()
df["製品"] = df["製品"].str.replace("-", "", regex=False)
df

        製品  レビュアー  評価
0    YQ310    655   4
1    PY110    115   5
2    PY220     26   2
3    PY220    760   3
4    YQ330    282   2
..     ...    ...  ..
295  PY310     97   2
296  YQ220    945   4
297  YQ110    675   4
298  PY220    442   5
299  PY330    363   4

[300 rows x 3 columns]

In [15]:
valid_names = {
    "PY110",
    "PY220",
    "PY310",
    "PY330",
    "YQ110",
    "YQ220",
    "YQ310",
    "YQ330",
}

In [17]:
# 問題5
invalid_df = df[~df["製品"].isin(valid_names)]
invalid_df.shape

(0, 3)

In [18]:
df["シリーズ名"] = df["製品"].str[:2]
df.head()

      製品  レビュアー  評価 シリーズ名
0  YQ310    655   4    YQ
1  PY110    115   5    PY
2  PY220     26   2    PY
3  PY220    760   3    PY
4  YQ330    282   2    YQ

In [21]:

df["バージョン番号"] = df["製品"].str[2:]
df.head()

      製品  レビュアー  評価 シリーズ名 バージョン番号
0  YQ310    655   4    YQ     310
1  PY110    115   5    PY     110
2  PY220     26   2    PY     220
3  PY220    760   3    PY     220
4  YQ330    282   2    YQ     330

In [22]:
df["シリーズ名"].unique
df

        製品  レビュアー  評価 シリーズ名 バージョン番号
0    YQ310    655   4    YQ     310
1    PY110    115   5    PY     110
2    PY220     26   2    PY     220
3    PY220    760   3    PY     220
4    YQ330    282   2    YQ     330
..     ...    ...  ..   ...     ...
295  PY310     97   2    PY     310
296  YQ220    945   4    YQ     220
297  YQ110    675   4    YQ     110
298  PY220    442   5    PY     220
299  PY330    363   4    PY     330

[300 rows x 5 columns]

In [23]:
df["バージョン番号"].unique()

array(['310', '110', '220', '330'], dtype=object)

In [24]:
df["製品"].value_counts()

製品
YQ110    54
PY220    39
PY330    36
PY110    36
YQ310    35
YQ330    34
PY310    34
YQ220    32
Name: count, dtype: int64

In [26]:
py_df = df[df["シリーズ名"] == "PY"]
py_df.head()

      製品  レビュアー  評価 シリーズ名 バージョン番号
1  PY110    115   5    PY     110
2  PY220     26   2    PY     220
3  PY220    760   3    PY     220
7  PY220    143   1    PY     220
8  PY110    755   5    PY     110