###### 133_4_display_dataframe_mid_cell.ipynb

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv(
    "dataset/score.csv",
)
display(df)

    生徒ID  国語   数学  理科  社会
0  ST001  70   97  80  78
1  ST002  68   89  78  92
2  ST003  88   92  90  98
3  ST004  71  100  79  68
4  ST005  73   87  65  60

In [4]:
score_cols = ["国語", "数学", "理科", "社会"]

In [5]:
for column in score_cols:
    filtered_df = df[df[column] >= 90]

    print(f"==={column}が90点以上の生徒===")
    display(filtered_df)

===国語が90点以上の生徒===

Empty DataFrame
Columns: [生徒ID, 国語, 数学, 理科, 社会]
Index: []

===数学が90点以上の生徒===

    生徒ID  国語   数学  理科  社会
0  ST001  70   97  80  78
2  ST003  88   92  90  98
3  ST004  71  100  79  68

===理科が90点以上の生徒===

    生徒ID  国語  数学  理科  社会
2  ST003  88  92  90  98

===社会が90点以上の生徒===

    生徒ID  国語  数学  理科  社会
1  ST002  68  89  78  92
2  ST003  88  92  90  98