###### 129_3_fill_missing_from_another_column

In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.DataFrame(
    [
        ["Alice", "", 87, 83],
        ["Alice", "", 72, np.nan],
        ["Bob", "", 65, np.nan],
        ["Bob", "", 92, 86],
    ],
    columns=["name", "subject", "point", "last"],
)
df

    name subject  point  last
0  Alice             87  83.0
1  Alice             72   NaN
2    Bob             65   NaN
3    Bob             92  86.0

In [3]:
df["last"] = df["last"].fillna(df["point"])
df

    name subject  point  last
0  Alice             87  83.0
1  Alice             72  72.0
2    Bob             65  65.0
3    Bob             92  86.0