###### 125-3: タブ区切り形式のファイルを読み込むには」

In [1]:
import pandas as pd

df = pd.read_table("dataset/test_score.tsv")
df

    Name Subject  Point
0  Alice      国語     87
1  Alice      数学     72
2    Bob      国語     65
3    Bob      数学     92

In [5]:
import pandas as pd

df_quality = pd.read_table("input/quality_check.tsv")
df_quality

    site product  defect  count
0  MELMB   LCM-A    点灯不良      3
1    WSE   LCM-B    外観不良      5
2    GSE   LCM-C    ショート      1
3    ISE   LCM-D  コネクタ浮き      2

###### TSVから品質危険ランキングを作ろう

In [8]:
import pandas as pd
import numpy as np
import os

os.makedirs("output", exist_ok=True)
df = pd.read_table("input/quality_check_practice.tsv")

In [11]:
df["ppm"] = df["defects"] / df["production"] * 1000000
df["ppm"] = df["ppm"].round(1)

In [12]:
df["判定"]  = np.where(
    df["ppm"] >= 800,
    "危険モンスター",
    "通常モンスター"
)

In [13]:
df_sorted = df.sort_values("ppm", ascending=False)

In [14]:
df_danger = df_sorted[df_sorted["判定"] == "危険モンスター"]

In [19]:
print(df_sorted)
df_sorted.to_csv("output/quality_report.csv", index=False, encoding="utf-8-sig")
print(df_danger)
df_danger.to_csv("output/danger_report.csv", index=False, encoding="utf-8-sig")

df_sorted

         date   site product  defect  production  defects     ppm       判定
5  2026/06/03    WSE   LCM-B    異物混入        7000        7  1000.0  危険モンスター
3  2026/06/02  MELMB   LCM-A    点灯不良       11000        8   727.3  通常モンスター
1  2026/06/01    WSE   LCM-B    外観不良        8000        5   625.0  通常モンスター
7  2026/06/04    GSE   LCM-C    ショート       10000        6   600.0  通常モンスター
0  2026/06/01  MELMB   LCM-A    点灯不良       10000        3   300.0  通常モンスター
6  2026/06/04  MELAC   LCM-E   はんだ不良       15000        4   266.7  通常モンスター
4  2026/06/03    ISE   LCM-D  コネクタ浮き        9000        2   222.2  通常モンスター
2  2026/06/02    GSE   LCM-C    ショート       12000        1    83.3  通常モンスター
         date site product defect  production  defects     ppm       判定
5  2026/06/03  WSE   LCM-B   異物混入        7000        7  1000.0  危険モンスター

         date   site product  defect  production  defects     ppm       判定
5  2026/06/03    WSE   LCM-B    異物混入        7000        7  1000.0  危険モンスター
3  2026/06/02  MELMB   LCM-A    点灯不良       11000        8   727.3  通常モンスター
1  2026/06/01    WSE   LCM-B    外観不良        8000        5   625.0  通常モンスター
7  2026/06/04    GSE   LCM-C    ショート       10000        6   600.0  通常モンスター
0  2026/06/01  MELMB   LCM-A    点灯不良       10000        3   300.0  通常モンスター
6  2026/06/04  MELAC   LCM-E   はんだ不良       15000        4   266.7  通常モンスター
4  2026/06/03    ISE   LCM-D  コネクタ浮き        9000        2   222.2  通常モンスター
2  2026/06/02    GSE   LCM-C    ショート       12000        1    83.3  通常モンスター