###### 129_4_light_duplicate_review

In [1]:
#cell 1
import pandas as pd

In [2]:
#cell 2
df = pd.DataFrame(
    [
         ["S001", "J69P", "MELMB", "OK", "2026-06-02 09:00"],
        ["S002", "J69P", "WSE", "NG", "2026-06-02 09:10"],
        ["S003", "310D", "GSE", "OK", "2026-06-02 09:20"],
        ["S002", "J69P", "WSE", "OK", "2026-06-02 10:00"],
        ["S004", "310D", "MELMB", "OK", "2026-06-02 10:10"],
        ["S005", "J69P", "GSE", "NG", "2026-06-02 10:20"],
        ["S005", "J69P", "GSE", "OK", "2026-06-02 11:00"],
    ],
    columns=[
        "serial_no",
        "project",
        "site",
        "inspection_result",
        "update_time",
    ],
)
df

  serial_no project   site inspection_result       update_time
0      S001    J69P  MELMB                OK  2026-06-02 09:00
1      S002    J69P    WSE                NG  2026-06-02 09:10
2      S003    310D    GSE                OK  2026-06-02 09:20
3      S002    J69P    WSE                OK  2026-06-02 10:00
4      S004    310D  MELMB                OK  2026-06-02 10:10
5      S005    J69P    GSE                NG  2026-06-02 10:20
6      S005    J69P    GSE                OK  2026-06-02 11:00

In [3]:
#cell3
df_work = df.copy()
df_work

  serial_no project   site inspection_result       update_time
0      S001    J69P  MELMB                OK  2026-06-02 09:00
1      S002    J69P    WSE                NG  2026-06-02 09:10
2      S003    310D    GSE                OK  2026-06-02 09:20
3      S002    J69P    WSE                OK  2026-06-02 10:00
4      S004    310D  MELMB                OK  2026-06-02 10:10
5      S005    J69P    GSE                NG  2026-06-02 10:20
6      S005    J69P    GSE                OK  2026-06-02 11:00

In [6]:
#cell4
df_work["update_time"] = pd.to_datetime(
    df_work["update_time"]
)

df_work
df_work["update_time"].dtype

dtype('<M8[ns]')

In [7]:
df_duplicate_check = df_work[
    df_work.duplicated(
        "serial_no",
        keep=False,
    )
].copy
df_duplicate_check

<bound method NDFrame.copy of   serial_no project site inspection_result         update_time
1      S002    J69P  WSE                NG 2026-06-02 09:10:00
3      S002    J69P  WSE                OK 2026-06-02 10:00:00
5      S005    J69P  GSE                NG 2026-06-02 10:20:00
6      S005    J69P  GSE                OK 2026-06-02 11:00:00>

In [8]:
#cell 6
before_count = len(df_work)
before_count

7

In [9]:
df_sort = df_work.sort_values(
    "update_time",
)
df_sort

  serial_no project   site inspection_result         update_time
0      S001    J69P  MELMB                OK 2026-06-02 09:00:00
1      S002    J69P    WSE                NG 2026-06-02 09:10:00
2      S003    310D    GSE                OK 2026-06-02 09:20:00
3      S002    J69P    WSE                OK 2026-06-02 10:00:00
4      S004    310D  MELMB                OK 2026-06-02 10:10:00
5      S005    J69P    GSE                NG 2026-06-02 10:20:00
6      S005    J69P    GSE                OK 2026-06-02 11:00:00

In [10]:
df_result = df_sort.drop_duplicates(
    "serial_no",
    keep="last",
)
df_result

  serial_no project   site inspection_result         update_time
0      S001    J69P  MELMB                OK 2026-06-02 09:00:00
2      S003    310D    GSE                OK 2026-06-02 09:20:00
3      S002    J69P    WSE                OK 2026-06-02 10:00:00
4      S004    310D  MELMB                OK 2026-06-02 10:10:00
6      S005    J69P    GSE                OK 2026-06-02 11:00:00

In [12]:
after_count = len(df_result)
after_count

5

In [ ]:
#cell 10
deleted_count = before_count - after_count
deleted_count

2

In [14]:
#cell 11
df_result_cross = df_result.pivot_table(
    values="serial_no",
    index="site",
    columns="inspection_result",
    aggfunc="count",
    fill_value=0,
)
df_result_cross

inspection_result  OK
site
GSE                 2
MELMB               2
WSE                 1