In [7]:
import pandas as pd

df = pd.read_csv(
    "visitors_sample.csv",
    index_col="日付",
    parse_dates=["日付"]
)
df.head()

            来店者数     売上
日付
2021-01-01   120  85000
2021-01-02    98  72000
2021-01-03   135  91000
2021-01-04   110  83000
2021-01-05    90  69000

In [8]:
monthly = df.resample("ME").sum()
monthly

            来店者数      売上
日付
2021-01-31  1143  825000
2021-02-28  1190  856000
2021-03-31  1398  987000

In [9]:
monthly_mean = df.resample("ME").mean()
monthly_mean

             来店者数       売上
日付
2021-01-31  114.3  82500.0
2021-02-28  119.0  85600.0
2021-03-31  139.8  98700.0

In [10]:
df.resample("ME")["来店者数"].max()

日付
2021-01-31    145
2021-02-28    142
2021-03-31    155
Freq: ME, Name: 来店者数, dtype: int64

In [12]:
df.resample("ME")["売上"].sum()

日付
2021-01-31    825000
2021-02-28    856000
2021-03-31    987000
Freq: ME, Name: 売上, dtype: int64

In [13]:
df.resample("ME").agg(["sum", "mean", "max"])

            来店者数                  売上
             sum   mean  max     sum     mean     max
日付
2021-01-31  1143  114.3  145  825000  82500.0   97000
2021-02-28  1190  119.0  142  856000  85600.0   99000
2021-03-31  1398  139.8  155  987000  98700.0  108000

In [14]:
monthly = df.resample("ME").sum()

In [15]:
monthly["平均売上"] = monthly["売上"] / monthly["来店者数"]
monthly

            来店者数      売上        平均売上
日付
2021-01-31  1143  825000  721.784777
2021-02-28  1190  856000  719.327731
2021-03-31  1398  987000  706.008584

In [17]:
monthly = df.resample("ME").sum()
monthly["不良率"] = monthly["来店者数"] / monthly["売上"]
monthly

            来店者数      売上       不良率
日付
2021-01-31  1143  825000  0.001385
2021-02-28  1190  856000  0.001390
2021-03-31  1398  987000  0.001416