###### 130_2_site_model_defect_category_list_answer.ipynb

In [1]:
import pandas as pd
pd.set_option("display.max_columns", None)

In [2]:
df_plan = pd.DataFrame(
    [
        ["SUS", "J69P", 50000],
        ["SUS", "310D", 30000],
        ["WSE", "310D", 45000],
        ["GSE", "J69P", 32000],
        ["MELMB", "310D", 60000],
        ["ISE", "J69P", 20000],
    ],
    columns=[
        "site",
        "model",
        "plan_qty",
    ],
)
df_plan

    site model  plan_qty
0    SUS  J69P     50000
1    SUS  310D     30000
2    WSE  310D     45000
3    GSE  J69P     32000
4  MELMB  310D     60000
5    ISE  J69P     20000

In [3]:
#cell3
df_defect = pd.DataFrame(
    [
        ["SUS", "J69P", "コイル", 3],
        ["SUS", "J69P", "Buck-IC", 1],
        ["SUS", "J69P", "コイル", 2],
        ["SUS", "310D", "NTF", 1],
        ["WSE", "310D", "コイル", 2],
        ["WSE", "310D", "NTF", 0],
        ["GSE", "J69P", "コイル", 4],
        ["GSE", "J69P", "Buck-IC", 2],
        ["MELMB", "310D", "コイル", 5],
        ["MELMB", "310D", "NTF", 1], 
    ],
    columns=[
        "site",
        "model",
        "defect_category",
        "defect_qty",
    ],
)
df_defect

    site model defect_category  defect_qty
0    SUS  J69P             コイル           3
1    SUS  J69P         Buck-IC           1
2    SUS  J69P             コイル           2
3    SUS  310D             NTF           1
4    WSE  310D             コイル           2
5    WSE  310D             NTF           0
6    GSE  J69P             コイル           4
7    GSE  J69P         Buck-IC           2
8  MELMB  310D             コイル           5
9  MELMB  310D             NTF           1

In [4]:
df_work = df_defect[
    [
        "site",
        "model",
        "defect_category",
        "defect_qty",
    ]
].copy()
df_work

    site model defect_category  defect_qty
0    SUS  J69P             コイル           3
1    SUS  J69P         Buck-IC           1
2    SUS  J69P             コイル           2
3    SUS  310D             NTF           1
4    WSE  310D             コイル           2
5    WSE  310D             NTF           0
6    GSE  J69P             コイル           4
7    GSE  J69P         Buck-IC           2
8  MELMB  310D             コイル           5
9  MELMB  310D             NTF           1

In [5]:
#cell5
df_work_positive = df_work[
    df_work["defect_qty"] > 0
].copy()

df_work_positive

    site model defect_category  defect_qty
0    SUS  J69P             コイル           3
1    SUS  J69P         Buck-IC           1
2    SUS  J69P             コイル           2
3    SUS  310D             NTF           1
4    WSE  310D             コイル           2
6    GSE  J69P             コイル           4
7    GSE  J69P         Buck-IC           2
8  MELMB  310D             コイル           5
9  MELMB  310D             NTF           1

In [6]:
df_category_unique = df_work_positive.drop_duplicates(
    [
        "site",
        "model",
        "defect_category",
    ]
)
df_category_unique

    site model defect_category  defect_qty
0    SUS  J69P             コイル           3
1    SUS  J69P         Buck-IC           1
3    SUS  310D             NTF           1
4    WSE  310D             コイル           2
6    GSE  J69P             コイル           4
7    GSE  J69P         Buck-IC           2
8  MELMB  310D             コイル           5
9  MELMB  310D             NTF           1

In [7]:
#cell7
df_category = (
    df_category_unique.groupby(
        [
            "site",
            "model",
        ],
        as_index=False,
    )["defect_category"].agg("/".join)
)
df_category

    site model defect_category
0    GSE  J69P     コイル/Buck-IC
1  MELMB  310D         コイル/NTF
2    SUS  310D             NTF
3    SUS  J69P     コイル/Buck-IC
4    WSE  310D             コイル

In [8]:
df_category = df_category.rename(
    columns={
        "defect_category": "defect_category_list",
    }
)
df_category

    site model defect_category_list
0    GSE  J69P          コイル/Buck-IC
1  MELMB  310D              コイル/NTF
2    SUS  310D                  NTF
3    SUS  J69P          コイル/Buck-IC
4    WSE  310D                  コイル

In [9]:
#cell9
df_result = pd.merge(
    df_plan,
    df_category,
    on=[
        "site",
        "model",
    ],
    how="left",
)
df_result

    site model  plan_qty defect_category_list
0    SUS  J69P     50000          コイル/Buck-IC
1    SUS  310D     30000                  NTF
2    WSE  310D     45000                  コイル
3    GSE  J69P     32000          コイル/Buck-IC
4  MELMB  310D     60000              コイル/NTF
5    ISE  J69P     20000                  NaN

In [10]:
df_result["defect_category_list"] = (
    df_result["defect_category_list"].fillna("発生なし")
)
df_result

    site model  plan_qty defect_category_list
0    SUS  J69P     50000          コイル/Buck-IC
1    SUS  310D     30000                  NTF
2    WSE  310D     45000                  コイル
3    GSE  J69P     32000          コイル/Buck-IC
4  MELMB  310D     60000              コイル/NTF
5    ISE  J69P     20000                 発生なし