###### 132_7_practical_daily_task_type_fill_answer.ipynb

In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [4]:
plt.rcParams["font.family"] = "Meiryo"
plt.rcParams["axes.unicode_minus"] = False

In [5]:
df = pd.read_csv(
    "dataset/daily_work_minutes_practice.csv",
)
df

       work_date task_type work_minutes comment
0     2022-01-01        集計           45    日次集計
1     2022-01-01        確認           30    内容確認
2     2022-01-02      資料作成           60    会議資料
3    2022-01-04         集計           90    空白あり
4     2022-01-05        確認          未入力    数値NG
5     2022-01-07        会議          120    週次会議
6     2022/01/07       議事録           40  日付表記違い
7     2022-01-09        集計           75    日次集計
8        NG_DATE        確認           30    日付NG
9     2022-01-10      資料作成          abc    数値NG
10    2022-01-10        確認           35    内容確認

In [6]:
df["work_date_raw"] = df["work_date"]
df.head()

      work_date task_type work_minutes comment work_date_raw
0    2022-01-01        集計           45    日次集計    2022-01-01
1    2022-01-01        確認           30    内容確認    2022-01-01
2    2022-01-02      資料作成           60    会議資料    2022-01-02
3   2022-01-04         集計           90    空白あり   2022-01-04
4    2022-01-05        確認          未入力    数値NG    2022-01-05

In [7]:
df["work_date_clean"] =(
    df["work_date"]
    .astype("string")
    .str.strip()
)
df

       work_date task_type work_minutes comment work_date_raw work_date_clean
0     2022-01-01        集計           45    日次集計    2022-01-01      2022-01-01
1     2022-01-01        確認           30    内容確認    2022-01-01      2022-01-01
2     2022-01-02      資料作成           60    会議資料    2022-01-02      2022-01-02
3    2022-01-04         集計           90    空白あり   2022-01-04       2022-01-04
4     2022-01-05        確認          未入力    数値NG    2022-01-05      2022-01-05
5     2022-01-07        会議          120    週次会議    2022-01-07      2022-01-07
6     2022/01/07       議事録           40  日付表記違い    2022/01/07      2022/01/07
7     2022-01-09        集計           75    日次集計    2022-01-09      2022-01-09
8        NG_DATE        確認           30    日付NG       NG_DATE         NG_DATE
9     2022-01-10      資料作成          abc    数値NG    2022-01-10      2022-01-10
10    2022-01-10        確認           35    内容確認    2022-01-10      2022-01-10

In [8]:
df.dtypes

work_date                  object
task_type                  object
work_minutes               object
comment                    object
work_date_raw              object
work_date_clean    string[python]
dtype: object

In [10]:
df["work_date_dt"] = pd.to_datetime(
    df["work_date_clean"],
    errors="coerce",
    format="mixed",
)
df.head().dtypes

work_date                  object
task_type                  object
work_minutes               object
comment                    object
work_date_raw              object
work_date_clean    string[python]
work_date_dt       datetime64[ns]
dtype: object

In [11]:
df["task_type"]

0       集計
1       確認
2     資料作成
3       集計
4       確認
5       会議
6      議事録
7       集計
8       確認
9     資料作成
10      確認
Name: task_type, dtype: object

In [12]:
df["task_type_clean"] = (
    df["task_type"]
    .astype("string")
    .str.strip()
)
df.head()

,work_date,task_type,work_minutes,comment,work_date_raw,work_date_clean,work_date_dt,task_type_clean
0,2022-01-01,集計,45,日次集計,2022-01-01,2022-01-01,2022-01-01,集計
1,2022-01-01,確認,30,内容確認,2022-01-01,2022-01-01,2022-01-01,確認
2,2022-01-02,資料作成,60,会議資料,2022-01-02,2022-01-02,2022-01-02,資料作成
3,2022-01-04,集計,90,空白あり,2022-01-04,2022-01-04,2022-01-04,集計
4,2022-01-05,確認,未入力,数値NG,2022-01-05,2022-01-05,2022-01-05,確認

In [13]:
df["work_minutes"]

0      45
1      30
2      60
3      90
4     未入力
5     120
6      40
7      75
8      30
9     abc
10     35
Name: work_minutes, dtype: object

In [14]:
df["work_minutes_clean"] = (
    df["work_minutes"]
    .astype("string")
    .str.strip()
)
df["work_minutes_clean"]

0      45
1      30
2      60
3      90
4     未入力
5     120
6      40
7      75
8      30
9     abc
10     35
Name: work_minutes_clean, dtype: string

In [15]:
df["work_minutes_clean"]

0      45
1      30
2      60
3      90
4     未入力
5     120
6      40
7      75
8      30
9     abc
10     35
Name: work_minutes_clean, dtype: string

In [17]:
df["work_minutes_num"] = pd.to_numeric(
    df["work_minutes_clean"],
    errors="coerce",
)
df["work_minutes_num"]

0       45
1       30
2       60
3       90
4     <NA>
5      120
6       40
7       75
8       30
9     <NA>
10      35
Name: work_minutes_num, dtype: Int64

In [19]:
df["work_date_dt"]

0    2022-01-01
1    2022-01-01
2    2022-01-02
3    2022-01-04
4    2022-01-05
5    2022-01-07
6    2022-01-07
7    2022-01-09
8           NaT
9    2022-01-10
10   2022-01-10
Name: work_date_dt, dtype: datetime64[ns]

In [18]:
df_date_ng = df[
    df["work_date_dt"].isna()
].copy()
df_date_ng

,work_date,task_type,work_minutes,comment,work_date_raw,work_date_clean,work_date_dt,task_type_clean,work_minutes_clean,work_minutes_num
8,NG_DATE,確認,30,日付NG,NG_DATE,NG_DATE,NaT,確認,30,30

In [24]:
df_work = df[
    df["work_date_dt"].notna()
    & df["work_minutes_num"].notna()
    & df["task_type_clean"].notna()
].copy()

df_work

,work_date,task_type,work_minutes,comment,work_date_raw,work_date_clean,work_date_dt,task_type_clean,work_minutes_clean,work_minutes_num,work_date_day
0,2022-01-01,集計,45,日次集計,2022-01-01,2022-01-01,2022-01-01,集計,45,45,2022-01-01
1,2022-01-01,確認,30,内容確認,2022-01-01,2022-01-01,2022-01-01,確認,30,30,2022-01-01
2,2022-01-02,資料作成,60,会議資料,2022-01-02,2022-01-02,2022-01-02,資料作成,60,60,2022-01-02
3,2022-01-04,集計,90,空白あり,2022-01-04,2022-01-04,2022-01-04,集計,90,90,2022-01-04
5,2022-01-07,会議,120,週次会議,2022-01-07,2022-01-07,2022-01-07,会議,120,120,2022-01-07
6,2022/01/07,議事録,40,日付表記違い,2022/01/07,2022/01/07,2022-01-07,議事録,40,40,2022-01-07
7,2022-01-09,集計,75,日次集計,2022-01-09,2022-01-09,2022-01-09,集計,75,75,2022-01-09
10,2022-01-10,確認,35,内容確認,2022-01-10,2022-01-10,2022-01-10,確認,35,35,2022-01-10

In [25]:
df_work["work_date_day"] = df_work["work_date_dt"].dt.normalize()
df_work["work_date_day"]

0    2022-01-01
1    2022-01-01
2    2022-01-02
3    2022-01-04
5    2022-01-07
6    2022-01-07
7    2022-01-09
10   2022-01-10
Name: work_date_day, dtype: datetime64[ns]

In [28]:
df_work[
    [
        "work_date_day",
        "task_type_clean",
    ]
]

   work_date_day task_type_clean
0     2022-01-01              集計
1     2022-01-01              確認
2     2022-01-02            資料作成
3     2022-01-04              集計
5     2022-01-07              会議
6     2022-01-07             議事録
7     2022-01-09              集計
10    2022-01-10              確認

In [29]:
df_daily_task = (
    df_work
    .groupby(
        [
            "work_date_day",
            "task_type_clean",
        ]
    )
    .agg(
        work_minutes_sum=("work_minutes_num", "sum"),
        record_count=("work_minutes_num", "count"),
    )
)
df_daily_task

                               work_minutes_sum  record_count
work_date_day task_type_clean
2022-01-01    確認                             30             1
              集計                             45             1
2022-01-02    資料作成                           60             1
2022-01-04    集計                             90             1
2022-01-07    会議                            120             1
              議事録                            40             1
2022-01-09    集計                             75             1
2022-01-10    確認                             35             1