###### 131_5_practical_lcm_control_no_check_answer.ipynb

In [12]:
import pandas as pd

In [13]:
pd.set_option("display.max_columns", None)

In [14]:
df_defect = pd.read_csv("dataset/lcm_control_no_check.csv")

In [15]:
pattern = r"[A-Z]{3}-\d{6}-\d{3}"

In [16]:
df_defect["control_no_ok"] = df_defect["control_no"].str.fullmatch(
    pattern,
    na=False,
)

In [18]:
df_valid = df_defect[
    df_defect["control_no_ok"]
].copy()
df_valid

,defect_id,site,customer,model,occ_month,control_no,defect_category,defect_qty,comment,control_no_ok
0,D001,SUS,Honda,J69P,2026-07,SUS-202607-001,Buck-IC,3,正式登録データ,True
6,D007,GSE,Honda,310D,2026-07,GSE-202607-006,NTF,1,正式登録データ,True
7,D008,SUS,Honda,J69P,2026-08,SUS-202608-007,Buck-IC,2,正式登録データ,True
9,D010,GSE,Honda,J69P,2026-08,GSE-202608-009,Buck-IC,5,正式登録データ,True

In [19]:
df_invalid = df_defect[
    ~df_defect["control_no_ok"]
].copy()
df_invalid

,defect_id,site,customer,model,occ_month,control_no,defect_category,defect_qty,comment,control_no_ok
1,D002,WSE,Honda,310D,2026-07,WSE_202607_002,Coil,2,区切り文字がアンダーバー,False
2,D003,GSE,Mitsubishi,310D,2026-07,GSE-2026-07-003,NTF,1,年月の間にハイフンあり,False
3,D004,MELMB,Honda,J69P,2026-07,MELMB-202607-004,Buck-IC,4,拠点コードが5文字,False
4,D005,SUS,Mitsubishi,J69P,2026-07,SUS-202607-ABC,Coil,1,末尾が数字ではない,False
5,D006,WSE,Honda,310D,2026-07,WSE-202607-005 メモあり,Coil,2,末尾に余計な文字あり,False
8,D009,WSE,Mitsubishi,310D,2026-08,WSE-202608-8,Coil,3,連番が3桁ではない,False

In [24]:
total_count = len(df_defect)
print(total_count)

valid_count = len(df_valid)
print(valid_count)

invalid_count = len(df_invalid)
print(invalid_count)

valid_rate = round(
    valid_count / total_count * 100,
    1,
)
print(valid_rate)

10
4
6
40.0

In [ ]:
df_check_summary = pd.DataFrame(
    {
            "item": [
                "全データ件数",
                "書式ok件数",
                "書式ng件数",
                "書式ok率",
            ],
            "value": [
                total_count,
                valid_count,
                invalid_count,
            valid_rate,
            ],
    }
)
df_check_summary

     item  value
0  全データ件数   10.0
1  書式ok件数    4.0
2  書式ng件数    6.0
3   書式ok率   40.0

In [30]:
df_site_valid_qty = df_valid.groupby(
    "site",
    as_index=False,
)["defect_qty"].sum()
df_site_valid_qty

  site  defect_qty
0  GSE           6
1  SUS           5

In [31]:
df_site_valid_qty = df_site_valid_qty.rename(
    columns={
        "defect_qty": "valid_defect_qty",
    }
)
df_site_valid_qty

  site  valid_defect_qty
0  GSE                 6
1  SUS                 5

In [32]:
df_site_valid_qty = df_site_valid_qty.sort_values(
    ["valid_defect_qty", "site"],
    ascending=[False, True],
).reset_index(drop=True)
df_site_valid_qty

  site  valid_defect_qty
0  GSE                 6
1  SUS                 5

In [33]:
df_invalid_check = df_invalid[
    [
        "defect_id",
        "site",
        "occ_month",
        "control_no",
        "comment",
    ]
].copy()
df_invalid_check

  defect_id   site occ_month           control_no       comment
1      D002    WSE   2026-07       WSE_202607_002  区切り文字がアンダーバー
2      D003    GSE   2026-07      GSE-2026-07-003   年月の間にハイフンあり
3      D004  MELMB   2026-07     MELMB-202607-004     拠点コードが5文字
4      D005    SUS   2026-07       SUS-202607-ABC     末尾が数字ではない
5      D006    WSE   2026-07  WSE-202607-005 メモあり    末尾に余計な文字あり
8      D009    WSE   2026-08         WSE-202608-8     連番が3桁ではない