###### フォルダー名：128_3_quality_pivot_total_practice
###### ファイル名：quality_pivot_total_practice.ipynb

In [1]:
import pandas as pd

In [2]:
df_defect = pd.DataFrame(
    [
        ["2026-06", "MELMB", "LCM-A", "点灯不良", 18],
        ["2026-06", "WSE", "LCM-A", "点灯不良", 25],
        ["2026-06", "GSE", "LCM-A", "点灯不良", 7],
        ["2026-06", "MELMB", "LCM-B", "ショート", 12],
        ["2026-06", "WSE", "LCM-B", "ショート", 32],
        ["2026-06", "GSE", "LCM-B", "ショート", 9],
        ["2026-06", "MELMB", "LCM-C", "外観キズ", 5],
        ["2026-06", "WSE", "LCM-C", "外観キズ", 14],
        ["2026-06", "GSE", "LCM-C", "外観キズ", 21],
        ["2026-06", "MELMB", "LCM-D", "コネクタ浮き", 8],
        ["2026-06", "WSE", "LCM-D", "コネクタ浮き", 11],
        ["2026-06", "GSE", "LCM-D", "コネクタ浮き", 4],
    ],
    columns=[
        "month",
        "site",
        "product",
        "defect_type",
        "defect_qty",
    ],
)

df_defect.head()

     month   site product defect_type  defect_qty
0  2026-06  MELMB   LCM-A        点灯不良          18
1  2026-06    WSE   LCM-A        点灯不良          25
2  2026-06    GSE   LCM-A        点灯不良           7
3  2026-06  MELMB   LCM-B        ショート          12
4  2026-06    WSE   LCM-B        ショート          32

In [3]:
df_product_master = pd.DataFrame(
    [
        ["LCM-A", "ヘッドランプ", "品質保証1課"],
        ["LCM-B", "ヘッドランプ", "品質保証1課"],
        ["LCM-C", "リアランプ", "品質保証2課"],
        ["LCM-D", "ヘッドランプ", "品質保証1課"],
    ],
    columns=[
        "product",
        "category",
        "owner_department",
    ],
)
df_product_master

  product category owner_department
0   LCM-A   ヘッドランプ           品質保証1課
1   LCM-B   ヘッドランプ           品質保証1課
2   LCM-C    リアランプ           品質保証2課
3   LCM-D   ヘッドランプ           品質保証1課

In [5]:
df_merge = df_defect.merge(df_product_master, on="product")
df_merge.tail()

      month   site product defect_type  defect_qty category owner_department
7   2026-06    WSE   LCM-C        外観キズ          14    リアランプ           品質保証2課
8   2026-06    GSE   LCM-C        外観キズ          21    リアランプ           品質保証2課
9   2026-06  MELMB   LCM-D      コネクタ浮き           8   ヘッドランプ           品質保証1課
10  2026-06    WSE   LCM-D      コネクタ浮き          11   ヘッドランプ           品質保証1課
11  2026-06    GSE   LCM-D      コネクタ浮き           4   ヘッドランプ           品質保証1課

In [6]:
df_headlamp = df_merge[df_merge["category"] == "ヘッドランプ"]
df_headlamp

      month   site product defect_type  defect_qty category owner_department
0   2026-06  MELMB   LCM-A        点灯不良          18   ヘッドランプ           品質保証1課
1   2026-06    WSE   LCM-A        点灯不良          25   ヘッドランプ           品質保証1課
2   2026-06    GSE   LCM-A        点灯不良           7   ヘッドランプ           品質保証1課
3   2026-06  MELMB   LCM-B        ショート          12   ヘッドランプ           品質保証1課
4   2026-06    WSE   LCM-B        ショート          32   ヘッドランプ           品質保証1課
5   2026-06    GSE   LCM-B        ショート           9   ヘッドランプ           品質保証1課
9   2026-06  MELMB   LCM-D      コネクタ浮き           8   ヘッドランプ           品質保証1課
10  2026-06    WSE   LCM-D      コネクタ浮き          11   ヘッドランプ           品質保証1課
11  2026-06    GSE   LCM-D      コネクタ浮き           4   ヘッドランプ           品質保証1課

In [7]:
df_wide = df_headlamp.pivot(
    index="product",
    columns="site",
    values="defect_qty",
)
df_wide

site     GSE  MELMB  WSE
product
LCM-A      7     18   25
LCM-B      9     12   32
LCM-D      4      8   11

In [8]:
df_wide = df_wide[["MELMB", "WSE", "GSE"]]
df_wide

site     MELMB  WSE  GSE
product
LCM-A       18   25    7
LCM-B       12   32    9
LCM-D        8   11    4

In [9]:
df_wide["total"] = df_wide["MELMB"] + df_wide["WSE"] + df_wide["GSE"]
df_wide

C:\Users\stj242381\AppData\Local\Temp\ipykernel_16276\1657570315.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_wide["total"] = df_wide["MELMB"] + df_wide["WSE"] + df_wide["GSE"]

site     MELMB  WSE  GSE  total
product
LCM-A       18   25    7     50
LCM-B       12   32    9     53
LCM-D        8   11    4     23

In [10]:
df_total_sort = df_wide.sort_values("total", ascending=False)
df_total_sort

site     MELMB  WSE  GSE  total
product
LCM-B       12   32    9     53
LCM-A       18   25    7     50
LCM-D        8   11    4     23