In [1]:
import pandas as pd

df = pd.read_csv('event_after_sample.csv')
df.head()

,イベント日,勉強会グループ,イベント,開催形式,定員,登録者数,リモート可,参加者数,満席率,カテゴリー
0,2019-01-23,Python輪読会,Python輪読会 No.1,S,20,19,False,19,0.95,輪読
1,2019-01-26,初心者の会,もくもく自習会,SL,20,12,True,12,0.60,自習
2,2019-01-27,なまこ部,Talk#1,SL,20,12,True,12,0.60,一般
3,2019-01-30,Python輪読会,Python輪読会 No.2,S,20,15,False,15,0.75,輪読
4,2019-02-02,電子工作シリーズ,CO2測定,S,50,41,False,41,0.82,一般

In [2]:
grouped = df.groupby("勉強会グループ")
grouped

In [3]:
summary_df = grouped["リモート可"].agg(["size", "sum"])
summary_df = summary_df.rename(
    columns={
        "size": "イベント数",
        "sum": "リモート可のイベント数"
    }
)
summary_df.head()

           イベント数  リモート可のイベント数
勉強会グループ
Python輪読会      3            0
なまこ部           2            2
初心者の会          2            2
電子工作シリーズ       1            0

In [4]:
summary_df["参加者の延べ人数"] = grouped["参加者数"].sum()
summary_df.head()

           イベント数  リモート可のイベント数  参加者の延べ人数
勉強会グループ
Python輪読会      3            0        52
なまこ部           2            2        32
初心者の会          2            2        40
電子工作シリーズ       1            0        41

In [6]:
bins = [-float("inf"), 50, 100, 500, 1000, float("inf")]
summary_df["参加者の延べ人数の区分"] = pd.cut(
    summary_df["参加者の延べ人数"],
    bins,
    right=False
)
summary_df

           イベント数  リモート可のイベント数  参加者の延べ人数    参加者の延べ人数の区分
勉強会グループ
Python輪読会      3            0        52  [50.0, 100.0)
なまこ部           2            2        32   [-inf, 50.0)
初心者の会          2            2        40   [-inf, 50.0)
電子工作シリーズ       1            0        41   [-inf, 50.0)

In [7]:
summary_df = summary_df.reset_index()
summary_df

     勉強会グループ  イベント数  リモート可のイベント数  参加者の延べ人数    参加者の延べ人数の区分
0  Python輪読会      3            0        52  [50.0, 100.0)
1       なまこ部      2            2        32   [-inf, 50.0)
2      初心者の会      2            2        40   [-inf, 50.0)
3   電子工作シリーズ      1            0        41   [-inf, 50.0)

In [8]:
summary_df["満席率平均"] = grouped["満席率"].mean()
summary_df

     勉強会グループ  イベント数  リモート可のイベント数  参加者の延べ人数    参加者の延べ人数の区分  満席率平均
0  Python輪読会      3            0        52  [50.0, 100.0)    NaN
1       なまこ部      2            2        32   [-inf, 50.0)    NaN
2      初心者の会      2            2        40   [-inf, 50.0)    NaN
3   電子工作シリーズ      1            0        41   [-inf, 50.0)    NaN

In [9]:
summary_df.sort_values("参加者の延べ人数", ascending=False)

     勉強会グループ  イベント数  リモート可のイベント数  参加者の延べ人数    参加者の延べ人数の区分  満席率平均
0  Python輪読会      3            0        52  [50.0, 100.0)    NaN
3   電子工作シリーズ      1            0        41   [-inf, 50.0)    NaN
2      初心者の会      2            2        40   [-inf, 50.0)    NaN
1       なまこ部      2            2        32   [-inf, 50.0)    NaN

In [10]:
summary_df.sort_values("イベント数", ascending=False)

     勉強会グループ  イベント数  リモート可のイベント数  参加者の延べ人数    参加者の延べ人数の区分  満席率平均
0  Python輪読会      3            0        52  [50.0, 100.0)    NaN
1       なまこ部      2            2        32   [-inf, 50.0)    NaN
2      初心者の会      2            2        40   [-inf, 50.0)    NaN
3   電子工作シリーズ      1            0        41   [-inf, 50.0)    NaN

In [11]:
summary_df["満席率最大"] = grouped["満席率"].max()

In [12]:
summary_df

     勉強会グループ  イベント数  リモート可のイベント数  参加者の延べ人数    参加者の延べ人数の区分  満席率平均  満席率最大
0  Python輪読会      3            0        52  [50.0, 100.0)    NaN    NaN
1       なまこ部      2            2        32   [-inf, 50.0)    NaN    NaN
2      初心者の会      2            2        40   [-inf, 50.0)    NaN    NaN
3   電子工作シリーズ      1            0        41   [-inf, 50.0)    NaN    NaN

In [13]:
summary_df.sort_values("イベント数", ascending=True)

     勉強会グループ  イベント数  リモート可のイベント数  参加者の延べ人数    参加者の延べ人数の区分  満席率平均  満席率最大
3   電子工作シリーズ      1            0        41   [-inf, 50.0)    NaN    NaN
1       なまこ部      2            2        32   [-inf, 50.0)    NaN    NaN
2      初心者の会      2            2        40   [-inf, 50.0)    NaN    NaN
0  Python輪読会      3            0        52  [50.0, 100.0)    NaN    NaN

In [14]:
summary_df[summary_df["イベント数"] >= 3]

     勉強会グループ  イベント数  リモート可のイベント数  参加者の延べ人数    参加者の延べ人数の区分  満席率平均  満席率最大
0  Python輪読会      3            0        52  [50.0, 100.0)    NaN    NaN

In [15]:
summary_df.sort_values("リモート可のイベント数", ascending=False)

     勉強会グループ  イベント数  リモート可のイベント数  参加者の延べ人数    参加者の延べ人数の区分  満席率平均  満席率最大
1       なまこ部      2            2        32   [-inf, 50.0)    NaN    NaN
2      初心者の会      2            2        40   [-inf, 50.0)    NaN    NaN
0  Python輪読会      3            0        52  [50.0, 100.0)    NaN    NaN
3   電子工作シリーズ      1            0        41   [-inf, 50.0)    NaN    NaN

In [16]:
summary_df[summary_df["参加者の延べ人数"] >= 50]

     勉強会グループ  イベント数  リモート可のイベント数  参加者の延べ人数    参加者の延べ人数の区分  満席率平均  満席率最大
0  Python輪読会      3            0        52  [50.0, 100.0)    NaN    NaN

In [17]:
grouped["満席率"].mean()

勉強会グループ
Python輪読会    0.866667
なまこ部         0.700000
初心者の会        0.765000
電子工作シリーズ     0.820000
Name: 満席率, dtype: float64

In [18]:
grouped["満席率"].max()

勉強会グループ
Python輪読会    0.95
なまこ部         0.80
初心者の会        0.93
電子工作シリーズ     0.82
Name: 満席率, dtype: float64

In [19]:
grouped["参加者数"].sum()

勉強会グループ
Python輪読会    52
なまこ部         32
初心者の会        40
電子工作シリーズ     41
Name: 参加者数, dtype: int64

In [20]:
summary_df.sort_values("イベント数")

     勉強会グループ  イベント数  リモート可のイベント数  参加者の延べ人数    参加者の延べ人数の区分  満席率平均  満席率最大
3   電子工作シリーズ      1            0        41   [-inf, 50.0)    NaN    NaN
1       なまこ部      2            2        32   [-inf, 50.0)    NaN    NaN
2      初心者の会      2            2        40   [-inf, 50.0)    NaN    NaN
0  Python輪読会      3            0        52  [50.0, 100.0)    NaN    NaN

In [21]:
summary_df[summary_df["イベント数"] >= 3]

     勉強会グループ  イベント数  リモート可のイベント数  参加者の延べ人数    参加者の延べ人数の区分  満席率平均  満席率最大
0  Python輪読会      3            0        52  [50.0, 100.0)    NaN    NaN