In [1]:
import pandas as pd

In [2]:
df = pd.DataFrame(
    [
        ["Alice", "国語", 87],
        ["Alice", "数学", 72],
        ["Bob", "国語", 65],
        ["Bob", "数学", 92],
    ],
    columns=["Name", "Subject", "Point"],
)
df

    Name Subject  Point
0  Alice      国語     87
1  Alice      数学     72
2    Bob      国語     65
3    Bob      数学     92

In [3]:
df_wide = df.pivot(columns="Subject", index="Name", values="Point")
df_wide

Subject  国語  数学
Name
Alice    87  72
Bob      65  92