###### 132_2_extract_date_weekday_answer.ipynb

In [3]:
import pandas as pd
pd.set_option("display.max_columns", None)

In [4]:
df = pd.read_csv(
    "dataset/study_log_jst.csv",
    parse_dates=[
        "start_at",
        "end_at",
    ],
)
df

,id,user_name,subject,start_at,end_at
0,1,Alice,数学,2021-12-31 13:01:07.915455+09:00,2021-12-31 13:31:10.568577+09:00
1,2,Alice,情報,2021-12-31 13:50:08.226816+09:00,2021-12-31 14:28:10.369856+09:00
2,3,Bob,国語,2021-12-31 23:22:30.684974+09:00,2021-12-31 23:42:21.650810+09:00
3,4,Bob,国語,2022-01-01 00:10:30.751069+09:00,2022-01-01 00:20:44.851817+09:00
4,5,Caroll,理科,2022-01-01 15:23:11.148775+09:00,2022-01-01 17:11:05.693765+09:00
5,6,Caroll,社会,2022-01-01 17:15:31.139724+09:00,2022-01-01 18:11:23.814643+09:00
6,7,Caroll,社会,2022-01-01 21:32:44.356243+09:00,2022-01-01 22:45:06.194202+09:00
7,8,Alice,国語,2022-01-02 19:22:42.668155+09:00,2022-01-02 19:58:44.191690+09:00

In [5]:
df.dtypes

id                               int64
user_name                       object
subject                         object
start_at     datetime64[ns, UTC+09:00]
end_at       datetime64[ns, UTC+09:00]
dtype: object

In [6]:
df["start_date"] = df["start_at"].dt.date

df[
    [
        "start_at",
        "start_date",
    ]
]

                          start_at  start_date
0 2021-12-31 13:01:07.915455+09:00  2021-12-31
1 2021-12-31 13:50:08.226816+09:00  2021-12-31
2 2021-12-31 23:22:30.684974+09:00  2021-12-31
3 2022-01-01 00:10:30.751069+09:00  2022-01-01
4 2022-01-01 15:23:11.148775+09:00  2022-01-01
5 2022-01-01 17:15:31.139724+09:00  2022-01-01
6 2022-01-01 21:32:44.356243+09:00  2022-01-01
7 2022-01-02 19:22:42.668155+09:00  2022-01-02

In [7]:
df["start_weekday"] = df["start_at"].dt.day_name(
    "ja_JP",
)

df[
    [
        "start_at",
        "start_weekday"
    ]
]

                          start_at start_weekday
0 2021-12-31 13:01:07.915455+09:00           金曜日
1 2021-12-31 13:50:08.226816+09:00           金曜日
2 2021-12-31 23:22:30.684974+09:00           金曜日
3 2022-01-01 00:10:30.751069+09:00           土曜日
4 2022-01-01 15:23:11.148775+09:00           土曜日
5 2022-01-01 17:15:31.139724+09:00           土曜日
6 2022-01-01 21:32:44.356243+09:00           土曜日
7 2022-01-02 19:22:42.668155+09:00           日曜日

In [9]:
df[
    [
        "start_at",
        "start_date",
        "start_weekday"
    ]
].dtypes

start_at         datetime64[ns, UTC+09:00]
start_date                          object
start_weekday                       object
dtype: object