###### 131_3_practical_exclude_test_comment.ipynb

In [1]:
import pandas as pd

In [2]:
pd.set_option("display.max_columns", None)

In [3]:
df_defect = pd.read_csv("dataset/defect_comment_filter.csv")
df_defect

  defect_id   site model occ_month defect_category                 comment
0      D001    SUS  J69P   2026-04             NTF      市場返却品を確認したが不具合再現せず
1      D002    SUS  J69P   2026-04         Buck-IC  TEST登録：Buck-IC焼損確認用データ
2      D003    WSE  310D   2026-05            Coil         コイル内部に鉄粉噛み込みを確認
3      D004    GSE  310D   2026-05            Coil            サンプル評価用として登録
4      D005  MELMB  J69P   2026-06             NTF          現品確認の結果、症状再現せず
5      D006    WSE  310D   2026-06            Coil            重複登録のため集計対象外
6      D007    SUS  J69P   2026-06         Buck-IC     Buck-ICのHS-FET損傷を確認
7      D008    GSE  310D   2026-06            Coil        確認用：検査条件変更前の仮データ
8      D009  MELMB  310D   2026-07            Coil        160Vインパルス検査で異常検出
9      D010    SUS  J69P   2026-07             NTF          test memo only

In [5]:
#cell4
exclude_pattern = "TEST|確認用|サンプル|重複"

In [7]:
#cell5
df_defect["exclude_flag"] = df_defect["comment"].str.contains(
    exclude_pattern,
    case=False,
    na=False,
)
df_defect

,defect_id,site,model,occ_month,defect_category,comment,exclude_flag
0,D001,SUS,J69P,2026-04,NTF,市場返却品を確認したが不具合再現せず,False
1,D002,SUS,J69P,2026-04,Buck-IC,TEST登録：Buck-IC焼損確認用データ,True
2,D003,WSE,310D,2026-05,Coil,コイル内部に鉄粉噛み込みを確認,False
3,D004,GSE,310D,2026-05,Coil,サンプル評価用として登録,True
4,D005,MELMB,J69P,2026-06,NTF,現品確認の結果、症状再現せず,False
5,D006,WSE,310D,2026-06,Coil,重複登録のため集計対象外,True
6,D007,SUS,J69P,2026-06,Buck-IC,Buck-ICのHS-FET損傷を確認,False
7,D008,GSE,310D,2026-06,Coil,確認用：検査条件変更前の仮データ,True
8,D009,MELMB,310D,2026-07,Coil,160Vインパルス検査で異常検出,False
9,D010,SUS,J69P,2026-07,NTF,test memo only,True

In [8]:
df_actual = df_defect[
    ~df_defect["exclude_flag"]
].copy()
df_actual

,defect_id,site,model,occ_month,defect_category,comment,exclude_flag
0,D001,SUS,J69P,2026-04,NTF,市場返却品を確認したが不具合再現せず,False
2,D003,WSE,310D,2026-05,Coil,コイル内部に鉄粉噛み込みを確認,False
4,D005,MELMB,J69P,2026-06,NTF,現品確認の結果、症状再現せず,False
6,D007,SUS,J69P,2026-06,Buck-IC,Buck-ICのHS-FET損傷を確認,False
8,D009,MELMB,310D,2026-07,Coil,160Vインパルス検査で異常検出,False

In [9]:
df_exclude = df_defect[
    df_defect["exclude_flag"]
].copy()
df_exclude

,defect_id,site,model,occ_month,defect_category,comment,exclude_flag
1,D002,SUS,J69P,2026-04,Buck-IC,TEST登録：Buck-IC焼損確認用データ,True
3,D004,GSE,310D,2026-05,Coil,サンプル評価用として登録,True
5,D006,WSE,310D,2026-06,Coil,重複登録のため集計対象外,True
7,D008,GSE,310D,2026-06,Coil,確認用：検査条件変更前の仮データ,True
9,D010,SUS,J69P,2026-07,NTF,test memo only,True

In [17]:
df_site_count = df_actual.groupby(
    "site",
    as_index=False,
)["defect_id"].count()

df_site_count = df_site_count.rename(
    columns={
        "defect_id": "actual_count",
    }
)

df_site_count

    site  actual_count
0  MELMB             2
1    SUS             2
2    WSE             1

In [19]:
df_category_count = df_actual.groupby(
    "defect_category",
    as_index=False,
)["defect_id"].count()
df_category_count

df_category_count = df_category_count.rename(
    columns={
        "defect_id": "count"
    }
)
df_category_count

  defect_category  count
0         Buck-IC      1
1            Coil      2
2             NTF      2