###### 128-1 Practical exercises2

In [2]:
import pandas as pd

In [ ]:
df_check_a = pd.DataFrame(
    [
        ["2026-04", "MELMB", "LCM-A", "点灯不良", 12],
        ["2026-04", "WSE", "LCM-B", "外観キズ", 8],
        ["2026-04", "GSE", "LCM-C", "コネクタ浮き", 5],
    ],
    columns=[
        "check_month",
        "factory",
        "item",
        "ng_name",
        "ng_qty",
    ],
)
df_check_a

  check_month factory   item ng_name  ng_qty
0     2026-04   MELMB  LCM-A    点灯不良      12
1     2026-04     WSE  LCM-B    外観キズ       8
2     2026-04     GSE  LCM-C  コネクタ浮き       5

In [4]:
df_check_b = pd.DataFrame(
    [
         ["2026-05", "MELMB", "LCM-A", "点灯不良", 18],
        ["2026-05", "WSE", "LCM-B", "ショート", 22],
        ["2026-05", "GSE", "LCM-C", "外観キズ", 6],
    ],
    columns=[
        "month",
        "site",
        "product",
        "defect_type",
        "defect_qty",
    ],
)
df_check_b

     month   site product defect_type  defect_qty
0  2026-05  MELMB   LCM-A        点灯不良          18
1  2026-05    WSE   LCM-B        ショート          22
2  2026-05    GSE   LCM-C        外観キズ           6

In [6]:
df_check_a_rename = df_check_a.rename(
    columns={
        "check_month": "month",
        "factory": "site",
        "item": "product",
        "ng_name": "defect_type",
        "ng_qty": "defect_qty",
    }
)
df_check_a_rename

     month   site product defect_type  defect_qty
0  2026-04  MELMB   LCM-A        点灯不良          12
1  2026-04    WSE   LCM-B        外観キズ           8
2  2026-04    GSE   LCM-C      コネクタ浮き           5

In [7]:
df_check_all = pd.concat([df_check_a_rename, df_check_b], ignore_index=True)
df_check_all

     month   site product defect_type  defect_qty
0  2026-04  MELMB   LCM-A        点灯不良          12
1  2026-04    WSE   LCM-B        外観キズ           8
2  2026-04    GSE   LCM-C      コネクタ浮き           5
3  2026-05  MELMB   LCM-A        点灯不良          18
4  2026-05    WSE   LCM-B        ショート          22
5  2026-05    GSE   LCM-C        外観キズ           6