In [10]:
import pandas as pd
from IPython.display import display

def query_bot(fnam, max_rows=5, **option):
    df = pd.read_excel(fnam, **option)
    df["名前"] = df["名前"].str.replace("\u3000", " ", regex=False)
    
    with pd.option_context("display.max_rows", max_rows):
        while s := input("> "):
            try:
                if s.isdigit():
                    i = int(s)
                    display(df[i:i + 1])
                elif s == "columns":
                    print(df.columns)
                else:
                    result = df.query(s)
                    display(result)
            except:
                    print("クエリを正しくしてください")
names = ["名前", "クラス", "クラブ", "実施月", "数学"]
query_bot("input/exam.xlsx", header=1, names=names)

Index(['名前', 'クラス', 'クラブ', '実施月', '数学'], dtype='object')

     名前 クラス  クラブ     実施月  数学
5  平山 詩   A  写真部  201908  70

       名前 クラス  クラブ     実施月   数学
6   茂木 聖香   A  NaN  201905  100
58  相川 昭信   B  NaN  201905  100

クエリを正しくしてください

In [ ]:
#練習1
#columns ではなく cols と入力しても列名が出るようにしてください。

import pandas as pd
from IPython.display import display

def query_bot(fnam, max_rows=5, **option):
    df = pd.read_excel(fnam, **option)
    df["名前"] = df["名前"].str.replace("\u3000", " ", regex=False)

    with pd.option_context("display.max_rows", max_rows):
        while s := input("> "):
            try:
                if s.isdigit():
                    i = int(s)
                    display(df[i:i + 1])
                elif s == "columns" or s == "cols":
                    print(df.columns)
                else:
                    result = df.query(s)
                    display(result)
            except:
                    print("クエリを正しくしてください")
names = ["名前", "クラス", "クラブ", "実施月", "数学"]
query_bot("input/exam.xlsx", header=1, names=names)

クエリを正しくしてください
Index(['名前', 'クラス', 'クラブ', '実施月', '数学'], dtype='object')
Index(['名前', 'クラス', 'クラブ', '実施月', '数学'], dtype='object')
Index(['名前', 'クラス', 'クラブ', '実施月', '数学'], dtype='object')

In [14]:
#練習2
#数字を入力したとき、行だけでなく
#"3行目を表示します" のようなメッセージも出してください。
import pandas as pd
from IPython.display import display

def query_bot(fnam, max_rows=5, **option):
    df = pd.read_excel(fnam, **option)
    df["名前"] = df["名前"].str.replace("u\3000", " ", regex=False)

    with pd.option_context("display.max_rows", max_rows):
        while s := input("> "):
            try:
                if s.isdigit():
                    i = int(s)
                    print(f"{i}行目を表示します")
                    display(df[i:i +1])
                elif s == "columns":
                    print(df.columns)
                else:
                    result = df.query(s)
                    display(result)
            except:
                    print("クエリを正しくしてください")
names = ["名前", "クラス", "クラブ", "実施月", "数学"]
query_bot("input/exam.xlsx", header=1, names=names)

3行目を表示します

       名前 クラス  クラブ     実施月  数学
3  吉澤 あきの   A  NaN  201908  76

5行目を表示します

     名前 クラス  クラブ     実施月  数学
5  平山 詩   A  写真部  201908  70

クエリを正しくしてください
6行目を表示します

      名前 クラス  クラブ     実施月   数学
6  茂木 聖香   A  NaN  201905  100

10行目を表示します

       名前 クラス  クラブ     実施月  数学
10  新田　嘉明   A  NaN  201905  49

In [15]:
#練習3
#shape と入力したら、行数・列数を表示する機能を追加してください。
import pandas as pd
from IPython.display import display

def query_bot(fnam, max_rows=5, **option):
    df = pd.read_excel(fnam, **option)
    df["名前"] = df["名前"].str.replace("\u3000", " ", regex=False)

    with pd.option_context("display.max_rows", max_rows):
        while s := input("> "):
            try:
                if s.isdigit():
                    i =int(s)
                    display(df[i:i +1])
                elif s == "columns":
                    print(df.columns)
                elif s == "shape":
                    print(df.shape)
                else:
                    result = df.query(s)
                    display(result)
            except:
                print("クエリを正しくしてください")
names = ["名前", "クラス", "クラブ", "実施月", "数学"]
query_bot("input/exam.xlsx", header=1, names= names)

(108, 5)
クエリを正しくしてください
クエリを正しくしてください
Index(['名前', 'クラス', 'クラブ', '実施月', '数学'], dtype='object')

      名前 クラス  クラブ     実施月   数学
6  茂木 聖香   A  NaN  201905  100