In [2]:
def mini_bot():
    while s := input("> "):
        if s == "hello":
            print("こんにちは")
        elif s == "bye":
            print("さようなら")
        else:
            print("そのコマンドはありません")
mini_bot()

こんにちは
さようなら
そのコマンドはありません

In [3]:
#step2
def mini_bot():
    while s := input("> "):
        print("入力された文字:", s)
mini_bot()

入力された文字: kajima
入力された文字: tanaka
入力された文字: oiji

In [4]:
#step3
def mini_bot():
    while s := input("> "):
        if s == "hello":
            print("こんにちは")
mini_bot()

こんにちは

In [5]:
# step4
def mini_bot():
    while s := input("> "):
        if s == "hello":
            print("こんにちは")
        else:
            print("helloではありません")
mini_bot()

こんにちは
helloではありません

In [6]:
def mini_bot():
    while s := input("> "):
        if s == "hello":
            print("こんにちは")
        elif s == "bye":
            print("さようなら")
        else:
            print("そのこまんどはありません")
mini_bot()

こんにちは
さようなら
そのこまんどはありません

In [7]:
# practice1
def mini_bot():
    while s := input("> "):
        if s =="red":
            print("赤です")
        elif s == "blue":
            print("青です")
        else:
            print("わかりません")
mini_bot()

赤です
わかりません
青です

In [9]:
def animal_bot():
    while s := input("> "):
        if s == "dog":
            print("犬だに")
        elif s == "cat":
            print("猫だにゃ")
        else:
            print("わからないわん")
animal_bot()

猫だにゃ
犬だに
わからないわん

In [10]:
def one_bot():
    while s := input("> "):
        if s == "1":
            print("数字の１です")
        else:
            print("1ではありません")
one_bot()

1ではありません
1ではありません
数字の１です

In [ ]:
def command_bot():
    while s := input("> "):
        if s.isdigit():
            print("数字が入力されました。")
        elif s == "columns":
            print("列を表示します")
        else:
            print("クエリとして扱います")
command_bot()

数字が入力されました。
列を表示します
数字が入力されました。

In [12]:
def command_bot():
    while s := input("> "):
        if s.isdigit():
            print("数字コマンドです")
        elif s == "columns":
            print("columnsコマンドです。")
        else:
            print("クエリとです")
command_bot()

数字コマンドです
columnsコマンドです。
クエリとです

In [14]:
def simple_bot():
    while s := input("> "):
        if s.isdigit():
            print("数字です")
        elif s == "hello":
            print("挨拶です")
        else:
            print("その他です")
simple_bot()

数字です
数字です
数字です
挨拶です

In [15]:
def simple_bot():
    while s := input("> "):
        if s.isdigit():
            print("数字です")
        elif s == "show":
            print("表示します")
        else:
            print("そのたです")
simple_bot()

数字です
表示します
数字です

In [17]:
import pandas as pd
from IPython.display import display

df = pd.DataFrame({
    "名前": ["田中", "佐藤", "鈴木"],
    "点数": [80, 90, 70]
})
display(df)

   名前  点数
0  田中  80
1  佐藤  90
2  鈴木  70

In [20]:
import pandas as pd
from IPython.display import display

df = pd.DataFrame({
    "名前": ["田中", "佐藤", "鈴木"],
    "点数": [80, 90, 70]
})

def row_bot():
    while s := input("> "):
        if s.isdigit():
            i = int(s)
            display(df[i:i + 1])
        elif s == "columns":
            print(df.columns)
        else:
            print("数字か columns を入れてください")

row_bot()

   名前  点数
0  田中  80

   名前  点数
1  佐藤  90

   名前  点数
2  鈴木  70

Index(['名前', '点数'], dtype='object')