In [1]:
import pandas as pd
from IPython.display import display

In [3]:
import pandas as pd
from IPython.display import display

def query_bot(fnam, max_rows=5, **option):
    # Excelファイルを読み込む
    df = pd.read_excel(fnam, **option)

    # 名前の表記ゆれ（全角スペース）を半角スペースに直す
    df["名前"] = df["名前"].str.replace("\u3000", " ", regex=False)

    # 表示行数を一時的に制限する
    with pd.option_context("display.max_rows", max_rows):
        # 空文字が入力されるまで繰り返す
        while s := input("> "):
            try:
                # 入力された文字列を query として実行
                result = df.query(s)

                # 見やすく表示
                display(result)

            except:
                print("クエリを正しくしてください")

names = ["名前", "クラス", "クラブ", "実施月", "数学"]
query_bot("input/exam.xlsx", header=1, names=names)

クエリを正しくしてください

        名前 クラス  クラブ     実施月  数学
0   松原 勇二郎   A  弓道部  201905  93
1   松原 勇二郎   A  弓道部  201908  69
..     ...  ..  ...     ...  ..
33   沼田 悠斗   A  NaN  201905  61
34   沼田 悠斗   A  NaN  201908  71

[35 rows x 5 columns]

        名前 クラス  クラブ     実施月  数学
0   松原 勇二郎   A  弓道部  201905  93
1   松原 勇二郎   A  弓道部  201908  69
..     ...  ..  ...     ...  ..
31    西沢 匡   A  弓道部  201905  88
32    西沢 匡   A  弓道部  201908  79

[22 rows x 5 columns]

       名前 クラス  クラブ     実施月   数学
6   茂木 聖香   A  NaN  201905  100
58  相川 昭信   B  NaN  201905  100

In [4]:
import pandas as pd
from IPython.display import display

def query_bot(fnam, max_rows=5, **option):
    df = pd.read_excel(fnam, **option)
    df["名前"] = df["名前"].str.replace("\u3000", " ", regex=False)

    print("クエリーを入力してください。空Enterで終了します。")

    with pd.option_context("display.max_rows", max_rows):
        while s := input("> "):
            try:
                result = df.query(s)
                display(result)
            except:
                print("クエリを正しくしてください")
names = ["名前", "クラス", "クラブ", "実施月", "数学"]
query_bot("input/exam.xlsx", header=1, names=names)

クエリーを入力してください。空Enterで終了します。

        名前 クラス  クラブ     実施月  数学
0   松原 勇二郎   A  弓道部  201905  93
1   松原 勇二郎   A  弓道部  201908  69
..     ...  ..  ...     ...  ..
33   沼田 悠斗   A  NaN  201905  61
34   沼田 悠斗   A  NaN  201908  71

[35 rows x 5 columns]

        名前 クラス  クラブ     実施月  数学
0   松原 勇二郎   A  弓道部  201905  93
1   松原 勇二郎   A  弓道部  201908  69
..     ...  ..  ...     ...  ..
69   大澤 宗春   B  弓道部  201905  67
70   大澤 宗春   B  弓道部  201908  83

[10 rows x 5 columns]

Empty DataFrame
Columns: [名前, クラス, クラブ, 実施月, 数学]
Index: []

クエリを正しくしてください

In [5]:
names = ["名前", "クラス", "クラブ", "実施月", "数学"]

In [6]:
query_bot("input/exam.xlsx", header=1, names=names, max_rows=10)

クエリーを入力してください。空Enterで終了します。

        名前 クラス  クラブ     実施月  数学
0   松原 勇二郎   A  弓道部  201905  93
1   松原 勇二郎   A  弓道部  201908  69
2   吉澤 あきの   A  NaN  201905  71
3   吉澤 あきの   A  NaN  201908  76
4     平山 詩   A  写真部  201905  80
..     ...  ..  ...     ...  ..
30   前野 麗菜   A  剣道部  201908  70
31    西沢 匡   A  弓道部  201905  88
32    西沢 匡   A  弓道部  201908  79
33   沼田 悠斗   A  NaN  201905  61
34   沼田 悠斗   A  NaN  201908  71

[35 rows x 5 columns]