###### 130_3_practical_defect_check_master_dict.ipynb

In [13]:
#cell1
import pandas as pd
pd.set_option("display.max_columns", None)

In [14]:
#cell 2

df_defect = pd.DataFrame(
    [
        ["D001", "SUS", "J69P", "コイル", 3],
        ["D002", "SUS", "J69P", "Buck-IC", 1],
        ["D003", "WSE", "310D", "コイル", 2],
        ["D004", "GSE", "J69P", "Buck-IC", 2],
        ["D005", "MELMB", "310D", "NTF", 1],
        ["D006", "ISE", "J69P", "CAN通信", 1],
        ["D007", "SUS", "310D", "NTF", 0],
        ["D008", "MELMB", "310D", "コイル", 5],
        ["D009", "GSE", "J69P", "コイル", 1],
    ],
    columns=[
        "defect_id",
        "site",
        "model",
        "defect_category",
        "defect_qty",
    ],
)

df_defect

  defect_id   site model defect_category  defect_qty
0      D001    SUS  J69P             コイル           3
1      D002    SUS  J69P         Buck-IC           1
2      D003    WSE  310D             コイル           2
3      D004    GSE  J69P         Buck-IC           2
4      D005  MELMB  310D             NTF           1
5      D006    ISE  J69P           CAN通信           1
6      D007    SUS  310D             NTF           0
7      D008  MELMB  310D             コイル           5
8      D009    GSE  J69P             コイル           1

In [15]:
df_check_master = pd.DataFrame(
    [
        ["コイル", "断面観察"],
        ["コイル", "インパルス検査条件確認"],
        ["コイル", "巻線状態・鉄粉混入確認"],
        ["Buck-IC", "外観焼損確認"],
        ["Buck-IC", "Lot / DateCode確認"],
        ["Buck-IC", "メーカー解析依頼状況確認"],
        ["NTF", "再現試験条件確認"],
        ["NTF", "車両側・単品側の切り分け確認"],
    ],
    columns=[
        "defect_category",
        "check_item",
    ],
)
df_check_master

  defect_category        check_item
0             コイル              断面観察
1             コイル       インパルス検査条件確認
2             コイル       巻線状態・鉄粉混入確認
3         Buck-IC            外観焼損確認
4         Buck-IC  Lot / DateCode確認
5         Buck-IC      メーカー解析依頼状況確認
6             NTF          再現試験条件確認
7             NTF    車両側・単品側の切り分け確認

In [16]:
#cell4
df_owner_master = pd.DataFrame(
    [
        ["コイル", "部品/サプライヤ確認", "高"],
        ["Buck-IC", "電子部品解析", "高"],
        ["NTF", "再現確認チーム", "中"],
    ],
    columns=[
        "defect_category",
        "owner_team",
        "priority"
    ],
)
df_owner_master

  defect_category  owner_team priority
0             コイル  部品/サプライヤ確認        高
1         Buck-IC      電子部品解析        高
2             NTF     再現確認チーム        中

In [17]:
df_defect_positive = df_defect[
    df_defect["defect_qty"] > 0
].copy()

df_defect_positive

  defect_id   site model defect_category  defect_qty
0      D001    SUS  J69P             コイル           3
1      D002    SUS  J69P         Buck-IC           1
2      D003    WSE  310D             コイル           2
3      D004    GSE  J69P         Buck-IC           2
4      D005  MELMB  310D             NTF           1
5      D006    ISE  J69P           CAN通信           1
7      D008  MELMB  310D             コイル           5
8      D009    GSE  J69P             コイル           1

In [18]:
#cell 6
dict_check_items = (
    df_check_master.groupby("defect_category")["check_item"]
    .apply(list)
    .to_dict()
)
dict_check_items

{'Buck-IC': ['外観焼損確認', 'Lot / DateCode確認', 'メーカー解析依頼状況確認'],
 'NTF': ['再現試験条件確認', '車両側・単品側の切り分け確認'],
 'コイル': ['断面観察', 'インパルス検査条件確認', '巻線状態・鉄粉混入確認']}

In [19]:
#cell7

dict_owner_team = (
    df_owner_master.set_index("defect_category")["owner_team"]
    .to_dict()
)
dict_owner_team

{'コイル': '部品/サプライヤ確認', 'Buck-IC': '電子部品解析', 'NTF': '再現確認チーム'}

In [24]:
#cell3
dict_priority = (
    df_owner_master.set_index("defect_category")["priority"]
    .to_dict()
)
dict_priority

{'コイル': '高', 'Buck-IC': '高', 'NTF': '中'}

In [25]:
#cell9
df_defect_positive["check_item_list"] = (
    df_defect_positive["defect_category"].map(dict_check_items)
)
df_defect_positive

,defect_id,site,model,defect_category,defect_qty,check_item_list
0,D001,SUS,J69P,コイル,3,"[断面観察, インパルス検査条件確認, 巻線状態・鉄粉混入確認]"
1,D002,SUS,J69P,Buck-IC,1,"[外観焼損確認, Lot / DateCode確認, メーカー解析依頼状況確認]"
2,D003,WSE,310D,コイル,2,"[断面観察, インパルス検査条件確認, 巻線状態・鉄粉混入確認]"
3,D004,GSE,J69P,Buck-IC,2,"[外観焼損確認, Lot / DateCode確認, メーカー解析依頼状況確認]"
4,D005,MELMB,310D,NTF,1,"[再現試験条件確認, 車両側・単品側の切り分け確認]"
5,D006,ISE,J69P,CAN通信,1,NaN
7,D008,MELMB,310D,コイル,5,"[断面観察, インパルス検査条件確認, 巻線状態・鉄粉混入確認]"
8,D009,GSE,J69P,コイル,1,"[断面観察, インパルス検査条件確認, 巻線状態・鉄粉混入確認]"

In [26]:
#cell10
df_defect_positive["owner_team"] = (
    df_defect_positive["defect_category"].map(dict_owner_team)
)
df_defect_positive

,defect_id,site,model,defect_category,defect_qty,check_item_list,owner_team
0,D001,SUS,J69P,コイル,3,"[断面観察, インパルス検査条件確認, 巻線状態・鉄粉混入確認]",部品/サプライヤ確認
1,D002,SUS,J69P,Buck-IC,1,"[外観焼損確認, Lot / DateCode確認, メーカー解析依頼状況確認]",電子部品解析
2,D003,WSE,310D,コイル,2,"[断面観察, インパルス検査条件確認, 巻線状態・鉄粉混入確認]",部品/サプライヤ確認
3,D004,GSE,J69P,Buck-IC,2,"[外観焼損確認, Lot / DateCode確認, メーカー解析依頼状況確認]",電子部品解析
4,D005,MELMB,310D,NTF,1,"[再現試験条件確認, 車両側・単品側の切り分け確認]",再現確認チーム
5,D006,ISE,J69P,CAN通信,1,NaN,NaN
7,D008,MELMB,310D,コイル,5,"[断面観察, インパルス検査条件確認, 巻線状態・鉄粉混入確認]",部品/サプライヤ確認
8,D009,GSE,J69P,コイル,1,"[断面観察, インパルス検査条件確認, 巻線状態・鉄粉混入確認]",部品/サプライヤ確認

In [34]:
#cell 12
df_defect_positive["check_status"] = "登録あり"
df_defect_positive.head()

df_defect_positive.loc[
    df_defect_positive["check_item_list"].isna(),
    "check_status",
] = "マスター未登録"
df_defect_positive

,defect_id,site,model,defect_category,defect_qty,check_item_list,owner_team,priority,check_status
0,D001,SUS,J69P,コイル,3,"[断面観察, インパルス検査条件確認, 巻線状態・鉄粉混入確認]",部品/サプライヤ確認,高,登録あり
1,D002,SUS,J69P,Buck-IC,1,"[外観焼損確認, Lot / DateCode確認, メーカー解析依頼状況確認]",電子部品解析,高,登録あり
2,D003,WSE,310D,コイル,2,"[断面観察, インパルス検査条件確認, 巻線状態・鉄粉混入確認]",部品/サプライヤ確認,高,登録あり
3,D004,GSE,J69P,Buck-IC,2,"[外観焼損確認, Lot / DateCode確認, メーカー解析依頼状況確認]",電子部品解析,高,登録あり
4,D005,MELMB,310D,NTF,1,"[再現試験条件確認, 車両側・単品側の切り分け確認]",再現確認チーム,中,登録あり
5,D006,ISE,J69P,CAN通信,1,NaN,NaN,NaN,マスター未登録
7,D008,MELMB,310D,コイル,5,"[断面観察, インパルス検査条件確認, 巻線状態・鉄粉混入確認]",部品/サプライヤ確認,高,登録あり
8,D009,GSE,J69P,コイル,1,"[断面観察, インパルス検査条件確認, 巻線状態・鉄粉混入確認]",部品/サプライヤ確認,高,登録あり

In [36]:
df_unregistered = df_defect_positive[
    df_defect_positive["check_status"] == "マスター未登録"
].copy()

df_unregistered

,defect_id,site,model,defect_category,defect_qty,check_item_list,owner_team,priority,check_status
5,D006,ISE,J69P,CAN通信,1,NaN,NaN,NaN,マスター未登録

In [39]:
#cell 14
df_investigation_list = df_defect_positive[
    [
        "defect_id",
        "site",
        "model",
        "defect_category",
        "defect_qty",
        "owner_team",
        "priority",
        "check_status",
        "check_item_list",
    ]
].copy()
df_investigation_list

,defect_id,site,model,defect_category,defect_qty,owner_team,priority,check_status,check_item_list
0,D001,SUS,J69P,コイル,3,部品/サプライヤ確認,高,登録あり,"[断面観察, インパルス検査条件確認, 巻線状態・鉄粉混入確認]"
1,D002,SUS,J69P,Buck-IC,1,電子部品解析,高,登録あり,"[外観焼損確認, Lot / DateCode確認, メーカー解析依頼状況確認]"
2,D003,WSE,310D,コイル,2,部品/サプライヤ確認,高,登録あり,"[断面観察, インパルス検査条件確認, 巻線状態・鉄粉混入確認]"
3,D004,GSE,J69P,Buck-IC,2,電子部品解析,高,登録あり,"[外観焼損確認, Lot / DateCode確認, メーカー解析依頼状況確認]"
4,D005,MELMB,310D,NTF,1,再現確認チーム,中,登録あり,"[再現試験条件確認, 車両側・単品側の切り分け確認]"
5,D006,ISE,J69P,CAN通信,1,NaN,NaN,マスター未登録,NaN
7,D008,MELMB,310D,コイル,5,部品/サプライヤ確認,高,登録あり,"[断面観察, インパルス検査条件確認, 巻線状態・鉄粉混入確認]"
8,D009,GSE,J69P,コイル,1,部品/サプライヤ確認,高,登録あり,"[断面観察, インパルス検査条件確認, 巻線状態・鉄粉混入確認]"