###### 129_6_cut_value_category_practice.ipynb

In [8]:
import numpy as np
import pandas as pd

In [10]:
rnd = np.random.default_rng(3)
df = pd.DataFrame(
    rnd.standard_normal(100),
    columns=[
        "Value",
    ],
)
df

       Value
0   2.040919
1  -2.555665
2   0.418099
3  -0.567770
4  -0.452649
..       ...
95 -1.730013
96 -0.004414
97  1.213564
98  0.757058
99  0.215651

[100 rows x 1 columns]

In [11]:
bins = [
    -np.inf,
    -2,
    -1,
    0,
    1,
    2,
    np.inf,
]

In [12]:
df["Category"] = pd.cut(
    df["Value"],
    bins,
)
df

       Value      Category
0   2.040919    (2.0, inf]
1  -2.555665  (-inf, -2.0]
2   0.418099    (0.0, 1.0]
3  -0.567770   (-1.0, 0.0]
4  -0.452649   (-1.0, 0.0]
..       ...           ...
95 -1.730013  (-2.0, -1.0]
96 -0.004414   (-1.0, 0.0]
97  1.213564    (1.0, 2.0]
98  0.757058    (0.0, 1.0]
99  0.215651    (0.0, 1.0]

[100 rows x 2 columns]