In [1]:
import datetime
%run practice_120_2_step2.ipynb

Date datetime64[ns]
Date datetime64[ns]
Date datetime64[ns]
Date datetime64[ns]

In [3]:
df_sale.head()

            Num Product  Price    Sale
Date
2017-01-03  1.0       B   1200  1200.0
2017-01-06  2.0       B   1200  2400.0
2017-01-07  1.0       A   1000  1000.0
2017-01-11  2.0       A   1000  2000.0
2017-01-12  2.0       B   1200  2400.0

In [4]:
df_sale.loc[datetime.datetime(2017, 1, 3)]

Num           1.0
Product         B
Price        1200
Sale       1200.0
Name: 2017-01-03 00:00:00, dtype: object

In [5]:
df_sale.loc["2017/1/3"]

Num           1.0
Product         B
Price        1200
Sale       1200.0
Name: 2017-01-03 00:00:00, dtype: object

In [6]:
df_sale.iloc[0]

Num           1.0
Product         B
Price        1200
Sale       1200.0
Name: 2017-01-03 00:00:00, dtype: object

In [8]:
#df_sale.loc["2017/1/1"]

In [9]:
df_sale_slice = df_sale.loc["2017/1/1":"2017/1/7"]
df_sale_slice

            Num Product  Price    Sale
Date
2017-01-03  1.0       B   1200  1200.0
2017-01-06  2.0       B   1200  2400.0
2017-01-07  1.0       A   1000  1000.0

In [10]:
import datetime
%run practice_120_2_step2.ipynb
df_sale.head()

Date datetime64[ns]
Date datetime64[ns]
Date datetime64[ns]
Date datetime64[ns]

            Num Product  Price    Sale
Date
2017-01-03  1.0       B   1200  1200.0
2017-01-06  2.0       B   1200  2400.0
2017-01-07  1.0       A   1000  1000.0
2017-01-11  2.0       A   1000  2000.0
2017-01-12  2.0       B   1200  2400.0

In [11]:
df_sale.loc[datetime.datetime(2017, 1, 3)]

Num           1.0
Product         B
Price        1200
Sale       1200.0
Name: 2017-01-03 00:00:00, dtype: object

In [12]:
df_sale.loc["2017/1/3"]

Num           1.0
Product         B
Price        1200
Sale       1200.0
Name: 2017-01-03 00:00:00, dtype: object

In [13]:
df_sale.iloc[0]

Num           1.0
Product         B
Price        1200
Sale       1200.0
Name: 2017-01-03 00:00:00, dtype: object

In [14]:
df_sale_slice = df_sale.loc["2017/1/1":"2017/1/7"]
df_sale_slice

            Num Product  Price    Sale
Date
2017-01-03  1.0       B   1200  1200.0
2017-01-06  2.0       B   1200  2400.0
2017-01-07  1.0       A   1000  1000.0

In [15]:
df_sale.loc["2017/1/6"]

Num           2.0
Product         B
Price        1200
Sale       2400.0
Name: 2017-01-06 00:00:00, dtype: object

In [16]:
df_sale.iloc[1]

Num           2.0
Product         B
Price        1200
Sale       2400.0
Name: 2017-01-06 00:00:00, dtype: object

In [17]:
df_sale.loc["2017/1/3":"2017/1/12"]

            Num Product  Price    Sale
Date
2017-01-03  1.0       B   1200  1200.0
2017-01-06  2.0       B   1200  2400.0
2017-01-07  1.0       A   1000  1000.0
2017-01-11  2.0       A   1000  2000.0
2017-01-12  2.0       B   1200  2400.0

In [18]:
df_sale_slice = df_sale.loc["2017/1/1":"2017/1/7"]
df_sale_slice.shape

(3, 4)

In [19]:
df_sale_slice

            Num Product  Price    Sale
Date
2017-01-03  1.0       B   1200  1200.0
2017-01-06  2.0       B   1200  2400.0
2017-01-07  1.0       A   1000  1000.0