In [5]:
import pandas as pd
import datetime

df_sale = pd.read_csv(
    "dataset/product_sale.csv",
    parse_dates=["Date"],
    index_col="Date"
)

print(df_sale.index.name, df_sale.index.dtype)

Date datetime64[ns]

In [6]:
df_sale2 = pd.read_csv("dataset/product_sale.csv")
df_sale2.head()

         Date  Num Product  Price    Sale
0  2017-01-03  1.0       B   1200  1200.0
1  2017-01-06  2.0       B   1200  2400.0
2  2017-01-07  1.0       A   1000  1000.0
3  2017-01-11  2.0       A   1000  2000.0
4  2017-01-12  2.0       B   1200  2400.0

In [7]:
df_sale2["Date"] = df_sale2["Date"].apply(pd.to_datetime)
df_sale2.dtypes

Date       datetime64[ns]
Num               float64
Product            object
Price               int64
Sale              float64
dtype: object

In [9]:
df_sale3 = df_sale2.set_index("Date")
print(df_sale3.index.name, df_sale3.index.dtype)

Date datetime64[ns]

In [10]:
df_sale = pd.read_csv(
    "dataset/product_sale.csv",
    parse_dates=["Date"],
    index_col="Date"
)
print(df_sale.index.name, df_sale.index.dtype)

Date datetime64[ns]

In [12]:
df_sale2 = pd.read_csv("dataset/product_sale.csv")
df_sale2["Date"] = df_sale2["Date"].apply(pd.to_datetime)
df_sale3 = df_sale2.set_index("Date")

print(df_sale3.index.name, df_sale3.index.dtype)

Date datetime64[ns]

In [13]:
df_sale2 = pd.read_csv("dataset/product_sale.csv")
df_sale2["Date"] = pd.to_datetime(df_sale2["Date"])
df_sale2.dtypes

Date       datetime64[ns]
Num               float64
Product            object
Price               int64
Sale              float64
dtype: object

In [14]:
df_sale2.head()

        Date  Num Product  Price    Sale
0 2017-01-03  1.0       B   1200  1200.0
1 2017-01-06  2.0       B   1200  2400.0
2 2017-01-07  1.0       A   1000  1000.0
3 2017-01-11  2.0       A   1000  2000.0
4 2017-01-12  2.0       B   1200  2400.0

In [16]:
df_sale2 = pd.read_csv("dataset/product_sale.csv")
df_sale2["Date"] = pd.to_datetime(df_sale2["Date"])
df_sale3 = df_sale2.set_index("Date")

df_sale3.head()

            Num Product  Price    Sale
Date
2017-01-03  1.0       B   1200  1200.0
2017-01-06  2.0       B   1200  2400.0
2017-01-07  1.0       A   1000  1000.0
2017-01-11  2.0       A   1000  2000.0
2017-01-12  2.0       B   1200  2400.0