###### 133_6_number_format.ipynb

In [1]:
import pandas as pd

In [3]:
df = pd.read_csv(
    "dataset/ctr.csv",
)

In [4]:
display(df)

         月   表示数  クリック数     クリック率  クリック数の変化率
0  2022-01  2010    162  0.080597        NaN
1  2022-02  2140    158  0.073832  -0.024691
2  2022-03  2429    198  0.081515   0.253165
3  2022-04  2340    198  0.084615   0.000000

In [5]:
display(
    df.style.format(
        precision=3,
    )
)

In [6]:
display(df)

         月   表示数  クリック数     クリック率  クリック数の変化率
0  2022-01  2010    162  0.080597        NaN
1  2022-02  2140    158  0.073832  -0.024691
2  2022-03  2429    198  0.081515   0.253165
3  2022-04  2340    198  0.084615   0.000000