###### 133_6_practical_lcm_number_format.ipynb

In [47]:
import pandas as pd

In [48]:
df = pd.read_csv(
    "dataset/lcm_monthly_quality_format_practice.csv",
)

In [49]:
display(df)

     site    month inspection_qty_raw defect_qty_raw   ppm_raw change_rate_raw
0     SUS  2026-06            1250000              8  6.400000             NaN
1     SUS  2026-07            1320000              7  5.303030       -0.125000
2     SUS  2026-08            1410000              6  4.255319       -0.142857
3     SUS  2026-09            1480000              5  3.378378       -0.166667
4     GSE  2026-06             820000              6  7.317073             NaN
5     GSE  2026-07             850000              5  5.882353       -0.166667
6     GSE  2026-08             900000              4  4.444444       -0.200000
7     GSE  2026-09             930000              4  4.301075        0.000000
8   MELMB  2026-06             980000              7  7.142857             NaN
9   MELMB  2026-07            1020000              6  5.882353       -0.142857
10  MELMB  2026-08                未確認              5  4.761905       -0.166667
11  MELMB  2026-09            1120000          error  4.464286       -0.100000
12   META  2026-06             760000              5  6.578947             NaN
13   META  2026-07             810000              4       確認中       -0.200000
14   META  2026-08             845000              4  4.733728             要確認

In [50]:
df.dtypes

site                  object
month                 object
inspection_qty_raw    object
defect_qty_raw        object
ppm_raw               object
change_rate_raw       object
dtype: object

In [51]:
df["inspection_qty"] = pd.to_numeric(
    df["inspection_qty_raw"],
    errors="coerce",
)

In [52]:
df["inspection_qty"].dtypes

dtype('float64')

In [53]:
df["inspection_qty_raw"].dtypes

dtype('O')

In [54]:
#cell 5 残りの列も数値化する。
df["defect_qty"] = pd.to_numeric(
    df["defect_qty_raw"],
    errors="coerce",
)

df["ppm"] = pd.to_numeric(
    df["ppm_raw"],
    errors="coerce",
)

df["change_rate"] = pd.to_numeric(
    df["change_rate_raw"],
    errors="coerce",
)

In [55]:
df.dtypes

site                   object
month                  object
inspection_qty_raw     object
defect_qty_raw         object
ppm_raw                object
change_rate_raw        object
inspection_qty        float64
defect_qty            float64
ppm                   float64
change_rate           float64
dtype: object

In [56]:
#cell 6
mask_inspection_ng = (
    df["inspection_qty_raw"].notna()
    & df["inspection_qty"].isna()
)

In [57]:
mask_defect_ng = (
    df["defect_qty_raw"].notna()
    & df["defect_qty"].isna()
)

mask_ppm_ng = (
    df["ppm_raw"].notna()
    & df["ppm"].isna()
)

mask_change_rate_ng = (
    df["change_rate_raw"].notna()
    & df["change_rate"].isna()
)

In [58]:
#cell 8
mask_any_ng = (
    mask_inspection_ng
    | mask_defect_ng
    | mask_ppm_ng
    | mask_change_rate_ng
)

In [59]:
#cell 9
df_ng = df[
    mask_any_ng
].copy()
display(df_ng)

,site,month,inspection_qty_raw,defect_qty_raw,ppm_raw,change_rate_raw,inspection_qty,defect_qty,ppm,change_rate
10,MELMB,2026-08,未確認,5,4.761905,-0.166667,NaN,5.0,4.761905,-0.166667
11,MELMB,2026-09,1120000,error,4.464286,-0.100000,1120000.0,NaN,4.464286,-0.100000
13,META,2026-07,810000,4,確認中,-0.200000,810000.0,4.0,NaN,-0.200000
14,META,2026-08,845000,4,4.733728,要確認,845000.0,4.0,4.733728,NaN

In [60]:
df_work  = df[
    ~mask_any_ng
].copy()

In [61]:
df_work.dtypes

site                   object
month                  object
inspection_qty_raw     object
defect_qty_raw         object
ppm_raw                object
change_rate_raw        object
inspection_qty        float64
defect_qty            float64
ppm                   float64
change_rate           float64
dtype: object

In [62]:
df_display = df_work[
    [
        "site",
        "month",
        "inspection_qty",
        "defect_qty",
        "ppm",
        "change_rate",
    ]
].copy()

In [63]:
display(df_display)

     site    month  inspection_qty  defect_qty       ppm  change_rate
0     SUS  2026-06       1250000.0         8.0  6.400000          NaN
1     SUS  2026-07       1320000.0         7.0  5.303030    -0.125000
2     SUS  2026-08       1410000.0         6.0  4.255319    -0.142857
3     SUS  2026-09       1480000.0         5.0  3.378378    -0.166667
4     GSE  2026-06        820000.0         6.0  7.317073          NaN
5     GSE  2026-07        850000.0         5.0  5.882353    -0.166667
6     GSE  2026-08        900000.0         4.0  4.444444    -0.200000
7     GSE  2026-09        930000.0         4.0  4.301075     0.000000
8   MELMB  2026-06        980000.0         7.0  7.142857          NaN
9   MELMB  2026-07       1020000.0         6.0  5.882353    -0.142857
12   META  2026-06        760000.0         5.0  6.578947          NaN

In [64]:
display(df_display)

     site    month  inspection_qty  defect_qty       ppm  change_rate
0     SUS  2026-06       1250000.0         8.0  6.400000          NaN
1     SUS  2026-07       1320000.0         7.0  5.303030    -0.125000
2     SUS  2026-08       1410000.0         6.0  4.255319    -0.142857
3     SUS  2026-09       1480000.0         5.0  3.378378    -0.166667
4     GSE  2026-06        820000.0         6.0  7.317073          NaN
5     GSE  2026-07        850000.0         5.0  5.882353    -0.166667
6     GSE  2026-08        900000.0         4.0  4.444444    -0.200000
7     GSE  2026-09        930000.0         4.0  4.301075     0.000000
8   MELMB  2026-06        980000.0         7.0  7.142857          NaN
9   MELMB  2026-07       1020000.0         6.0  5.882353    -0.142857
12   META  2026-06        760000.0         5.0  6.578947          NaN

In [68]:
display(
    df_display.style.format(
        {
            "inspection_qty": "{:,.0f}",
            "defect_aty": "{:.0f}",
            "ppm": "{:.1f}",
            "change_rate": "{:.1%}",
        },
        na_rep="-",
    )
)

In [67]:
display(df_display)

     site    month  inspection_qty  defect_qty       ppm  change_rate
0     SUS  2026-06       1250000.0         8.0  6.400000          NaN
1     SUS  2026-07       1320000.0         7.0  5.303030    -0.125000
2     SUS  2026-08       1410000.0         6.0  4.255319    -0.142857
3     SUS  2026-09       1480000.0         5.0  3.378378    -0.166667
4     GSE  2026-06        820000.0         6.0  7.317073          NaN
5     GSE  2026-07        850000.0         5.0  5.882353    -0.166667
6     GSE  2026-08        900000.0         4.0  4.444444    -0.200000
7     GSE  2026-09        930000.0         4.0  4.301075     0.000000
8   MELMB  2026-06        980000.0         7.0  7.142857          NaN
9   MELMB  2026-07       1020000.0         6.0  5.882353    -0.142857
12   META  2026-06        760000.0         5.0  6.578947          NaN