###### 132_7_fill_missing_dates_answer.ipynb

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv(
    "dataset/study_total_minutes.csv",
    parse_dates=["date"],
    index_col="date",
)
df

            total_minutes
date
2022-01-01             32
2022-01-03            156
2022-01-05            201
2022-01-06             34

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 4 entries, 2022-01-01 to 2022-01-06
Data columns (total 1 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   total_minutes  4 non-null      int64
dtypes: int64(1)
memory usage: 64.0 bytes

In [4]:
filled_df = df.asfreq(
    "D",
    fill_value=0,
)
filled_df

            total_minutes
date
2022-01-01             32
2022-01-02              0
2022-01-03            156
2022-01-04              0
2022-01-05            201
2022-01-06             34