###### 129_6_cut_groupby_inspection_category_answer.ipynb

In [1]:
#cell1
import pandas as pd
import numpy as np

In [2]:
#cell2
df = pd.DataFrame(
    [
        ["D001", "J69P", "MELMB", "コイル", 3, 12000, "調査中"],
        ["D002", "J69P", "WSE", "Buck-IC", 5, 18000, "対策検討中"],
        ["D003", "310D", "GSE", "コイル", 12, 25000, "暫定対策済"],
        ["D004", "310D", "MELMB", "はんだ", 2, 9000, "調査中"],
        ["D005", "J69P", "GSE", "コイル", 7, 15000, "調査中"],
        ["D006", "310D", "WSE", "コネクタ", 1, 6000, "完了"],
        ["D007", "J69P", "MELMB", "Buck-IC", 8, 20000, "調査中"],
        ["D008", "310D", "GSE", "コイル", 4, 10000, "対策検討中"],
        ["D009", "J69P", "GSE", "Buck-IC", 6, 14000, "調査中"],
        ["D010", "310D", "MELMB", "コイル", 5, 16000, "暫定対策済"],
        ["D011", "J69P", "WSE", "コイル", 9, 22000, "調査中"],
        ["D012", "310D", "GSE", "はんだ", 3, 8000, "完了"],
    ],
    columns=[
        "defect_id",
        "project",
        "site",
        "defect_category",
        "defect_qty",
        "inspection_qty",
        "status",
    ],
)
df

   defect_id project   site defect_category  defect_qty  inspection_qty status
0       D001    J69P  MELMB             コイル           3           12000    調査中
1       D002    J69P    WSE         Buck-IC           5           18000  対策検討中
2       D003    310D    GSE             コイル          12           25000  暫定対策済
3       D004    310D  MELMB             はんだ           2            9000    調査中
4       D005    J69P    GSE             コイル           7           15000    調査中
5       D006    310D    WSE            コネクタ           1            6000     完了
6       D007    J69P  MELMB         Buck-IC           8           20000    調査中
7       D008    310D    GSE             コイル           4           10000  対策検討中
8       D009    J69P    GSE         Buck-IC           6           14000    調査中
9       D010    310D  MELMB             コイル           5           16000  暫定対策済
10      D011    J69P    WSE             コイル           9           22000    調査中
11      D012    310D    GSE             はんだ           3            8000     完了

In [3]:
#cell3
df_work = df.copy()
df_work

   defect_id project   site defect_category  defect_qty  inspection_qty status
0       D001    J69P  MELMB             コイル           3           12000    調査中
1       D002    J69P    WSE         Buck-IC           5           18000  対策検討中
2       D003    310D    GSE             コイル          12           25000  暫定対策済
3       D004    310D  MELMB             はんだ           2            9000    調査中
4       D005    J69P    GSE             コイル           7           15000    調査中
5       D006    310D    WSE            コネクタ           1            6000     完了
6       D007    J69P  MELMB         Buck-IC           8           20000    調査中
7       D008    310D    GSE             コイル           4           10000  対策検討中
8       D009    J69P    GSE         Buck-IC           6           14000    調査中
9       D010    310D  MELMB             コイル           5           16000  暫定対策済
10      D011    J69P    WSE             コイル           9           22000    調査中
11      D012    310D    GSE             はんだ           3            8000     完了

In [4]:
bins = [
    0,
    10000,
    20000,
    np.inf,
]

labels = [
    "少ない",
    "普通",
    "多い",
]

In [5]:
df_work["inspection_category"] = pd.cut(
    df_work["inspection_qty"],
    bins=bins,
    labels=labels,
    include_lowest=True,
)
df_work

,defect_id,project,site,defect_category,defect_qty,inspection_qty,status,inspection_category
0,D001,J69P,MELMB,コイル,3,12000,調査中,普通
1,D002,J69P,WSE,Buck-IC,5,18000,対策検討中,普通
2,D003,310D,GSE,コイル,12,25000,暫定対策済,多い
3,D004,310D,MELMB,はんだ,2,9000,調査中,少ない
4,D005,J69P,GSE,コイル,7,15000,調査中,普通
5,D006,310D,WSE,コネクタ,1,6000,完了,少ない
6,D007,J69P,MELMB,Buck-IC,8,20000,調査中,普通
7,D008,310D,GSE,コイル,4,10000,対策検討中,少ない
8,D009,J69P,GSE,Buck-IC,6,14000,調査中,普通
9,D010,310D,MELMB,コイル,5,16000,暫定対策済,普通
10,D011,J69P,WSE,コイル,9,22000,調査中,多い
11,D012,310D,GSE,はんだ,3,8000,完了,少ない

In [6]:
#cell6
df_category_summary = df_work.groupby(
    "inspection_category",
    as_index=False,
    observed=False,
)["defect_qty"].sum()
df_category_summary

  inspection_category  defect_qty
0                 少ない          10
1                  普通          34
2                  多い          21

In [8]:
#cell7
df_category_summary = df_category_summary.rename(
    columns={
        "defect_qty": "total_defect_qty",
    }
)
df_category_summary

  inspection_category  total_defect_qty
0                 少ない                10
1                  普通                34
2                  多い                21

In [9]:
df_category_report = df_category_summary.sort_values(
    "total_defect_qty",
    ascending=False,
)
df_category_report

  inspection_category  total_defect_qty
1                  普通                34
2                  多い                21
0                 少ない                10