In [21]:
import pandas as pd
df = pd.read_csv("service_detail_step4_sample.csv")
df.head()

      レンタル開始日  顧客名  個数  期間 プラン  個数x期間    単価    契約金額 契約規模
0  2018/04/01  顧客A  15   1  通常     15  6000   90000   小口
1  2018/06/15  顧客A  20   2  通常     40  6000  240000   中口
2  2018/04/05  顧客B  15   2  学割     30  3500  105000   中口
3  2018/07/05  顧客B  15   2  学割     30  3500  105000   中口
4  2018/04/20  顧客C  10   2  通常     20  6000  120000   中口

In [22]:
grouped = df.groupby("顧客名")
grouped

In [23]:
grouped = df.groupby("顧客名")
grouped.size()

顧客名
顧客A    2
顧客B    2
顧客C    2
顧客D    1
顧客E    2
顧客F    2
顧客G    1
dtype: int64

In [24]:
grouped = df.groupby("顧客名")
grouped["契約金額"].sum()

顧客名
顧客A    330000
顧客B    210000
顧客C    720000
顧客D    216000
顧客E    300000
顧客F    768000
顧客G    180000
Name: 契約金額, dtype: int64

In [25]:
grouped = df.groupby("顧客名")
grouped["レンタル開始日"].min()

顧客名
顧客A    2018/04/01
顧客B    2018/04/05
顧客C    2018/04/20
顧客D    2018/09/02
顧客E    2018/10/01
顧客F    2019/01/10
顧客G    2019/03/20
Name: レンタル開始日, dtype: object

In [26]:
def count_small(x):
    return (x == "小口").sum()

In [27]:
grouped = df.groupby("顧客名")

def count_small(x):
    return (x == "小口").sum()
grouped["契約規模"].agg(count_small)

顧客名
顧客A    1
顧客B    0
顧客C    0
顧客D    0
顧客E    1
顧客F    1
顧客G    0
Name: 契約規模, dtype: int64

In [28]:
def count_by_category(x, category):
    return (x == category).sum()

In [29]:
import pandas as pd
df = pd.read_csv("service_detail_step4_sample.csv")

summary_df = pd.DataFrame(index=df["顧客名"].unique())
grouped = df.groupby("顧客名")

summary_df["初回レンタル開始日"] = grouped["レンタル開始日"].min()
summary_df

      初回レンタル開始日
顧客A  2018/04/01
顧客B  2018/04/05
顧客C  2018/04/20
顧客D  2018/09/02
顧客E  2018/10/01
顧客F  2019/01/10
顧客G  2019/03/20

In [30]:
import pandas as pd

df = pd.read_csv("service_detail_step4_sample.csv")

summary_df = pd.DataFrame(index=df["顧客名"].unique())
grouped = df.groupby("顧客名")

def count_by_category(x, category):
    return (x == category).sum()

for category in ["小口", "中口", "大口"]:
    summary_df[f"契約回数_{category}"] = grouped["契約規模"].agg(
        count_by_category, category=category
    )
summary_df

     契約回数_小口  契約回数_中口  契約回数_大口
顧客A        1        1        0
顧客B        0        2        0
顧客C        0        1        1
顧客D        0        1        0
顧客E        1        1        0
顧客F        1        0        1
顧客G        0        1        0

In [31]:
import pandas as pd
df = pd.read_csv("service_detail_step4_sample.csv")
grouped = df.groupby("顧客名")

summary_df = pd.DataFrame()
summary_df["契約回数"] = grouped.size()
summary_df["契約金額合計"] = grouped["契約金額"].sum()
summary_df["初回レンタル開始日"] = grouped["レンタル開始日"].min()

def count_by_category(x, category):
    return (x == category).sum()

for category in ["小口", "中口", "大口"]:
    summary_df[f"契約回数_{category}"] = grouped["契約規模"].agg(
        count_by_category, category=category
    )

summary_df

     契約回数  契約金額合計   初回レンタル開始日  契約回数_小口  契約回数_中口  契約回数_大口
顧客名
顧客A     2  330000  2018/04/01        1        1        0
顧客B     2  210000  2018/04/05        0        2        0
顧客C     2  720000  2018/04/20        0        1        1
顧客D     1  216000  2018/09/02        0        1        0
顧客E     2  300000  2018/10/01        1        1        0
顧客F     2  768000  2019/01/10        1        0        1
顧客G     1  180000  2019/03/20        0        1        0

In [34]:
summary_df = summary_df.sort_values(
    ["契約金額合計", "初回レンタル開始日"],
    ascending=False
)
summary_df

     契約回数  契約金額合計   初回レンタル開始日  契約回数_小口  契約回数_中口  契約回数_大口
顧客名
顧客F     2  768000  2019/01/10        1        0        1
顧客C     2  720000  2018/04/20        0        1        1
顧客A     2  330000  2018/04/01        1        1        0
顧客E     2  300000  2018/10/01        1        1        0
顧客D     1  216000  2018/09/02        0        1        0
顧客B     2  210000  2018/04/05        0        2        0
顧客G     1  180000  2019/03/20        0        1        0