###### 129_5_quality_top3_rank_practice

In [2]:
#cell 1
import pandas as pd

In [3]:
df = pd.DataFrame(
    [
        ["D001", "J69P", "MELMB", "コイル", 3, "調査中"],
        ["D002", "J69P", "WSE", "Buck-IC", 5, "対策検討中"],
        ["D003", "310D", "GSE", "コイル", 12, "暫定対策済"],
        ["D004", "310D", "MELMB", "はんだ", 2, "調査中"],
        ["D005", "J69P", "GSE", "コイル", 12, "調査中"],
        ["D006", "310D", "WSE", "コネクタ", 1, "完了"],
        ["D007", "J69P", "MELMB", "Buck-IC", 8, "調査中"],
        ["D008", "310D", "GSE", "コイル", 4, "対策検討中"],
    ],
    columns=[
        "defect_id",
        "project",
        "site",
        "defect_category",
        "defect_qty",
        "status",
    ],
)
df

  defect_id project   site defect_category  defect_qty status
0      D001    J69P  MELMB             コイル           3    調査中
1      D002    J69P    WSE         Buck-IC           5  対策検討中
2      D003    310D    GSE             コイル          12  暫定対策済
3      D004    310D  MELMB             はんだ           2    調査中
4      D005    J69P    GSE             コイル          12    調査中
5      D006    310D    WSE            コネクタ           1     完了
6      D007    J69P  MELMB         Buck-IC           8    調査中
7      D008    310D    GSE             コイル           4  対策検討中

In [4]:
df_work = df.copy()
df_work

  defect_id project   site defect_category  defect_qty status
0      D001    J69P  MELMB             コイル           3    調査中
1      D002    J69P    WSE         Buck-IC           5  対策検討中
2      D003    310D    GSE             コイル          12  暫定対策済
3      D004    310D  MELMB             はんだ           2    調査中
4      D005    J69P    GSE             コイル          12    調査中
5      D006    310D    WSE            コネクタ           1     完了
6      D007    J69P  MELMB         Buck-IC           8    調査中
7      D008    310D    GSE             コイル           4  対策検討中

In [ ]:
#cell 4
top3_index = df_work["defect_qty"].nlargest(3).index
top3_index

Index([2, 4, 6], dtype='int64')

In [6]:
#cell5
df_work.loc[
    top3_index,
    "priority_rank",
] = [
    1,
    2,
    3,
]
df_work

  defect_id project   site defect_category  defect_qty status  priority_rank
0      D001    J69P  MELMB             コイル           3    調査中            NaN
1      D002    J69P    WSE         Buck-IC           5  対策検討中            NaN
2      D003    310D    GSE             コイル          12  暫定対策済            1.0
3      D004    310D  MELMB             はんだ           2    調査中            NaN
4      D005    J69P    GSE             コイル          12    調査中            2.0
5      D006    310D    WSE            コネクタ           1     完了            NaN
6      D007    J69P  MELMB         Buck-IC           8    調査中            3.0
7      D008    310D    GSE             コイル           4  対策検討中            NaN

In [8]:
#cell 6

df_work["priority_flag"] = "通常確認"
df_work

df_work.loc[
    df_work["priority_rank"].notna(),
    "priority_flag",
] = "重点確認"

df_work

,defect_id,project,site,defect_category,defect_qty,status,priority_rank,priority_flag
0,D001,J69P,MELMB,コイル,3,調査中,NaN,通常確認
1,D002,J69P,WSE,Buck-IC,5,対策検討中,NaN,通常確認
2,D003,310D,GSE,コイル,12,暫定対策済,1.0,重点確認
3,D004,310D,MELMB,はんだ,2,調査中,NaN,通常確認
4,D005,J69P,GSE,コイル,12,調査中,2.0,重点確認
5,D006,310D,WSE,コネクタ,1,完了,NaN,通常確認
6,D007,J69P,MELMB,Buck-IC,8,調査中,3.0,重点確認
7,D008,310D,GSE,コイル,4,対策検討中,NaN,通常確認

In [10]:
#cell 7
df_priority = df_work[
    df_work["priority_flag"] == "重点確認"
].copy()

df_priority = df_priority.sort_values(
    "priority_rank"
)
df_priority

,defect_id,project,site,defect_category,defect_qty,status,priority_rank,priority_flag
2,D003,310D,GSE,コイル,12,暫定対策済,1.0,重点確認
4,D005,J69P,GSE,コイル,12,調査中,2.0,重点確認
6,D007,J69P,MELMB,Buck-IC,8,調査中,3.0,重点確認

In [11]:
#cell8
df_count_summary = pd.DataFrame(
    [
        ["全データ件数", len(df_work)],
        ["重点確認件数", len(df_priority)],
        ["通常確認件数", len(df_work) - len(df_priority)],
    ],
    columns=[
        "確認項目",
        "件数",
    ],
)
df_count_summary

     確認項目  件数
0  全データ件数   8
1  重点確認件数   3
2  通常確認件数   5