###### 130_4_practical_site_category_ppm_rank.ipynb

In [1]:
import pandas as pd
pd.set_option("display.max_columns", None)

In [2]:
df_defect = pd.DataFrame(
    [
        ["2026-06", "SUS", "J69P", "コイル", 3, 12000],
        ["2026-06", "SUS", "J69P", "Buck-IC", 1, 12000],
        ["2026-06", "SUS", "310D", "NTF", 2, 8000],
        ["2026-06", "SUS", "310D", "コイル", 0, 8000],
        ["2026-06", "WSE", "J69P", "Buck-IC", 2, 6000],
        ["2026-06", "WSE", "J69P", "コイル", 1, 6000],
        ["2026-06", "WSE", "310D", "コイル", 4, 5000],
        ["2026-06", "WSE", "310D", "NTF", 1, 5000],
        ["2026-06", "GSE", "J69P", "コイル", 2, 4000],
        ["2026-06", "GSE", "J69P", "Buck-IC", 1, 4000],
        ["2026-06", "GSE", "310D", "NTF", 3, 3000],
        ["2026-06", "GSE", "310D", "CAN通信", 1, 3000],
        ["2026-06", "MELMB", "310D", "コイル", 5, 10000],
        ["2026-06", "MELMB", "310D", "NTF", 0, 10000],
        ["2026-06", "MELMB", "J69P", "Buck-IC", 2, 9000],
        ["2026-06", "MELMB", "J69P", "CAN通信", 1, 9000],
    ],
    columns=[
        "month",
        "site",
        "model",
        "defect_category",
        "defect_qty",
        "production_qty",
    ],
)
df_defect

      month   site model defect_category  defect_qty  production_qty
0   2026-06    SUS  J69P             コイル           3           12000
1   2026-06    SUS  J69P         Buck-IC           1           12000
2   2026-06    SUS  310D             NTF           2            8000
3   2026-06    SUS  310D             コイル           0            8000
4   2026-06    WSE  J69P         Buck-IC           2            6000
5   2026-06    WSE  J69P             コイル           1            6000
6   2026-06    WSE  310D             コイル           4            5000
7   2026-06    WSE  310D             NTF           1            5000
8   2026-06    GSE  J69P             コイル           2            4000
9   2026-06    GSE  J69P         Buck-IC           1            4000
10  2026-06    GSE  310D             NTF           3            3000
11  2026-06    GSE  310D           CAN通信           1            3000
12  2026-06  MELMB  310D             コイル           5           10000
13  2026-06  MELMB  310D             NTF           0           10000
14  2026-06  MELMB  J69P         Buck-IC           2            9000
15  2026-06  MELMB  J69P           CAN通信           1            9000

In [3]:
df_work = df_defect.copy()
df_work

      month   site model defect_category  defect_qty  production_qty
0   2026-06    SUS  J69P             コイル           3           12000
1   2026-06    SUS  J69P         Buck-IC           1           12000
2   2026-06    SUS  310D             NTF           2            8000
3   2026-06    SUS  310D             コイル           0            8000
4   2026-06    WSE  J69P         Buck-IC           2            6000
5   2026-06    WSE  J69P             コイル           1            6000
6   2026-06    WSE  310D             コイル           4            5000
7   2026-06    WSE  310D             NTF           1            5000
8   2026-06    GSE  J69P             コイル           2            4000
9   2026-06    GSE  J69P         Buck-IC           1            4000
10  2026-06    GSE  310D             NTF           3            3000
11  2026-06    GSE  310D           CAN通信           1            3000
12  2026-06  MELMB  310D             コイル           5           10000
13  2026-06  MELMB  310D             NTF           0           10000
14  2026-06  MELMB  J69P         Buck-IC           2            9000
15  2026-06  MELMB  J69P           CAN通信           1            9000

In [7]:
df_summary = df_work.groupby(
    [
        "site",
        "defect_category",
    ],
    as_index=False,
).agg(
    defect_qty_total=("defect_qty", "sum"),
    production_qty_total=("production_qty", "sum"),
)
df_summary

     site defect_category  defect_qty_total  production_qty_total
0     GSE         Buck-IC                 1                  4000
1     GSE           CAN通信                 1                  3000
2     GSE             NTF                 3                  3000
3     GSE             コイル                 2                  4000
4   MELMB         Buck-IC                 2                  9000
5   MELMB           CAN通信                 1                  9000
6   MELMB             NTF                 0                 10000
7   MELMB             コイル                 5                 10000
8     SUS         Buck-IC                 1                 12000
9     SUS             NTF                 2                  8000
10    SUS             コイル                 3                 20000
11    WSE         Buck-IC                 2                  6000
12    WSE             NTF                 1                  5000
13    WSE             コイル                 5                 11000

In [5]:
df_summary["defect_ppm"] = 0.0
df_summary

     site defect_category  defectqty_total  production_qty_total  defect_ppm
0     GSE         Buck-IC                1                  4000         0.0
1     GSE           CAN通信                1                  3000         0.0
2     GSE             NTF                3                  3000         0.0
3     GSE             コイル                2                  4000         0.0
4   MELMB         Buck-IC                2                  9000         0.0
5   MELMB           CAN通信                1                  9000         0.0
6   MELMB             NTF                0                 10000         0.0
7   MELMB             コイル                5                 10000         0.0
8     SUS         Buck-IC                1                 12000         0.0
9     SUS             NTF                2                  8000         0.0
10    SUS             コイル                3                 20000         0.0
11    WSE         Buck-IC                2                  6000         0.0
12    WSE             NTF                1                  5000         0.0
13    WSE             コイル                5                 11000         0.0

In [8]:
df_summary.loc[
    df_summary["production_qty_total"] > 0,
    "defect_ppm",
] = (
    df_summary["defect_qty_total"]
    / df_summary["production_qty_total"]
    * 1000000
)
df_summary

     site defect_category  defect_qty_total  production_qty_total   defect_ppm
0     GSE         Buck-IC                 1                  4000   250.000000
1     GSE           CAN通信                 1                  3000   333.333333
2     GSE             NTF                 3                  3000  1000.000000
3     GSE             コイル                 2                  4000   500.000000
4   MELMB         Buck-IC                 2                  9000   222.222222
5   MELMB           CAN通信                 1                  9000   111.111111
6   MELMB             NTF                 0                 10000     0.000000
7   MELMB             コイル                 5                 10000   500.000000
8     SUS         Buck-IC                 1                 12000    83.333333
9     SUS             NTF                 2                  8000   250.000000
10    SUS             コイル                 3                 20000   150.000000
11    WSE         Buck-IC                 2                  6000   333.333333
12    WSE             NTF                 1                  5000   200.000000
13    WSE             コイル                 5                 11000   454.545455

In [10]:
df_summary["ppm_rank"] = df_summary.groupby("site")["defect_ppm"].rank(
    ascending=False
)
df_summary

,site,defect_category,defect_qty_total,production_qty_total,defect_ppm,ppm_rank
0,GSE,Buck-IC,1,4000,250.000000,4.0
1,GSE,CAN通信,1,3000,333.333333,3.0
2,GSE,NTF,3,3000,1000.000000,1.0
3,GSE,コイル,2,4000,500.000000,2.0
4,MELMB,Buck-IC,2,9000,222.222222,2.0
5,MELMB,CAN通信,1,9000,111.111111,3.0
6,MELMB,NTF,0,10000,0.000000,4.0
7,MELMB,コイル,5,10000,500.000000,1.0
8,SUS,Buck-IC,1,12000,83.333333,3.0
9,SUS,NTF,2,8000,250.000000,1.0
10,SUS,コイル,3,20000,150.000000,2.0
11,WSE,Buck-IC,2,6000,333.333333,2.0
12,WSE,NTF,1,5000,200.000000,3.0
13,WSE,コイル,5,11000,454.545455,1.0

In [11]:
df_summary["priority"] = "通常確認"
df_summary

,site,defect_category,defect_qty_total,production_qty_total,defect_ppm,ppm_rank,priority
0,GSE,Buck-IC,1,4000,250.000000,4.0,通常確認
1,GSE,CAN通信,1,3000,333.333333,3.0,通常確認
2,GSE,NTF,3,3000,1000.000000,1.0,通常確認
3,GSE,コイル,2,4000,500.000000,2.0,通常確認
4,MELMB,Buck-IC,2,9000,222.222222,2.0,通常確認
5,MELMB,CAN通信,1,9000,111.111111,3.0,通常確認
6,MELMB,NTF,0,10000,0.000000,4.0,通常確認
7,MELMB,コイル,5,10000,500.000000,1.0,通常確認
8,SUS,Buck-IC,1,12000,83.333333,3.0,通常確認
9,SUS,NTF,2,8000,250.000000,1.0,通常確認
10,SUS,コイル,3,20000,150.000000,2.0,通常確認
11,WSE,Buck-IC,2,6000,333.333333,2.0,通常確認
12,WSE,NTF,1,5000,200.000000,3.0,通常確認
13,WSE,コイル,5,11000,454.545455,1.0,通常確認

In [12]:
df_summary.loc[
    df_summary["ppm_rank"] == 1.0,
    "priority",
] = "最優先"
df_summary

,site,defect_category,defect_qty_total,production_qty_total,defect_ppm,ppm_rank,priority
0,GSE,Buck-IC,1,4000,250.000000,4.0,通常確認
1,GSE,CAN通信,1,3000,333.333333,3.0,通常確認
2,GSE,NTF,3,3000,1000.000000,1.0,最優先
3,GSE,コイル,2,4000,500.000000,2.0,通常確認
4,MELMB,Buck-IC,2,9000,222.222222,2.0,通常確認
5,MELMB,CAN通信,1,9000,111.111111,3.0,通常確認
6,MELMB,NTF,0,10000,0.000000,4.0,通常確認
7,MELMB,コイル,5,10000,500.000000,1.0,最優先
8,SUS,Buck-IC,1,12000,83.333333,3.0,通常確認
9,SUS,NTF,2,8000,250.000000,1.0,最優先
10,SUS,コイル,3,20000,150.000000,2.0,通常確認
11,WSE,Buck-IC,2,6000,333.333333,2.0,通常確認
12,WSE,NTF,1,5000,200.000000,3.0,通常確認
13,WSE,コイル,5,11000,454.545455,1.0,最優先

In [13]:
df_summary.loc[
    df_summary["ppm_rank"] == 2.0,
    "priority",
] = "要確認"

df_summary

,site,defect_category,defect_qty_total,production_qty_total,defect_ppm,ppm_rank,priority
0,GSE,Buck-IC,1,4000,250.000000,4.0,通常確認
1,GSE,CAN通信,1,3000,333.333333,3.0,通常確認
2,GSE,NTF,3,3000,1000.000000,1.0,最優先
3,GSE,コイル,2,4000,500.000000,2.0,要確認
4,MELMB,Buck-IC,2,9000,222.222222,2.0,要確認
5,MELMB,CAN通信,1,9000,111.111111,3.0,通常確認
6,MELMB,NTF,0,10000,0.000000,4.0,通常確認
7,MELMB,コイル,5,10000,500.000000,1.0,最優先
8,SUS,Buck-IC,1,12000,83.333333,3.0,通常確認
9,SUS,NTF,2,8000,250.000000,1.0,最優先
10,SUS,コイル,3,20000,150.000000,2.0,要確認
11,WSE,Buck-IC,2,6000,333.333333,2.0,要確認
12,WSE,NTF,1,5000,200.000000,3.0,通常確認
13,WSE,コイル,5,11000,454.545455,1.0,最優先

In [15]:
df_summary_sorted = df_summary.sort_values(
    [
        "site",
        "ppm_rank",
    ]
).reset_index(drop=True)

df_summary_sorted

,site,defect_category,defect_qty_total,production_qty_total,defect_ppm,ppm_rank,priority
0,GSE,NTF,3,3000,1000.000000,1.0,最優先
1,GSE,コイル,2,4000,500.000000,2.0,要確認
2,GSE,CAN通信,1,3000,333.333333,3.0,通常確認
3,GSE,Buck-IC,1,4000,250.000000,4.0,通常確認
4,MELMB,コイル,5,10000,500.000000,1.0,最優先
5,MELMB,Buck-IC,2,9000,222.222222,2.0,要確認
6,MELMB,CAN通信,1,9000,111.111111,3.0,通常確認
7,MELMB,NTF,0,10000,0.000000,4.0,通常確認
8,SUS,NTF,2,8000,250.000000,1.0,最優先
9,SUS,コイル,3,20000,150.000000,2.0,要確認
10,SUS,Buck-IC,1,12000,83.333333,3.0,通常確認
11,WSE,コイル,5,11000,454.545455,1.0,最優先
12,WSE,Buck-IC,2,6000,333.333333,2.0,要確認
13,WSE,NTF,1,5000,200.000000,3.0,通常確認