In [2]:
import pandas as pd

In [3]:
df_defect  = pd.DataFrame(
    [
        ["2026-06", "MELMB", "LCM-A", 18],
        ["2026-06", "WSE", "LCM-A", 25],
        ["2026-06", "GSE", "LCM-A", 7],
        ["2026-06", "MELMB", "LCM-B", 12],
        ["2026-06", "WSE", "LCM-B", 32],
        ["2026-06", "GSE", "LCM-B", 9],
        ["2026-06", "MELMB", "LCM-C", 5],
        ["2026-06", "WSE", "LCM-C", 14],
        ["2026-06", "GSE", "LCM-C", 21],
    ],
    columns=[
        "month",
        "site",
        "product",
        "defect_qty",
    ],
)
df_defect

     month   site product  defect_qty
0  2026-06  MELMB   LCM-A          18
1  2026-06    WSE   LCM-A          25
2  2026-06    GSE   LCM-A           7
3  2026-06  MELMB   LCM-B          12
4  2026-06    WSE   LCM-B          32
5  2026-06    GSE   LCM-B           9
6  2026-06  MELMB   LCM-C           5
7  2026-06    WSE   LCM-C          14
8  2026-06    GSE   LCM-C          21

In [4]:
df_wide = df_defect.pivot(index="product", columns="site", values="defect_qty")
df_wide

site     GSE  MELMB  WSE
product
LCM-A      7     18   25
LCM-B      9     12   32
LCM-C     21      5   14