###### 132_5_practical_lcm_weekly_defect_summary.ipynb

In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
plt.rcParams["font.family"] = "Meiryo"
plt.rcParams["axes.unicode_minus"] = False

In [6]:
df = pd.read_csv(
    "dataset/lcm_weekly_defect_practice.csv",
    encoding="utf-8-sig",
)
df.head()

,defect_id,site,model,defect_category,defect_qty,inspection_qty,occ_at_jst,status
0,D001,SUS,J69P,Buck-IC,3,30000.0,2026-06-29 08:30:00+09:00,回答済
1,D002,WSE,310D,Coil,1,28000.0,2026-06-30 13:20:00+09:00,回答済
2,D003,GSE,36WA,NTF,1,24000.0,2026-07-01 09:10:00+09:00,調査中
3,D004,META,J69P,Buck-IC,2,52000.0,2026-07-03 21:45:00+09:00,回答済
4,D005,MEAX,310D,Coil,4,18000.0,2026-07-05 11:05:00+09:00,回答済

In [7]:
df["defect_qty_num"] = pd.to_numeric(
    df["defect_qty"],
    errors="coerce",
)
df.dtypes

defect_id              str
site                   str
model                  str
defect_category        str
defect_qty             str
inspection_qty     float64
occ_at_jst             str
status                 str
defect_qty_num     float64
dtype: object

In [8]:
df["inspection_qty_num"] = pd.to_numeric(
    df["inspection_qty"],
    errors="coerce",
)
df.dtypes

defect_id                 str
site                      str
model                     str
defect_category           str
defect_qty                str
inspection_qty        float64
occ_at_jst                str
status                    str
defect_qty_num        float64
inspection_qty_num    float64
dtype: object

In [9]:
df.head()

,defect_id,site,model,defect_category,defect_qty,inspection_qty,occ_at_jst,status,defect_qty_num,inspection_qty_num
0,D001,SUS,J69P,Buck-IC,3,30000.0,2026-06-29 08:30:00+09:00,回答済,3.0,30000.0
1,D002,WSE,310D,Coil,1,28000.0,2026-06-30 13:20:00+09:00,回答済,1.0,28000.0
2,D003,GSE,36WA,NTF,1,24000.0,2026-07-01 09:10:00+09:00,調査中,1.0,24000.0
3,D004,META,J69P,Buck-IC,2,52000.0,2026-07-03 21:45:00+09:00,回答済,2.0,52000.0
4,D005,MEAX,310D,Coil,4,18000.0,2026-07-05 11:05:00+09:00,回答済,4.0,18000.0

In [10]:
df["occ_at_jst_raw"] = df["occ_at_jst"]

In [11]:
df["occ_at_jst_clean"] = (
    df["occ_at_jst"]
    .astype("string")
    .str.strip()
)
df

,defect_id,site,model,defect_category,defect_qty,inspection_qty,occ_at_jst,status,defect_qty_num,inspection_qty_num,occ_at_jst_raw,occ_at_jst_clean
0,D001,SUS,J69P,Buck-IC,3,30000.0,2026-06-29 08:30:00+09:00,回答済,3.0,30000.0,2026-06-29 08:30:00+09:00,2026-06-29 08:30:00+09:00
1,D002,WSE,310D,Coil,1,28000.0,2026-06-30 13:20:00+09:00,回答済,1.0,28000.0,2026-06-30 13:20:00+09:00,2026-06-30 13:20:00+09:00
2,D003,GSE,36WA,NTF,1,24000.0,2026-07-01 09:10:00+09:00,調査中,1.0,24000.0,2026-07-01 09:10:00+09:00,2026-07-01 09:10:00+09:00
3,D004,META,J69P,Buck-IC,2,52000.0,2026-07-03 21:45:00+09:00,回答済,2.0,52000.0,2026-07-03 21:45:00+09:00,2026-07-03 21:45:00+09:00
4,D005,MEAX,310D,Coil,4,18000.0,2026-07-05 11:05:00+09:00,回答済,4.0,18000.0,2026-07-05 11:05:00+09:00,2026-07-05 11:05:00+09:00
5,D006,MELAC,3BVT,NTF,1,16000.0,2026-07-06 07:40:00+09:00,回答済,1.0,16000.0,2026-07-06 07:40:00+09:00,2026-07-06 07:40:00+09:00
6,D007,SUS,36WA,Buck-IC,5,31000.0,2026-07-07 17:20:00+09:00,調査中,5.0,31000.0,2026-07-07 17:20:00+09:00,2026-07-07 17:20:00+09:00
7,D008,WSE,J69P,Coil,2,30000.0,2026-07-08 19:30:00+09:00,回答済,2.0,30000.0,2026-07-08 19:30:00+09:00,2026-07-08 19:30:00+09:00
8,D009,GSE,310D,Coil,3,22000.0,2026-07-10 10:15:00+09:00,回答済,3.0,22000.0,2026-07-10 10:15:00+09:00,2026-07-10 10:15:00+09:00
9,D010,META,36WA,Buck-IC,2,50000.0,2026-07-12 23:55:00+09:00,回答済,2.0,50000.0,2026-07-12 23:55:00+09:00,2026-07-12 23:55:00+09:00
10,D011,MEAX,3BVT,NTF,1,19000.0,2026-07-13 06:25:00+09:00,回答済,1.0,19000.0,2026-07-13 06:25:00+09:00,2026-07-13 06:25:00+09:00
11,D012,MELAC,J69P,Coil,3,17000.0,2026-07-14 14:00:00+09:00,調査中,3.0,17000.0,2026-07-14 14:00:00+09:00,2026-07-14 14:00:00+09:00
12,D013,SUS,310D,Buck-IC,4,32000.0,2026-07-16 09:50:00+09:00,回答済,4.0,32000.0,2026-07-16 09:50:00+09:00,2026-07-16 09:50:00+09:00
13,D014,WSE,36WA,Coil,1,29000.0,2026-07-18 18:10:00+09:00,回答済,1.0,29000.0,2026-07-18 18:10:00+09:00,2026-07-18 18:10:00+09:00
14,D015,GSE,3BVT,NTF,1,23000.0,2026-07-19 12:35:00+09:00,回答済,1.0,23000.0,2026-07-19 12:35:00+09:00,2026-07-19 12:35:00+09:00
15,D016,META,J69P,Buck-IC,3,51000.0,2026-07-20 08:15:00+09:00,回答済,3.0,51000.0,2026-07-20 08:15:00+09:00,2026-07-20 08:15:00+09:00
16,D017,MEAX,310D,Coil,2,20000.0,2026-07-21 16:45:00+09:00,回答済,2.0,20000.0,2026-07-21 16:45:00+09:00,2026-07-21 16:45:00+09:00
17,D018,MELAC,36WA,Buck-IC,2,18000.0,2026-07-23 20:30:00+09:00,調査中,2.0,18000.0,2026-07-23 20:30:00+09:00,2026-07-23 20:30:00+09:00
18,D019,SUS,3BVT,NTF,1,33000.0,2026-07-25 09:05:00+09:00,回答済,1.0,33000.0,2026-07-25 09:05:00+09:00,2026-07-25 09:05:00+09:00
19,D020,WSE,J69P,Coil,4,31000.0,2026-07-26 22:10:00+09:00,回答済,4.0,31000.0,2026-07-26 22:10:00+09:00,2026-07-26 22:10:00+09:00
20,D021,GSE,310D,Buck-IC,2,24000.0,2026-07-27 07:55:00+09:00,回答済,2.0,24000.0,2026-07-27 07:55:00+09:00,2026-07-27 07:55:00+09:00
21,D022,META,36WA,Coil,1,48000.0,2026-07-29 13:05:00+09:00,回答済,1.0,48000.0,2026-07-29 13:05:00+09:00,2026-07-29 13:05:00+09:00
22,D023,MEAX,3BVT,NTF,1,21000.0,2026-07-31 10:20:00+09:00,回答済,1.0,21000.0,2026-07-31 10:20:00+09:00,2026-07-31 10:20:00+09:00
23,D024,MELAC,J69P,Buck-IC,3,19000.0,2026-08-02 18:40:00+09:00,調査中,3.0,19000.0,2026-08-02 18:40:00+09:00,2026-08-02 18:40:00+09:00
24,D025,SUS,310D,Coil,2,34000.0,2026-08-03 09:15:00+09:00,回答済,2.0,34000.0,2026-08-03 09:15:00+09:00,2026-08-03 09:15:00+09:00
25,D026,WSE,36WA,Buck-IC,1,32000.0,2026-08-04 15:30:00+09:00,回答済,1.0,32000.0,2026-08-04 15:30:00+09:00,2026-08-04 15:30:00+09:00
26,D027,GSE,3BVT,NTF,1,25000.0,2026-08-06 11:25:00+09:00,回答済,1.0,25000.0,2026-08-06 11:25:00+09:00,2026-08-06 11:25:00+09:00
27,D028,META,J69P,Coil,2,53000.0,2026-08-08 20:55:00+09:00,回答済,2.0,53000.0,2026-08-08 20:55:00+09:00,2026-08-08 20:55:00+09:00
28,D029,MEAX,310D,Buck-IC,3,22000.0,2026-08-09 07:35:00+09:00,回答済,3.0,22000.0,2026-08-09 07:35:00+09:00,2026-08-09 07:35:00+09:00
29,D030,MELAC,36WA,Coil,1,20000.0,2026-08-10 17:10:00+09:00,回答済,1.0,20000.0,2026-08-10 17:10:00+09:00,2026-08-10 17:10:00+09:00
30,D031,SUS,J69P,NTF,1,35000.0,NaN,未回答,1.0,35000.0,NaN,<NA>
31,D032,WSE,310D,Coil,不明,31000.0,2026-08-11 08:00:00+09:00,調査中,NaN,31000.0,2026-08-11 08:00:00+09:00,2026-08-11 08:00:00+09:00
32,D033,GSE,36WA,Buck-IC,2,NaN,2026-08-12 12:30:00+09:00,回答済,2.0,NaN,2026-08-12 12:30:00+09:00,2026-08-12 12:30:00+09:00
33,D034,META,3BVT,NTF,1,50000.0,日付不正,未回答,1.0,50000.0,日付不正,日付不正

In [12]:
df.head()

,defect_id,site,model,defect_category,defect_qty,inspection_qty,occ_at_jst,status,defect_qty_num,inspection_qty_num,occ_at_jst_raw,occ_at_jst_clean
0,D001,SUS,J69P,Buck-IC,3,30000.0,2026-06-29 08:30:00+09:00,回答済,3.0,30000.0,2026-06-29 08:30:00+09:00,2026-06-29 08:30:00+09:00
1,D002,WSE,310D,Coil,1,28000.0,2026-06-30 13:20:00+09:00,回答済,1.0,28000.0,2026-06-30 13:20:00+09:00,2026-06-30 13:20:00+09:00
2,D003,GSE,36WA,NTF,1,24000.0,2026-07-01 09:10:00+09:00,調査中,1.0,24000.0,2026-07-01 09:10:00+09:00,2026-07-01 09:10:00+09:00
3,D004,META,J69P,Buck-IC,2,52000.0,2026-07-03 21:45:00+09:00,回答済,2.0,52000.0,2026-07-03 21:45:00+09:00,2026-07-03 21:45:00+09:00
4,D005,MEAX,310D,Coil,4,18000.0,2026-07-05 11:05:00+09:00,回答済,4.0,18000.0,2026-07-05 11:05:00+09:00,2026-07-05 11:05:00+09:00

In [13]:
df.dtypes

defect_id                 str
site                      str
model                     str
defect_category           str
defect_qty                str
inspection_qty        float64
occ_at_jst                str
status                    str
defect_qty_num        float64
inspection_qty_num    float64
occ_at_jst_raw            str
occ_at_jst_clean       string
dtype: object

In [14]:
df["occ_at_jst_dt"] = pd.to_datetime(
    df["occ_at_jst_clean"],
    errors="coerce",
)
df.dtypes

defect_id                                   str
site                                        str
model                                       str
defect_category                             str
defect_qty                                  str
inspection_qty                          float64
occ_at_jst                                  str
status                                      str
defect_qty_num                          float64
inspection_qty_num                      float64
occ_at_jst_raw                              str
occ_at_jst_clean                         string
occ_at_jst_dt         datetime64[us, UTC+09:00]
dtype: object

In [15]:
df_data_ng = df[
    df["occ_at_jst_dt"].isna()
].copy()
df_data_ng

,defect_id,site,model,defect_category,defect_qty,inspection_qty,occ_at_jst,status,defect_qty_num,inspection_qty_num,occ_at_jst_raw,occ_at_jst_clean,occ_at_jst_dt
30,D031,SUS,J69P,NTF,1,35000.0,NaN,未回答,1.0,35000.0,NaN,<NA>,NaT
33,D034,META,3BVT,NTF,1,50000.0,日付不正,未回答,1.0,50000.0,日付不正,日付不正,NaT

In [16]:
df_qty_ng = df[
    df["defect_qty_num"].isna()
].copy()
df_qty_ng

,defect_id,site,model,defect_category,defect_qty,inspection_qty,occ_at_jst,status,defect_qty_num,inspection_qty_num,occ_at_jst_raw,occ_at_jst_clean,occ_at_jst_dt
31,D032,WSE,310D,Coil,不明,31000.0,2026-08-11 08:00:00+09:00,調査中,NaN,31000.0,2026-08-11 08:00:00+09:00,2026-08-11 08:00:00+09:00,2026-08-11 08:00:00+09:00

In [17]:
df_inspection_ng = df[
    df["inspection_qty_num"].isna()
].copy()
df_inspection_ng

,defect_id,site,model,defect_category,defect_qty,inspection_qty,occ_at_jst,status,defect_qty_num,inspection_qty_num,occ_at_jst_raw,occ_at_jst_clean,occ_at_jst_dt
32,D033,GSE,36WA,Buck-IC,2,NaN,2026-08-12 12:30:00+09:00,回答済,2.0,NaN,2026-08-12 12:30:00+09:00,2026-08-12 12:30:00+09:00,2026-08-12 12:30:00+09:00

In [18]:
df_work = df[
    df["occ_at_jst_dt"].notna()
    & df["defect_qty_num"].notna()
    & df["inspection_qty_num"].notna()
].copy()

In [19]:
df_work

,defect_id,site,model,defect_category,defect_qty,inspection_qty,occ_at_jst,status,defect_qty_num,inspection_qty_num,occ_at_jst_raw,occ_at_jst_clean,occ_at_jst_dt
0,D001,SUS,J69P,Buck-IC,3,30000.0,2026-06-29 08:30:00+09:00,回答済,3.0,30000.0,2026-06-29 08:30:00+09:00,2026-06-29 08:30:00+09:00,2026-06-29 08:30:00+09:00
1,D002,WSE,310D,Coil,1,28000.0,2026-06-30 13:20:00+09:00,回答済,1.0,28000.0,2026-06-30 13:20:00+09:00,2026-06-30 13:20:00+09:00,2026-06-30 13:20:00+09:00
2,D003,GSE,36WA,NTF,1,24000.0,2026-07-01 09:10:00+09:00,調査中,1.0,24000.0,2026-07-01 09:10:00+09:00,2026-07-01 09:10:00+09:00,2026-07-01 09:10:00+09:00
3,D004,META,J69P,Buck-IC,2,52000.0,2026-07-03 21:45:00+09:00,回答済,2.0,52000.0,2026-07-03 21:45:00+09:00,2026-07-03 21:45:00+09:00,2026-07-03 21:45:00+09:00
4,D005,MEAX,310D,Coil,4,18000.0,2026-07-05 11:05:00+09:00,回答済,4.0,18000.0,2026-07-05 11:05:00+09:00,2026-07-05 11:05:00+09:00,2026-07-05 11:05:00+09:00
5,D006,MELAC,3BVT,NTF,1,16000.0,2026-07-06 07:40:00+09:00,回答済,1.0,16000.0,2026-07-06 07:40:00+09:00,2026-07-06 07:40:00+09:00,2026-07-06 07:40:00+09:00
6,D007,SUS,36WA,Buck-IC,5,31000.0,2026-07-07 17:20:00+09:00,調査中,5.0,31000.0,2026-07-07 17:20:00+09:00,2026-07-07 17:20:00+09:00,2026-07-07 17:20:00+09:00
7,D008,WSE,J69P,Coil,2,30000.0,2026-07-08 19:30:00+09:00,回答済,2.0,30000.0,2026-07-08 19:30:00+09:00,2026-07-08 19:30:00+09:00,2026-07-08 19:30:00+09:00
8,D009,GSE,310D,Coil,3,22000.0,2026-07-10 10:15:00+09:00,回答済,3.0,22000.0,2026-07-10 10:15:00+09:00,2026-07-10 10:15:00+09:00,2026-07-10 10:15:00+09:00
9,D010,META,36WA,Buck-IC,2,50000.0,2026-07-12 23:55:00+09:00,回答済,2.0,50000.0,2026-07-12 23:55:00+09:00,2026-07-12 23:55:00+09:00,2026-07-12 23:55:00+09:00
10,D011,MEAX,3BVT,NTF,1,19000.0,2026-07-13 06:25:00+09:00,回答済,1.0,19000.0,2026-07-13 06:25:00+09:00,2026-07-13 06:25:00+09:00,2026-07-13 06:25:00+09:00
11,D012,MELAC,J69P,Coil,3,17000.0,2026-07-14 14:00:00+09:00,調査中,3.0,17000.0,2026-07-14 14:00:00+09:00,2026-07-14 14:00:00+09:00,2026-07-14 14:00:00+09:00
12,D013,SUS,310D,Buck-IC,4,32000.0,2026-07-16 09:50:00+09:00,回答済,4.0,32000.0,2026-07-16 09:50:00+09:00,2026-07-16 09:50:00+09:00,2026-07-16 09:50:00+09:00
13,D014,WSE,36WA,Coil,1,29000.0,2026-07-18 18:10:00+09:00,回答済,1.0,29000.0,2026-07-18 18:10:00+09:00,2026-07-18 18:10:00+09:00,2026-07-18 18:10:00+09:00
14,D015,GSE,3BVT,NTF,1,23000.0,2026-07-19 12:35:00+09:00,回答済,1.0,23000.0,2026-07-19 12:35:00+09:00,2026-07-19 12:35:00+09:00,2026-07-19 12:35:00+09:00
15,D016,META,J69P,Buck-IC,3,51000.0,2026-07-20 08:15:00+09:00,回答済,3.0,51000.0,2026-07-20 08:15:00+09:00,2026-07-20 08:15:00+09:00,2026-07-20 08:15:00+09:00
16,D017,MEAX,310D,Coil,2,20000.0,2026-07-21 16:45:00+09:00,回答済,2.0,20000.0,2026-07-21 16:45:00+09:00,2026-07-21 16:45:00+09:00,2026-07-21 16:45:00+09:00
17,D018,MELAC,36WA,Buck-IC,2,18000.0,2026-07-23 20:30:00+09:00,調査中,2.0,18000.0,2026-07-23 20:30:00+09:00,2026-07-23 20:30:00+09:00,2026-07-23 20:30:00+09:00
18,D019,SUS,3BVT,NTF,1,33000.0,2026-07-25 09:05:00+09:00,回答済,1.0,33000.0,2026-07-25 09:05:00+09:00,2026-07-25 09:05:00+09:00,2026-07-25 09:05:00+09:00
19,D020,WSE,J69P,Coil,4,31000.0,2026-07-26 22:10:00+09:00,回答済,4.0,31000.0,2026-07-26 22:10:00+09:00,2026-07-26 22:10:00+09:00,2026-07-26 22:10:00+09:00
20,D021,GSE,310D,Buck-IC,2,24000.0,2026-07-27 07:55:00+09:00,回答済,2.0,24000.0,2026-07-27 07:55:00+09:00,2026-07-27 07:55:00+09:00,2026-07-27 07:55:00+09:00
21,D022,META,36WA,Coil,1,48000.0,2026-07-29 13:05:00+09:00,回答済,1.0,48000.0,2026-07-29 13:05:00+09:00,2026-07-29 13:05:00+09:00,2026-07-29 13:05:00+09:00
22,D023,MEAX,3BVT,NTF,1,21000.0,2026-07-31 10:20:00+09:00,回答済,1.0,21000.0,2026-07-31 10:20:00+09:00,2026-07-31 10:20:00+09:00,2026-07-31 10:20:00+09:00
23,D024,MELAC,J69P,Buck-IC,3,19000.0,2026-08-02 18:40:00+09:00,調査中,3.0,19000.0,2026-08-02 18:40:00+09:00,2026-08-02 18:40:00+09:00,2026-08-02 18:40:00+09:00
24,D025,SUS,310D,Coil,2,34000.0,2026-08-03 09:15:00+09:00,回答済,2.0,34000.0,2026-08-03 09:15:00+09:00,2026-08-03 09:15:00+09:00,2026-08-03 09:15:00+09:00
25,D026,WSE,36WA,Buck-IC,1,32000.0,2026-08-04 15:30:00+09:00,回答済,1.0,32000.0,2026-08-04 15:30:00+09:00,2026-08-04 15:30:00+09:00,2026-08-04 15:30:00+09:00
26,D027,GSE,3BVT,NTF,1,25000.0,2026-08-06 11:25:00+09:00,回答済,1.0,25000.0,2026-08-06 11:25:00+09:00,2026-08-06 11:25:00+09:00,2026-08-06 11:25:00+09:00
27,D028,META,J69P,Coil,2,53000.0,2026-08-08 20:55:00+09:00,回答済,2.0,53000.0,2026-08-08 20:55:00+09:00,2026-08-08 20:55:00+09:00,2026-08-08 20:55:00+09:00
28,D029,MEAX,310D,Buck-IC,3,22000.0,2026-08-09 07:35:00+09:00,回答済,3.0,22000.0,2026-08-09 07:35:00+09:00,2026-08-09 07:35:00+09:00,2026-08-09 07:35:00+09:00
29,D030,MELAC,36WA,Coil,1,20000.0,2026-08-10 17:10:00+09:00,回答済,1.0,20000.0,2026-08-10 17:10:00+09:00,2026-08-10 17:10:00+09:00,2026-08-10 17:10:00+09:00

In [20]:
df_work.head()

,defect_id,site,model,defect_category,defect_qty,inspection_qty,occ_at_jst,status,defect_qty_num,inspection_qty_num,occ_at_jst_raw,occ_at_jst_clean,occ_at_jst_dt
0,D001,SUS,J69P,Buck-IC,3,30000.0,2026-06-29 08:30:00+09:00,回答済,3.0,30000.0,2026-06-29 08:30:00+09:00,2026-06-29 08:30:00+09:00,2026-06-29 08:30:00+09:00
1,D002,WSE,310D,Coil,1,28000.0,2026-06-30 13:20:00+09:00,回答済,1.0,28000.0,2026-06-30 13:20:00+09:00,2026-06-30 13:20:00+09:00,2026-06-30 13:20:00+09:00
2,D003,GSE,36WA,NTF,1,24000.0,2026-07-01 09:10:00+09:00,調査中,1.0,24000.0,2026-07-01 09:10:00+09:00,2026-07-01 09:10:00+09:00,2026-07-01 09:10:00+09:00
3,D004,META,J69P,Buck-IC,2,52000.0,2026-07-03 21:45:00+09:00,回答済,2.0,52000.0,2026-07-03 21:45:00+09:00,2026-07-03 21:45:00+09:00,2026-07-03 21:45:00+09:00
4,D005,MEAX,310D,Coil,4,18000.0,2026-07-05 11:05:00+09:00,回答済,4.0,18000.0,2026-07-05 11:05:00+09:00,2026-07-05 11:05:00+09:00,2026-07-05 11:05:00+09:00

In [23]:
iso_df = df_work["occ_at_jst_dt"].dt.isocalendar()
iso_df.head()

   year  week  day
0  2026    27    1
1  2026    27    2
2  2026    27    3
3  2026    27    5
4  2026    27    7

In [25]:
df_work["week_group"] = (
    iso_df["year"] * 100 + iso_df["week"]
).astype(int)
df_work.head()

,defect_id,site,model,defect_category,defect_qty,inspection_qty,occ_at_jst,status,defect_qty_num,inspection_qty_num,occ_at_jst_raw,occ_at_jst_clean,occ_at_jst_dt,week_group
0,D001,SUS,J69P,Buck-IC,3,30000.0,2026-06-29 08:30:00+09:00,回答済,3.0,30000.0,2026-06-29 08:30:00+09:00,2026-06-29 08:30:00+09:00,2026-06-29 08:30:00+09:00,202627
1,D002,WSE,310D,Coil,1,28000.0,2026-06-30 13:20:00+09:00,回答済,1.0,28000.0,2026-06-30 13:20:00+09:00,2026-06-30 13:20:00+09:00,2026-06-30 13:20:00+09:00,202627
2,D003,GSE,36WA,NTF,1,24000.0,2026-07-01 09:10:00+09:00,調査中,1.0,24000.0,2026-07-01 09:10:00+09:00,2026-07-01 09:10:00+09:00,2026-07-01 09:10:00+09:00,202627
3,D004,META,J69P,Buck-IC,2,52000.0,2026-07-03 21:45:00+09:00,回答済,2.0,52000.0,2026-07-03 21:45:00+09:00,2026-07-03 21:45:00+09:00,2026-07-03 21:45:00+09:00,202627
4,D005,MEAX,310D,Coil,4,18000.0,2026-07-05 11:05:00+09:00,回答済,4.0,18000.0,2026-07-05 11:05:00+09:00,2026-07-05 11:05:00+09:00,2026-07-05 11:05:00+09:00,202627

In [26]:
df_work["ppm"] = (
    df_work["defect_qty_num"]
    / df_work["inspection_qty_num"]
    * 1000000
).round(1)
df_work.head()

,defect_id,site,model,defect_category,defect_qty,inspection_qty,occ_at_jst,status,defect_qty_num,inspection_qty_num,occ_at_jst_raw,occ_at_jst_clean,occ_at_jst_dt,week_group,ppm
0,D001,SUS,J69P,Buck-IC,3,30000.0,2026-06-29 08:30:00+09:00,回答済,3.0,30000.0,2026-06-29 08:30:00+09:00,2026-06-29 08:30:00+09:00,2026-06-29 08:30:00+09:00,202627,100.0
1,D002,WSE,310D,Coil,1,28000.0,2026-06-30 13:20:00+09:00,回答済,1.0,28000.0,2026-06-30 13:20:00+09:00,2026-06-30 13:20:00+09:00,2026-06-30 13:20:00+09:00,202627,35.7
2,D003,GSE,36WA,NTF,1,24000.0,2026-07-01 09:10:00+09:00,調査中,1.0,24000.0,2026-07-01 09:10:00+09:00,2026-07-01 09:10:00+09:00,2026-07-01 09:10:00+09:00,202627,41.7
3,D004,META,J69P,Buck-IC,2,52000.0,2026-07-03 21:45:00+09:00,回答済,2.0,52000.0,2026-07-03 21:45:00+09:00,2026-07-03 21:45:00+09:00,2026-07-03 21:45:00+09:00,202627,38.5
4,D005,MEAX,310D,Coil,4,18000.0,2026-07-05 11:05:00+09:00,回答済,4.0,18000.0,2026-07-05 11:05:00+09:00,2026-07-05 11:05:00+09:00,2026-07-05 11:05:00+09:00,202627,222.2

In [27]:
df_week_summary = df_work.groupby(
    "week_group",
    as_index=False,
).agg(
    defect_count=("defect_id", "count"),
    defect_qty_sum=("defect_qty_num", "sum"),
    inspection_qty_sum=("inspection_qty_num", "sum"),
)
df_week_summary

   week_group  defect_count  defect_qty_sum  inspection_qty_sum
0      202627             5            11.0            152000.0
1      202628             5            13.0            149000.0
2      202629             5            10.0            120000.0
3      202630             5            12.0            153000.0
4      202631             4             7.0            112000.0
5      202632             5             9.0            166000.0
6      202633             1             1.0             20000.0

In [28]:
df_week_summary["ppm"] = (
    df_week_summary["defect_qty_sum"]
    / df_week_summary["inspection_qty_sum"]
    * 1000000
).round(1)

In [29]:
df_week_summary["defect_qty_sum"] = (
    df_week_summary["defect_qty_sum"].astype(int)
)

In [30]:
df_week_summary["inspection_qty_sum"] = (
    df_week_summary["inspection_qty_sum"].astype(int)
)

In [31]:
df_week_summary

   week_group  defect_count  defect_qty_sum  inspection_qty_sum   ppm
0      202627             5              11              152000  72.4
1      202628             5              13              149000  87.2
2      202629             5              10              120000  83.3
3      202630             5              12              153000  78.4
4      202631             4               7              112000  62.5
5      202632             5               9              166000  54.2
6      202633             1               1               20000  50.0

In [32]:
df_work.head()

,defect_id,site,model,defect_category,defect_qty,inspection_qty,occ_at_jst,status,defect_qty_num,inspection_qty_num,occ_at_jst_raw,occ_at_jst_clean,occ_at_jst_dt,week_group,ppm
0,D001,SUS,J69P,Buck-IC,3,30000.0,2026-06-29 08:30:00+09:00,回答済,3.0,30000.0,2026-06-29 08:30:00+09:00,2026-06-29 08:30:00+09:00,2026-06-29 08:30:00+09:00,202627,100.0
1,D002,WSE,310D,Coil,1,28000.0,2026-06-30 13:20:00+09:00,回答済,1.0,28000.0,2026-06-30 13:20:00+09:00,2026-06-30 13:20:00+09:00,2026-06-30 13:20:00+09:00,202627,35.7
2,D003,GSE,36WA,NTF,1,24000.0,2026-07-01 09:10:00+09:00,調査中,1.0,24000.0,2026-07-01 09:10:00+09:00,2026-07-01 09:10:00+09:00,2026-07-01 09:10:00+09:00,202627,41.7
3,D004,META,J69P,Buck-IC,2,52000.0,2026-07-03 21:45:00+09:00,回答済,2.0,52000.0,2026-07-03 21:45:00+09:00,2026-07-03 21:45:00+09:00,2026-07-03 21:45:00+09:00,202627,38.5
4,D005,MEAX,310D,Coil,4,18000.0,2026-07-05 11:05:00+09:00,回答済,4.0,18000.0,2026-07-05 11:05:00+09:00,2026-07-05 11:05:00+09:00,2026-07-05 11:05:00+09:00,202627,222.2

In [34]:
df_week_site_summary = df_work.groupby(
    [
        "week_group",
        "site",
    ],
    as_index=False
).agg(
    defect_count=("defect_id", "count"),
    defect_qty_sum=("defect_qty_num", "sum"),
    inspection_qty_sum=("inspection_qty_num", "sum")
)
df_week_site_summary.head()

   week_group  site  defect_count  defect_qty_sum  inspection_qty_sum
0      202627   GSE             1             1.0             24000.0
1      202627  MEAX             1             4.0             18000.0
2      202627  META             1             2.0             52000.0
3      202627   SUS             1             3.0             30000.0
4      202627   WSE             1             1.0             28000.0

In [35]:
df_week_site_summary["ppm"] = (
    df_week_site_summary["defect_qty_sum"]
    / df_week_site_summary["inspection_qty_sum"]
    * 1000000
).round(1)

In [38]:
df_week_site_summary.head()

   week_group  site  defect_count  defect_qty_sum  inspection_qty_sum    ppm
0      202627   GSE             1             1.0             24000.0   41.7
1      202627  MEAX             1             4.0             18000.0  222.2
2      202627  META             1             2.0             52000.0   38.5
3      202627   SUS             1             3.0             30000.0  100.0
4      202627   WSE             1             1.0             28000.0   35.7

In [40]:
df_week_site_summary["defect_qty_sum"] = (
    df_week_site_summary["defect_qty_sum"].astype(int)
)
df_week_site_summary.head()

   week_group  site  defect_count  defect_qty_sum  inspection_qty_sum    ppm
0      202627   GSE             1               1             24000.0   41.7
1      202627  MEAX             1               4             18000.0  222.2
2      202627  META             1               2             52000.0   38.5
3      202627   SUS             1               3             30000.0  100.0
4      202627   WSE             1               1             28000.0   35.7

In [41]:
df_week_site_summary["inspection_qty_sum"] = (
    df_week_site_summary["inspection_qty_sum"].astype(int)
)
df_week_site_summary

    week_group   site  defect_count  defect_qty_sum  inspection_qty_sum    ppm
0       202627    GSE             1               1               24000   41.7
1       202627   MEAX             1               4               18000  222.2
2       202627   META             1               2               52000   38.5
3       202627    SUS             1               3               30000  100.0
4       202627    WSE             1               1               28000   35.7
5       202628    GSE             1               3               22000  136.4
6       202628  MELAC             1               1               16000   62.5
7       202628   META             1               2               50000   40.0
8       202628    SUS             1               5               31000  161.3
9       202628    WSE             1               2               30000   66.7
10      202629    GSE             1               1               23000   43.5
11      202629   MEAX             1               1               19000   52.6
12      202629  MELAC             1               3               17000  176.5
13      202629    SUS             1               4               32000  125.0
14      202629    WSE             1               1               29000   34.5
15      202630   MEAX             1               2               20000  100.0
16      202630  MELAC             1               2               18000  111.1
17      202630   META             1               3               51000   58.8
18      202630    SUS             1               1               33000   30.3
19      202630    WSE             1               4               31000  129.0
20      202631    GSE             1               2               24000   83.3
21      202631   MEAX             1               1               21000   47.6
22      202631  MELAC             1               3               19000  157.9
23      202631   META             1               1               48000   20.8
24      202632    GSE             1               1               25000   40.0
25      202632   MEAX             1               3               22000  136.4
26      202632   META             1               2               53000   37.7
27      202632    SUS             1               2               34000   58.8
28      202632    WSE             1               1               32000   31.2
29      202633  MELAC             1               1               20000   50.0

In [ ]:
#cell 18 から