###### 129_6_inspection_qty_category_answer.ipynb

In [1]:
import pandas as pd
import numpy as np

In [2]:
#cell2
df = pd.DataFrame(
    [
        ["D001", "J69P", "MELMB", "コイル", 3, 12000, "調査中"],
        ["D002", "J69P", "WSE", "Buck-IC", 5, 18000, "対策検討中"],
        ["D003", "310D", "GSE", "コイル", 12, 25000, "暫定対策済"],
        ["D004", "310D", "MELMB", "はんだ", 2, 9000, "調査中"],
        ["D005", "J69P", "GSE", "コイル", 7, 15000, "調査中"],
        ["D006", "310D", "WSE", "コネクタ", 1, 6000, "完了"],
        ["D007", "J69P", "MELMB", "Buck-IC", 8, 20000, "調査中"],
        ["D008", "310D", "GSE", "コイル", 4, 10000, "対策検討中"],
        ["D009", "J69P", "GSE", "Buck-IC", 6, 14000, "調査中"],
        ["D010", "310D", "MELMB", "コイル", 5, 16000, "暫定対策済"],
        ["D011", "J69P", "WSE", "コイル", 9, 22000, "調査中"],
        ["D012", "310D", "GSE", "はんだ", 3, 8000, "完了"],
    ],
    columns=[
            "defect_id",
            "project",
            "site",
            "defect_category",
            "defect_qty",
            "inspection_qty",
            "status",
    ],
)
df

   defect_id project   site defect_category  defect_qty  inspection_qty status
0       D001    J69P  MELMB             コイル           3           12000    調査中
1       D002    J69P    WSE         Buck-IC           5           18000  対策検討中
2       D003    310D    GSE             コイル          12           25000  暫定対策済
3       D004    310D  MELMB             はんだ           2            9000    調査中
4       D005    J69P    GSE             コイル           7           15000    調査中
5       D006    310D    WSE            コネクタ           1            6000     完了
6       D007    J69P  MELMB         Buck-IC           8           20000    調査中
7       D008    310D    GSE             コイル           4           10000  対策検討中
8       D009    J69P    GSE         Buck-IC           6           14000    調査中
9       D010    310D  MELMB             コイル           5           16000  暫定対策済
10      D011    J69P    WSE             コイル           9           22000    調査中
11      D012    310D    GSE             はんだ           3            8000     完了

In [3]:
df_work = df.copy()
df_work

   defect_id project   site defect_category  defect_qty  inspection_qty status
0       D001    J69P  MELMB             コイル           3           12000    調査中
1       D002    J69P    WSE         Buck-IC           5           18000  対策検討中
2       D003    310D    GSE             コイル          12           25000  暫定対策済
3       D004    310D  MELMB             はんだ           2            9000    調査中
4       D005    J69P    GSE             コイル           7           15000    調査中
5       D006    310D    WSE            コネクタ           1            6000     完了
6       D007    J69P  MELMB         Buck-IC           8           20000    調査中
7       D008    310D    GSE             コイル           4           10000  対策検討中
8       D009    J69P    GSE         Buck-IC           6           14000    調査中
9       D010    310D  MELMB             コイル           5           16000  暫定対策済
10      D011    J69P    WSE             コイル           9           22000    調査中
11      D012    310D    GSE             はんだ           3            8000     完了

In [4]:
bins = [
    0,
    10000,
    20000,
    np.inf,
]

labels = [
    "少ない",
    "普通",
    "多い",
]

In [6]:
#cell5
df_work["inspection_category"] = pd.cut(
    df_work["inspection_qty"],
    bins=bins,
    labels=labels,
    include_lowest=True,
)
df_work

,defect_id,project,site,defect_category,defect_qty,inspection_qty,status,inspection_category
0,D001,J69P,MELMB,コイル,3,12000,調査中,普通
1,D002,J69P,WSE,Buck-IC,5,18000,対策検討中,普通
2,D003,310D,GSE,コイル,12,25000,暫定対策済,多い
3,D004,310D,MELMB,はんだ,2,9000,調査中,少ない
4,D005,J69P,GSE,コイル,7,15000,調査中,普通
5,D006,310D,WSE,コネクタ,1,6000,完了,少ない
6,D007,J69P,MELMB,Buck-IC,8,20000,調査中,普通
7,D008,310D,GSE,コイル,4,10000,対策検討中,少ない
8,D009,J69P,GSE,Buck-IC,6,14000,調査中,普通
9,D010,310D,MELMB,コイル,5,16000,暫定対策済,普通
10,D011,J69P,WSE,コイル,9,22000,調査中,多い
11,D012,310D,GSE,はんだ,3,8000,完了,少ない

In [11]:
#cell6
df_inspection_count = df_work["inspection_category"].value_counts(
    sort=False
).reset_index()
df_inspection_count

df_inspection_count.colums = [
    "inspection_category",
    "count",
]

df_inspection_count

C:\Users\stj242381\AppData\Local\Temp\ipykernel_14552\1369320524.py:7: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  df_inspection_count.colums = [

  inspection_category  count
0                 少ない      4
1                  普通      6
2                  多い      2

In [12]:
df_many_inspection = df_work[
    df_work["inspection_category"] == "多い"
].copy()
df_many_inspection

,defect_id,project,site,defect_category,defect_qty,inspection_qty,status,inspection_category
2,D003,310D,GSE,コイル,12,25000,暫定対策済,多い
10,D011,J69P,WSE,コイル,9,22000,調査中,多い

In [16]:
df_work["inspection_comment"] = "通常確認"
df_work

df_work.loc[
    df_work["inspection_category"] == "少ない",
    "inspection_comment",
] = "サンプル数少ないため参考確認"
df_work

df_work.loc[
    df_work["inspection_category"] == "多い",
    "inspection_comment",
] = "検査数多めのため傾向確認しやすい"

df_work

,defect_id,project,site,defect_category,defect_qty,inspection_qty,status,inspection_category,inspection_comment
0,D001,J69P,MELMB,コイル,3,12000,調査中,普通,通常確認
1,D002,J69P,WSE,Buck-IC,5,18000,対策検討中,普通,通常確認
2,D003,310D,GSE,コイル,12,25000,暫定対策済,多い,検査数多めのため傾向確認しやすい
3,D004,310D,MELMB,はんだ,2,9000,調査中,少ない,サンプル数少ないため参考確認
4,D005,J69P,GSE,コイル,7,15000,調査中,普通,通常確認
5,D006,310D,WSE,コネクタ,1,6000,完了,少ない,サンプル数少ないため参考確認
6,D007,J69P,MELMB,Buck-IC,8,20000,調査中,普通,通常確認
7,D008,310D,GSE,コイル,4,10000,対策検討中,少ない,サンプル数少ないため参考確認
8,D009,J69P,GSE,Buck-IC,6,14000,調査中,普通,通常確認
9,D010,310D,MELMB,コイル,5,16000,暫定対策済,普通,通常確認
10,D011,J69P,WSE,コイル,9,22000,調査中,多い,検査数多めのため傾向確認しやすい
11,D012,310D,GSE,はんだ,3,8000,完了,少ない,サンプル数少ないため参考確認

In [17]:
df_report = df_work.sort_values(
    "inspection_qty",
    ascending=False,
)
df_report

,defect_id,project,site,defect_category,defect_qty,inspection_qty,status,inspection_category,inspection_comment
2,D003,310D,GSE,コイル,12,25000,暫定対策済,多い,検査数多めのため傾向確認しやすい
10,D011,J69P,WSE,コイル,9,22000,調査中,多い,検査数多めのため傾向確認しやすい
6,D007,J69P,MELMB,Buck-IC,8,20000,調査中,普通,通常確認
1,D002,J69P,WSE,Buck-IC,5,18000,対策検討中,普通,通常確認
9,D010,310D,MELMB,コイル,5,16000,暫定対策済,普通,通常確認
4,D005,J69P,GSE,コイル,7,15000,調査中,普通,通常確認
8,D009,J69P,GSE,Buck-IC,6,14000,調査中,普通,通常確認
0,D001,J69P,MELMB,コイル,3,12000,調査中,普通,通常確認
7,D008,310D,GSE,コイル,4,10000,対策検討中,少ない,サンプル数少ないため参考確認
3,D004,310D,MELMB,はんだ,2,9000,調査中,少ない,サンプル数少ないため参考確認
11,D012,310D,GSE,はんだ,3,8000,完了,少ない,サンプル数少ないため参考確認
5,D006,310D,WSE,コネクタ,1,6000,完了,少ない,サンプル数少ないため参考確認