In [2]:
import pandas as pd

df_log = pd.read_csv("dataset/product_log.csv")
df_log.head()

         Date  Num Product
0  2017-01-03    1       B
1  2017-01-06    2       B
2  2017-01-07    1       A
3  2017-01-11    2       A
4  2017-01-12    2       B

In [3]:
df_master = pd.read_csv("dataset/product_master.csv")
df_master

   Price Product
0   1000       A
1   1200       B

In [4]:
df_sale = pd.merge(df_log, df_master)
df_sale.head()

         Date  Num Product  Price
0  2017-01-03    1       B   1200
1  2017-01-06    2       B   1200
2  2017-01-07    1       A   1000
3  2017-01-11    2       A   1000
4  2017-01-12    2       B   1200

In [5]:
df_sale = pd.merge(df_log, df_master, on="Product")
df_sale.head()

         Date  Num Product  Price
0  2017-01-03    1       B   1200
1  2017-01-06    2       B   1200
2  2017-01-07    1       A   1000
3  2017-01-11    2       A   1000
4  2017-01-12    2       B   1200

In [6]:
df_sale = pd.merge(df_log, df_master, how="inner")
df_sale.head()

         Date  Num Product  Price
0  2017-01-03    1       B   1200
1  2017-01-06    2       B   1200
2  2017-01-07    1       A   1000
3  2017-01-11    2       A   1000
4  2017-01-12    2       B   1200

In [7]:
df_log2 = pd.DataFrame(
    [
        ["2024-01-01", 1, "A"],
        ["2024-01-02", 2, "B"],
        ["2024-01-03", 3, "C"],
    ],
    columns=["Date", "Num", "Product"]
)

In [8]:
df_log2

         Date  Num Product
0  2024-01-01    1       A
1  2024-01-02    2       B
2  2024-01-03    3       C

In [11]:
df_master2 = pd.DataFrame(
    [
        [100, "A"],
        [200, "B"]
    ],
    columns=["Price", "Product"]
)

In [13]:
df_master2

   Price Product
0    100       A
1    200       B

In [15]:
df_sale2 = pd.merge(df_log2, df_master2, on="Product")

In [16]:
df_sale2

         Date  Num Product  Price
0  2024-01-01    1       A    100
1  2024-01-02    2       B    200

In [18]:
df_master2 = pd.DataFrame(
    [
        [100, "A"],
        [200, "B"],
        [300, "C"]
    ],
    columns=["Price", "Product"]
)

df_sale2 = pd.merge(df_log2, df_master2, on="Product", how="inner")
df_sale2

         Date  Num Product  Price
0  2024-01-01    1       A    100
1  2024-01-02    2       B    200
2  2024-01-03    3       C    300

In [20]:
df_log2 = pd.DataFrame(
    [
        ["2024-01-01", 1, "A"],
        ["2024-01-02", 2, "B"],
        ["2024-01-03", 3, "A"],
        ["2024-01-04", 3, "C"]
    ],
    columns=["Date", "Num", "Product"] 
)
df_sale2 = pd.merge(df_log2, df_master2, on="Product", how="inner")
df_sale2

         Date  Num Product  Price
0  2024-01-01    1       A    100
1  2024-01-02    2       B    200
2  2024-01-03    3       A    100
3  2024-01-04    3       C    300