In [1]:
import pandas as pd

In [2]:
df_log = pd.read_csv('dataset/product_log.csv')
df_log.head()

         Date  Num Product
0  2017-01-03    1       B
1  2017-01-06    2       B
2  2017-01-07    1       A
3  2017-01-11    2       A
4  2017-01-12    2       B

In [3]:
df_master = pd.read_csv('dataset/product_master.csv')
df_master

   Price Product
0   1000       A
1   1200       B

In [4]:
df_sale = pd.merge(df_log, df_master)
df_sale.head()

         Date  Num Product  Price
0  2017-01-03    1       B   1200
1  2017-01-06    2       B   1200
2  2017-01-07    1       A   1000
3  2017-01-11    2       A   1000
4  2017-01-12    2       B   1200

In [6]:
df_sale['Sale'] = df_sale['Price'] * df_sale['Num']
df_sale.head()

         Date  Num Product  Price  Sale
0  2017-01-03    1       B   1200  1200
1  2017-01-06    2       B   1200  2400
2  2017-01-07    1       A   1000  1000
3  2017-01-11    2       A   1000  2000
4  2017-01-12    2       B   1200  2400

In [7]:
df_log2 = pd.DataFrame(
    [
        ['2024-01-01', 1, 'A'],
        ['2024-01-02', 2, 'B'],
        ['2024-01-03', 3, 'C'],
    ],
    columns=['Date', 'Num', 'Product']
)
df_log2

         Date  Num Product
0  2024-01-01    1       A
1  2024-01-02    2       B
2  2024-01-03    3       C

In [9]:
df_master2  = pd.DataFrame(
    [
        [100,'A'],
        [200,'B']
    ],
    columns=["Price", "Product"]
)
df_master2

   Price Product
0    100       A
1    200       B

In [10]:
df_sale2 = pd.merge(df_log2, df_master2)

In [11]:
df_sale2

         Date  Num Product  Price
0  2024-01-01    1       A    100
1  2024-01-02    2       B    200

In [12]:
df_sale2["Sale"] = df_sale2["Price"] * df_sale2["Num"]

In [13]:
df_sale2

         Date  Num Product  Price  Sale
0  2024-01-01    1       A    100   100
1  2024-01-02    2       B    200   400

In [16]:
df_master2 = pd.DataFrame(
    [
        [150,'A'],
        [250, 'B']
    ],
    columns=["Price", "Product"]
)
df_sale2 = pd.merge(df_log2, df_master2)
df_sale2["Sale"] = df_sale2["Price"] * df_sale2["Num"]

df_sale2

         Date  Num Product  Price  Sale
0  2024-01-01    1       A    150   150
1  2024-01-02    2       B    250   500