In [1]:
import pandas as pd

df_log = pd.read_csv("dataset/product_log.csv", parse_dates=["Date"])
df_log.head()

        Date  Num Product
0 2017-01-03  1.0       B
1 2017-01-06  2.0       B
2 2017-01-07  1.0       A
3 2017-01-11  2.0       A
4 2017-01-12  2.0       B

In [2]:
df_log.dtypes

Date       datetime64[ns]
Num               float64
Product            object
dtype: object

In [3]:
df_master = pd.read_csv("dataset/product_master.csv")
df_master

   Price Product
0   1000       A
1   1200       B

In [5]:
df_sale = pd.merge(df_log, df_master)
df_sale.head()

        Date  Num Product  Price
0 2017-01-03  1.0       B   1200
1 2017-01-06  2.0       B   1200
2 2017-01-07  1.0       A   1000
3 2017-01-11  2.0       A   1000
4 2017-01-12  2.0       B   1200

In [6]:
df_sale["Sale"] = df_sale["Price"] * df_sale["Num"]
df_sale.head()

        Date  Num Product  Price    Sale
0 2017-01-03  1.0       B   1200  1200.0
1 2017-01-06  2.0       B   1200  2400.0
2 2017-01-07  1.0       A   1000  1000.0
3 2017-01-11  2.0       A   1000  2000.0
4 2017-01-12  2.0       B   1200  2400.0

In [7]:
df_sale.dtypes

Date       datetime64[ns]
Num               float64
Product            object
Price               int64
Sale              float64
dtype: object

In [10]:
#練習1
#df_log.dtypes を表示して、Date 列の型を確認してください。
df_sale["Sale"] * 1.1
#練習2
#df_sale.dtypes を表示して、結合後も Date 列が日付型か確認してください。
df_sale.dtypes
#練習3
#Sale 列ではなく、
#Tax_included_sale という列を作ってください。
df_sale["Tax_included_sale"] = df_sale["Sale"] * 1.1
df_sale.head()

        Date  Num Product  Price    Sale  Tax_included_sale
0 2017-01-03  1.0       B   1200  1200.0             1320.0
1 2017-01-06  2.0       B   1200  2400.0             2640.0
2 2017-01-07  1.0       A   1000  1000.0             1100.0
3 2017-01-11  2.0       A   1000  2000.0             2200.0
4 2017-01-12  2.0       B   1200  2400.0             2640.0