In [2]:
import numpy as np
import pandas as pd

In [4]:
df = pd.DataFrame([[0], [1]], columns=["A"])
df

   A
0  0
1  1

In [5]:
np.c_[df,df]

array([[0, 0],
       [1, 1]])

In [6]:
np.c_[df,df].reshape(-1, df.shape[1])

array([[0],
       [0],
       [1],
       [1]])

In [7]:
np.mod(np.arange(df.shape[0] * 2), 2)

array([0, 1, 0, 1])

In [8]:
L = np.c_[
    np.c_[df,df].reshape(-1, df.shape[1]),
    np.mod(np.arange(df.shape[0] * 2), 2)
]
L

array([[0, 0],
       [0, 1],
       [1, 0],
       [1, 1]])

In [9]:
L.T[0]

array([0, 0, 1, 1])

In [10]:
L.T[-1]

array([0, 1, 0, 1])

In [11]:
L.T[0] ^ L.T[-1]

array([0, 1, 1, 0])

In [12]:
L = np.c_[L, L.T[0] ^ L.T[-1]]
L

array([[0, 0, 0],
       [0, 1, 1],
       [1, 0, 1],
       [1, 1, 0]])

In [13]:
df = pd.DataFrame(L)
df

   0  1  2
0  0  0  0
1  0  1  1
2  1  0  1
3  1  1  0

In [14]:
df.columns = (df.columns + 65).map(chr)
df

   A  B  C
0  0  0  0
1  0  1  1
2  1  0  1
3  1  1  0

In [16]:
import pandas as pd

df = pd.DataFrame([[0], [1]], columns=["A"])

df.shape[0]
df.shape[1]

1

In [17]:
import numpy as np

np.mod(np.arange(6), 2)

array([0, 1, 0, 1, 0, 1])

In [18]:
import numpy as np

a = np.array([0, 0, 1, 1])
b = np.array([0, 1, 0, 1])

a ^ b

array([0, 1, 1, 0])

In [19]:
import pandas as pd

df = pd.DataFrame(
    [[0, 0, 0],
     [0, 1, 1],
     [1, 0, 1],
     [1, 1, 0]],
     columns=["A", "B", "C"]
)
df

   A  B  C
0  0  0  0
1  0  1  1
2  1  0  1
3  1  1  0

In [20]:
import pandas as pd

df1 = pd.DataFrame([[0], [1]], columns=["A"])
df1

   A
0  0
1  1

In [21]:
import pandas as pd

df2 = pd.DataFrame(
    [[0], [0], [1],[1]],
    columns=["A"]
    )
df2

   A
0  0
1  0
2  1
3  1

In [22]:
import pandas as pd

df3 = pd.DataFrame(
    [[0, 0],
     [0, 1],
     [1, 0],
     [1, 1]],
     columns=["A", "B"]
)
df3

   A  B
0  0  0
1  0  1
2  1  0
3  1  1

In [23]:
import pandas as pd

df4 = pd.DataFrame(
    [[0, 0, 0],
     [0, 1, 1],
     [1, 0, 1],
     [1, 1, 0]],
     columns=["A", "B", "C"]
)
df4

   A  B  C
0  0  0  0
1  0  1  1
2  1  0  1
3  1  1  0

In [25]:
import numpy as np

a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]

In [26]:
import numpy as np

a = np.array([1, 2, 3])
print(a + 10)

[11 12 13]

In [27]:
import numpy as np

a = np.array([1, 2, 3, 4, 5, 6])
b = a.reshape(2, 3)
print(b)

[[1 2 3]
 [4 5 6]]

In [29]:
import numpy as np

x = np.arange(0, 11)
y = x ** 2

print(x)
print(y)

[ 0  1  2  3  4  5  6  7  8  9 10]
[  0   1   4   9  16  25  36  49  64  81 100]