###### 129_3_quality_fill_with_method_practice

In [11]:
import numpy as np
import pandas as pd

In [12]:
df = pd.DataFrame(
    [
        ["D001", "J69P", "MELMB", "L250601-A", "コイル", 1, np.nan, 300],
        ["D002", "J69P", "WSE", "L250601-B", "Buck-IC", 2, 2, 280],
        ["D003", "310D", "GSE", "L250602-C", "はんだ", 1, np.nan, 250],
        ["D004", "J69P", "MELMB", "L250603-D", "コイル", 3, 4, 310],
        ["D005", "310D", "WSE", "L250604-E", "NTF", 0, np.nan, 260],
        ["D006", "J69P", "GSE", "L250605-F", "コイル", 2, np.nan, 290],
        ["D007", "310D", "MELMB", "L250606-G", "はんだ", 1, 1, 240],
        ["D008", "J69P", "WSE", "L250607-H", "Buck-IC", 1, np.nan, 270],
        ["D009", "J69P", "MELMB", "L250608-I", "コイル", np.nan, np.nan, 320],
        ["D010", "310D", "GSE", "L250609-J", "NTF", np.nan, 0, 300],
    ],
    columns=[
        "defect_id",
        "project",
        "site",
        "lot_no",
        "defect_category",
        "first_report_defect_qty",
        "confirmed_defect_qty",
        "inspection_qty",
    ],
)
df

,defect_id,project,site,lot_no,defect_category,first_report_defect_qty,confirmed_defect_qty,inspection_qty
0,D001,J69P,MELMB,L250601-A,コイル,1.0,NaN,300
1,D002,J69P,WSE,L250601-B,Buck-IC,2.0,2.0,280
2,D003,310D,GSE,L250602-C,はんだ,1.0,NaN,250
3,D004,J69P,MELMB,L250603-D,コイル,3.0,4.0,310
4,D005,310D,WSE,L250604-E,NTF,0.0,NaN,260
5,D006,J69P,GSE,L250605-F,コイル,2.0,NaN,290
6,D007,310D,MELMB,L250606-G,はんだ,1.0,1.0,240
7,D008,J69P,WSE,L250607-H,Buck-IC,1.0,NaN,270
8,D009,J69P,MELMB,L250608-I,コイル,NaN,NaN,320
9,D010,310D,GSE,L250609-J,NTF,NaN,0.0,300

In [13]:
#cell3
df_work = df.copy()
df_work

,defect_id,project,site,lot_no,defect_category,first_report_defect_qty,confirmed_defect_qty,inspection_qty
0,D001,J69P,MELMB,L250601-A,コイル,1.0,NaN,300
1,D002,J69P,WSE,L250601-B,Buck-IC,2.0,2.0,280
2,D003,310D,GSE,L250602-C,はんだ,1.0,NaN,250
3,D004,J69P,MELMB,L250603-D,コイル,3.0,4.0,310
4,D005,310D,WSE,L250604-E,NTF,0.0,NaN,260
5,D006,J69P,GSE,L250605-F,コイル,2.0,NaN,290
6,D007,310D,MELMB,L250606-G,はんだ,1.0,1.0,240
7,D008,J69P,WSE,L250607-H,Buck-IC,1.0,NaN,270
8,D009,J69P,MELMB,L250608-I,コイル,NaN,NaN,320
9,D010,310D,GSE,L250609-J,NTF,NaN,0.0,300

In [14]:
#cell4
df_work["defect_qty_for_analysis"] = df_work["confirmed_defect_qty"].fillna(
    df_work["first_report_defect_qty"]
)
df_work

,defect_id,project,site,lot_no,defect_category,first_report_defect_qty,confirmed_defect_qty,inspection_qty,defect_qty_for_analysis
0,D001,J69P,MELMB,L250601-A,コイル,1.0,NaN,300,1.0
1,D002,J69P,WSE,L250601-B,Buck-IC,2.0,2.0,280,2.0
2,D003,310D,GSE,L250602-C,はんだ,1.0,NaN,250,1.0
3,D004,J69P,MELMB,L250603-D,コイル,3.0,4.0,310,4.0
4,D005,310D,WSE,L250604-E,NTF,0.0,NaN,260,0.0
5,D006,J69P,GSE,L250605-F,コイル,2.0,NaN,290,2.0
6,D007,310D,MELMB,L250606-G,はんだ,1.0,1.0,240,1.0
7,D008,J69P,WSE,L250607-H,Buck-IC,1.0,NaN,270,1.0
8,D009,J69P,MELMB,L250608-I,コイル,NaN,NaN,320,NaN
9,D010,310D,GSE,L250609-J,NTF,NaN,0.0,300,0.0

In [18]:
df_work["fill_method"] = "未確認"

df_work.loc[
    df_work["confirmed_defect_qty"].notna(),
    "fill_method",
] = "確定値"
df_work

df_work.loc[
    df_work["confirmed_defect_qty"].isna()
    & df_work["first_report_defect_qty"].notna(),
    "fill_method",
] = "速報値で補完"

df_work

,defect_id,project,site,lot_no,defect_category,first_report_defect_qty,confirmed_defect_qty,inspection_qty,defect_qty_for_analysis,fill_method
0,D001,J69P,MELMB,L250601-A,コイル,1.0,NaN,300,1.0,速報値で補完
1,D002,J69P,WSE,L250601-B,Buck-IC,2.0,2.0,280,2.0,確定値
2,D003,310D,GSE,L250602-C,はんだ,1.0,NaN,250,1.0,速報値で補完
3,D004,J69P,MELMB,L250603-D,コイル,3.0,4.0,310,4.0,確定値
4,D005,310D,WSE,L250604-E,NTF,0.0,NaN,260,0.0,速報値で補完
5,D006,J69P,GSE,L250605-F,コイル,2.0,NaN,290,2.0,速報値で補完
6,D007,310D,MELMB,L250606-G,はんだ,1.0,1.0,240,1.0,確定値
7,D008,J69P,WSE,L250607-H,Buck-IC,1.0,NaN,270,1.0,速報値で補完
8,D009,J69P,MELMB,L250608-I,コイル,NaN,NaN,320,NaN,未確認
9,D010,310D,GSE,L250609-J,NTF,NaN,0.0,300,0.0,確定値

In [21]:
#cell6

df_check_fill = df_work[
    [
        "defect_id",
        "project",
        "site",
        "defect_category",
        "first_report_defect_qty",
        "confirmed_defect_qty",
        "defect_qty_for_analysis",
        "fill_method",
    ]
].copy()
df_check_fill

,defect_id,project,site,defect_category,first_report_defect_qty,confirmed_defect_qty,defect_qty_for_analysis,fill_method
0,D001,J69P,MELMB,コイル,1.0,NaN,1.0,速報値で補完
1,D002,J69P,WSE,Buck-IC,2.0,2.0,2.0,確定値
2,D003,310D,GSE,はんだ,1.0,NaN,1.0,速報値で補完
3,D004,J69P,MELMB,コイル,3.0,4.0,4.0,確定値
4,D005,310D,WSE,NTF,0.0,NaN,0.0,速報値で補完
5,D006,J69P,GSE,コイル,2.0,NaN,2.0,速報値で補完
6,D007,310D,MELMB,はんだ,1.0,1.0,1.0,確定値
7,D008,J69P,WSE,Buck-IC,1.0,NaN,1.0,速報値で補完
8,D009,J69P,MELMB,コイル,NaN,NaN,NaN,未確認
9,D010,310D,GSE,NTF,NaN,0.0,0.0,確定値

In [22]:
df_unconfirmed = df_work[
    df_work["fill_method"] == "未確認"
].copy()

df_unconfirmed

,defect_id,project,site,lot_no,defect_category,first_report_defect_qty,confirmed_defect_qty,inspection_qty,defect_qty_for_analysis,fill_method
8,D009,J69P,MELMB,L250608-I,コイル,NaN,NaN,320,NaN,未確認

In [23]:
#cell8

df_work["defect_rate"] =(
    df_work["defect_qty_for_analysis"] / df_work["inspection_qty"]
)
df_work

,defect_id,project,site,lot_no,defect_category,first_report_defect_qty,confirmed_defect_qty,inspection_qty,defect_qty_for_analysis,fill_method,defect_rate
0,D001,J69P,MELMB,L250601-A,コイル,1.0,NaN,300,1.0,速報値で補完,0.003333
1,D002,J69P,WSE,L250601-B,Buck-IC,2.0,2.0,280,2.0,確定値,0.007143
2,D003,310D,GSE,L250602-C,はんだ,1.0,NaN,250,1.0,速報値で補完,0.004000
3,D004,J69P,MELMB,L250603-D,コイル,3.0,4.0,310,4.0,確定値,0.012903
4,D005,310D,WSE,L250604-E,NTF,0.0,NaN,260,0.0,速報値で補完,0.000000
5,D006,J69P,GSE,L250605-F,コイル,2.0,NaN,290,2.0,速報値で補完,0.006897
6,D007,310D,MELMB,L250606-G,はんだ,1.0,1.0,240,1.0,確定値,0.004167
7,D008,J69P,WSE,L250607-H,Buck-IC,1.0,NaN,270,1.0,速報値で補完,0.003704
8,D009,J69P,MELMB,L250608-I,コイル,NaN,NaN,320,NaN,未確認,NaN
9,D010,310D,GSE,L250609-J,NTF,NaN,0.0,300,0.0,確定値,0.000000

In [26]:
#cell9
df_work["check_result"] = "通常"

df_work.loc[
    df_work["fill_method"] == "未確認",
    "check_result",
] = "要確認：不具合数未確認"
df_work

df_work.loc[
    df_work["defect_rate"] > 0.005,
    "check_result",
] = "要確認：不具合率高い"

df_work

,defect_id,project,site,lot_no,defect_category,first_report_defect_qty,confirmed_defect_qty,inspection_qty,defect_qty_for_analysis,fill_method,defect_rate,check_result
0,D001,J69P,MELMB,L250601-A,コイル,1.0,NaN,300,1.0,速報値で補完,0.003333,通常
1,D002,J69P,WSE,L250601-B,Buck-IC,2.0,2.0,280,2.0,確定値,0.007143,要確認：不具合率高い
2,D003,310D,GSE,L250602-C,はんだ,1.0,NaN,250,1.0,速報値で補完,0.004000,通常
3,D004,J69P,MELMB,L250603-D,コイル,3.0,4.0,310,4.0,確定値,0.012903,要確認：不具合率高い
4,D005,310D,WSE,L250604-E,NTF,0.0,NaN,260,0.0,速報値で補完,0.000000,通常
5,D006,J69P,GSE,L250605-F,コイル,2.0,NaN,290,2.0,速報値で補完,0.006897,要確認：不具合率高い
6,D007,310D,MELMB,L250606-G,はんだ,1.0,1.0,240,1.0,確定値,0.004167,通常
7,D008,J69P,WSE,L250607-H,Buck-IC,1.0,NaN,270,1.0,速報値で補完,0.003704,通常
8,D009,J69P,MELMB,L250608-I,コイル,NaN,NaN,320,NaN,未確認,NaN,要確認：不具合数未確認
9,D010,310D,GSE,L250609-J,NTF,NaN,0.0,300,0.0,確定値,0.000000,通常

In [ ]:
#cell10
df_need_check = df_work[
    df_work["check_result"].str.contains("要確認")
].copy()
df_need_check

,defect_id,project,site,lot_no,defect_category,first_report_defect_qty,confirmed_defect_qty,inspection_qty,defect_qty_for_analysis,fill_method,defect_rate,check_result
1,D002,J69P,WSE,L250601-B,Buck-IC,2.0,2.0,280,2.0,確定値,0.007143,要確認：不具合率高い
3,D004,J69P,MELMB,L250603-D,コイル,3.0,4.0,310,4.0,確定値,0.012903,要確認：不具合率高い
5,D006,J69P,GSE,L250605-F,コイル,2.0,NaN,290,2.0,速報値で補完,0.006897,要確認：不具合率高い
8,D009,J69P,MELMB,L250608-I,コイル,NaN,NaN,320,NaN,未確認,NaN,要確認：不具合数未確認

In [28]:
#cell11
fill_method_count = df_work["fill_method"].value_counts()
fill_method_count

fill_method
速報値で補完    5
確定値       4
未確認       1
Name: count, dtype: int64