In [4]:
import pandas as pd

df_log = pd.read_csv("dataset/product_log.csv")
df_log["Num"] = df_log["Num"].interpolate()
df_log.head()

         Date  Num Product
0  2017-01-03  1.0       B
1  2017-01-06  2.0       B
2  2017-01-07  1.0       A
3  2017-01-11  2.0       A
4  2017-01-12  2.0       B

In [5]:
df_master = pd.read_csv("dataset/product_master.csv")
df_master

   Price Product
0   1000       A
1   1200       B

In [7]:
df_sale = pd.merge(df_log, df_master, on="Product")
df_sale.head()

         Date  Num Product  Price
0  2017-01-03  1.0       B   1200
1  2017-01-06  2.0       B   1200
2  2017-01-07  1.0       A   1000
3  2017-01-11  2.0       A   1000
4  2017-01-12  2.0       B   1200

In [8]:
df_sale["Sale"] = df_sale["Num"] * df_sale["Price"]
df_sale.head()

         Date  Num Product  Price    Sale
0  2017-01-03  1.0       B   1200  1200.0
1  2017-01-06  2.0       B   1200  2400.0
2  2017-01-07  1.0       A   1000  1000.0
3  2017-01-11  2.0       A   1000  2000.0
4  2017-01-12  2.0       B   1200  2400.0

In [9]:
df_sale

          Date  Num Product  Price    Sale
0   2017-01-03  1.0       B   1200  1200.0
1   2017-01-06  2.0       B   1200  2400.0
2   2017-01-07  1.0       A   1000  1000.0
3   2017-01-11  2.0       A   1000  2000.0
4   2017-01-12  2.0       B   1200  2400.0
5   2017-01-13  3.0       B   1200  3600.0
6   2017-01-15  2.0       B   1200  2400.0
7   2017-01-18  3.0       B   1200  3600.0
8   2017-01-20  2.0       B   1200  2400.0
9   2017-01-21  2.0       A   1000  2000.0
10  2017-01-29  3.0       A   1000  3000.0
11  2017-01-30  2.0       B   1200  2400.0
12  2017-02-01  4.0       A   1000  4000.0
13  2017-02-02  3.0       B   1200  3600.0
14  2017-02-03  3.0       B   1200  3600.0
15  2017-02-05  2.0       A   1000  2000.0
16  2017-02-08  2.5       A   1000  2500.0
17  2017-02-12  3.0       B   1200  3600.0
18  2017-02-14  4.0       A   1000  4000.0
19  2017-02-16  4.0       A   1000  4000.0
20  2017-02-18  4.0       A   1000  4000.0
21  2017-02-20  4.0       B   1200  4800.0
22  2017-02-23  4.0       A   1000  4000.0
23  2017-02-24  4.0       A   1000  4000.0
24  2017-02-26  4.0       B   1200  4800.0
25  2017-02-28  4.0       A   1000  4000.0
26  2017-03-01  4.0       A   1000  4000.0
27  2017-03-04  5.0       A   1000  5000.0
28  2017-03-08  4.0       B   1200  4800.0
29  2017-03-09  5.0       A   1000  5000.0
30  2017-03-11  5.0       A   1000  5000.0
31  2017-03-16  4.0       A   1000  4000.0
32  2017-03-17  6.0       B   1200  7200.0
33  2017-03-18  5.0       B   1200  6000.0
34  2017-03-20  6.0       B   1200  7200.0
35  2017-03-21  4.0       B   1200  4800.0
36  2017-03-22  4.0       B   1200  4800.0
37  2017-03-24  6.0       A   1000  6000.0
38  2017-03-27  6.0       A   1000  6000.0
39  2017-03-28  5.0       A   1000  5000.0

In [11]:
df_sale[df_sale["Product"] == "A"]

          Date  Num Product  Price    Sale
2   2017-01-07  1.0       A   1000  1000.0
3   2017-01-11  2.0       A   1000  2000.0
9   2017-01-21  2.0       A   1000  2000.0
10  2017-01-29  3.0       A   1000  3000.0
12  2017-02-01  4.0       A   1000  4000.0
15  2017-02-05  2.0       A   1000  2000.0
16  2017-02-08  2.5       A   1000  2500.0
18  2017-02-14  4.0       A   1000  4000.0
19  2017-02-16  4.0       A   1000  4000.0
20  2017-02-18  4.0       A   1000  4000.0
22  2017-02-23  4.0       A   1000  4000.0
23  2017-02-24  4.0       A   1000  4000.0
25  2017-02-28  4.0       A   1000  4000.0
26  2017-03-01  4.0       A   1000  4000.0
27  2017-03-04  5.0       A   1000  5000.0
29  2017-03-09  5.0       A   1000  5000.0
30  2017-03-11  5.0       A   1000  5000.0
31  2017-03-16  4.0       A   1000  4000.0
37  2017-03-24  6.0       A   1000  6000.0
38  2017-03-27  6.0       A   1000  6000.0
39  2017-03-28  5.0       A   1000  5000.0

In [16]:
df_sale.loc[df_sale["Product"] == "B","Sale"]

0     1200.0
1     2400.0
4     2400.0
5     3600.0
6     2400.0
7     3600.0
8     2400.0
11    2400.0
13    3600.0
14    3600.0
17    3600.0
21    4800.0
24    4800.0
28    4800.0
32    7200.0
33    6000.0
34    7200.0
35    4800.0
36    4800.0
Name: Sale, dtype: float64