###### 130_2_site_model_category_total_practice.ipynb

In [3]:
#cell 1
import pandas as pd
pd.set_option("display.max_columns", None)

In [4]:
#cell2
df_plan = pd.DataFrame(
    [
        ["SUS", "J69P", 50000],
        ["SUS", "310D", 30000],
        ["WSE", "310D", 45000],
        ["GSE", "J69P", 32000],
        ["MELMB", "310D", 60000],
        ["ISE", "J69P", 20000], 
    ],
    columns=[
        "site",
        "model",
        "plan_qty",
    ],
)
df_plan

    site model  plan_qty
0    SUS  J69P     50000
1    SUS  310D     30000
2    WSE  310D     45000
3    GSE  J69P     32000
4  MELMB  310D     60000
5    ISE  J69P     20000

In [5]:
df_defect = pd.DataFrame(
    [
        ["SUS", "J69P", "コイル", 3],
        ["SUS", "J69P", "Buck-IC", 1],
        ["SUS", "J69P", "コイル", 2],
        ["SUS", "310D", "NTF", 1],
        ["WSE", "310D", "コイル", 2],
        ["WSE", "310D", "NTF", 0],
        ["GSE", "J69P", "コイル", 4],
        ["GSE", "J69P", "Buck-IC", 2],
        ["MELMB", "310D", "コイル", 5],
        ["MELMB", "310D", "NTF", 1],
    ],
    columns=[
        "site",
        "model",
        "defect_category",
        "defect_qty",
    ],
)
df_defect

    site model defect_category  defect_qty
0    SUS  J69P             コイル           3
1    SUS  J69P         Buck-IC           1
2    SUS  J69P             コイル           2
3    SUS  310D             NTF           1
4    WSE  310D             コイル           2
5    WSE  310D             NTF           0
6    GSE  J69P             コイル           4
7    GSE  J69P         Buck-IC           2
8  MELMB  310D             コイル           5
9  MELMB  310D             NTF           1

In [6]:
df_work = df_defect[
    [
        "site",
        "model",
        "defect_category",
        "defect_qty",
    ]
].copy()
df_work

    site model defect_category  defect_qty
0    SUS  J69P             コイル           3
1    SUS  J69P         Buck-IC           1
2    SUS  J69P             コイル           2
3    SUS  310D             NTF           1
4    WSE  310D             コイル           2
5    WSE  310D             NTF           0
6    GSE  J69P             コイル           4
7    GSE  J69P         Buck-IC           2
8  MELMB  310D             コイル           5
9  MELMB  310D             NTF           1

In [7]:
df_work_positive = df_work[
    df_work["defect_qty"] > 0
].copy()
df_work_positive

    site model defect_category  defect_qty
0    SUS  J69P             コイル           3
1    SUS  J69P         Buck-IC           1
2    SUS  J69P             コイル           2
3    SUS  310D             NTF           1
4    WSE  310D             コイル           2
6    GSE  J69P             コイル           4
7    GSE  J69P         Buck-IC           2
8  MELMB  310D             コイル           5
9  MELMB  310D             NTF           1

In [8]:
#cell6
df_category_unique = df_work_positive.drop_duplicates(
    [
        "site",
        "model",
        "defect_category",
    ]
)
df_category_unique

    site model defect_category  defect_qty
0    SUS  J69P             コイル           3
1    SUS  J69P         Buck-IC           1
3    SUS  310D             NTF           1
4    WSE  310D             コイル           2
6    GSE  J69P             コイル           4
7    GSE  J69P         Buck-IC           2
8  MELMB  310D             コイル           5
9  MELMB  310D             NTF           1

In [10]:
#cell7
df_category = (
    df_category_unique.groupby(
        [
            "site",
            "model",
        ],
        as_index=False,
    )["defect_category"].agg("/".join)
)
df_category

    site model defect_category
0    GSE  J69P     コイル/Buck-IC
1  MELMB  310D         コイル/NTF
2    SUS  310D             NTF
3    SUS  J69P     コイル/Buck-IC
4    WSE  310D             コイル

In [ ]:
#cell 8
df_category = df_category.rename(
    columns={
        "defect_category": "defect_category_list",
    }
)
df_category

    site model defect_category_list
0    GSE  J69P          コイル/Buck-IC
1  MELMB  310D              コイル/NTF
2    SUS  310D                  NTF
3    SUS  J69P          コイル/Buck-IC
4    WSE  310D                  コイル

In [12]:
#cell 9
df_total = (
    df_work_positive.groupby(
        [
            "site",
            "model",
        ],
        as_index=False,
    )["defect_qty"].sum()
)
df_total

    site model  defect_qty
0    GSE  J69P           6
1  MELMB  310D           6
2    SUS  310D           1
3    SUS  J69P           6
4    WSE  310D           2

In [13]:
df_total = df_total.rename(
    columns={
        "defect_qty": "total_defect_qty",
    }
)
df_total

    site model  total_defect_qty
0    GSE  J69P                 6
1  MELMB  310D                 6
2    SUS  310D                 1
3    SUS  J69P                 6
4    WSE  310D                 2

In [15]:
#cell11
df_summary = pd.merge(
    df_category,
    df_total,
    on=[
        "site",
        "model",
    ],
    how="left",
)
df_summary

    site model defect_category_list  total_defect_qty
0    GSE  J69P          コイル/Buck-IC                 6
1  MELMB  310D              コイル/NTF                 6
2    SUS  310D                  NTF                 1
3    SUS  J69P          コイル/Buck-IC                 6
4    WSE  310D                  コイル                 2

In [16]:
#cell 12
df_result = pd.merge(
    df_plan,
    df_summary,
    on=[
        "site",
        "model",
    ],
    how="left",
)
df_result

    site model  plan_qty defect_category_list  total_defect_qty
0    SUS  J69P     50000          コイル/Buck-IC               6.0
1    SUS  310D     30000                  NTF               1.0
2    WSE  310D     45000                  コイル               2.0
3    GSE  J69P     32000          コイル/Buck-IC               6.0
4  MELMB  310D     60000              コイル/NTF               6.0
5    ISE  J69P     20000                  NaN               NaN

In [20]:
df_result["defect_category_list"] = (
    df_result["defect_category_list"].fillna("発生なし")
)
df_result

df_result["total_defect_qty"] = (
    df_result["total_defect_qty"].fillna(0)
)
df_result

df_result["total_defect_qty"] = (
    df_result["total_defect_qty"].astype(int)
)
df_result

    site model  plan_qty defect_category_list  total_defect_qty
0    SUS  J69P     50000          コイル/Buck-IC                 6
1    SUS  310D     30000                  NTF                 1
2    WSE  310D     45000                  コイル                 2
3    GSE  J69P     32000          コイル/Buck-IC                 6
4  MELMB  310D     60000              コイル/NTF                 6
5    ISE  J69P     20000                 発生なし                 0