## 「193-2: 複数のDataFrameを結合しよう」 1問目

In [4]:
import pandas as pd

df = pd.read_csv("input/data.csv", encoding="Shift_JIS")
df.head()

       date station  temp
0  2018/9/1      札幌  19.5
1  2018/9/1      青森  21.5
2  2018/9/1      仙台  21.5
3  2018/9/1      東京  25.9
4  2018/9/1      福岡  25.5

In [3]:
df_station = pd.read_csv("input/amedas_stations.csv",
                         encoding="Shift_JIS",
                         index_col=0)
df_station.head()

              latitude  longitude  altitude
station_name
稚内               45.42     141.68         3
札幌               43.06     141.33        17
函館               41.82     140.75        35
青森               40.82     140.77         3
秋田               39.72     140.10         6

In [5]:
df_join = df.join(df_station, on="station")
df_join.head()

       date station  temp  latitude  longitude  altitude
0  2018/9/1      札幌  19.5     43.06     141.33        17
1  2018/9/1      青森  21.5     40.82     140.77         3
2  2018/9/1      仙台  21.5     38.26     140.90        39
3  2018/9/1      東京  25.9     35.69     139.75        25
4  2018/9/1      福岡  25.5     33.58     130.38         3