## 「193-2: 複数のDataFrameを結合しよう」 1問目

In [4]:
import pandas as pd

df = pd.read_csv("input/data.csv", encoding="Shift_JIS")
df.head()

       date station  temp
0  2018/9/1      札幌  19.5
1  2018/9/1      青森  21.5
2  2018/9/1      仙台  21.5
3  2018/9/1      東京  25.9
4  2018/9/1      福岡  25.5

In [3]:
df_station = pd.read_csv("input/amedas_stations.csv",
                         encoding="Shift_JIS",
                         index_col=0)
df_station.head()

              latitude  longitude  altitude
station_name
稚内               45.42     141.68         3
札幌               43.06     141.33        17
函館               41.82     140.75        35
青森               40.82     140.77         3
秋田               39.72     140.10         6

In [5]:
df_join = df.join(df_station, on="station")
df_join.head()

       date station  temp  latitude  longitude  altitude
0  2018/9/1      札幌  19.5     43.06     141.33        17
1  2018/9/1      青森  21.5     40.82     140.77         3
2  2018/9/1      仙台  21.5     38.26     140.90        39
3  2018/9/1      東京  25.9     35.69     139.75        25
4  2018/9/1      福岡  25.5     33.58     130.38         3

## 実務練習問題

In [6]:
import pandas as pd
import numpy as np
import os

os.makedirs("input", exist_ok=True)

In [7]:
quality_data = pd.DataFrame({
     'date': ['2026/6/1', '2026/6/1', '2026/6/1', '2026/6/2', '2026/6/2', '2026/6/2'],
    'site': ['MELMB', 'WSE', 'GSE', 'MELMB', 'WSE', 'ISE'],
    'defect': ['点灯不良', '外観不良', 'ショート', '点灯不良', '外観不良', 'コネクタ浮き'],
    'production': [10000, 8000, 12000, 11000, 8500, 9000],
    'defects': [3, 5, 1, 4, 6, 2]
})

site_master = pd.DataFrame({
      'site': ['MELMB', 'WSE', 'GSE', 'ISE'],
    'country': ['Thailand', 'China', 'China', 'Japan'],
    'region': ['Asia', 'Asia', 'Asia', 'Japan'],
    'owner': ['Lighting Team', 'Appearance Team', 'Circuit Team', 'Connector Team']
})

In [8]:
quality_data.to_csv("input/quality_monsters.csv", index=False, encoding="Shift_JIS")
site_master.to_csv("input/site_master.csv", index=False, encoding="Shift_JIS")

In [9]:
df = pd.read_csv("input/quality_monsters.csv", encoding="Shift_JIS")
df.head()

       date   site defect  production  defects
0  2026/6/1  MELMB   点灯不良       10000        3
1  2026/6/1    WSE   外観不良        8000        5
2  2026/6/1    GSE   ショート       12000        1
3  2026/6/2  MELMB   点灯不良       11000        4
4  2026/6/2    WSE   外観不良        8500        6

In [15]:
df_sites = pd.read_csv("input/site_master.csv",
                      encoding="Shift_JIS",
                      index_col=0)
df_sites.head()

        country region            owner
site
MELMB  Thailand   Asia    Lighting Team
WSE       China   Asia  Appearance Team
GSE       China   Asia     Circuit Team
ISE       Japan  Japan   Connector Team

In [14]:
df_join = df.join(df_sites, on="site")
df_join.head()

,date,site,defect,production,defects,country,region,owner
0,2026/6/1,MELMB,点灯不良,10000,3,Thailand,Asia,Lighting Team
1,2026/6/1,WSE,外観不良,8000,5,China,Asia,Appearance Team
2,2026/6/1,GSE,ショート,12000,1,China,Asia,Circuit Team
3,2026/6/2,MELMB,点灯不良,11000,4,Thailand,Asia,Lighting Team
4,2026/6/2,WSE,外観不良,8500,6,China,Asia,Appearance Team

In [16]:
df_join["ppm"] = (df_join["defects"] / df_join["production"] * 1000000).round(1)

In [17]:
df_join.head()

,date,site,defect,production,defects,country,region,owner,ppm
0,2026/6/1,MELMB,点灯不良,10000,3,Thailand,Asia,Lighting Team,300.0
1,2026/6/1,WSE,外観不良,8000,5,China,Asia,Appearance Team,625.0
2,2026/6/1,GSE,ショート,12000,1,China,Asia,Circuit Team,83.3
3,2026/6/2,MELMB,点灯不良,11000,4,Thailand,Asia,Lighting Team,363.6
4,2026/6/2,WSE,外観不良,8500,6,China,Asia,Appearance Team,705.9

In [18]:
df_join["判定"] = np.where(df_join["ppm"] >= 500, "要確認", "通常")

In [19]:
df_join.head()

,date,site,defect,production,defects,country,region,owner,ppm,判定
0,2026/6/1,MELMB,点灯不良,10000,3,Thailand,Asia,Lighting Team,300.0,通常
1,2026/6/1,WSE,外観不良,8000,5,China,Asia,Appearance Team,625.0,要確認
2,2026/6/1,GSE,ショート,12000,1,China,Asia,Circuit Team,83.3,通常
3,2026/6/2,MELMB,点灯不良,11000,4,Thailand,Asia,Lighting Team,363.6,通常
4,2026/6/2,WSE,外観不良,8500,6,China,Asia,Appearance Team,705.9,要確認

In [20]:
df_ranking = df_join.sort_values(by="ppm", ascending=False)

In [21]:
df_ranking

,date,site,defect,production,defects,country,region,owner,ppm,判定
4,2026/6/2,WSE,外観不良,8500,6,China,Asia,Appearance Team,705.9,要確認
1,2026/6/1,WSE,外観不良,8000,5,China,Asia,Appearance Team,625.0,要確認
3,2026/6/2,MELMB,点灯不良,11000,4,Thailand,Asia,Lighting Team,363.6,通常
0,2026/6/1,MELMB,点灯不良,10000,3,Thailand,Asia,Lighting Team,300.0,通常
5,2026/6/2,ISE,コネクタ浮き,9000,2,Japan,Japan,Connector Team,222.2,通常
2,2026/6/1,GSE,ショート,12000,1,China,Asia,Circuit Team,83.3,通常

## 「193-2: 複数のDataFrameを結合しよう」 2問目

In [22]:
import pandas as pd

df = pd.read_csv("input/data.csv", encoding="Shift_JIS")

In [27]:
df_search1 = df[df["temp"] >= 18]
df_search1.head()

       date station  temp
0  2018/9/1      札幌  19.5
1  2018/9/1      青森  21.5
2  2018/9/1      仙台  21.5
3  2018/9/1      東京  25.9
4  2018/9/1      福岡  25.5

In [29]:
df_search2 = df[(df["temp"] > 18) & (df["temp"] < 20)]
df_search2.head()

         date station  temp
0    2018/9/1      札幌  19.5
100  2018/9/3      札幌  19.7
148  2018/9/3      稚内  18.4
198  2018/9/4      稚内  19.5
398  2018/9/8      稚内  19.2

In [31]:
df_search3 = df[(df["station"].isin(["東京", "札幌"])) & (df["temp"] < 20)]
df_search3.head()

          date station  temp
0     2018/9/1      札幌  19.5
100   2018/9/3      札幌  19.7
400   2018/9/9      札幌  18.3
550  2018/9/12      札幌  16.5
600  2018/9/13      札幌  18.8

In [32]:
import pandas as pd

df = pd.DataFrame({
     'date': ['2026/6/1', '2026/6/1', '2026/6/2', '2026/6/2', '2026/6/3'],
    'site': ['MELMB', 'WSE', 'GSE', 'MELMB', 'ISE'],
    'defect': ['点灯不良', '外観不良', 'ショート', '点灯不良', 'コネクタ浮き'],
    'production': [10000, 8000, 12000, 11000, 9000],
    'defects': [3, 5, 1, 8, 2]
})

In [33]:
df.head()

       date   site  defect  production  defects
0  2026/6/1  MELMB    点灯不良       10000        3
1  2026/6/1    WSE    外観不良        8000        5
2  2026/6/2    GSE    ショート       12000        1
3  2026/6/2  MELMB    点灯不良       11000        8
4  2026/6/3    ISE  コネクタ浮き        9000        2

In [34]:
df["ppm"] = (df["defects"] / df["production"] * 1000000).round(1)

In [35]:
df.head()

       date   site  defect  production  defects    ppm
0  2026/6/1  MELMB    点灯不良       10000        3  300.0
1  2026/6/1    WSE    外観不良        8000        5  625.0
2  2026/6/2    GSE    ショート       12000        1   83.3
3  2026/6/2  MELMB    点灯不良       11000        8  727.3
4  2026/6/3    ISE  コネクタ浮き        9000        2  222.2

In [39]:
df_ppm_high = df[df["ppm"] >= 500]
df_ppm_high.head()

       date   site defect  production  defects    ppm
1  2026/6/1    WSE   外観不良        8000        5  625.0
3  2026/6/2  MELMB   点灯不良       11000        8  727.3

In [37]:
df.head()

       date   site  defect  production  defects    ppm
0  2026/6/1  MELMB    点灯不良       10000        3  300.0
1  2026/6/1    WSE    外観不良        8000        5  625.0
2  2026/6/2    GSE    ショート       12000        1   83.3
3  2026/6/2  MELMB    点灯不良       11000        8  727.3
4  2026/6/3    ISE  コネクタ浮き        9000        2  222.2

In [42]:
df_target = df[(df["site"].isin(["MELMB", "WSE"])) & (df["ppm"] >= 500)]

In [43]:
df_target

       date   site defect  production  defects    ppm
1  2026/6/1    WSE   外観不良        8000        5  625.0
3  2026/6/2  MELMB   点灯不良       11000        8  727.3