In [1]:
import pandas as pd

In [2]:
df = pd.DataFrame(
    [
        ["Alice", "国語", 87],
        ["Alice", "数学", 72],
        ["Bob", "国語", 65],
        ["Bob", "数学", 92],
    ],
    columns=["Name", "Subject", "Point"],
)
df

    Name Subject  Point
0  Alice      国語     87
1  Alice      数学     72
2    Bob      国語     65
3    Bob      数学     92

In [3]:
df_class = pd.DataFrame(
    [
        ["Alice", "1-A"],
        ["Bob", "1-B"],
        ["Carol", "1-C"],

    ],
    columns=["Name", "Class"],
)
df_class

    Name Class
0  Alice   1-A
1    Bob   1-B
2  Carol   1-C

In [4]:
df_result = df.merge(df_class)
df_result

    Name Subject  Point Class
0  Alice      国語     87   1-A
1  Alice      数学     72   1-A
2    Bob      国語     65   1-B
3    Bob      数学     92   1-B