In [2]:
import pandas as pd

df = pd.read_csv("event_sample.csv")
df.head()

        イベント日    勉強会グループ    イベント 開催形式  定員  登録者数
0  2019-01-23  Python輪読会    No.1    S  20    19
1  2019-01-26      初心者の会   もくもく会   SL  20    12
2  2019-01-27       なまこ部  Talk#1   SL  20    12
3  2019-01-30  Python輪読会    No.2    S  20    15
4  2019-02-02   電子工作シリーズ   CO2測定    S  50    41

In [5]:
df_shape = df.shape
df_shape

(6, 6)

In [6]:
group_count = df["勉強会グループ"].value_counts()
group_count

勉強会グループ
Python輪読会    2
初心者の会        2
なまこ部         1
電子工作シリーズ     1
Name: count, dtype: int64

In [7]:
onoff_values = df["開催形式"].unique()
onoff_values

<StringArray>
['S', 'SL', 'L']
Length: 3, dtype: str

In [8]:
df_desc = df[["定員", "登録者数"]].describe()
df_desc

              定員       登録者数
count   6.000000   6.000000
mean   26.666667  21.166667
std    12.110601  11.409061
min    20.000000  12.000000
25%    20.000000  12.750000
50%    20.000000  17.000000
75%    27.500000  25.750000
max    50.000000  41.000000

In [10]:
df["登録者数"].max()

np.int64(41)

In [11]:
df[df["定員"] >= 30]

        イベント日   勉強会グループ   イベント 開催形式  定員  登録者数
4  2019-02-02  電子工作シリーズ  CO2測定    S  50    41
5  2019-02-10     初心者の会    勉強会    L  30    28

In [12]:
df[df["開催形式"] == "S"]

        イベント日    勉強会グループ   イベント 開催形式  定員  登録者数
0  2019-01-23  Python輪読会   No.1    S  20    19
3  2019-01-30  Python輪読会   No.2    S  20    15
4  2019-02-02   電子工作シリーズ  CO2測定    S  50    41

In [13]:
df["登録者数"].max()

np.int64(41)

In [14]:
df["登録者数"].max()

np.int64(41)

In [15]:
df["登録者数"].max()

np.int64(41)

In [16]:
code_map = {"S": False, "L": True, "SL": True}
df["リモート可"] = df["開催形式"].map(code_map)
df.head()

        イベント日    勉強会グループ    イベント 開催形式  定員  登録者数  リモート可
0  2019-01-23  Python輪読会    No.1    S  20    19  False
1  2019-01-26      初心者の会   もくもく会   SL  20    12   True
2  2019-01-27       なまこ部  Talk#1   SL  20    12   True
3  2019-01-30  Python輪読会    No.2    S  20    15  False
4  2019-02-02   電子工作シリーズ   CO2測定    S  50    41  False

In [17]:
df["参加者数"] = df["登録者数"].mask(
    df["登録者数"] > df ["定員"],
    df["定員"]
)
df.head()

        イベント日    勉強会グループ    イベント 開催形式  定員  登録者数  リモート可  参加者数
0  2019-01-23  Python輪読会    No.1    S  20    19  False    19
1  2019-01-26      初心者の会   もくもく会   SL  20    12   True    12
2  2019-01-27       なまこ部  Talk#1   SL  20    12   True    12
3  2019-01-30  Python輪読会    No.2    S  20    15  False    15
4  2019-02-02   電子工作シリーズ   CO2測定    S  50    41  False    41

In [18]:
df["満席率"] = df["登録者数"] / df["定員"]
df.head()

        イベント日    勉強会グループ    イベント 開催形式  定員  登録者数  リモート可  参加者数   満席率
0  2019-01-23  Python輪読会    No.1    S  20    19  False    19  0.95
1  2019-01-26      初心者の会   もくもく会   SL  20    12   True    12  0.60
2  2019-01-27       なまこ部  Talk#1   SL  20    12   True    12  0.60
3  2019-01-30  Python輪読会    No.2    S  20    15  False    15  0.75
4  2019-02-02   電子工作シリーズ   CO2測定    S  50    41  False    41  0.82

In [19]:
def categorize(x):
    if "次週" in  x or "もくもく" in x:
        return "次週"
    elif "輪読" in x:
        return "輪読"
    else:
        return "一般"
df["カテゴリー"] = df["イベント"].apply(categorize)
df.head()

        イベント日    勉強会グループ    イベント 開催形式  定員  登録者数  リモート可  参加者数   満席率 カテゴリー
0  2019-01-23  Python輪読会    No.1    S  20    19  False    19  0.95    一般
1  2019-01-26      初心者の会   もくもく会   SL  20    12   True    12  0.60    次週
2  2019-01-27       なまこ部  Talk#1   SL  20    12   True    12  0.60    一般
3  2019-01-30  Python輪読会    No.2    S  20    15  False    15  0.75    一般
4  2019-02-02   電子工作シリーズ   CO2測定    S  50    41  False    41  0.82    一般