###### 129_2_quality_ffill_practice

In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.DataFrame(
    [
        ["2026-06-01", "08:00", "J69P", "MELMB", "Line1", "L250601-A", 300, 0],
        ["2026-06-01", "10:00", np.nan, np.nan, np.nan, np.nan, 280, 1],
        ["2026-06-01", "13:00", np.nan, np.nan, np.nan, np.nan, 320, 2],
        ["2026-06-02", "08:00", "310D", "WSE", "Line2", "L250602-B", 250, 0],
        ["2026-06-02", "10:00", np.nan, np.nan, np.nan, np.nan, 260, 1],
        ["2026-06-02", "13:00", np.nan, np.nan, np.nan, np.nan, 240, 0],
        ["2026-06-03", "08:00", "J69P", "GSE", "Line1", "L250603-C", 310, 3],
        ["2026-06-03", "10:00", np.nan, np.nan, np.nan, np.nan, 290, 0],
        ["2026-06-03", "13:00", np.nan, np.nan, np.nan, np.nan, 300, 1],
    ],
    columns=[
        "inspection_date",
        "inspection_time",
        "project",
        "site",
        "line",
        "lot_no",
        "inspection_qty",
        "defect_qty",
    ],
)
df

,inspection_date,inspection_time,project,site,line,lot_no,inspection_qty,defect_qty
0,2026-06-01,08:00,J69P,MELMB,Line1,L250601-A,300,0
1,2026-06-01,10:00,NaN,NaN,NaN,NaN,280,1
2,2026-06-01,13:00,NaN,NaN,NaN,NaN,320,2
3,2026-06-02,08:00,310D,WSE,Line2,L250602-B,250,0
4,2026-06-02,10:00,NaN,NaN,NaN,NaN,260,1
5,2026-06-02,13:00,NaN,NaN,NaN,NaN,240,0
6,2026-06-03,08:00,J69P,GSE,Line1,L250603-C,310,3
7,2026-06-03,10:00,NaN,NaN,NaN,NaN,290,0
8,2026-06-03,13:00,NaN,NaN,NaN,NaN,300,1

In [4]:
df_work = df.copy()
df_work

,inspection_date,inspection_time,project,site,line,lot_no,inspection_qty,defect_qty
0,2026-06-01,08:00,J69P,MELMB,Line1,L250601-A,300,0
1,2026-06-01,10:00,NaN,NaN,NaN,NaN,280,1
2,2026-06-01,13:00,NaN,NaN,NaN,NaN,320,2
3,2026-06-02,08:00,310D,WSE,Line2,L250602-B,250,0
4,2026-06-02,10:00,NaN,NaN,NaN,NaN,260,1
5,2026-06-02,13:00,NaN,NaN,NaN,NaN,240,0
6,2026-06-03,08:00,J69P,GSE,Line1,L250603-C,310,3
7,2026-06-03,10:00,NaN,NaN,NaN,NaN,290,0
8,2026-06-03,13:00,NaN,NaN,NaN,NaN,300,1

In [10]:
df_work["project_filled"] = df_work["project"].ffill()
df_work
df_work["site_filled"] = df_work["site"].ffill()
df_work
df_work["line_filled"] = df_work["line"].ffill()
df_work
df_work["lot_no_filled"] = df_work["lot_no"].ffill()
df_work

,inspection_date,inspection_time,project,site,line,lot_no,inspection_qty,defect_qty,project_filled,site_filled,line_filled,lot_no_filled
0,2026-06-01,08:00,J69P,MELMB,Line1,L250601-A,300,0,J69P,MELMB,Line1,L250601-A
1,2026-06-01,10:00,NaN,NaN,NaN,NaN,280,1,J69P,MELMB,Line1,L250601-A
2,2026-06-01,13:00,NaN,NaN,NaN,NaN,320,2,J69P,MELMB,Line1,L250601-A
3,2026-06-02,08:00,310D,WSE,Line2,L250602-B,250,0,310D,WSE,Line2,L250602-B
4,2026-06-02,10:00,NaN,NaN,NaN,NaN,260,1,310D,WSE,Line2,L250602-B
5,2026-06-02,13:00,NaN,NaN,NaN,NaN,240,0,310D,WSE,Line2,L250602-B
6,2026-06-03,08:00,J69P,GSE,Line1,L250603-C,310,3,J69P,GSE,Line1,L250603-C
7,2026-06-03,10:00,NaN,NaN,NaN,NaN,290,0,J69P,GSE,Line1,L250603-C
8,2026-06-03,13:00,NaN,NaN,NaN,NaN,300,1,J69P,GSE,Line1,L250603-C

In [11]:
df_result = df_work[
    [
        "inspection_date",
        "inspection_time",
        "project_filled",
        "site_filled",
        "line_filled",
        "lot_no_filled",
        "inspection_qty",
        "defect_qty",
    ]
].copy()
df_result

,inspection_date,inspection_time,project_filled,site_filled,line_filled,lot_no_filled,inspection_qty,defect_qty
0,2026-06-01,08:00,J69P,MELMB,Line1,L250601-A,300,0
1,2026-06-01,10:00,J69P,MELMB,Line1,L250601-A,280,1
2,2026-06-01,13:00,J69P,MELMB,Line1,L250601-A,320,2
3,2026-06-02,08:00,310D,WSE,Line2,L250602-B,250,0
4,2026-06-02,10:00,310D,WSE,Line2,L250602-B,260,1
5,2026-06-02,13:00,310D,WSE,Line2,L250602-B,240,0
6,2026-06-03,08:00,J69P,GSE,Line1,L250603-C,310,3
7,2026-06-03,10:00,J69P,GSE,Line1,L250603-C,290,0
8,2026-06-03,13:00,J69P,GSE,Line1,L250603-C,300,1

In [12]:
df_result["defect_rate"] = df_result["defect_qty"] / df_result["inspection_qty"]
df_result

,inspection_date,inspection_time,project_filled,site_filled,line_filled,lot_no_filled,inspection_qty,defect_qty,defect_rate
0,2026-06-01,08:00,J69P,MELMB,Line1,L250601-A,300,0,0.000000
1,2026-06-01,10:00,J69P,MELMB,Line1,L250601-A,280,1,0.003571
2,2026-06-01,13:00,J69P,MELMB,Line1,L250601-A,320,2,0.006250
3,2026-06-02,08:00,310D,WSE,Line2,L250602-B,250,0,0.000000
4,2026-06-02,10:00,310D,WSE,Line2,L250602-B,260,1,0.003846
5,2026-06-02,13:00,310D,WSE,Line2,L250602-B,240,0,0.000000
6,2026-06-03,08:00,J69P,GSE,Line1,L250603-C,310,3,0.009677
7,2026-06-03,10:00,J69P,GSE,Line1,L250603-C,290,0,0.000000
8,2026-06-03,13:00,J69P,GSE,Line1,L250603-C,300,1,0.003333

In [13]:
df_result_sort = df_result.sort_values(
    "defect_rate",
    ascending=False,
)
df_result_sort

,inspection_date,inspection_time,project_filled,site_filled,line_filled,lot_no_filled,inspection_qty,defect_qty,defect_rate
6,2026-06-03,08:00,J69P,GSE,Line1,L250603-C,310,3,0.009677
2,2026-06-01,13:00,J69P,MELMB,Line1,L250601-A,320,2,0.006250
4,2026-06-02,10:00,310D,WSE,Line2,L250602-B,260,1,0.003846
1,2026-06-01,10:00,J69P,MELMB,Line1,L250601-A,280,1,0.003571
8,2026-06-03,13:00,J69P,GSE,Line1,L250603-C,300,1,0.003333
0,2026-06-01,08:00,J69P,MELMB,Line1,L250601-A,300,0,0.000000
3,2026-06-02,08:00,310D,WSE,Line2,L250602-B,250,0,0.000000
5,2026-06-02,13:00,310D,WSE,Line2,L250602-B,240,0,0.000000
7,2026-06-03,10:00,J69P,GSE,Line1,L250603-C,290,0,0.000000