###### 129_5_super_practical_quality_priority_rank/

In [1]:
#cell 1
import pandas as pd

In [2]:
df = pd.DataFrame(
    [
        ["D001", "J69P", "MELMB", "コイル", 3, 12000, "調査中", "2026-06-01"],
        ["D002", "J69P", "WSE", "Buck-IC", 5, 18000, "対策検討中", "2026-06-02"],
        ["D003", "310D", "GSE", "コイル", 12, 25000, "暫定対策済", "2026-06-03"],
        ["D004", "310D", "MELMB", "はんだ", 2, 9000, "調査中", "2026-06-04"],
        ["D005", "J69P", "GSE", "コイル", 7, 15000, "調査中", "2026-06-05"],
        ["D006", "310D", "WSE", "コネクタ", 1, 6000, "完了", "2026-06-06"],
        ["D007", "J69P", "MELMB", "Buck-IC", 8, 20000, "調査中", "2026-06-07"],
        ["D008", "310D", "GSE", "コイル", 4, 10000, "対策検討中", "2026-06-08"],
        ["D009", "J69P", "GSE", "Buck-IC", 6, 14000, "調査中", "2026-06-09"],
        ["D010", "310D", "MELMB", "コイル", 5, 16000, "暫定対策済", "2026-06-10"],
        ["D011", "J69P", "WSE", "コイル", 9, 22000, "調査中", "2026-06-11"],
        ["D012", "310D", "GSE", "はんだ", 3, 8000, "完了", "2026-06-12"],
        ["D013", "J69P", "MELMB", "コイル", 4, 11000, "調査中", "2026-06-13"],
        ["D014", "310D", "WSE", "Buck-IC", 2, 7000, "対策検討中", "2026-06-14"],
        ["D015", "J69P", "GSE", "コイル", 5, 13000, "調査中", "2026-06-15"],
    ],
    columns=[
        "defect_id",
        "project",
        "site",
        "defect_category",
        "defect_qty",
        "inspection_qty",
        "status",
        "occ_date",
    ],
)
df

,defect_id,project,site,defect_category,defect_qty,inspection_qty,status,occ_date
0,D001,J69P,MELMB,コイル,3,12000,調査中,2026-06-01
1,D002,J69P,WSE,Buck-IC,5,18000,対策検討中,2026-06-02
2,D003,310D,GSE,コイル,12,25000,暫定対策済,2026-06-03
3,D004,310D,MELMB,はんだ,2,9000,調査中,2026-06-04
4,D005,J69P,GSE,コイル,7,15000,調査中,2026-06-05
5,D006,310D,WSE,コネクタ,1,6000,完了,2026-06-06
6,D007,J69P,MELMB,Buck-IC,8,20000,調査中,2026-06-07
7,D008,310D,GSE,コイル,4,10000,対策検討中,2026-06-08
8,D009,J69P,GSE,Buck-IC,6,14000,調査中,2026-06-09
9,D010,310D,MELMB,コイル,5,16000,暫定対策済,2026-06-10
10,D011,J69P,WSE,コイル,9,22000,調査中,2026-06-11
11,D012,310D,GSE,はんだ,3,8000,完了,2026-06-12
12,D013,J69P,MELMB,コイル,4,11000,調査中,2026-06-13
13,D014,310D,WSE,Buck-IC,2,7000,対策検討中,2026-06-14
14,D015,J69P,GSE,コイル,5,13000,調査中,2026-06-15

In [3]:
#cell 3
df_work = df.copy()
df_work

,defect_id,project,site,defect_category,defect_qty,inspection_qty,status,occ_date
0,D001,J69P,MELMB,コイル,3,12000,調査中,2026-06-01
1,D002,J69P,WSE,Buck-IC,5,18000,対策検討中,2026-06-02
2,D003,310D,GSE,コイル,12,25000,暫定対策済,2026-06-03
3,D004,310D,MELMB,はんだ,2,9000,調査中,2026-06-04
4,D005,J69P,GSE,コイル,7,15000,調査中,2026-06-05
5,D006,310D,WSE,コネクタ,1,6000,完了,2026-06-06
6,D007,J69P,MELMB,Buck-IC,8,20000,調査中,2026-06-07
7,D008,310D,GSE,コイル,4,10000,対策検討中,2026-06-08
8,D009,J69P,GSE,Buck-IC,6,14000,調査中,2026-06-09
9,D010,310D,MELMB,コイル,5,16000,暫定対策済,2026-06-10
10,D011,J69P,WSE,コイル,9,22000,調査中,2026-06-11
11,D012,310D,GSE,はんだ,3,8000,完了,2026-06-12
12,D013,J69P,MELMB,コイル,4,11000,調査中,2026-06-13
13,D014,310D,WSE,Buck-IC,2,7000,対策検討中,2026-06-14
14,D015,J69P,GSE,コイル,5,13000,調査中,2026-06-15

In [4]:
df_work["occ_date"] = pd.to_datetime(
    df_work["occ_date"]
)

df_work

,defect_id,project,site,defect_category,defect_qty,inspection_qty,status,occ_date
0,D001,J69P,MELMB,コイル,3,12000,調査中,2026-06-01
1,D002,J69P,WSE,Buck-IC,5,18000,対策検討中,2026-06-02
2,D003,310D,GSE,コイル,12,25000,暫定対策済,2026-06-03
3,D004,310D,MELMB,はんだ,2,9000,調査中,2026-06-04
4,D005,J69P,GSE,コイル,7,15000,調査中,2026-06-05
5,D006,310D,WSE,コネクタ,1,6000,完了,2026-06-06
6,D007,J69P,MELMB,Buck-IC,8,20000,調査中,2026-06-07
7,D008,310D,GSE,コイル,4,10000,対策検討中,2026-06-08
8,D009,J69P,GSE,Buck-IC,6,14000,調査中,2026-06-09
9,D010,310D,MELMB,コイル,5,16000,暫定対策済,2026-06-10
10,D011,J69P,WSE,コイル,9,22000,調査中,2026-06-11
11,D012,310D,GSE,はんだ,3,8000,完了,2026-06-12
12,D013,J69P,MELMB,コイル,4,11000,調査中,2026-06-13
13,D014,310D,WSE,Buck-IC,2,7000,対策検討中,2026-06-14
14,D015,J69P,GSE,コイル,5,13000,調査中,2026-06-15

In [5]:
df_work["occ_date"].dtypes

dtype('<M8[ns]')

In [6]:
#cell5
df_summary = df_work.groupby(
    [
        "site",
        "defect_category",
    ],
    as_index=False,
)[
    [
        "defect_qty",
        "inspection_qty",
    ]
].sum()

df_summary

    site defect_category  defect_qty  inspection_qty
0    GSE         Buck-IC           6           14000
1    GSE             はんだ           3            8000
2    GSE             コイル          28           63000
3  MELMB         Buck-IC           8           20000
4  MELMB             はんだ           2            9000
5  MELMB             コイル          12           39000
6    WSE         Buck-IC           7           25000
7    WSE             コイル           9           22000
8    WSE            コネクタ           1            6000

In [7]:
#cell6
df_summary = df_summary.rename(
    columns={
        "defect_qty": "total_defect_qty",
        "inspection_qty": "total_inspection_qty",
    }
)
df_summary

    site defect_category  total_defect_qty  total_inspection_qty
0    GSE         Buck-IC                 6                 14000
1    GSE             はんだ                 3                  8000
2    GSE             コイル                28                 63000
3  MELMB         Buck-IC                 8                 20000
4  MELMB             はんだ                 2                  9000
5  MELMB             コイル                12                 39000
6    WSE         Buck-IC                 7                 25000
7    WSE             コイル                 9                 22000
8    WSE            コネクタ                 1                  6000

In [8]:
#cell7
df_summary["defect_rate"] = (
    df_summary["total_defect_qty"]
    / df_summary["total_inspection_qty"]
)

df_summary

    site defect_category  total_defect_qty  total_inspection_qty  defect_rate
0    GSE         Buck-IC                 6                 14000     0.000429
1    GSE             はんだ                 3                  8000     0.000375
2    GSE             コイル                28                 63000     0.000444
3  MELMB         Buck-IC                 8                 20000     0.000400
4  MELMB             はんだ                 2                  9000     0.000222
5  MELMB             コイル                12                 39000     0.000308
6    WSE         Buck-IC                 7                 25000     0.000280
7    WSE             コイル                 9                 22000     0.000409
8    WSE            コネクタ                 1                  6000     0.000167

In [9]:
#cell8
df_summary["defect_ppm"] = (
    df_summary["defect_rate"] * 1000000
)
df_summary

,site,defect_category,total_defect_qty,total_inspection_qty,defect_rate,defect_ppm
0,GSE,Buck-IC,6,14000,0.000429,428.571429
1,GSE,はんだ,3,8000,0.000375,375.000000
2,GSE,コイル,28,63000,0.000444,444.444444
3,MELMB,Buck-IC,8,20000,0.000400,400.000000
4,MELMB,はんだ,2,9000,0.000222,222.222222
5,MELMB,コイル,12,39000,0.000308,307.692308
6,WSE,Buck-IC,7,25000,0.000280,280.000000
7,WSE,コイル,9,22000,0.000409,409.090909
8,WSE,コネクタ,1,6000,0.000167,166.666667

In [10]:
top3_index = df_summary["total_defect_qty"].nlargest(3).index
top3_index

Index([2, 5, 7], dtype='int64')

In [11]:
df_summary.loc[
    top3_index,
    "priority_rank",
] = [
    1,
    2,
    3,
]

df_summary

,site,defect_category,total_defect_qty,total_inspection_qty,defect_rate,defect_ppm,priority_rank
0,GSE,Buck-IC,6,14000,0.000429,428.571429,NaN
1,GSE,はんだ,3,8000,0.000375,375.000000,NaN
2,GSE,コイル,28,63000,0.000444,444.444444,1.0
3,MELMB,Buck-IC,8,20000,0.000400,400.000000,NaN
4,MELMB,はんだ,2,9000,0.000222,222.222222,NaN
5,MELMB,コイル,12,39000,0.000308,307.692308,2.0
6,WSE,Buck-IC,7,25000,0.000280,280.000000,NaN
7,WSE,コイル,9,22000,0.000409,409.090909,3.0
8,WSE,コネクタ,1,6000,0.000167,166.666667,NaN

In [12]:
#cell11
df_summary["priority_flag"] = "通常確認"
df_summary

,site,defect_category,total_defect_qty,total_inspection_qty,defect_rate,defect_ppm,priority_rank,priority_flag
0,GSE,Buck-IC,6,14000,0.000429,428.571429,NaN,通常確認
1,GSE,はんだ,3,8000,0.000375,375.000000,NaN,通常確認
2,GSE,コイル,28,63000,0.000444,444.444444,1.0,通常確認
3,MELMB,Buck-IC,8,20000,0.000400,400.000000,NaN,通常確認
4,MELMB,はんだ,2,9000,0.000222,222.222222,NaN,通常確認
5,MELMB,コイル,12,39000,0.000308,307.692308,2.0,通常確認
6,WSE,Buck-IC,7,25000,0.000280,280.000000,NaN,通常確認
7,WSE,コイル,9,22000,0.000409,409.090909,3.0,通常確認
8,WSE,コネクタ,1,6000,0.000167,166.666667,NaN,通常確認

In [13]:
df_summary.loc[
    df_summary["priority_rank"].notna(),
    "priority_flag",
] = "重点確認"

df_summary

,site,defect_category,total_defect_qty,total_inspection_qty,defect_rate,defect_ppm,priority_rank,priority_flag
0,GSE,Buck-IC,6,14000,0.000429,428.571429,NaN,通常確認
1,GSE,はんだ,3,8000,0.000375,375.000000,NaN,通常確認
2,GSE,コイル,28,63000,0.000444,444.444444,1.0,重点確認
3,MELMB,Buck-IC,8,20000,0.000400,400.000000,NaN,通常確認
4,MELMB,はんだ,2,9000,0.000222,222.222222,NaN,通常確認
5,MELMB,コイル,12,39000,0.000308,307.692308,2.0,重点確認
6,WSE,Buck-IC,7,25000,0.000280,280.000000,NaN,通常確認
7,WSE,コイル,9,22000,0.000409,409.090909,3.0,重点確認
8,WSE,コネクタ,1,6000,0.000167,166.666667,NaN,通常確認

In [15]:
df_summary["report_comment"] = "通常監視"

df_summary.loc[
    df_summary["priority_flag"] == "重点確認",
    "report_comment",
] = "不良数top3のための優先確認"
df_summary

,site,defect_category,total_defect_qty,total_inspection_qty,defect_rate,defect_ppm,priority_rank,priority_flag,report_comment
0,GSE,Buck-IC,6,14000,0.000429,428.571429,NaN,通常確認,通常監視
1,GSE,はんだ,3,8000,0.000375,375.000000,NaN,通常確認,通常監視
2,GSE,コイル,28,63000,0.000444,444.444444,1.0,重点確認,不良数top3のための優先確認
3,MELMB,Buck-IC,8,20000,0.000400,400.000000,NaN,通常確認,通常監視
4,MELMB,はんだ,2,9000,0.000222,222.222222,NaN,通常確認,通常監視
5,MELMB,コイル,12,39000,0.000308,307.692308,2.0,重点確認,不良数top3のための優先確認
6,WSE,Buck-IC,7,25000,0.000280,280.000000,NaN,通常確認,通常監視
7,WSE,コイル,9,22000,0.000409,409.090909,3.0,重点確認,不良数top3のための優先確認
8,WSE,コネクタ,1,6000,0.000167,166.666667,NaN,通常確認,通常監視

In [16]:
df_report = df_summary.sort_values(
    [
        "priority_rank",
        "total_defect_qty",
        "defect_ppm",
    ],
    ascending=[
        True,
        False,
        False,
    ],
)

df_report

,site,defect_category,total_defect_qty,total_inspection_qty,defect_rate,defect_ppm,priority_rank,priority_flag,report_comment
2,GSE,コイル,28,63000,0.000444,444.444444,1.0,重点確認,不良数top3のための優先確認
5,MELMB,コイル,12,39000,0.000308,307.692308,2.0,重点確認,不良数top3のための優先確認
7,WSE,コイル,9,22000,0.000409,409.090909,3.0,重点確認,不良数top3のための優先確認
3,MELMB,Buck-IC,8,20000,0.000400,400.000000,NaN,通常確認,通常監視
6,WSE,Buck-IC,7,25000,0.000280,280.000000,NaN,通常確認,通常監視
0,GSE,Buck-IC,6,14000,0.000429,428.571429,NaN,通常確認,通常監視
1,GSE,はんだ,3,8000,0.000375,375.000000,NaN,通常確認,通常監視
4,MELMB,はんだ,2,9000,0.000222,222.222222,NaN,通常確認,通常監視
8,WSE,コネクタ,1,6000,0.000167,166.666667,NaN,通常確認,通常監視

In [18]:
#cell14
df_priority = df_report[
    df_report["priority_flag"] == "重点確認"
].copy()

df_priority

,site,defect_category,total_defect_qty,total_inspection_qty,defect_rate,defect_ppm,priority_rank,priority_flag,report_comment
2,GSE,コイル,28,63000,0.000444,444.444444,1.0,重点確認,不良数top3のための優先確認
5,MELMB,コイル,12,39000,0.000308,307.692308,2.0,重点確認,不良数top3のための優先確認
7,WSE,コイル,9,22000,0.000409,409.090909,3.0,重点確認,不良数top3のための優先確認

In [19]:
df_count_summary = pd.DataFrame(
    [
        ["集計後の組み合わせ数", len(df_summary)],
        ["重点確認件数", len(df_priority)],
        ["通常確認件数", len(df_summary) - len(df_priority)]
    ],
    columns=[
        "確認項目",
        "件数"
    ],
)

df_count_summary

         確認項目  件数
0  集計後の組み合わせ数   9
1      重点確認件数   3
2      通常確認件数   6