###### 128_6_split_string_column_practice

In [1]:
import pandas as pd

In [3]:
df_ticket = pd.DataFrame(
    [
        ["T001", "J69P", "MELMB/Line1/組立", "コイル/鉄粉/ショート", "RH Lo不灯", 2],
        ["T002", "J69P", "MELMB/Line1/検査", "コイル/巻線ばらつき", "RH Hi/Lo不灯", 3],
        ["T003", "J69P", "MELMB/Line2/組立", "Buck-IC/焼損", "全灯火不点灯", 5],
        ["T004", "310D", "WSE/Line1/検査", "異物/混入", "点灯不安定", 1],
        ["T005", "310D", "WSE/Line2/組立", "はんだ/クラック", "点灯不安定", 4],
        ["T006", "J69P", "GSE/Line1/組立", "コイル/鉄粉/ショート", "RH Lo不灯", 2],
        ["T007", "310D", "GSE/Line2/検査", "NTF", "再現せず", 1],
        ["T008", "J69P", "ISE/Line1/組立", "コイル/巻線ばらつき", "RH Lo不灯", 3],
        ["T009", "310D", "ISE/Line1/検査", "異物/付着", "点灯不安定", 2],
        ["T010", "J69P", "WSE/Line2/検査", "Buck-IC/焼損", "RH Lo不灯", 4],
        ["T011", "310D", "MELMB/Line2/組立", "はんだ/濡れ不足", "点灯不安定", 3],
        ["T012", "J69P", "GSE/Line1/検査", "コイル/鉄粉/ショート", "RH Hi/Lo不灯", 5],
    ],
    columns=[
        "ticket_id",
        "project",
        "発生場所",
        "原因タグ",
        "symptom",
        "risk_score",
    ],
)
df_ticket.head()

  ticket_id project            発生場所         原因タグ     symptom  risk_score
0      T001    J69P  MELMB/Line1/組立  コイル/鉄粉/ショート     RH Lo不灯           2
1      T002    J69P  MELMB/Line1/検査   コイル/巻線ばらつき  RH Hi/Lo不灯           3
2      T003    J69P  MELMB/Line2/組立   Buck-IC/焼損      全灯火不点灯           5
3      T004    310D    WSE/Line1/検査        異物/混入       点灯不安定           1
4      T005    310D    WSE/Line2/組立     はんだ/クラック       点灯不安定           4

In [4]:
df_ticket[["拠点", "ライン", "工程"]] = df_ticket["発生場所"].str.split("/", expand=True)
df_ticket.head()

,ticket_id,project,発生場所,原因タグ,symptom,risk_score,拠点,ライン,工程
0,T001,J69P,MELMB/Line1/組立,コイル/鉄粉/ショート,RH Lo不灯,2,MELMB,Line1,組立
1,T002,J69P,MELMB/Line1/検査,コイル/巻線ばらつき,RH Hi/Lo不灯,3,MELMB,Line1,検査
2,T003,J69P,MELMB/Line2/組立,Buck-IC/焼損,全灯火不点灯,5,MELMB,Line2,組立
3,T004,310D,WSE/Line1/検査,異物/混入,点灯不安定,1,WSE,Line1,検査
4,T005,310D,WSE/Line2/組立,はんだ/クラック,点灯不安定,4,WSE,Line2,組立

In [5]:
df_ticket[["原因1", "原因2", "原因3"]] = df_ticket["原因タグ"].str.split("/", expand=True)
df_ticket.head()

,ticket_id,project,発生場所,原因タグ,symptom,risk_score,拠点,ライン,工程,原因1,原因2,原因3
0,T001,J69P,MELMB/Line1/組立,コイル/鉄粉/ショート,RH Lo不灯,2,MELMB,Line1,組立,コイル,鉄粉,ショート
1,T002,J69P,MELMB/Line1/検査,コイル/巻線ばらつき,RH Hi/Lo不灯,3,MELMB,Line1,検査,コイル,巻線ばらつき,None
2,T003,J69P,MELMB/Line2/組立,Buck-IC/焼損,全灯火不点灯,5,MELMB,Line2,組立,Buck-IC,焼損,None
3,T004,310D,WSE/Line1/検査,異物/混入,点灯不安定,1,WSE,Line1,検査,異物,混入,None
4,T005,310D,WSE/Line2/組立,はんだ/クラック,点灯不安定,4,WSE,Line2,組立,はんだ,クラック,None

In [6]:
df_ticket[["原因1", "原因2", "原因3"]]  = df_ticket[["原因1", "原因2", "原因3"]].fillna("")
df_ticket

,ticket_id,project,発生場所,原因タグ,symptom,risk_score,拠点,ライン,工程,原因1,原因2,原因3
0,T001,J69P,MELMB/Line1/組立,コイル/鉄粉/ショート,RH Lo不灯,2,MELMB,Line1,組立,コイル,鉄粉,ショート
1,T002,J69P,MELMB/Line1/検査,コイル/巻線ばらつき,RH Hi/Lo不灯,3,MELMB,Line1,検査,コイル,巻線ばらつき,
2,T003,J69P,MELMB/Line2/組立,Buck-IC/焼損,全灯火不点灯,5,MELMB,Line2,組立,Buck-IC,焼損,
3,T004,310D,WSE/Line1/検査,異物/混入,点灯不安定,1,WSE,Line1,検査,異物,混入,
4,T005,310D,WSE/Line2/組立,はんだ/クラック,点灯不安定,4,WSE,Line2,組立,はんだ,クラック,
5,T006,J69P,GSE/Line1/組立,コイル/鉄粉/ショート,RH Lo不灯,2,GSE,Line1,組立,コイル,鉄粉,ショート
6,T007,310D,GSE/Line2/検査,NTF,再現せず,1,GSE,Line2,検査,NTF,,
7,T008,J69P,ISE/Line1/組立,コイル/巻線ばらつき,RH Lo不灯,3,ISE,Line1,組立,コイル,巻線ばらつき,
8,T009,310D,ISE/Line1/検査,異物/付着,点灯不安定,2,ISE,Line1,検査,異物,付着,
9,T010,J69P,WSE/Line2/検査,Buck-IC/焼損,RH Lo不灯,4,WSE,Line2,検査,Buck-IC,焼損,
10,T011,310D,MELMB/Line2/組立,はんだ/濡れ不足,点灯不安定,3,MELMB,Line2,組立,はんだ,濡れ不足,
11,T012,J69P,GSE/Line1/検査,コイル/鉄粉/ショート,RH Hi/Lo不灯,5,GSE,Line1,検査,コイル,鉄粉,ショート

In [7]:
df_ticket.drop(["発生場所", "原因タグ"], axis=1, inplace=True)
df_ticket

,ticket_id,project,symptom,risk_score,拠点,ライン,工程,原因1,原因2,原因3
0,T001,J69P,RH Lo不灯,2,MELMB,Line1,組立,コイル,鉄粉,ショート
1,T002,J69P,RH Hi/Lo不灯,3,MELMB,Line1,検査,コイル,巻線ばらつき,
2,T003,J69P,全灯火不点灯,5,MELMB,Line2,組立,Buck-IC,焼損,
3,T004,310D,点灯不安定,1,WSE,Line1,検査,異物,混入,
4,T005,310D,点灯不安定,4,WSE,Line2,組立,はんだ,クラック,
5,T006,J69P,RH Lo不灯,2,GSE,Line1,組立,コイル,鉄粉,ショート
6,T007,310D,再現せず,1,GSE,Line2,検査,NTF,,
7,T008,J69P,RH Lo不灯,3,ISE,Line1,組立,コイル,巻線ばらつき,
8,T009,310D,点灯不安定,2,ISE,Line1,検査,異物,付着,
9,T010,J69P,RH Lo不灯,4,WSE,Line2,検査,Buck-IC,焼損,
10,T011,310D,点灯不安定,3,MELMB,Line2,組立,はんだ,濡れ不足,
11,T012,J69P,RH Hi/Lo不灯,5,GSE,Line1,検査,コイル,鉄粉,ショート

In [9]:
df_report = df_ticket[
    [
        "ticket_id",
        "project",
        "拠点",
        "ライン",
        "原因1",
        "原因2",
        "原因3",
        "symptom",
        "risk_score"
    ]
].copy()

In [11]:
df_report.head()

,ticket_id,project,拠点,ライン,原因1,原因2,原因3,symptom,risk_score
0,T001,J69P,MELMB,Line1,コイル,鉄粉,ショート,RH Lo不灯,2
1,T002,J69P,MELMB,Line1,コイル,巻線ばらつき,,RH Hi/Lo不灯,3
2,T003,J69P,MELMB,Line2,Buck-IC,焼損,,全灯火不点灯,5
3,T004,310D,WSE,Line1,異物,混入,,点灯不安定,1
4,T005,310D,WSE,Line2,はんだ,クラック,,点灯不安定,4

In [13]:
df_report_sort = df_report.sort_values(
    "risk_score",
    ascending=False,
)
df_report_sort.head()

,ticket_id,project,拠点,ライン,原因1,原因2,原因3,symptom,risk_score
2,T003,J69P,MELMB,Line2,Buck-IC,焼損,,全灯火不点灯,5
11,T012,J69P,GSE,Line1,コイル,鉄粉,ショート,RH Hi/Lo不灯,5
4,T005,310D,WSE,Line2,はんだ,クラック,,点灯不安定,4
9,T010,J69P,WSE,Line2,Buck-IC,焼損,,RH Lo不灯,4
10,T011,310D,MELMB,Line2,はんだ,濡れ不足,,点灯不安定,3

In [14]:
df_j69p = df_report_sort[
    df_report_sort["project"] == "J69P"
]
df_j69p

,ticket_id,project,拠点,ライン,原因1,原因2,原因3,symptom,risk_score
2,T003,J69P,MELMB,Line2,Buck-IC,焼損,,全灯火不点灯,5
11,T012,J69P,GSE,Line1,コイル,鉄粉,ショート,RH Hi/Lo不灯,5
9,T010,J69P,WSE,Line2,Buck-IC,焼損,,RH Lo不灯,4
7,T008,J69P,ISE,Line1,コイル,巻線ばらつき,,RH Lo不灯,3
1,T002,J69P,MELMB,Line1,コイル,巻線ばらつき,,RH Hi/Lo不灯,3
0,T001,J69P,MELMB,Line1,コイル,鉄粉,ショート,RH Lo不灯,2
5,T006,J69P,GSE,Line1,コイル,鉄粉,ショート,RH Lo不灯,2

In [18]:
df_cause_count = df_report["原因1"].value_counts()
print("----- 原因1 -----")
print(df_cause_count)

df_cause_count1 = df_report["原因2"].value_counts()
print("----- 原因2 -----")
print(df_cause_count1)

----- 原因1 -----
原因1
コイル        5
Buck-IC    2
異物         2
はんだ        2
NTF        1
Name: count, dtype: int64
----- 原因2 -----
原因2
鉄粉        3
巻線ばらつき    2
焼損        2
混入        1
クラック      1
          1
付着        1
濡れ不足      1
Name: count, dtype: int64