In [12]:
import pandas as pd
df = pd.read_csv("dataset/reading.txt", sep=" ", encoding="utf-8-sig")
df.head()

           日付   クラス  出席番号            タイトル  ページ数
0  2021-10-01  3年A組     1  ハバタンとフカタンの迷路の旅    49
1  2021-10-01    4B    24      キューちゃん海へゆく    67
2  2021-10-01  4年A組    20     キューちゃん、海へ行く     3
3  2021-10-01    4A    11     キューちゃん、海へ行く    40
4  2021-10-01    4B    23  ハバタンとフカタンの迷路の旅    41

In [13]:
for char in ["-", "年", "組"]:
    df["クラス"] = df["クラス"].str.replace(char, "", regex=False)

df.head()

           日付 クラス  出席番号            タイトル  ページ数
0  2021-10-01  3A     1  ハバタンとフカタンの迷路の旅    49
1  2021-10-01  4B    24      キューちゃん海へゆく    67
2  2021-10-01  4A    20     キューちゃん、海へ行く     3
3  2021-10-01  4A    11     キューちゃん、海へ行く    40
4  2021-10-01  4B    23  ハバタンとフカタンの迷路の旅    41

In [14]:
valid_title = "キューちゃん海へゆく"
df.loc[df["タイトル"].str.contains("キューちゃん"), "タイトル"] = valid_title
df["タイトル"].unique()

<StringArray>
['ハバタンとフカタンの迷路の旅', 'キューちゃん海へゆく', 'へびとアルゴリズム']
Length: 3, dtype: str

In [15]:
df["学年"] = df["クラス"].str[0] + "年"
df["組"] = df["クラス"].str[1] + "組"
df.head()

           日付 クラス  出席番号            タイトル  ページ数  学年   組
0  2021-10-01  3A     1  ハバタンとフカタンの迷路の旅    49  3年  A組
1  2021-10-01  4B    24      キューちゃん海へゆく    67  4年  B組
2  2021-10-01  4A    20      キューちゃん海へゆく     3  4年  A組
3  2021-10-01  4A    11      キューちゃん海へゆく    40  4年  A組
4  2021-10-01  4B    23  ハバタンとフカタンの迷路の旅    41  4年  B組

In [16]:
df.to_csv("dataset/reading_after.txt", sep=" ", index=False, encoding="utf-8-sig")

In [18]:
user_grouped = df.groupby(["学年", "組", "出席番号"])

user_df = user_grouped.agg({
    "タイトル": "nunique",
    "ページ数": "sum"
}).reset_index()

user_df.head()

   学年   組  出席番号  タイトル  ページ数
0  3年  A組     1     1    49
1  3年  A組     5     1    28
2  3年  B組    12     1    15
3  3年  C組     9     1    18
4  4年  A組     7     1    22

In [19]:
class_df = user_df.groupby(["学年", "組"]).agg({
    "タイトル": "sum",
    "ページ数": "mean",
    "出席番号": "nunique"
})

class_df = class_df.rename(columns={
    "タイトル": "読んだ本の数",
    "ページ数": "平均ページ数",
    "出席番号": "参加人数",
})
class_df

       読んだ本の数     平均ページ数  参加人数
学年 組
3年 A組       2  38.500000     2
   B組       1  15.000000     1
   C組       1  18.000000     1
4年 A組       3  21.666667     3
   B組       3  46.333333     3

In [20]:
rank_df = class_df.rank(ascending=False)

In [21]:
rank_df = rank_df.add_suffix("_全体順位")

In [22]:
class_df[rank_df.columns] = rank_df

In [23]:
class_df

       読んだ本の数     平均ページ数  参加人数  読んだ本の数_全体順位  平均ページ数_全体順位  参加人数_全体順位
学年 組
3年 A組       2  38.500000     2          3.0          2.0        3.0
   B組       1  15.000000     1          4.5          5.0        4.5
   C組       1  18.000000     1          4.5          4.0        4.5
4年 A組       3  21.666667     3          1.5          3.0        1.5
   B組       3  46.333333     3          1.5          1.0        1.5

In [24]:
class_df.to_csv("dataset/class_df.txt", sep=" ", encoding="utf-8-sig")

In [25]:
class_df = class_df.reset_index()

In [26]:
grouped = class_df.groupby("学年")
rank_df = grouped[["読んだ本の数", "平均ページ数", "参加人数"]].rank(ascending=False)
rank_df = rank_df.add_suffix("_学年順位")
class_df[rank_df.columns] = rank_df
class_df

,学年,組,読んだ本の数,平均ページ数,参加人数,読んだ本の数_全体順位,平均ページ数_全体順位,参加人数_全体順位,読んだ本の数_学年順位,平均ページ数_学年順位,参加人数_学年順位
0,3年,A組,2,38.500000,2,3.0,2.0,3.0,1.0,1.0,1.0
1,3年,B組,1,15.000000,1,4.5,5.0,4.5,2.5,3.0,2.5
2,3年,C組,1,18.000000,1,4.5,4.0,4.5,2.5,2.0,2.5
3,4年,A組,3,21.666667,3,1.5,3.0,1.5,1.5,2.0,1.5
4,4年,B組,3,46.333333,3,1.5,1.0,1.5,1.5,1.0,1.5

In [27]:
class_df.to_csv("dataset/reading_ranking.txt", sep=" ", index=False, encoding="utf-8-sig")

In [29]:
display(df.head())

           日付 クラス  出席番号            タイトル  ページ数  学年   組
0  2021-10-01  3A     1  ハバタンとフカタンの迷路の旅    49  3年  A組
1  2021-10-01  4B    24      キューちゃん海へゆく    67  4年  B組
2  2021-10-01  4A    20      キューちゃん海へゆく     3  4年  A組
3  2021-10-01  4A    11      キューちゃん海へゆく    40  4年  A組
4  2021-10-01  4B    23  ハバタンとフカタンの迷路の旅    41  4年  B組

In [30]:
display(user_df.head())

   学年   組  出席番号  タイトル  ページ数
0  3年  A組     1     1    49
1  3年  A組     5     1    28
2  3年  B組    12     1    15
3  3年  C組     9     1    18
4  4年  A組     7     1    22

In [31]:
display(class_df)

,学年,組,読んだ本の数,平均ページ数,参加人数,読んだ本の数_全体順位,平均ページ数_全体順位,参加人数_全体順位,読んだ本の数_学年順位,平均ページ数_学年順位,参加人数_学年順位
0,3年,A組,2,38.500000,2,3.0,2.0,3.0,1.0,1.0,1.0
1,3年,B組,1,15.000000,1,4.5,5.0,4.5,2.5,3.0,2.5
2,3年,C組,1,18.000000,1,4.5,4.0,4.5,2.5,2.0,2.5
3,4年,A組,3,21.666667,3,1.5,3.0,1.5,1.5,2.0,1.5
4,4年,B組,3,46.333333,3,1.5,1.0,1.5,1.5,1.0,1.5