In [30]:
import pandas as pd

df = pd.read_csv("dataset/reading_after.txt", sep=" ", encoding="utf-8-sig")
df.head()

           日付 クラス  出席番号            タイトル  ページ数  学年   組
0  2021-10-01  3A     1  ハバタンとフカタンの迷路の旅    49  3年  A組
1  2021-10-01  4B    24      キューちゃん海へゆく    67  4年  B組
2  2021-10-01  4A    20      キューちゃん海へゆく     3  4年  A組
3  2021-10-01  4A    11      キューちゃん海へゆく    40  4年  A組
4  2021-10-01  4B    23  ハバタンとフカタンの迷路の旅    41  4年  B組

In [31]:
df.columns

Index(['日付', 'クラス', '出席番号', 'タイトル', 'ページ数', '学年', '組'], dtype='str')

In [32]:
user_grouped = df.groupby(["学年", "組", "出席番号"])
user_grouped

In [33]:
user_df = user_grouped.agg({

    "タイトル": "nunique",
    "ページ数": "sum"
})
user_df

            タイトル  ページ数
学年 組  出席番号
3年 A組 1        1    49
      5        1    28
   B組 12       1    15
   C組 9        1    18
4年 A組 7        1    22
      11       1    40
      20       1     3
   B組 14       1    31
      23       1    41
      24       1    67

In [34]:
user_df = user_df.reset_index()
user_df

   学年   組  出席番号  タイトル  ページ数
0  3年  A組     1     1    49
1  3年  A組     5     1    28
2  3年  B組    12     1    15
3  3年  C組     9     1    18
4  4年  A組     7     1    22
5  4年  A組    11     1    40
6  4年  A組    20     1     3
7  4年  B組    14     1    31
8  4年  B組    23     1    41
9  4年  B組    24     1    67

In [35]:
grouped = user_df.groupby(["学年", "組"])
grouped

In [36]:
class_df = grouped.agg({
    "タイトル":"sum",
    "ページ数":"mean",
    "出席番号":"nunique"
})
class_df

       タイトル       ページ数  出席番号
学年 組
3年 A組     2  38.500000     2
   B組     1  15.000000     1
   C組     1  18.000000     1
4年 A組     3  21.666667     3
   B組     3  46.333333     3

In [37]:
class_df = class_df.rename(columns={
    "タイトル": "読んだ本の数",
    "ページ数": "平均ページ数",
    "出席番号": "参加人数",
})
class_df

       読んだ本の数     平均ページ数  参加人数
学年 組
3年 A組       2  38.500000     2
   B組       1  15.000000     1
   C組       1  18.000000     1
4年 A組       3  21.666667     3
   B組       3  46.333333     3

In [38]:
rank_df = class_df.rank(ascending=False)
rank_df

       読んだ本の数  平均ページ数  参加人数
学年 組
3年 A組     3.0     2.0   3.0
   B組     4.5     5.0   4.5
   C組     4.5     4.0   4.5
4年 A組     1.5     3.0   1.5
   B組     1.5     1.0   1.5

In [39]:
rank_df = rank_df.add_suffix("_全体順位")
rank_df

       読んだ本の数_全体順位  平均ページ数_全体順位  参加人数_全体順位
学年 組
3年 A組          3.0          2.0        3.0
   B組          4.5          5.0        4.5
   C組          4.5          4.0        4.5
4年 A組          1.5          3.0        1.5
   B組          1.5          1.0        1.5

In [40]:
class_df[rank_df.columns] = rank_df
class_df

       読んだ本の数     平均ページ数  参加人数  読んだ本の数_全体順位  平均ページ数_全体順位  参加人数_全体順位
学年 組
3年 A組       2  38.500000     2          3.0          2.0        3.0
   B組       1  15.000000     1          4.5          5.0        4.5
   C組       1  18.000000     1          4.5          4.0        4.5
4年 A組       3  21.666667     3          1.5          3.0        1.5
   B組       3  46.333333     3          1.5          1.0        1.5

In [41]:
display(user_df.head())

   学年   組  出席番号  タイトル  ページ数
0  3年  A組     1     1    49
1  3年  A組     5     1    28
2  3年  B組    12     1    15
3  3年  C組     9     1    18
4  4年  A組     7     1    22

In [42]:
display(class_df)

       読んだ本の数     平均ページ数  参加人数  読んだ本の数_全体順位  平均ページ数_全体順位  参加人数_全体順位
学年 組
3年 A組       2  38.500000     2          3.0          2.0        3.0
   B組       1  15.000000     1          4.5          5.0        4.5
   C組       1  18.000000     1          4.5          4.0        4.5
4年 A組       3  21.666667     3          1.5          3.0        1.5
   B組       3  46.333333     3          1.5          1.0        1.5

In [43]:
user_grouped = df.groupby(["学年", "組", "出席番号"])

In [45]:
user_df = user_grouped.agg({
    "タイトル": "nunique",
    "ページ数": "sum"
})

In [46]:
grouped = user_df.groupby(["学年", "組"])

In [47]:
rank_df = class_df.rank(ascending=False)

In [48]:
rank_df = rank_df.add_suffix("_全体順位")

In [50]:
user_grouped = df.groupby(["学年","組", "出席番号"])

user_df = user_grouped.agg({
    "タイトル": "nunique",
    "ページ数": "sum"
})

user_df = user_df.reset_index()
user_df.head()

   学年   組  出席番号  タイトル  ページ数
0  3年  A組     1     1    49
1  3年  A組     5     1    28
2  3年  B組    12     1    15
3  3年  C組     9     1    18
4  4年  A組     7     1    22

In [51]:
grouped = user_df.groupby(["学年", "組"])

class_df = grouped.agg({
    "タイトル": "sum",
    "ページ数": "mean",
    "出席番号": "nunique"
})

class_df = class_df.rename(
    columns={
        "タイトル": "読書数",
        "ページ数": "平均ページ数",
        "出席番号": "生徒数"
    }
)
class_df.head()

       読書数     平均ページ数  生徒数
学年 組
3年 A組    2  38.500000    2
   B組    1  15.000000    1
   C組    1  18.000000    1
4年 A組    3  21.666667    3
   B組    3  46.333333    3

In [53]:
class_df.sort_values("平均ページ数", ascending=False)

       読書数     平均ページ数  生徒数
学年 組
4年 B組    3  46.333333    3
3年 A組    2  38.500000    2
4年 A組    3  21.666667    3
3年 C組    1  18.000000    1
   B組    1  15.000000    1

In [56]:
class_df[class_df["生徒数"] >= 2]

       読書数     平均ページ数  生徒数
学年 組
3年 A組    2  38.500000    2
4年 A組    3  21.666667    3
   B組    3  46.333333    3