In [ ]:
import pandas as pd

df = pd.read_csv("dataset/reading.txt", sep=" ", encoding="shift_jis")
df.head()

           日付   クラス  出席番号            タイトル  ページ数
0  2021-10-01  3年A組     1  ハバタンとフカタンの迷路の旅    49
1  2021-10-01    4B    24      キューちゃん海へゆく    67
2  2021-10-01  4年A組    20     キューちゃん、海へ行く     3
3  2021-10-01    4A    11     キューちゃん、海へ行く    40
4  2021-10-01    4B    23  ハバタンとフカタンの迷路の旅    41

In [3]:
df_shape = df.shape
df_shape

(10, 5)

In [4]:
df.isna().sum()

日付      0
クラス     0
出席番号    0
タイトル    0
ページ数    0
dtype: int64

In [5]:
na_count = df.isna().sum()
na_count

日付      0
クラス     0
出席番号    0
タイトル    0
ページ数    0
dtype: int64

In [6]:
df_desc = df.describe()

In [7]:
df_desc

            出席番号       ページ数
count  10.000000  10.000000
mean   12.600000  31.400000
std     7.705698  18.554424
min     1.000000   3.000000
25%     7.500000  19.000000
50%    11.500000  29.500000
75%    18.500000  40.750000
max    24.000000  67.000000

In [8]:
valid_classes = ["3A", "3B", "3C", "4A", "4B", "4C"]
valid_classes

['3A', '3B', '3C', '4A', '4B', '4C']

In [13]:
invalid_classes_df = df[~df["クラス"].isin(valid_classes)]
invalid_classes_df

           日付   クラス  出席番号            タイトル  ページ数
0  2021-10-01  3年A組     1  ハバタンとフカタンの迷路の旅    49
2  2021-10-01  4年A組    20     キューちゃん、海へ行く     3
5  2021-10-02   3-A     5       へびとアルゴリズム    28
7  2021-10-02   4-A     7      キューちゃん海へ行く    22
8  2021-10-03  3年C組     9     キューちゃんうみへいく    18
9  2021-10-03   4-B    14     キューちゃん海へゆく！    31

In [14]:
invalid_classes = invalid_classes["クラス"].unique()
invalid_classes

array(['3年A組', '4年A組', '3-A', '4-A', '3年C組', '4-B'], dtype=object)

In [ ]:
valid_titles =[
    "キューちゃん海へゆく",
    "ハバタンとフカタンの迷路の旅",
    "へびとアルゴリズム"
]
valid_titles

['キューちゃん海へゆく', 'ハバタンとフカタンの迷路の旅', 'へびとアルゴリズム']

In [16]:
invalid_title_df = df[~df["タイトル"].isin(valid_titles)]
invalid_title_df

           日付   クラス  出席番号         タイトル  ページ数
2  2021-10-01  4年A組    20  キューちゃん、海へ行く     3
3  2021-10-01    4A    11  キューちゃん、海へ行く    40
6  2021-10-02    3B    12   キューちゃん海へいく    15
7  2021-10-02   4-A     7   キューちゃん海へ行く    22
8  2021-10-03  3年C組     9  キューちゃんうみへいく    18
9  2021-10-03   4-B    14  キューちゃん海へゆく！    31

In [17]:
invalid_titles = invalid_title_df["タイトル"].unique()
invalid_titles

array(['キューちゃん、海へ行く', 'キューちゃん海へいく', 'キューちゃん海へ行く', 'キューちゃんうみへいく',
       'キューちゃん海へゆく！'], dtype=object)

In [25]:
display(df.head())
display(df.shape)
display(na_count)
display(df_desc)
display(invalid_classes)
display(invalid_titles)

           日付   クラス  出席番号            タイトル  ページ数
0  2021-10-01  3年A組     1  ハバタンとフカタンの迷路の旅    49
1  2021-10-01    4B    24      キューちゃん海へゆく    67
2  2021-10-01  4年A組    20     キューちゃん、海へ行く     3
3  2021-10-01    4A    11     キューちゃん、海へ行く    40
4  2021-10-01    4B    23  ハバタンとフカタンの迷路の旅    41

(10, 5)

日付      0
クラス     0
出席番号    0
タイトル    0
ページ数    0
dtype: int64

            出席番号       ページ数
count  10.000000  10.000000
mean   12.600000  31.400000
std     7.705698  18.554424
min     1.000000   3.000000
25%     7.500000  19.000000
50%    11.500000  29.500000
75%    18.500000  40.750000
max    24.000000  67.000000

array(['3年A組', '4年A組', '3-A', '4-A', '3年C組', '4-B'], dtype=object)

array(['キューちゃん、海へ行く', 'キューちゃん海へいく', 'キューちゃん海へ行く', 'キューちゃんうみへいく',
       'キューちゃん海へゆく！'], dtype=object)

In [26]:
df["クラス"].value_counts()

クラス
4B      2
3年A組    1
4年A組    1
4A      1
3-A     1
3B      1
4-A     1
3年C組    1
4-B     1
Name: count, dtype: int64

In [27]:
df["タイトル"].value_counts()

タイトル
ハバタンとフカタンの迷路の旅    2
キューちゃん、海へ行く       2
キューちゃん海へゆく        1
へびとアルゴリズム         1
キューちゃん海へいく        1
キューちゃん海へ行く        1
キューちゃんうみへいく       1
キューちゃん海へゆく！       1
Name: count, dtype: int64

In [29]:
df["ページ数"].min(), df["ページ数"].max()

(np.int64(3), np.int64(67))

In [34]:
df.loc[~df["クラス"].isin(valid_classes), ["日付", "クラス"]]

           日付   クラス
0  2021-10-01  3年A組
2  2021-10-01  4年A組
5  2021-10-02   3-A
7  2021-10-02   4-A
8  2021-10-03  3年C組
9  2021-10-03   4-B