In [18]:
import pandas as pd
df = pd.read_csv("dataset/reading.txt", sep=" ", encoding="shift_jis")
df.head()

           日付   クラス  出席番号            タイトル  ページ数
0  2021-10-01  3年A組     1  ハバタンとフカタンの迷路の旅    49
1  2021-10-01    4B    24      キューちゃん海へゆく    67
2  2021-10-01  4年A組    20     キューちゃん、海へ行く     3
3  2021-10-01    4A    11     キューちゃん、海へ行く    40
4  2021-10-01    4B    23  ハバタンとフカタンの迷路の旅    41

In [19]:
valid_title = "キューちゃん海へゆく"
valid_title

'キューちゃん海へゆく'

In [20]:
for char in ["-", "年", "組"]:
    df["クラス"] = df["クラス"].str.replace(char, "", regex=False)
df.head()

           日付 クラス  出席番号            タイトル  ページ数
0  2021-10-01  3A     1  ハバタンとフカタンの迷路の旅    49
1  2021-10-01  4B    24      キューちゃん海へゆく    67
2  2021-10-01  4A    20     キューちゃん、海へ行く     3
3  2021-10-01  4A    11     キューちゃん、海へ行く    40
4  2021-10-01  4B    23  ハバタンとフカタンの迷路の旅    41

In [21]:
df["クラス"].unique()

array(['3A', '4B', '4A', '3B', '3C'], dtype=object)

In [22]:
df.loc[df["タイトル"].str.contains("キューちゃん"), "タイトル"] = valid_title
df["タイトル"].unique()

array(['ハバタンとフカタンの迷路の旅', 'キューちゃん海へゆく', 'へびとアルゴリズム'], dtype=object)

In [23]:
df["学年"] = df["クラス"].str[0] + "年"
df.head()

           日付 クラス  出席番号            タイトル  ページ数  学年
0  2021-10-01  3A     1  ハバタンとフカタンの迷路の旅    49  3年
1  2021-10-01  4B    24      キューちゃん海へゆく    67  4年
2  2021-10-01  4A    20      キューちゃん海へゆく     3  4年
3  2021-10-01  4A    11      キューちゃん海へゆく    40  4年
4  2021-10-01  4B    23  ハバタンとフカタンの迷路の旅    41  4年

In [24]:
df["組"] = df["クラス"].str[1] + "組"
df.head()

           日付 クラス  出席番号            タイトル  ページ数  学年   組
0  2021-10-01  3A     1  ハバタンとフカタンの迷路の旅    49  3年  A組
1  2021-10-01  4B    24      キューちゃん海へゆく    67  4年  B組
2  2021-10-01  4A    20      キューちゃん海へゆく     3  4年  A組
3  2021-10-01  4A    11      キューちゃん海へゆく    40  4年  A組
4  2021-10-01  4B    23  ハバタンとフカタンの迷路の旅    41  4年  B組

In [25]:
display(df.head())

           日付 クラス  出席番号            タイトル  ページ数  学年   組
0  2021-10-01  3A     1  ハバタンとフカタンの迷路の旅    49  3年  A組
1  2021-10-01  4B    24      キューちゃん海へゆく    67  4年  B組
2  2021-10-01  4A    20      キューちゃん海へゆく     3  4年  A組
3  2021-10-01  4A    11      キューちゃん海へゆく    40  4年  A組
4  2021-10-01  4B    23  ハバタンとフカタンの迷路の旅    41  4年  B組

In [26]:
display(df["クラス"].unique())

array(['3A', '4B', '4A', '3B', '3C'], dtype=object)

In [27]:
display(df["タイトル"].unique())

array(['ハバタンとフカタンの迷路の旅', 'キューちゃん海へゆく', 'へびとアルゴリズム'], dtype=object)

In [32]:
df["クラス"] = df["クラス"].str.strip()
df["クラス"] = df["クラス"].str.upper()

for char in ["-", "年", "組"]:
    df["クラス"] = df["クラス"].str.replace(char, "", regex=False)
    
valid_classes = ["3A", "3B", "3C", "4A", "4B", "4C"]
df.loc[~df["クラス"].isin(valid_classes), "クラス"].unique()

array([], dtype=object)