###### 133_1_practical_lcm_due_style_answer.ipynb

In [64]:
import pandas as pd

In [65]:
df = pd.read_csv(
    "dataset/lcm_due_style_practice.csv",
)
df

,no,site,model,defect_category,defect_count,due_date,status,priority,comment
0,1,GSE,LCM-A,点灯不良,2,2026-08-01,対応中,中,通常確認
1,2,WSE,LCM-B,外観不良,6,2026-08-03,未対応,高,期限注意
2,3,META,LCM-A,寸法不良,1,2026-08-10,完了,低,問題なし
3,4,MELAC,LCM-C,異音,8,2026-07-30,未対応,高,期限超過
4,5,GSE,LCM-B,点灯不良,0,2026-08-15,完了,低,再発なし
5,6,WSE,LCM-C,外観不良,3,2026/08/05,対応中,中,日付表記ゆれ
6,7,META,LCM-B,寸法不良,未入力,2026-08-08,未対応,高,件数未入力
7,8,MELAC,LCM-A,異音,5,未入力,対応中,中,期限未入力
8,9,GSE,LCM-C,点灯不良,7,NG_DATE,完了,高,日付NG
9,10,WSE,LCM-A,外観不良,2,2026-08-02,不明,中,ステータス不明

In [66]:
df["defect_count_num"] = pd.to_numeric(
    df["defect_count"],
    errors="coerce",
)
df

,no,site,model,defect_category,defect_count,due_date,status,priority,comment,defect_count_num
0,1,GSE,LCM-A,点灯不良,2,2026-08-01,対応中,中,通常確認,2.0
1,2,WSE,LCM-B,外観不良,6,2026-08-03,未対応,高,期限注意,6.0
2,3,META,LCM-A,寸法不良,1,2026-08-10,完了,低,問題なし,1.0
3,4,MELAC,LCM-C,異音,8,2026-07-30,未対応,高,期限超過,8.0
4,5,GSE,LCM-B,点灯不良,0,2026-08-15,完了,低,再発なし,0.0
5,6,WSE,LCM-C,外観不良,3,2026/08/05,対応中,中,日付表記ゆれ,3.0
6,7,META,LCM-B,寸法不良,未入力,2026-08-08,未対応,高,件数未入力,NaN
7,8,MELAC,LCM-A,異音,5,未入力,対応中,中,期限未入力,5.0
8,9,GSE,LCM-C,点灯不良,7,NG_DATE,完了,高,日付NG,7.0
9,10,WSE,LCM-A,外観不良,2,2026-08-02,不明,中,ステータス不明,2.0

In [67]:
df["due_date_raw"] = df["due_date"]
df.dtypes

no                    int64
site                 object
model                object
defect_category      object
defect_count         object
due_date             object
status               object
priority             object
comment              object
defect_count_num    float64
due_date_raw         object
dtype: object

In [68]:
df["due_date_clean"] = (
    df["due_date"]
    .astype(str)
    .str.strip()
    .str.replace("/","-", regex=False)
)

df["due_date_dt"] = pd.to_datetime(
    df["due_date_clean"],
    errors="coerce",
)
df.dtypes

no                           int64
site                        object
model                       object
defect_category             object
defect_count                object
due_date                    object
status                      object
priority                    object
comment                     object
defect_count_num           float64
due_date_raw                object
due_date_clean              object
due_date_dt         datetime64[ns]
dtype: object

In [69]:
base_date = pd.Timestamp("2026-08-05")

In [70]:
df["defect_count_num"]

0    2.0
1    6.0
2    1.0
3    8.0
4    0.0
5    3.0
6    NaN
7    5.0
8    7.0
9    2.0
Name: defect_count_num, dtype: float64

In [71]:
df_defect_count_ng = df[
    df["defect_count_num"].isna()
].copy()
display(df_defect_count_ng)

,no,site,model,defect_category,defect_count,due_date,status,priority,comment,defect_count_num,due_date_raw,due_date_clean,due_date_dt
6,7,META,LCM-B,寸法不良,未入力,2026-08-08,未対応,高,件数未入力,NaN,2026-08-08,2026-08-08,2026-08-08

In [72]:
df["due_date_dt"]

0   2026-08-01
1   2026-08-03
2   2026-08-10
3   2026-07-30
4   2026-08-15
5   2026-08-05
6   2026-08-08
7          NaT
8          NaT
9   2026-08-02
Name: due_date_dt, dtype: datetime64[ns]

In [73]:
df_due_date_ng = df[
    df["due_date_dt"].isna()
].copy()
display(df_due_date_ng)

,no,site,model,defect_category,defect_count,due_date,status,priority,comment,defect_count_num,due_date_raw,due_date_clean,due_date_dt
7,8,MELAC,LCM-A,異音,5,未入力,対応中,中,期限未入力,5.0,未入力,未入力,NaT
8,9,GSE,LCM-C,点灯不良,7,NG_DATE,完了,高,日付NG,7.0,NG_DATE,NG_DATE,NaT

In [74]:
df_work = df[
    df["defect_count_num"].notna()
    & df["due_date_dt"].notna()
].copy()
df_work

,no,site,model,defect_category,defect_count,due_date,status,priority,comment,defect_count_num,due_date_raw,due_date_clean,due_date_dt
0,1,GSE,LCM-A,点灯不良,2,2026-08-01,対応中,中,通常確認,2.0,2026-08-01,2026-08-01,2026-08-01
1,2,WSE,LCM-B,外観不良,6,2026-08-03,未対応,高,期限注意,6.0,2026-08-03,2026-08-03,2026-08-03
2,3,META,LCM-A,寸法不良,1,2026-08-10,完了,低,問題なし,1.0,2026-08-10,2026-08-10,2026-08-10
3,4,MELAC,LCM-C,異音,8,2026-07-30,未対応,高,期限超過,8.0,2026-07-30,2026-07-30,2026-07-30
4,5,GSE,LCM-B,点灯不良,0,2026-08-15,完了,低,再発なし,0.0,2026-08-15,2026-08-15,2026-08-15
5,6,WSE,LCM-C,外観不良,3,2026/08/05,対応中,中,日付表記ゆれ,3.0,2026/08/05,2026-08-05,2026-08-05
9,10,WSE,LCM-A,外観不良,2,2026-08-02,不明,中,ステータス不明,2.0,2026-08-02,2026-08-02,2026-08-02

In [75]:
display_cols = [
    "no",
    "site",
    "model",
    "defect_category",
    "defect_count",
    "due_date",
    "status",
    "priority",
    "comment",
]

df_display = df[display_cols].copy()

df_display

,no,site,model,defect_category,defect_count,due_date,status,priority,comment
0,1,GSE,LCM-A,点灯不良,2,2026-08-01,対応中,中,通常確認
1,2,WSE,LCM-B,外観不良,6,2026-08-03,未対応,高,期限注意
2,3,META,LCM-A,寸法不良,1,2026-08-10,完了,低,問題なし
3,4,MELAC,LCM-C,異音,8,2026-07-30,未対応,高,期限超過
4,5,GSE,LCM-B,点灯不良,0,2026-08-15,完了,低,再発なし
5,6,WSE,LCM-C,外観不良,3,2026/08/05,対応中,中,日付表記ゆれ
6,7,META,LCM-B,寸法不良,未入力,2026-08-08,未対応,高,件数未入力
7,8,MELAC,LCM-A,異音,5,未入力,対応中,中,期限未入力
8,9,GSE,LCM-C,点灯不良,7,NG_DATE,完了,高,日付NG
9,10,WSE,LCM-A,外観不良,2,2026-08-02,不明,中,ステータス不明

In [76]:
#cell 9
def style_defect_count(x):
    value = pd.to_numeric(
        x,
        errors="coerce",
    )

    if pd.isna(value):
        style = "background-color: lightgray; color: black;"
    elif value >= 5:
        style = "font-weight: bold;"
    else:
        style = None

    return style

In [77]:
#cell 10
def style_due_date(x):
    value_clean = (
        str(x)
        .strip()
        .replace("/", "-")
    )

    value = pd.to_datetime(
        value_clean,
        errors="coerce",
    )

    if pd.isna(value):
        style = "background-color: lightgray; color: black;"
    elif value < base_date:
        style = "color: red; font-weight: bold;"
    else:
        style = None

    return style

In [78]:
#cell 11
def style_status(x):
    if x == "未対応":
        style = "background-color: yellow; color: black;"
    elif x == "不明":
        style = "background-color: lightgray; color: black;"
    else:
        style = None

    return style

In [79]:
#cell 12
def style_priority(x):
    if x == "高":
        style = "font-weight: bold;"
    else:
        style = None

    return style

In [80]:
styled_df = (
    df_display.style
    .map(style_defect_count, subset=["defect_count"])
    .map(style_due_date, subset=["due_date"])
    .map(style_status, subset=["status"])
    .map(style_priority, subset=["priority"])
)

display(styled_df)