###### 129_2_fun_quality_ffill_patrol

In [1]:
#cell 1
import numpy as np
import pandas as pd

In [2]:
df = pd.DataFrame(
    [
        ["2026-06-01", "08:00", "J69P", "MELMB", "Line1", "L250601-A", "コイル", 300, 0],
        ["2026-06-01", "10:00", "", "", "", "", "コイル", 280, 1],
        ["2026-06-01", "13:00", "", "", "", "", "Buck-IC", 320, 2],
        ["2026-06-02", "08:00", "310D", "WSE", "Line2", "L250602-B", "はんだ", 250, 0],
        ["2026-06-02", "10:00", "", "", "", "", "コイル", 260, 1],
        ["2026-06-02", "13:00", "", "", "", "", "NTF", 240, 0],
        ["2026-06-03", "08:00", "J69P", "GSE", "Line1", "L250603-C", "コイル", 310, 3],
        ["2026-06-03", "10:00", "", "", "", "", "Buck-IC", 290, 0],
        ["2026-06-03", "13:00", "", "", "", "", "コイル", 300, 1],
        ["2026-06-04", "08:00", "310D", "MELMB", "Line3", "L250604-D", "はんだ", 0, 1],
        ["2026-06-04", "10:00", "", "", "", "", "コイル", 270, 2],
        ["2026-06-04", "13:00", "", "", "", "", "NTF", 260, 0],
    ],
    columns=[
        "inspection_date",
        "inspection_time",
        "project",
        "site",
        "line",
        "lot_no",
        "defect_category",
        "inspection_qty",
        "defect_qty",
    ],
)
df

,inspection_date,inspection_time,project,site,line,lot_no,defect_category,inspection_qty,defect_qty
0,2026-06-01,08:00,J69P,MELMB,Line1,L250601-A,コイル,300,0
1,2026-06-01,10:00,,,,,コイル,280,1
2,2026-06-01,13:00,,,,,Buck-IC,320,2
3,2026-06-02,08:00,310D,WSE,Line2,L250602-B,はんだ,250,0
4,2026-06-02,10:00,,,,,コイル,260,1
5,2026-06-02,13:00,,,,,NTF,240,0
6,2026-06-03,08:00,J69P,GSE,Line1,L250603-C,コイル,310,3
7,2026-06-03,10:00,,,,,Buck-IC,290,0
8,2026-06-03,13:00,,,,,コイル,300,1
9,2026-06-04,08:00,310D,MELMB,Line3,L250604-D,はんだ,0,1
10,2026-06-04,10:00,,,,,コイル,270,2
11,2026-06-04,13:00,,,,,NTF,260,0

In [4]:
#cell 3
df_work = df.copy()
df_work

,inspection_date,inspection_time,project,site,line,lot_no,defect_category,inspection_qty,defect_qty
0,2026-06-01,08:00,J69P,MELMB,Line1,L250601-A,コイル,300,0
1,2026-06-01,10:00,,,,,コイル,280,1
2,2026-06-01,13:00,,,,,Buck-IC,320,2
3,2026-06-02,08:00,310D,WSE,Line2,L250602-B,はんだ,250,0
4,2026-06-02,10:00,,,,,コイル,260,1
5,2026-06-02,13:00,,,,,NTF,240,0
6,2026-06-03,08:00,J69P,GSE,Line1,L250603-C,コイル,310,3
7,2026-06-03,10:00,,,,,Buck-IC,290,0
8,2026-06-03,13:00,,,,,コイル,300,1
9,2026-06-04,08:00,310D,MELMB,Line3,L250604-D,はんだ,0,1
10,2026-06-04,10:00,,,,,コイル,270,2
11,2026-06-04,13:00,,,,,NTF,260,0

In [5]:
df_work = df_work.replace(
    "",
    np.nan,
)
df_work

,inspection_date,inspection_time,project,site,line,lot_no,defect_category,inspection_qty,defect_qty
0,2026-06-01,08:00,J69P,MELMB,Line1,L250601-A,コイル,300,0
1,2026-06-01,10:00,NaN,NaN,NaN,NaN,コイル,280,1
2,2026-06-01,13:00,NaN,NaN,NaN,NaN,Buck-IC,320,2
3,2026-06-02,08:00,310D,WSE,Line2,L250602-B,はんだ,250,0
4,2026-06-02,10:00,NaN,NaN,NaN,NaN,コイル,260,1
5,2026-06-02,13:00,NaN,NaN,NaN,NaN,NTF,240,0
6,2026-06-03,08:00,J69P,GSE,Line1,L250603-C,コイル,310,3
7,2026-06-03,10:00,NaN,NaN,NaN,NaN,Buck-IC,290,0
8,2026-06-03,13:00,NaN,NaN,NaN,NaN,コイル,300,1
9,2026-06-04,08:00,310D,MELMB,Line3,L250604-D,はんだ,0,1
10,2026-06-04,10:00,NaN,NaN,NaN,NaN,コイル,270,2
11,2026-06-04,13:00,NaN,NaN,NaN,NaN,NTF,260,0

In [13]:
#cell 4
df_work["project_filled"] = df_work["project"].ffill()
df_work["site_filled"] = df_work["site"].ffill()
df_work["lot_no_filled"] = df_work["lot_no"].ffill()
df_work["line_filled"] = df_work["line"].ffill()

df_work

,inspection_date,inspection_time,project,site,line,lot_no,defect_category,inspection_qty,defect_qty,project_filled,site_filled,lot_no_filled,line_filled
0,2026-06-01,08:00,J69P,MELMB,Line1,L250601-A,コイル,300,0,J69P,MELMB,L250601-A,Line1
1,2026-06-01,10:00,NaN,NaN,NaN,NaN,コイル,280,1,J69P,MELMB,L250601-A,Line1
2,2026-06-01,13:00,NaN,NaN,NaN,NaN,Buck-IC,320,2,J69P,MELMB,L250601-A,Line1
3,2026-06-02,08:00,310D,WSE,Line2,L250602-B,はんだ,250,0,310D,WSE,L250602-B,Line2
4,2026-06-02,10:00,NaN,NaN,NaN,NaN,コイル,260,1,310D,WSE,L250602-B,Line2
5,2026-06-02,13:00,NaN,NaN,NaN,NaN,NTF,240,0,310D,WSE,L250602-B,Line2
6,2026-06-03,08:00,J69P,GSE,Line1,L250603-C,コイル,310,3,J69P,GSE,L250603-C,Line1
7,2026-06-03,10:00,NaN,NaN,NaN,NaN,Buck-IC,290,0,J69P,GSE,L250603-C,Line1
8,2026-06-03,13:00,NaN,NaN,NaN,NaN,コイル,300,1,J69P,GSE,L250603-C,Line1
9,2026-06-04,08:00,310D,MELMB,Line3,L250604-D,はんだ,0,1,310D,MELMB,L250604-D,Line3
10,2026-06-04,10:00,NaN,NaN,NaN,NaN,コイル,270,2,310D,MELMB,L250604-D,Line3
11,2026-06-04,13:00,NaN,NaN,NaN,NaN,NTF,260,0,310D,MELMB,L250604-D,Line3

In [14]:
#cell 5

df_clean = df_work[
    [
        "inspection_date",
        "inspection_time",
        "project_filled",
        "site_filled",
        "line_filled",
        "lot_no_filled",
        "defect_category",
        "inspection_qty",
        "defect_qty",
    ]
].copy()
df_clean

,inspection_date,inspection_time,project_filled,site_filled,line_filled,lot_no_filled,defect_category,inspection_qty,defect_qty
0,2026-06-01,08:00,J69P,MELMB,Line1,L250601-A,コイル,300,0
1,2026-06-01,10:00,J69P,MELMB,Line1,L250601-A,コイル,280,1
2,2026-06-01,13:00,J69P,MELMB,Line1,L250601-A,Buck-IC,320,2
3,2026-06-02,08:00,310D,WSE,Line2,L250602-B,はんだ,250,0
4,2026-06-02,10:00,310D,WSE,Line2,L250602-B,コイル,260,1
5,2026-06-02,13:00,310D,WSE,Line2,L250602-B,NTF,240,0
6,2026-06-03,08:00,J69P,GSE,Line1,L250603-C,コイル,310,3
7,2026-06-03,10:00,J69P,GSE,Line1,L250603-C,Buck-IC,290,0
8,2026-06-03,13:00,J69P,GSE,Line1,L250603-C,コイル,300,1
9,2026-06-04,08:00,310D,MELMB,Line3,L250604-D,はんだ,0,1
10,2026-06-04,10:00,310D,MELMB,Line3,L250604-D,コイル,270,2
11,2026-06-04,13:00,310D,MELMB,Line3,L250604-D,NTF,260,0

In [16]:
df_clean["defect_rate_safe"] = (
    (df_clean["defect_qty"] / df_clean["inspection_qty"] * 1_000_000)
    .where(df_clean["inspection_qty"] > 0, 0)
    .round(1)
)

df_clean

,inspection_date,inspection_time,project_filled,site_filled,line_filled,lot_no_filled,defect_category,inspection_qty,defect_qty,defect_rate_safe
0,2026-06-01,08:00,J69P,MELMB,Line1,L250601-A,コイル,300,0,0.0
1,2026-06-01,10:00,J69P,MELMB,Line1,L250601-A,コイル,280,1,3571.4
2,2026-06-01,13:00,J69P,MELMB,Line1,L250601-A,Buck-IC,320,2,6250.0
3,2026-06-02,08:00,310D,WSE,Line2,L250602-B,はんだ,250,0,0.0
4,2026-06-02,10:00,310D,WSE,Line2,L250602-B,コイル,260,1,3846.2
5,2026-06-02,13:00,310D,WSE,Line2,L250602-B,NTF,240,0,0.0
6,2026-06-03,08:00,J69P,GSE,Line1,L250603-C,コイル,310,3,9677.4
7,2026-06-03,10:00,J69P,GSE,Line1,L250603-C,Buck-IC,290,0,0.0
8,2026-06-03,13:00,J69P,GSE,Line1,L250603-C,コイル,300,1,3333.3
9,2026-06-04,08:00,310D,MELMB,Line3,L250604-D,はんだ,0,1,0.0
10,2026-06-04,10:00,310D,MELMB,Line3,L250604-D,コイル,270,2,7407.4
11,2026-06-04,13:00,310D,MELMB,Line3,L250604-D,NTF,260,0,0.0

In [18]:
#cell 7
df_clean["check_result"] = "通常"

df_clean.loc[
    df_clean["defect_rate_safe"] > 5000,
    "check_result",
 ] = "要確認"
df_clean

,inspection_date,inspection_time,project_filled,site_filled,line_filled,lot_no_filled,defect_category,inspection_qty,defect_qty,defect_rate_safe,check_result
0,2026-06-01,08:00,J69P,MELMB,Line1,L250601-A,コイル,300,0,0.0,通常
1,2026-06-01,10:00,J69P,MELMB,Line1,L250601-A,コイル,280,1,3571.4,通常
2,2026-06-01,13:00,J69P,MELMB,Line1,L250601-A,Buck-IC,320,2,6250.0,要確認
3,2026-06-02,08:00,310D,WSE,Line2,L250602-B,はんだ,250,0,0.0,通常
4,2026-06-02,10:00,310D,WSE,Line2,L250602-B,コイル,260,1,3846.2,通常
5,2026-06-02,13:00,310D,WSE,Line2,L250602-B,NTF,240,0,0.0,通常
6,2026-06-03,08:00,J69P,GSE,Line1,L250603-C,コイル,310,3,9677.4,要確認
7,2026-06-03,10:00,J69P,GSE,Line1,L250603-C,Buck-IC,290,0,0.0,通常
8,2026-06-03,13:00,J69P,GSE,Line1,L250603-C,コイル,300,1,3333.3,通常
9,2026-06-04,08:00,310D,MELMB,Line3,L250604-D,はんだ,0,1,0.0,通常
10,2026-06-04,10:00,310D,MELMB,Line3,L250604-D,コイル,270,2,7407.4,要確認
11,2026-06-04,13:00,310D,MELMB,Line3,L250604-D,NTF,260,0,0.0,通常

In [19]:
df_check = df_clean[
    df_clean["check_result"] == "要確認"
].copy()

df_check

,inspection_date,inspection_time,project_filled,site_filled,line_filled,lot_no_filled,defect_category,inspection_qty,defect_qty,defect_rate_safe,check_result
2,2026-06-01,13:00,J69P,MELMB,Line1,L250601-A,Buck-IC,320,2,6250.0,要確認
6,2026-06-03,08:00,J69P,GSE,Line1,L250603-C,コイル,310,3,9677.4,要確認
10,2026-06-04,10:00,310D,MELMB,Line3,L250604-D,コイル,270,2,7407.4,要確認

In [21]:
df_check_sort = df_check.sort_values(
    "defect_rate_safe",
    ascending=False
)
df_check_sort

,inspection_date,inspection_time,project_filled,site_filled,line_filled,lot_no_filled,defect_category,inspection_qty,defect_qty,defect_rate_safe,check_result
6,2026-06-03,08:00,J69P,GSE,Line1,L250603-C,コイル,310,3,9677.4,要確認
10,2026-06-04,10:00,310D,MELMB,Line3,L250604-D,コイル,270,2,7407.4,要確認
2,2026-06-01,13:00,J69P,MELMB,Line1,L250601-A,Buck-IC,320,2,6250.0,要確認

In [23]:
df_cross = df_clean.pivot_table(
    values="defect_qty",
    index="line_filled",
    columns="defect_category",
    aggfunc="sum",
    fill_value=0,
)
df_cross

defect_category  Buck-IC  NTF  はんだ  コイル
line_filled
Line1                  2    0    0    5
Line2                  0    0    0    1
Line3                  0    0    1    2

In [24]:
df_cross["total"] = df_cross.sum(axis=1)
df_cross

defect_category  Buck-IC  NTF  はんだ  コイル  total
line_filled
Line1                  2    0    0    5      7
Line2                  0    0    0    1      1
Line3                  0    0    1    2      3

In [25]:
df_cross_sort = df_cross.sort_values(
    "total",
    ascending=False
)
df_cross_sort

defect_category  Buck-IC  NTF  はんだ  コイル  total
line_filled
Line1                  2    0    0    5      7
Line3                  0    0    1    2      3
Line2                  0    0    0    1      1