In [3]:
%run practice_118_1_step1.ipynb
df3.head()

       Date Name  Size  Price
0  2017/1/3    A     3    100
1  2017/2/4    B     4    200
2  2017/3/5    A     5    300

In [4]:
df5 = pd.DataFrame([[0], [0], [-1]], columns=['Extra'])
df5

   Extra
0      0
1      0
2     -1

In [5]:
df6 = pd.concat([df3, df5], axis=1)
df6

       Date Name  Size  Price  Extra
0  2017/1/3    A     3    100      0
1  2017/2/4    B     4    200      0
2  2017/3/5    A     5    300     -1

In [6]:
df7 =df3.copy()
df7['Extra'] = [0, 0, -1]
df7

       Date Name  Size  Price  Extra
0  2017/1/3    A     3    100      0
1  2017/2/4    B     4    200      0
2  2017/3/5    A     5    300     -1

In [7]:
df7 = df3.copy()

In [9]:
df7['Extra'] = [0, 0, -1]

In [10]:
df6

       Date Name  Size  Price  Extra
0  2017/1/3    A     3    100      0
1  2017/2/4    B     4    200      0
2  2017/3/5    A     5    300     -1

In [11]:
df7

       Date Name  Size  Price  Extra
0  2017/1/3    A     3    100      0
1  2017/2/4    B     4    200      0
2  2017/3/5    A     5    300     -1

In [12]:
(df6 == df7).all().all()

np.True_

In [13]:
df_a = pd.DataFrame(
    [['Sato', 80], ['Suzuki', 90],['Tanaka', 70]],
    columns=['Name', 'Score']
)

In [14]:
df_a

     Name  Score
0    Sato     80
1  Suzuki     90
2  Tanaka     70

In [15]:
df_b = pd.DataFrame(
    [['A'],['B'],['C']],
    columns=['Rank']
)

In [16]:
df_b

  Rank
0    A
1    B
2    C

In [17]:
df_c = pd.concat([df_a, df_b], axis=1)
df_c

     Name  Score Rank
0    Sato     80    A
1  Suzuki     90    B
2  Tanaka     70    C

In [18]:
df_d = df_a.copy()

In [19]:
df_d

     Name  Score
0    Sato     80
1  Suzuki     90
2  Tanaka     70

In [20]:
df_d['Rank'] = ['A', 'B', 'C']
df_d

     Name  Score Rank
0    Sato     80    A
1  Suzuki     90    B
2  Tanaka     70    C

In [22]:
(df_c == df_d).all().all()

np.True_

In [23]:
df_5 = pd.DataFrame([[1],[2],[3]], columns=['Extra'])
df_5

   Extra
0      1
1      2
2      3

In [25]:
df5 = pd.DataFrame([[1], [2], [3]], columns=['Extra'])
df6 = pd.concat([df3, df5], axis=1)
df6

       Date Name  Size  Price  Extra
0  2017/1/3    A     3    100      1
1  2017/2/4    B     4    200      2
2  2017/3/5    A     5    300      3

In [27]:
df7 = df3.copy()

In [28]:
df7

       Date Name  Size  Price
0  2017/1/3    A     3    100
1  2017/2/4    B     4    200
2  2017/3/5    A     5    300

In [29]:
df3.shape

(3, 4)

In [30]:
df6.shape

(3, 5)

In [31]:
df3

       Date Name  Size  Price
0  2017/1/3    A     3    100
1  2017/2/4    B     4    200
2  2017/3/5    A     5    300

In [32]:
df5

   Extra
0      1
1      2
2      3

In [34]:
pd.concat([df3, df5])

       Date Name  Size  Price  Extra
0  2017/1/3    A   3.0  100.0    NaN
1  2017/2/4    B   4.0  200.0    NaN
2  2017/3/5    A   5.0  300.0    NaN
0       NaN  NaN   NaN    NaN    1.0
1       NaN  NaN   NaN    NaN    2.0
2       NaN  NaN   NaN    NaN    3.0