In [1]:
import pandas as pd

df1 = pd.DataFrame(
    [['2017/1/3', 'A', 3], ['2017/2/4', 'B', 4]],
    columns=['Date', 'Name', 'Size']
)
df1

       Date Name  Size
0  2017/1/3    A     3
1  2017/2/4    B     4

In [2]:
df2 = pd.DataFrame(
    [['2017/3/5', 'A', 5]],
    columns=['Date', 'Name', 'Size']
)
df2

       Date Name  Size
0  2017/3/5    A     5

In [3]:
df3 = pd.concat([df1,df2])
df3

       Date Name  Size
0  2017/1/3    A     3
1  2017/2/4    B     4
0  2017/3/5    A     5

In [4]:
df3 = pd.concat([df1, df2], ignore_index=True)
df3

       Date Name  Size
0  2017/1/3    A     3
1  2017/2/4    B     4
2  2017/3/5    A     5

In [5]:
df4 = pd.concat([df1, df2]).reset_index(drop=True)
df4

       Date Name  Size
0  2017/1/3    A     3
1  2017/2/4    B     4
2  2017/3/5    A     5

In [6]:
df3 == df4

   Date  Name  Size
0  True  True  True
1  True  True  True
2  True  True  True

In [7]:
(df3 == df4).all()

Date    True
Name    True
Size    True
dtype: bool

In [8]:
(df3 == df4).all().all()

np.True_

In [12]:
df_a = pd.DataFrame(
    [['2024/1/1', 'X', 10], ['2024/1/2', 'Y', 20]],
    columns=['Date', 'Name', 'Size']
)

df_b = pd.DataFrame(
    [['2024/1/3', 'Z', 30]],
    columns=['Date', 'Name', 'Size']
)

df_c = pd.concat([df_a, df_b]).reset_index(drop=True)
df_c

       Date Name  Size
0  2024/1/1    X    10
1  2024/1/2    Y    20
2  2024/1/3    Z    30

In [13]:
df_d = pd.concat([df_a, df_b]).reset_index(drop=True)
df_d

       Date Name  Size
0  2024/1/1    X    10
1  2024/1/2    Y    20
2  2024/1/3    Z    30

In [15]:
(df_c == df_d).all().all()

np.True_

In [16]:
df1 = pd.DataFrame(
    [['2017/1/3', 'A', 3, 100], ['2017/2/4', 'B', 4, 200]],
    columns=['Date', 'Name', 'Size', 'Price']
)
df1

       Date Name  Size  Price
0  2017/1/3    A     3    100
1  2017/2/4    B     4    200

In [17]:
df2 = pd.DataFrame(
    [['2017/3/5', 'A', 5, 300]],
    columns= ['Date', 'Name', 'Size', 'Price']
)
df2

       Date Name  Size  Price
0  2017/3/5    A     5    300

In [18]:
df3 = pd.concat([df1,df2], ignore_index=True)
df3

       Date Name  Size  Price
0  2017/1/3    A     3    100
1  2017/2/4    B     4    200
2  2017/3/5    A     5    300

In [19]:
df3.shape

(3, 4)