In [1]:
import pandas as pd
df = pd.read_csv('service_sample.csv')
df

      レンタル開始日  顧客名  個数  期間 プラン
0  2018/04/01  顧客A  10   1  通常
1  2018/04/05  顧客B   5   2  学割
2  2018/04/10  顧客A  20   1  通常
3  2018/04/15  顧客C   8   3  通常
4  2018/04/20  顧客B  15   1  学割

In [2]:
print(df)

      レンタル開始日  顧客名  個数  期間 プラン
0  2018/04/01  顧客A  10   1  通常
1  2018/04/05  顧客B   5   2  学割
2  2018/04/10  顧客A  20   1  通常
3  2018/04/15  顧客C   8   3  通常
4  2018/04/20  顧客B  15   1  学割

In [3]:
df["個数x期間"] = df["個数"] * df["期間"]
display(df)

      レンタル開始日  顧客名  個数  期間 プラン  個数x期間
0  2018/04/01  顧客A  10   1  通常     10
1  2018/04/05  顧客B   5   2  学割     10
2  2018/04/10  顧客A  20   1  通常     20
3  2018/04/15  顧客C   8   3  通常     24
4  2018/04/20  顧客B  15   1  学割     15

In [4]:
price_map = {
    "通常": 6000,
    "学割": 3000
}
df["単価"] = df["プラン"].map(price_map)

In [5]:
df

      レンタル開始日  顧客名  個数  期間 プラン  個数x期間    単価
0  2018/04/01  顧客A  10   1  通常     10  6000
1  2018/04/05  顧客B   5   2  学割     10  3000
2  2018/04/10  顧客A  20   1  通常     20  6000
3  2018/04/15  顧客C   8   3  通常     24  6000
4  2018/04/20  顧客B  15   1  学割     15  3000

In [6]:
df["契約金額"] = df["個数x期間"] * df["単価"]
df

      レンタル開始日  顧客名  個数  期間 プラン  個数x期間    単価    契約金額
0  2018/04/01  顧客A  10   1  通常     10  6000   60000
1  2018/04/05  顧客B   5   2  学割     10  3000   30000
2  2018/04/10  顧客A  20   1  通常     20  6000  120000
3  2018/04/15  顧客C   8   3  通常     24  6000  144000
4  2018/04/20  顧客B  15   1  学割     15  3000   45000

In [8]:
def size_category(x):
    if x < 100000:
        return "小口"
    elif x < 200000:
        return "重要"
    elif x < 600000:
        return "中口"
    else:
        return "大口"
df["契約規模"] = df["契約金額"].apply(size_category)
display(df)

      レンタル開始日  顧客名  個数  期間 プラン  個数x期間    単価    契約金額 契約規模
0  2018/04/01  顧客A  10   1  通常     10  6000   60000   小口
1  2018/04/05  顧客B   5   2  学割     10  3000   30000   小口
2  2018/04/10  顧客A  20   1  通常     20  6000  120000   重要
3  2018/04/15  顧客C   8   3  通常     24  6000  144000   重要
4  2018/04/20  顧客B  15   1  学割     15  3000   45000   小口

In [9]:
df_normal = df[df["プラン"] == "通常"]

In [10]:
df_normal

      レンタル開始日  顧客名  個数  期間 プラン  個数x期間    単価    契約金額 契約規模
0  2018/04/01  顧客A  10   1  通常     10  6000   60000   小口
2  2018/04/10  顧客A  20   1  通常     20  6000  120000   重要
3  2018/04/15  顧客C   8   3  通常     24  6000  144000   重要

In [11]:
df.groupby("顧客名")["契約金額"].sum()

顧客名
顧客A    180000
顧客B     75000
顧客C    144000
Name: 契約金額, dtype: int64