###### 130_1_total_point_answer.ipynb

In [7]:
#cell1

import pandas as pd

In [8]:
#cell2 
df = pd.DataFrame(
    [
        ["Alice", "国語", 87],
        ["Alice", "数学", 72],
        ["Bob", "国語", 65],
        ["Bob", "数学", 92],
    ],
    columns=[
        "Name",
        "Subject",
        "Point",
    ],
)
df

    Name Subject  Point
0  Alice      国語     87
1  Alice      数学     72
2    Bob      国語     65
3    Bob      数学     92

In [9]:
#cell3
sr = df.groupby("Name")["Point"].sum()
sr

Name
Alice    159
Bob      157
Name: Point, dtype: int64

In [11]:
#cell4 
df_result = df.join(
    sr.rename("Total"),
    on="Name",
)
df_result

    Name Subject  Point  Total
0  Alice      国語     87    159
1  Alice      数学     72    159
2    Bob      国語     65    157
3    Bob      数学     92    157