In [2]:
import pandas as pd

In [3]:
df_defect = pd.DataFrame(
    [
        ["2026-06", "MELMB", "LCM-A", "点灯不良", 18],
        ["2026-06", "WSE", "LCM-B", "ショート", 32],
        ["2026-06", "GSE", "LCM-C", "外観キズ", 7],
        ["2026-06", "MELMB", "LCM-A", "ちらつき", 12],
        ["2026-06", "WSE", "LCM-D", "コネクタ浮き", 5],
    ],
    columns=[
        "month",
        "site",
        "product",
        "defect_type",
        "defect_qty",
    ],
)
df_defect

     month   site product defect_type  defect_qty
0  2026-06  MELMB   LCM-A        点灯不良          18
1  2026-06    WSE   LCM-B        ショート          32
2  2026-06    GSE   LCM-C        外観キズ           7
3  2026-06  MELMB   LCM-A        ちらつき          12
4  2026-06    WSE   LCM-D      コネクタ浮き           5

In [4]:
df_product_master = pd.DataFrame(
    [
        ["LCM-A", "ヘッドランプ", "品質保証1課"],
        ["LCM-B", "リアランプ", "品質保証2課"],
        ["LCM-C", "ルームランプ", "品質保証3課"],
        ["LCM-D", "ヘッドランプ", "品質保証1課"],
        ["LCM-X", "試作品", "開発部"],
    ],
    columns=[
        "product",
        "product_category",
        "owner_department",
    ],
)
df_product_master

  product product_category owner_department
0   LCM-A           ヘッドランプ           品質保証1課
1   LCM-B            リアランプ           品質保証2課
2   LCM-C           ルームランプ           品質保証3課
3   LCM-D           ヘッドランプ           品質保証1課
4   LCM-X              試作品              開発部

In [5]:
df_result = df_defect.merge(df_product_master, on="product")

In [6]:
df_result

,month,site,product,defect_type,defect_qty,product_category,owner_department
0,2026-06,MELMB,LCM-A,点灯不良,18,ヘッドランプ,品質保証1課
1,2026-06,WSE,LCM-B,ショート,32,リアランプ,品質保証2課
2,2026-06,GSE,LCM-C,外観キズ,7,ルームランプ,品質保証3課
3,2026-06,MELMB,LCM-A,ちらつき,12,ヘッドランプ,品質保証1課
4,2026-06,WSE,LCM-D,コネクタ浮き,5,ヘッドランプ,品質保証1課

In [7]:
df_ranking = df_result.sort_values("defect_qty", ascending=False)
df_ranking

,month,site,product,defect_type,defect_qty,product_category,owner_department
1,2026-06,WSE,LCM-B,ショート,32,リアランプ,品質保証2課
0,2026-06,MELMB,LCM-A,点灯不良,18,ヘッドランプ,品質保証1課
3,2026-06,MELMB,LCM-A,ちらつき,12,ヘッドランプ,品質保証1課
2,2026-06,GSE,LCM-C,外観キズ,7,ルームランプ,品質保証3課
4,2026-06,WSE,LCM-D,コネクタ浮き,5,ヘッドランプ,品質保証1課