###### 128_4_quality_melt_merge_practice.ipynb

In [15]:
import pandas as pd

In [16]:
index = pd.Index(
    [
        "LCM-A",
        "LCM-B",
        "LCM-C",
        "LCM-D",
        "LCM-E",
    ],
    name="product",
)

columns = pd.Index(
    [
        "MELMB",
        "WSE",
        "GSE",
    ],
    name="site",
)

data = [
    [18, 25, 7],
    [12, 32, 9],
    [5, 14, 21],
    [8, 11, 4],
    [22, 6, 13],
]

df_wide = pd.DataFrame(
    data,
    index=index,
    columns=columns,
)

df_wide

site     MELMB  WSE  GSE
product
LCM-A       18   25    7
LCM-B       12   32    9
LCM-C        5   14   21
LCM-D        8   11    4
LCM-E       22    6   13

In [17]:
df_product_master = pd.DataFrame(
    [
        ["LCM-A", "ヘッドランプ", "品質保証1課"],
        ["LCM-B", "ヘッドランプ", "品質保証1課"],
        ["LCM-C", "リアランプ", "品質保証2課"],
        ["LCM-D", "ヘッドランプ", "品質保証1課"],
        ["LCM-E", "リアランプ", "品質保証2課"],
    ],
    columns=[
        "product",
        "category",
        "owner_department",
    ],
)

df_product_master

  product category owner_department
0   LCM-A   ヘッドランプ           品質保証1課
1   LCM-B   ヘッドランプ           品質保証1課
2   LCM-C    リアランプ           品質保証2課
3   LCM-D   ヘッドランプ           品質保証1課
4   LCM-E    リアランプ           品質保証2課

In [18]:
df_long = df_wide.melt(
    value_name="defect_qty",
    ignore_index=False,
)
print(df_long)
df_long = df_long.reset_index()
df_long

          site  defect_qty
product
LCM-A    MELMB          18
LCM-B    MELMB          12
LCM-C    MELMB           5
LCM-D    MELMB           8
LCM-E    MELMB          22
LCM-A      WSE          25
LCM-B      WSE          32
LCM-C      WSE          14
LCM-D      WSE          11
LCM-E      WSE           6
LCM-A      GSE           7
LCM-B      GSE           9
LCM-C      GSE          21
LCM-D      GSE           4
LCM-E      GSE          13

   product   site  defect_qty
0    LCM-A  MELMB          18
1    LCM-B  MELMB          12
2    LCM-C  MELMB           5
3    LCM-D  MELMB           8
4    LCM-E  MELMB          22
5    LCM-A    WSE          25
6    LCM-B    WSE          32
7    LCM-C    WSE          14
8    LCM-D    WSE          11
9    LCM-E    WSE           6
10   LCM-A    GSE           7
11   LCM-B    GSE           9
12   LCM-C    GSE          21
13   LCM-D    GSE           4
14   LCM-E    GSE          13

In [19]:
df_merge = df_long.merge(
    df_product_master,
    on="product",
)

df_merge.head()

  product   site  defect_qty category owner_department
0   LCM-A  MELMB          18   ヘッドランプ           品質保証1課
1   LCM-B  MELMB          12   ヘッドランプ           品質保証1課
2   LCM-C  MELMB           5    リアランプ           品質保証2課
3   LCM-D  MELMB           8   ヘッドランプ           品質保証1課
4   LCM-E  MELMB          22    リアランプ           品質保証2課

In [20]:
df_sort = df_merge.sort_values(
    "defect_qty",
    ascending=False,
)
df_sort

   product   site  defect_qty category owner_department
6    LCM-B    WSE          32   ヘッドランプ           品質保証1課
5    LCM-A    WSE          25   ヘッドランプ           品質保証1課
4    LCM-E  MELMB          22    リアランプ           品質保証2課
12   LCM-C    GSE          21    リアランプ           品質保証2課
0    LCM-A  MELMB          18   ヘッドランプ           品質保証1課
7    LCM-C    WSE          14    リアランプ           品質保証2課
14   LCM-E    GSE          13    リアランプ           品質保証2課
1    LCM-B  MELMB          12   ヘッドランプ           品質保証1課
8    LCM-D    WSE          11   ヘッドランプ           品質保証1課
11   LCM-B    GSE           9   ヘッドランプ           品質保証1課
3    LCM-D  MELMB           8   ヘッドランプ           品質保証1課
10   LCM-A    GSE           7   ヘッドランプ           品質保証1課
9    LCM-E    WSE           6    リアランプ           品質保証2課
2    LCM-C  MELMB           5    リアランプ           品質保証2課
13   LCM-D    GSE           4   ヘッドランプ           品質保証1課

In [23]:
df_sort["check_level"] = "通常確認"
df_sort.head()

df_sort.loc[
    df_sort["defect_qty"] >= 20,
    "check_level",
] = "重点確認"
df_sort.head()

   product   site  defect_qty category owner_department check_level
6    LCM-B    WSE          32   ヘッドランプ           品質保証1課        重点確認
5    LCM-A    WSE          25   ヘッドランプ           品質保証1課        重点確認
4    LCM-E  MELMB          22    リアランプ           品質保証2課        重点確認
12   LCM-C    GSE          21    リアランプ           品質保証2課        重点確認
0    LCM-A  MELMB          18   ヘッドランプ           品質保証1課        通常確認

In [25]:
df_priority = df_sort[
    df_sort["check_level"] == "重点確認"
]
df_priority

   product   site  defect_qty category owner_department check_level
6    LCM-B    WSE          32   ヘッドランプ           品質保証1課        重点確認
5    LCM-A    WSE          25   ヘッドランプ           品質保証1課        重点確認
4    LCM-E  MELMB          22    リアランプ           品質保証2課        重点確認
12   LCM-C    GSE          21    リアランプ           品質保証2課        重点確認

In [30]:
df_report = df_priority[
    [
        "owner_department",
        "product",
        "site",
        "defect_qty",
        "check_level",
    ]
]
df_report = df_report.reset_index(drop=True)
df_report

  owner_department product   site  defect_qty check_level
0           品質保証1課   LCM-B    WSE          32        重点確認
1           品質保証1課   LCM-A    WSE          25        重点確認
2           品質保証2課   LCM-E  MELMB          22        重点確認
3           品質保証2課   LCM-C    GSE          21        重点確認