In [1]:
import pandas as pd

names = ["名前", "クラス", "クラブ", "実施月", "数学"]
df = pd.read_excel("input/exam.xlsx", header=1, names=names)
df.head()

       名前 クラス  クラブ     実施月  数学
0  松原　勇二郎   A  弓道部  201905  93
1  松原 勇二郎   A  弓道部  201908  69
2  吉澤 あきの   A  NaN  201905  71
3  吉澤 あきの   A  NaN  201908  76
4    平山 詩   A  写真部  201905  80

In [2]:
df["名前"] = df["名前"].str.replace("\u3000", " ", regex=False)
df.head()

       名前 クラス  クラブ     実施月  数学
0  松原 勇二郎   A  弓道部  201905  93
1  松原 勇二郎   A  弓道部  201908  69
2  吉澤 あきの   A  NaN  201905  71
3  吉澤 あきの   A  NaN  201908  76
4    平山 詩   A  写真部  201905  80

In [9]:
df["クラブ活動"] = ~df["クラブ"].isna()
df[["名前", "クラブ", "クラブ活動"]].head()

       名前  クラブ  クラブ活動
0  松原 勇二郎  弓道部   True
1  松原 勇二郎  弓道部   True
2  吉澤 あきの  NaN  False
3  吉澤 あきの  NaN  False
4    平山 詩  写真部   True

In [11]:
result = df.groupby("クラブ活動")["数学"].mean()
result

クラブ活動
False    69.000000
True     68.754098
Name: 数学, dtype: float64

In [17]:
import pandas as pd

names = ["名前", "クラス", "クラブ", "実施月", "数学"]
df = pd.read_excel("input/exam.xlsx", header=1, names=names)

df["名前"] = df["名前"].str.replace("\u3000", " ", regex=False)

df["クラブ活動"] = ~df["クラブ"].isna()
result = df.groupby("クラブ活動")["数学"].mean()

df[["クラブ", "クラブ活動"]].head()
print(result)

クラブ活動
False    69.000000
True     68.754098
Name: 数学, dtype: float64

In [19]:
#練習1
#クラブ活動ごとの 数学の最高点 を出してください。
#変数名は result_max にしてください。
result_max = df.groupby("クラブ活動")["数学"].max()
result_max

クラブ活動
False    100
True      95
Name: 数学, dtype: int64

In [22]:
#練習2
#クラブ活動ごとの 数学の最低点 を出してください。
#変数名は result_min にしてください。
result_min = df.groupby("クラブ活動")["数学"].min()
result_min

クラブ活動
False    37
True     33
Name: 数学, dtype: int64

In [23]:
#練習3
#クラブ活動ごとの 人数（行数） を出してください。
#変数名は result_count にしてください。
result_count = df.groupby("クラブ活動")["数学"].count()
result_count

クラブ活動
False    47
True     61
Name: 数学, dtype: int64