In [4]:
import pandas as pd

names = ["名前", "クラス", "クラブ", "実施月", "数学"]
df = pd.read_excel("input/exam.xlsx", header=1, names=names)

df.head()

       名前 クラス  クラブ     実施月  数学
0  松原　勇二郎   A  弓道部  201905  93
1  松原 勇二郎   A  弓道部  201908  69
2  吉澤 あきの   A  NaN  201905  71
3  吉澤 あきの   A  NaN  201908  76
4    平山 詩   A  写真部  201905  80

In [5]:
df["名前"] = df["名前"].str.replace("\u3000", " ", regex=False)
df.head()

       名前 クラス  クラブ     実施月  数学
0  松原 勇二郎   A  弓道部  201905  93
1  松原 勇二郎   A  弓道部  201908  69
2  吉澤 あきの   A  NaN  201905  71
3  吉澤 あきの   A  NaN  201908  76
4    平山 詩   A  写真部  201905  80

In [6]:
sr1 = df.groupby("名前")["実施月"].count()
sr1.head()

名前
中嶋 政斗    1
今 梨瑛     2
八木 佑希    2
前野 麗菜    2
加納 昭信    1
Name: 実施月, dtype: int64

In [9]:
result1 = sr1[sr1 < 2].index
result1

Index(['中嶋 政斗', '加納 昭信', '柴山 尚毅', '根本 奈々香', '相川 昭信', '重田 凌一'], dtype='object', name='名前')

In [11]:
print(result1)
print(len(result1))

Index(['中嶋 政斗', '加納 昭信', '柴山 尚毅', '根本 奈々香', '相川 昭信', '重田 凌一'], dtype='object', name='名前')
6