In [1]:
import pandas as pd

names = ["名前", "クラス", "クラブ", "実施月", "数学"]
df = pd.read_excel("input/exam.xlsx", header=1, names=names)
df.head()

       名前 クラス  クラブ     実施月  数学
0  松原　勇二郎   A  弓道部  201905  93
1  松原 勇二郎   A  弓道部  201908  69
2  吉澤 あきの   A  NaN  201905  71
3  吉澤 あきの   A  NaN  201908  76
4    平山 詩   A  写真部  201905  80

In [2]:
df["名前"] = df["名前"].str.replace("\u3000", " ", regex=False)
df.head()

       名前 クラス  クラブ     実施月  数学
0  松原 勇二郎   A  弓道部  201905  93
1  松原 勇二郎   A  弓道部  201908  69
2  吉澤 あきの   A  NaN  201905  71
3  吉澤 あきの   A  NaN  201908  76
4    平山 詩   A  写真部  201905  80

In [8]:
sr2 = df.groupby("名前")["数学"].mean()
sr2.head()

名前
中嶋 政斗    44.0
今 梨瑛     46.0
八木 佑希    67.5
前野 麗菜    70.0
加納 昭信    65.0
Name: 数学, dtype: float64

In [9]:
result2 = sr2[sr2 < 50].index

In [10]:
result2

Index(['中嶋 政斗', '今 梨瑛'], dtype='object', name='名前')

In [11]:
result_low60 = sr2[sr2 < 60].index
result_low60

Index(['中嶋 政斗', '今 梨瑛', '堀 清華', '寺島 京一朗', '小椋 有華', '新田 嘉明', '松永 紗恵', '柴山 尚毅',
       '森 紗名', '森川 俊雄', '植木 京介', '神野 奏輔', '織田 俊道', '重田 凌一', '高田 睦輝', '高野 結那'],
      dtype='object', name='名前')

In [12]:
result_high80 = sr2[sr2 >= 80].index
result_high80

Index(['勝又 舞香', '吉川 政斗', '大橋 益穂', '小杉 奈々香', '岡村 奈乃葉', '松原 勇二郎', '楠本 愛花',
       '相川 昭信', '真田 結依子', '茂木 聖香', '西沢 匡'],
      dtype='object', name='名前')

In [13]:
low_score_students = sr2[sr2 < 50]
low_score_students

名前
中嶋 政斗    44.0
今 梨瑛     46.0
Name: 数学, dtype: float64