###### 129_1_quality_negative_to_zero_practice

In [30]:
import pandas as pd

In [31]:
df = pd.DataFrame(
    [
         ["D001", "J69P", "MELMB", 1200, 3],
        ["D002", "J69P", "WSE", 980, -2],
        ["D003", "310D", "GSE", -500, 1],
        ["D004", "310D", "ISE", 760, 0],
        ["D005", "J69P", "MELMB", 1100, 5],
        ["D006", "310D", "WSE", 850, -1],
        ["D007", "J69P", "GSE", 920, 2],
    ],
    columns=[
        "defect_id",
        "project",
        "site",
        "inspection_qty",
        "defect_qty",
    ],
)

df

  defect_id project   site  inspection_qty  defect_qty
0      D001    J69P  MELMB            1200           3
1      D002    J69P    WSE             980          -2
2      D003    310D    GSE            -500           1
3      D004    310D    ISE             760           0
4      D005    J69P  MELMB            1100           5
5      D006    310D    WSE             850          -1
6      D007    J69P    GSE             920           2

In [32]:
df["defect_qty_fixed"] = df["defect_qty"].where(
    df["defect_qty"] >= 0,
    0,
)
df

  defect_id project   site  inspection_qty  defect_qty  defect_qty_fixed
0      D001    J69P  MELMB            1200           3                 3
1      D002    J69P    WSE             980          -2                 0
2      D003    310D    GSE            -500           1                 1
3      D004    310D    ISE             760           0                 0
4      D005    J69P  MELMB            1100           5                 5
5      D006    310D    WSE             850          -1                 0
6      D007    J69P    GSE             920           2                 2

In [33]:
#cell4
df["inspection_qty_fixed"] = df["inspection_qty"].where(
    df["inspection_qty"] >= 0,
    0,
)
df

,defect_id,project,site,inspection_qty,defect_qty,defect_qty_fixed,inspection_qty_fixed
0,D001,J69P,MELMB,1200,3,3,1200
1,D002,J69P,WSE,980,-2,0,980
2,D003,310D,GSE,-500,1,1,0
3,D004,310D,ISE,760,0,0,760
4,D005,J69P,MELMB,1100,5,5,1100
5,D006,310D,WSE,850,-1,0,850
6,D007,J69P,GSE,920,2,2,920

In [34]:
#df["defect_rate"] = (df["defect_qty_fixed"] / df["inspection_qty_fixed"] * 1000000).round(1)
#df

df["defect_rate_safe"] = (
    df["defect_qty_fixed"] / df["inspection_qty_fixed"]
    ).where(
    df["inspection_qty_fixed"] > 0,
    0,
)

df

,defect_id,project,site,inspection_qty,defect_qty,defect_qty_fixed,inspection_qty_fixed,defect_rate_safe
0,D001,J69P,MELMB,1200,3,3,1200,0.002500
1,D002,J69P,WSE,980,-2,0,980,0.000000
2,D003,310D,GSE,-500,1,1,0,0.000000
3,D004,310D,ISE,760,0,0,760,0.000000
4,D005,J69P,MELMB,1100,5,5,1100,0.004545
5,D006,310D,WSE,850,-1,0,850,0.000000
6,D007,J69P,GSE,920,2,2,920,0.002174

In [35]:
#cell6

df_sort = df.sort_values(
    "defect_rate_safe",
    ascending=False,
)
df_sort

,defect_id,project,site,inspection_qty,defect_qty,defect_qty_fixed,inspection_qty_fixed,defect_rate_safe
4,D005,J69P,MELMB,1100,5,5,1100,0.004545
0,D001,J69P,MELMB,1200,3,3,1200,0.002500
6,D007,J69P,GSE,920,2,2,920,0.002174
2,D003,310D,GSE,-500,1,1,0,0.000000
1,D002,J69P,WSE,980,-2,0,980,0.000000
3,D004,310D,ISE,760,0,0,760,0.000000
5,D006,310D,WSE,850,-1,0,850,0.000000