######  pandas groupby + transform 練習

In [3]:
import pandas as pd

###### STEP1 データ作成 顧客ごとの購入データを作る

In [4]:
data = {
    "顧客": ["A", "A", "A", "B", "B", "C", "C", "C"],
    "購入金額": [100, 200, 150, 300, 250, 80, 120,160]
}

df = pd.DataFrame(data)
df

  顧客  購入金額
0  A   100
1  A   200
2  A   150
3  B   300
4  B   250
5  C    80
6  C   120
7  C   160

###### STEP2 groupby: 顧客ごとにグループ化する

In [5]:
grouped = df.groupby("顧客")

###### STEP3 累積購入回数:cumcount()を使う 0から始まるので +1 する

In [6]:
df["購入回数"] = grouped.cumcount() + 1
df

  顧客  購入金額  購入回数
0  A   100     1
1  A   200     2
2  A   150     3
3  B   300     1
4  B   250     2
5  C    80     1
6  C   120     2
7  C   160     3

###### STEP4 平均との差 : 平均との差 = 自分 − 平均

In [7]:
def diff_mean(sr):
    return sr - sr.mean()
df["平均との差"] = grouped["購入金額"].transform(diff_mean)
df

  顧客  購入金額  購入回数  平均との差
0  A   100     1  -50.0
1  A   200     2   50.0
2  A   150     3    0.0
3  B   300     1   25.0
4  B   250     2  -25.0
5  C    80     1  -40.0
6  C   120     2    0.0
7  C   160     3   40.0