###### 129_4_quality_drop_duplicates_count_check

In [1]:
#cell1 
import pandas as pd

In [2]:
#cell2
df = pd.DataFrame(
    [
        ["D001", "J69P", "MELMB", "コイル", 1, "確定", "2026-06-01 09:00", "file_A"],
        ["D002", "J69P", "WSE", "Buck-IC", 0, "仮登録", "2026-06-01 09:10", "file_A"],
        ["D003", "310D", "GSE", "はんだ", 1, "確定", "2026-06-01 09:20", "file_A"],
        ["D004", "J69P", "MELMB", "コイル", 3, "仮登録", "2026-06-01 09:30", "file_A"],
        ["D002", "J69P", "WSE", "Buck-IC", 2, "修正", "2026-06-01 10:00", "file_B"],
        ["D005", "310D", "WSE", "NTF", 0, "確定", "2026-06-01 10:10", "file_A"],
        ["D006", "J69P", "GSE", "コイル", 2, "確定", "2026-06-01 10:20", "file_A"],
        ["D004", "J69P", "MELMB", "コイル", 4, "修正", "2026-06-01 10:30", "file_B"],
        ["D007", "310D", "MELMB", "はんだ", 1, "確定", "2026-06-01 10:40", "file_A"],
        ["D008", "J69P", "WSE", "コイル", 1, "仮登録", "2026-06-01 10:50", "file_A"],
        ["D008", "J69P", "WSE", "コイル", 3, "修正", "2026-06-01 11:20", "file_B"],
        ["D009", "310D", "GSE", "NTF", 0, "確定", "2026-06-01 11:30", "file_A"],
        ["D010", "J69P", "MELMB", "Buck-IC", 1, "確定", "2026-06-01 11:40", "file_A"],
        ["D002", "J69P", "WSE", "Buck-IC", 2, "承認済", "2026-06-01 12:00", "file_C"],
    ],
    columns=[
        "defect_id",
        "project",
        "site",
        "defect_category",
        "defect_qty",
        "status",
        "update_time",
        "source_file",
    ],
)
df

,defect_id,project,site,defect_category,defect_qty,status,update_time,source_file
0,D001,J69P,MELMB,コイル,1,確定,2026-06-01 09:00,file_A
1,D002,J69P,WSE,Buck-IC,0,仮登録,2026-06-01 09:10,file_A
2,D003,310D,GSE,はんだ,1,確定,2026-06-01 09:20,file_A
3,D004,J69P,MELMB,コイル,3,仮登録,2026-06-01 09:30,file_A
4,D002,J69P,WSE,Buck-IC,2,修正,2026-06-01 10:00,file_B
5,D005,310D,WSE,NTF,0,確定,2026-06-01 10:10,file_A
6,D006,J69P,GSE,コイル,2,確定,2026-06-01 10:20,file_A
7,D004,J69P,MELMB,コイル,4,修正,2026-06-01 10:30,file_B
8,D007,310D,MELMB,はんだ,1,確定,2026-06-01 10:40,file_A
9,D008,J69P,WSE,コイル,1,仮登録,2026-06-01 10:50,file_A
10,D008,J69P,WSE,コイル,3,修正,2026-06-01 11:20,file_B
11,D009,310D,GSE,NTF,0,確定,2026-06-01 11:30,file_A
12,D010,J69P,MELMB,Buck-IC,1,確定,2026-06-01 11:40,file_A
13,D002,J69P,WSE,Buck-IC,2,承認済,2026-06-01 12:00,file_C

In [ ]:
#cell3
df_work = df.copy()
df_work

,defect_id,project,site,defect_category,defect_qty,status,update_time,source_file
0,D001,J69P,MELMB,コイル,1,確定,2026-06-01 09:00,file_A
1,D002,J69P,WSE,Buck-IC,0,仮登録,2026-06-01 09:10,file_A
2,D003,310D,GSE,はんだ,1,確定,2026-06-01 09:20,file_A
3,D004,J69P,MELMB,コイル,3,仮登録,2026-06-01 09:30,file_A
4,D002,J69P,WSE,Buck-IC,2,修正,2026-06-01 10:00,file_B
5,D005,310D,WSE,NTF,0,確定,2026-06-01 10:10,file_A
6,D006,J69P,GSE,コイル,2,確定,2026-06-01 10:20,file_A
7,D004,J69P,MELMB,コイル,4,修正,2026-06-01 10:30,file_B
8,D007,310D,MELMB,はんだ,1,確定,2026-06-01 10:40,file_A
9,D008,J69P,WSE,コイル,1,仮登録,2026-06-01 10:50,file_A
10,D008,J69P,WSE,コイル,3,修正,2026-06-01 11:20,file_B
11,D009,310D,GSE,NTF,0,確定,2026-06-01 11:30,file_A
12,D010,J69P,MELMB,Buck-IC,1,確定,2026-06-01 11:40,file_A
13,D002,J69P,WSE,Buck-IC,2,承認済,2026-06-01 12:00,file_C

In [ ]:
#cell4
df_work["update_time"] = pd.to_datetime(
    df_work["update_time"]
)
df_work

,defect_id,project,site,defect_category,defect_qty,status,update_time,source_file
0,D001,J69P,MELMB,コイル,1,確定,2026-06-01 09:00:00,file_A
1,D002,J69P,WSE,Buck-IC,0,仮登録,2026-06-01 09:10:00,file_A
2,D003,310D,GSE,はんだ,1,確定,2026-06-01 09:20:00,file_A
3,D004,J69P,MELMB,コイル,3,仮登録,2026-06-01 09:30:00,file_A
4,D002,J69P,WSE,Buck-IC,2,修正,2026-06-01 10:00:00,file_B
5,D005,310D,WSE,NTF,0,確定,2026-06-01 10:10:00,file_A
6,D006,J69P,GSE,コイル,2,確定,2026-06-01 10:20:00,file_A
7,D004,J69P,MELMB,コイル,4,修正,2026-06-01 10:30:00,file_B
8,D007,310D,MELMB,はんだ,1,確定,2026-06-01 10:40:00,file_A
9,D008,J69P,WSE,コイル,1,仮登録,2026-06-01 10:50:00,file_A
10,D008,J69P,WSE,コイル,3,修正,2026-06-01 11:20:00,file_B
11,D009,310D,GSE,NTF,0,確定,2026-06-01 11:30:00,file_A
12,D010,J69P,MELMB,Buck-IC,1,確定,2026-06-01 11:40:00,file_A
13,D002,J69P,WSE,Buck-IC,2,承認済,2026-06-01 12:00:00,file_C

In [ ]:
#cell5
df_duplicate_check = df_work[
    df_work.duplicated(
    "defect_id",
    keep=False,
    )
].copy()
df_duplicate_check

,defect_id,project,site,defect_category,defect_qty,status,update_time,source_file
1,D002,J69P,WSE,Buck-IC,0,仮登録,2026-06-01 09:10:00,file_A
3,D004,J69P,MELMB,コイル,3,仮登録,2026-06-01 09:30:00,file_A
4,D002,J69P,WSE,Buck-IC,2,修正,2026-06-01 10:00:00,file_B
7,D004,J69P,MELMB,コイル,4,修正,2026-06-01 10:30:00,file_B
9,D008,J69P,WSE,コイル,1,仮登録,2026-06-01 10:50:00,file_A
10,D008,J69P,WSE,コイル,3,修正,2026-06-01 11:20:00,file_B
13,D002,J69P,WSE,Buck-IC,2,承認済,2026-06-01 12:00:00,file_C

In [ ]:
#call6
before_count = len(df_work)
before_count

14

In [9]:
#cell7
df_sort = df_work.sort_values(
    "update_time"
)
df_sort

,defect_id,project,site,defect_category,defect_qty,status,update_time,source_file
0,D001,J69P,MELMB,コイル,1,確定,2026-06-01 09:00:00,file_A
1,D002,J69P,WSE,Buck-IC,0,仮登録,2026-06-01 09:10:00,file_A
2,D003,310D,GSE,はんだ,1,確定,2026-06-01 09:20:00,file_A
3,D004,J69P,MELMB,コイル,3,仮登録,2026-06-01 09:30:00,file_A
4,D002,J69P,WSE,Buck-IC,2,修正,2026-06-01 10:00:00,file_B
5,D005,310D,WSE,NTF,0,確定,2026-06-01 10:10:00,file_A
6,D006,J69P,GSE,コイル,2,確定,2026-06-01 10:20:00,file_A
7,D004,J69P,MELMB,コイル,4,修正,2026-06-01 10:30:00,file_B
8,D007,310D,MELMB,はんだ,1,確定,2026-06-01 10:40:00,file_A
9,D008,J69P,WSE,コイル,1,仮登録,2026-06-01 10:50:00,file_A
10,D008,J69P,WSE,コイル,3,修正,2026-06-01 11:20:00,file_B
11,D009,310D,GSE,NTF,0,確定,2026-06-01 11:30:00,file_A
12,D010,J69P,MELMB,Buck-IC,1,確定,2026-06-01 11:40:00,file_A
13,D002,J69P,WSE,Buck-IC,2,承認済,2026-06-01 12:00:00,file_C

In [10]:
df_deleted = df_sort[
    df_sort.duplicated(
        "defect_id",
        keep="last",
    )
].copy()
df_deleted

,defect_id,project,site,defect_category,defect_qty,status,update_time,source_file
1,D002,J69P,WSE,Buck-IC,0,仮登録,2026-06-01 09:10:00,file_A
3,D004,J69P,MELMB,コイル,3,仮登録,2026-06-01 09:30:00,file_A
4,D002,J69P,WSE,Buck-IC,2,修正,2026-06-01 10:00:00,file_B
9,D008,J69P,WSE,コイル,1,仮登録,2026-06-01 10:50:00,file_A

In [11]:
#cell9
df_result = df_sort.drop_duplicates(
    "defect_id",
    keep="last",
)
df_result

,defect_id,project,site,defect_category,defect_qty,status,update_time,source_file
0,D001,J69P,MELMB,コイル,1,確定,2026-06-01 09:00:00,file_A
2,D003,310D,GSE,はんだ,1,確定,2026-06-01 09:20:00,file_A
5,D005,310D,WSE,NTF,0,確定,2026-06-01 10:10:00,file_A
6,D006,J69P,GSE,コイル,2,確定,2026-06-01 10:20:00,file_A
7,D004,J69P,MELMB,コイル,4,修正,2026-06-01 10:30:00,file_B
8,D007,310D,MELMB,はんだ,1,確定,2026-06-01 10:40:00,file_A
10,D008,J69P,WSE,コイル,3,修正,2026-06-01 11:20:00,file_B
11,D009,310D,GSE,NTF,0,確定,2026-06-01 11:30:00,file_A
12,D010,J69P,MELMB,Buck-IC,1,確定,2026-06-01 11:40:00,file_A
13,D002,J69P,WSE,Buck-IC,2,承認済,2026-06-01 12:00:00,file_C

In [12]:
after_count = len(df_result)
after_count

10

In [13]:
deleted_count = before_count - after_count
deleted_count

4

In [14]:
#cell12

duplicated_id_count = df_duplicate_check["defect_id"].nunique()

df_count_summary = pd.DataFrame(
    [
        ["削除前行数", before_count],
        ["削除後行数", after_count],
        ["削除行数", deleted_count],
        ["重複していたdefect_id数", duplicated_id_count], 
    ],
    columns=[
        "確認項目",
        "件数",
    ],
)
df_count_summary

               確認項目  件数
0             削除前行数  14
1             削除後行数  10
2              削除行数   4
3  重複していたdefect_id数   3

In [17]:
#cell13
df_site_total = df_result.pivot_table(
    values="defect_qty",
    index="site",
    aggfunc="sum",
)
df_site_total

       defect_qty
site
GSE             3
MELMB           7
WSE             5

In [18]:
#cell14
df_site_total_sort = df_site_total.sort_values(
    "defect_qty",
    ascending=False,
)
df_site_total_sort

       defect_qty
site
MELMB           7
WSE             5
GSE             3