###### 130_5_practical_defect_manage_no_answer.ipynb

In [1]:
import pandas as pd
pd.set_option("display.max_columns", None)

In [2]:
df_defect = pd.DataFrame(
    [
        ["2026-06-03", "SUS", "J69P", "D-004", "コイル", 1],
        ["2026-06-01", "SUS", "J69P", "D-001", "NTF", 1],
        ["2026-06-02", "SUS", "310D", "D-002", "Buck-IC", 1],
        ["2026-06-04", "WSE", "310D", "D-005", "コイル", 2],
        ["2026-06-01", "WSE", "310D", "D-003", "NTF", 1],
        ["2026-06-05", "SUS", "J69P", "D-006", "Buck-IC", 1],
        ["2026-06-02", "GSE", "J69P", "D-007", "コイル", 1],
        ["2026-06-03", "GSE", "J69P", "D-008", "CAN通信", 1],
        ["2026-06-06", "WSE", "310D", "D-009", "コイル", 1],
        ["2026-06-02", "SUS", "J69P", "D-010", "コイル", 1],
    ],
    columns=[
        "occ_date",
        "site",
        "model",
        "defect_id",
        "defect_category",
        "defect_qty",
    ],
)
df_defect

     occ_date site model defect_id defect_category  defect_qty
0  2026-06-03  SUS  J69P     D-004             コイル           1
1  2026-06-01  SUS  J69P     D-001             NTF           1
2  2026-06-02  SUS  310D     D-002         Buck-IC           1
3  2026-06-04  WSE  310D     D-005             コイル           2
4  2026-06-01  WSE  310D     D-003             NTF           1
5  2026-06-05  SUS  J69P     D-006         Buck-IC           1
6  2026-06-02  GSE  J69P     D-007             コイル           1
7  2026-06-03  GSE  J69P     D-008           CAN通信           1
8  2026-06-06  WSE  310D     D-009             コイル           1
9  2026-06-02  SUS  J69P     D-010             コイル           1

In [3]:
df_work = df_defect.copy()
df_work

     occ_date site model defect_id defect_category  defect_qty
0  2026-06-03  SUS  J69P     D-004             コイル           1
1  2026-06-01  SUS  J69P     D-001             NTF           1
2  2026-06-02  SUS  310D     D-002         Buck-IC           1
3  2026-06-04  WSE  310D     D-005             コイル           2
4  2026-06-01  WSE  310D     D-003             NTF           1
5  2026-06-05  SUS  J69P     D-006         Buck-IC           1
6  2026-06-02  GSE  J69P     D-007             コイル           1
7  2026-06-03  GSE  J69P     D-008           CAN通信           1
8  2026-06-06  WSE  310D     D-009             コイル           1
9  2026-06-02  SUS  J69P     D-010             コイル           1

In [4]:
df_work = df_work.sort_values(
    [
        "site",
        "model",
        "occ_date",
        "defect_id",
    ]
).reset_index(drop=True)
df_work

     occ_date site model defect_id defect_category  defect_qty
0  2026-06-02  GSE  J69P     D-007             コイル           1
1  2026-06-03  GSE  J69P     D-008           CAN通信           1
2  2026-06-02  SUS  310D     D-002         Buck-IC           1
3  2026-06-01  SUS  J69P     D-001             NTF           1
4  2026-06-02  SUS  J69P     D-010             コイル           1
5  2026-06-03  SUS  J69P     D-004             コイル           1
6  2026-06-05  SUS  J69P     D-006         Buck-IC           1
7  2026-06-01  WSE  310D     D-003             NTF           1
8  2026-06-04  WSE  310D     D-005             コイル           2
9  2026-06-06  WSE  310D     D-009             コイル           1

In [5]:
df_work["occurrence_no"] = df_work.groupby(
    [
        "site",
        "model",
    ]
).cumcount() + 1
df_work

     occ_date site model defect_id defect_category  defect_qty  occurrence_no
0  2026-06-02  GSE  J69P     D-007             コイル           1              1
1  2026-06-03  GSE  J69P     D-008           CAN通信           1              2
2  2026-06-02  SUS  310D     D-002         Buck-IC           1              1
3  2026-06-01  SUS  J69P     D-001             NTF           1              1
4  2026-06-02  SUS  J69P     D-010             コイル           1              2
5  2026-06-03  SUS  J69P     D-004             コイル           1              3
6  2026-06-05  SUS  J69P     D-006         Buck-IC           1              4
7  2026-06-01  WSE  310D     D-003             NTF           1              1
8  2026-06-04  WSE  310D     D-005             コイル           2              2
9  2026-06-06  WSE  310D     D-009             コイル           1              3

In [7]:
df_work["occurrence_no_text"] = df_work["occurrence_no"].astype(str).str.zfill(3)
df_work

,occ_date,site,model,defect_id,defect_category,defect_qty,occurrence_no,occurrence_no_text
0,2026-06-02,GSE,J69P,D-007,コイル,1,1,001
1,2026-06-03,GSE,J69P,D-008,CAN通信,1,2,002
2,2026-06-02,SUS,310D,D-002,Buck-IC,1,1,001
3,2026-06-01,SUS,J69P,D-001,NTF,1,1,001
4,2026-06-02,SUS,J69P,D-010,コイル,1,2,002
5,2026-06-03,SUS,J69P,D-004,コイル,1,3,003
6,2026-06-05,SUS,J69P,D-006,Buck-IC,1,4,004
7,2026-06-01,WSE,310D,D-003,NTF,1,1,001
8,2026-06-04,WSE,310D,D-005,コイル,2,2,002
9,2026-06-06,WSE,310D,D-009,コイル,1,3,003

In [8]:
df_work["defect_manage_no"] = (
    df_work["site"]
    + "-"
    + df_work["model"]
    + "-"
    + df_work["occurrence_no_text"]
)
df_work

,occ_date,site,model,defect_id,defect_category,defect_qty,occurrence_no,occurrence_no_text,defect_manage_no
0,2026-06-02,GSE,J69P,D-007,コイル,1,1,001,GSE-J69P-001
1,2026-06-03,GSE,J69P,D-008,CAN通信,1,2,002,GSE-J69P-002
2,2026-06-02,SUS,310D,D-002,Buck-IC,1,1,001,SUS-310D-001
3,2026-06-01,SUS,J69P,D-001,NTF,1,1,001,SUS-J69P-001
4,2026-06-02,SUS,J69P,D-010,コイル,1,2,002,SUS-J69P-002
5,2026-06-03,SUS,J69P,D-004,コイル,1,3,003,SUS-J69P-003
6,2026-06-05,SUS,J69P,D-006,Buck-IC,1,4,004,SUS-J69P-004
7,2026-06-01,WSE,310D,D-003,NTF,1,1,001,WSE-310D-001
8,2026-06-04,WSE,310D,D-005,コイル,2,2,002,WSE-310D-002
9,2026-06-06,WSE,310D,D-009,コイル,1,3,003,WSE-310D-003

In [10]:
df_result = df_work[
    [
        "defect_manage_no",
        "site",
        "model",
        "occ_date",
        "defect_id",
        "defect_category",
        "defect_qty",
        "occurrence_no",
    ]
]
df_result.head()

,defect_manage_no,site,model,occ_date,defect_id,defect_category,defect_qty,occurrence_no
0,GSE-J69P-001,GSE,J69P,2026-06-02,D-007,コイル,1,1
1,GSE-J69P-002,GSE,J69P,2026-06-03,D-008,CAN通信,1,2
2,SUS-310D-001,SUS,310D,2026-06-02,D-002,Buck-IC,1,1
3,SUS-J69P-001,SUS,J69P,2026-06-01,D-001,NTF,1,1
4,SUS-J69P-002,SUS,J69P,2026-06-02,D-010,コイル,1,2