In [2]:
import pandas as pd
df = pd.read_csv("service_detail_sample.csv")

In [3]:
print(df.head())

      レンタル開始日  顧客名    個数  期間 プラン
0  2022/04/01  顧客A  15.0   1  通常
1  2022/04/05  顧客B  15.0   2  学割
2  2022/04/20  顧客C  10.0   2  通常
3  2018/06/15  顧客A  20.0   2  通常
4  2019/07/01  顧客D   NaN   3  通常

In [4]:
df.shape

(8, 5)

In [5]:
print(df.shape)

(8, 5)

In [6]:
print(df.isna().sum())

レンタル開始日    0
顧客名        0
個数         1
期間         0
プラン        0
dtype: int64

In [7]:
print(df["顧客名"].value_counts())

顧客名
顧客A    3
顧客B    2
顧客C    1
顧客D    1
顧客X    1
Name: count, dtype: int64

In [8]:
print(df["プラン"].value_counts())

プラン
通常     5
学割     2
???    1
Name: count, dtype: int64

In [9]:
print(df.describe())

               個数         期間
count    7.000000   8.000000
mean    38.285714   3.125000
std     71.558168   3.642507
min      3.000000   1.000000
25%      7.500000   1.750000
50%     15.000000   2.000000
75%     17.500000   2.250000
max    200.000000  12.000000

In [10]:
df_shape = df.shape
print(df_shape)

(8, 5)

In [11]:
na_count = df.isna().sum()
na_count

レンタル開始日    0
顧客名        0
個数         1
期間         0
プラン        0
dtype: int64

In [12]:
print(df["プラン"].value_counts())

プラン
通常     5
学割     2
???    1
Name: count, dtype: int64

In [13]:
print(df.describe())

               個数         期間
count    7.000000   8.000000
mean    38.285714   3.125000
std     71.558168   3.642507
min      3.000000   1.000000
25%      7.500000   1.750000
50%     15.000000   2.000000
75%     17.500000   2.250000
max    200.000000  12.000000

In [14]:
df_large = df[df["個数"] >= 100]
print(df_large)

      レンタル開始日  顧客名     個数  期間 プラン
5  2020/08/10  顧客A  200.0  12  通常

In [15]:
df[df["個数"] <= 10]

      レンタル開始日  顧客名    個数  期間  プラン
2  2022/04/20  顧客C  10.0   2   通常
6  2021/09/05  顧客B   5.0   1   学割
7  2021/10/12  顧客X   3.0   2  ???

In [17]:
df[df["プラン"] == "通常"]

      レンタル開始日  顧客名     個数  期間 プラン
0  2022/04/01  顧客A   15.0   1  通常
2  2022/04/20  顧客C   10.0   2  通常
3  2018/06/15  顧客A   20.0   2  通常
4  2019/07/01  顧客D    NaN   3  通常
5  2020/08/10  顧客A  200.0  12  通常

In [18]:
df[(df["個数"] >= 10) & (df["プラン"] == "通常")]

      レンタル開始日  顧客名     個数  期間 プラン
0  2022/04/01  顧客A   15.0   1  通常
2  2022/04/20  顧客C   10.0   2  通常
3  2018/06/15  顧客A   20.0   2  通常
5  2020/08/10  顧客A  200.0  12  通常