###### 129_6_groupby_cut_defect_ppm_practice.ipynb

In [1]:
##cell1
import pandas as pd
import numpy as np

In [3]:
df = pd.DataFrame(
    [
        ["D001", "J69P", "MELMB", "コイル", 3, 12000, "調査中"],
        ["D002", "J69P", "WSE", "Buck-IC", 5, 18000, "対策検討中"],
        ["D003", "310D", "GSE", "コイル", 12, 25000, "暫定対策済"],
        ["D004", "310D", "MELMB", "はんだ", 2, 9000, "調査中"],
        ["D005", "J69P", "GSE", "コイル", 7, 15000, "調査中"],
        ["D006", "310D", "WSE", "コネクタ", 1, 6000, "完了"],
        ["D007", "J69P", "MELMB", "Buck-IC", 8, 20000, "調査中"],
        ["D008", "310D", "GSE", "コイル", 4, 10000, "対策検討中"],
        ["D009", "J69P", "GSE", "Buck-IC", 6, 14000, "調査中"],
        ["D010", "310D", "MELMB", "コイル", 5, 16000, "暫定対策済"],
        ["D011", "J69P", "WSE", "コイル", 9, 22000, "調査中"],
        ["D012", "310D", "GSE", "はんだ", 3, 8000, "完了"],
        ["D013", "J69P", "MELMB", "コイル", 4, 11000, "調査中"],
        ["D014", "310D", "WSE", "Buck-IC", 2, 7000, "対策検討中"],
        ["D015", "J69P", "GSE", "コイル", 5, 13000, "調査中"],
        ["D016", "310D", "MELMB", "コネクタ", 4, 5000, "調査中"],
        ["D017", "J69P", "WSE", "はんだ", 1, 20000, "完了"],
        ["D018", "310D", "GSE", "Buck-IC", 3, 6000, "調査中"],
    ],
    columns=[
        "defect_id",
        "project",
        "site",
        "defect_category",
        "defect_qty",
        "inspection_qty",
        "status",
    ],
)
df

   defect_id project   site defect_category  defect_qty  inspection_qty status
0       D001    J69P  MELMB             コイル           3           12000    調査中
1       D002    J69P    WSE         Buck-IC           5           18000  対策検討中
2       D003    310D    GSE             コイル          12           25000  暫定対策済
3       D004    310D  MELMB             はんだ           2            9000    調査中
4       D005    J69P    GSE             コイル           7           15000    調査中
5       D006    310D    WSE            コネクタ           1            6000     完了
6       D007    J69P  MELMB         Buck-IC           8           20000    調査中
7       D008    310D    GSE             コイル           4           10000  対策検討中
8       D009    J69P    GSE         Buck-IC           6           14000    調査中
9       D010    310D  MELMB             コイル           5           16000  暫定対策済
10      D011    J69P    WSE             コイル           9           22000    調査中
11      D012    310D    GSE             はんだ           3            8000     完了
12      D013    J69P  MELMB             コイル           4           11000    調査中
13      D014    310D    WSE         Buck-IC           2            7000  対策検討中
14      D015    J69P    GSE             コイル           5           13000    調査中
15      D016    310D  MELMB            コネクタ           4            5000    調査中
16      D017    J69P    WSE             はんだ           1           20000     完了
17      D018    310D    GSE         Buck-IC           3            6000    調査中

In [4]:
df_work = df.copy()
df_work

   defect_id project   site defect_category  defect_qty  inspection_qty status
0       D001    J69P  MELMB             コイル           3           12000    調査中
1       D002    J69P    WSE         Buck-IC           5           18000  対策検討中
2       D003    310D    GSE             コイル          12           25000  暫定対策済
3       D004    310D  MELMB             はんだ           2            9000    調査中
4       D005    J69P    GSE             コイル           7           15000    調査中
5       D006    310D    WSE            コネクタ           1            6000     完了
6       D007    J69P  MELMB         Buck-IC           8           20000    調査中
7       D008    310D    GSE             コイル           4           10000  対策検討中
8       D009    J69P    GSE         Buck-IC           6           14000    調査中
9       D010    310D  MELMB             コイル           5           16000  暫定対策済
10      D011    J69P    WSE             コイル           9           22000    調査中
11      D012    310D    GSE             はんだ           3            8000     完了
12      D013    J69P  MELMB             コイル           4           11000    調査中
13      D014    310D    WSE         Buck-IC           2            7000  対策検討中
14      D015    J69P    GSE             コイル           5           13000    調査中
15      D016    310D  MELMB            コネクタ           4            5000    調査中
16      D017    J69P    WSE             はんだ           1           20000     完了
17      D018    310D    GSE         Buck-IC           3            6000    調査中

In [5]:
df_summary = df_work.groupby(
    [
        "site",
        "defect_category",
    ],
    as_index=False,
)[
    [
        "defect_qty",
        "inspection_qty",
    ]
].sum()
df_summary

     site defect_category  defect_qty  inspection_qty
0     GSE         Buck-IC           9           20000
1     GSE             はんだ           3            8000
2     GSE             コイル          28           63000
3   MELMB         Buck-IC           8           20000
4   MELMB             はんだ           2            9000
5   MELMB             コイル          12           39000
6   MELMB            コネクタ           4            5000
7     WSE         Buck-IC           7           25000
8     WSE             はんだ           1           20000
9     WSE             コイル           9           22000
10    WSE            コネクタ           1            6000

In [6]:
df_summary = df_summary.rename(
    columns={
        "defect_qty": "total_defect_qty",
        "inspection_qty": "total_inspeciton_qty",
    }
)
df_summary

     site defect_category  total_defect_qty  total_inspeciton_qty
0     GSE         Buck-IC                 9                 20000
1     GSE             はんだ                 3                  8000
2     GSE             コイル                28                 63000
3   MELMB         Buck-IC                 8                 20000
4   MELMB             はんだ                 2                  9000
5   MELMB             コイル                12                 39000
6   MELMB            コネクタ                 4                  5000
7     WSE         Buck-IC                 7                 25000
8     WSE             はんだ                 1                 20000
9     WSE             コイル                 9                 22000
10    WSE            コネクタ                 1                  6000

In [8]:
#cell6
df_summary["defect_rate"] = (
    df_summary["total_defect_qty"]
    / df_summary["total_inspeciton_qty"]
)

df_summary["defect_ppm"] = (
    df_summary["defect_rate"] * 1000000
)

df_summary

,site,defect_category,total_defect_qty,total_inspeciton_qty,defect_rate,defect_ppm
0,GSE,Buck-IC,9,20000,0.000450,450.000000
1,GSE,はんだ,3,8000,0.000375,375.000000
2,GSE,コイル,28,63000,0.000444,444.444444
3,MELMB,Buck-IC,8,20000,0.000400,400.000000
4,MELMB,はんだ,2,9000,0.000222,222.222222
5,MELMB,コイル,12,39000,0.000308,307.692308
6,MELMB,コネクタ,4,5000,0.000800,800.000000
7,WSE,Buck-IC,7,25000,0.000280,280.000000
8,WSE,はんだ,1,20000,0.000050,50.000000
9,WSE,コイル,9,22000,0.000409,409.090909
10,WSE,コネクタ,1,6000,0.000167,166.666667

In [9]:
#cell7

bins = [
    0,
    100,
    300,
    600,
    np.inf,
]

labels = [
    "良好",
    "注意",
    "要確認",
    "重大確認",
]

In [10]:
#cell8
df_summary["risk_category"] = pd.cut(
    df_summary["defect_ppm"],
    bins=bins,
    labels=labels,
    include_lowest=True,
)
df_summary

,site,defect_category,total_defect_qty,total_inspeciton_qty,defect_rate,defect_ppm,risk_category
0,GSE,Buck-IC,9,20000,0.000450,450.000000,要確認
1,GSE,はんだ,3,8000,0.000375,375.000000,要確認
2,GSE,コイル,28,63000,0.000444,444.444444,要確認
3,MELMB,Buck-IC,8,20000,0.000400,400.000000,要確認
4,MELMB,はんだ,2,9000,0.000222,222.222222,注意
5,MELMB,コイル,12,39000,0.000308,307.692308,要確認
6,MELMB,コネクタ,4,5000,0.000800,800.000000,重大確認
7,WSE,Buck-IC,7,25000,0.000280,280.000000,注意
8,WSE,はんだ,1,20000,0.000050,50.000000,良好
9,WSE,コイル,9,22000,0.000409,409.090909,要確認
10,WSE,コネクタ,1,6000,0.000167,166.666667,注意

In [11]:
df_summary["check_comment"] = "通常監視"
df_summary

,site,defect_category,total_defect_qty,total_inspeciton_qty,defect_rate,defect_ppm,risk_category,check_comment
0,GSE,Buck-IC,9,20000,0.000450,450.000000,要確認,通常監視
1,GSE,はんだ,3,8000,0.000375,375.000000,要確認,通常監視
2,GSE,コイル,28,63000,0.000444,444.444444,要確認,通常監視
3,MELMB,Buck-IC,8,20000,0.000400,400.000000,要確認,通常監視
4,MELMB,はんだ,2,9000,0.000222,222.222222,注意,通常監視
5,MELMB,コイル,12,39000,0.000308,307.692308,要確認,通常監視
6,MELMB,コネクタ,4,5000,0.000800,800.000000,重大確認,通常監視
7,WSE,Buck-IC,7,25000,0.000280,280.000000,注意,通常監視
8,WSE,はんだ,1,20000,0.000050,50.000000,良好,通常監視
9,WSE,コイル,9,22000,0.000409,409.090909,要確認,通常監視
10,WSE,コネクタ,1,6000,0.000167,166.666667,注意,通常監視

In [15]:
df_summary.loc[
    df_summary["risk_category"] == "注意",
    "check_comment",
] = "推移確認"
df_summary

df_summary.loc[
    df_summary["risk_category"] == "要確認",
    "check_comment",
] = "原因確認"

df_summary.loc[
    df_summary["risk_category"] == "重大確認",
    "check_comment",
] = "至急確認"

df_summary

,site,defect_category,total_defect_qty,total_inspeciton_qty,defect_rate,defect_ppm,risk_category,check_comment
0,GSE,Buck-IC,9,20000,0.000450,450.000000,要確認,原因確認
1,GSE,はんだ,3,8000,0.000375,375.000000,要確認,原因確認
2,GSE,コイル,28,63000,0.000444,444.444444,要確認,原因確認
3,MELMB,Buck-IC,8,20000,0.000400,400.000000,要確認,原因確認
4,MELMB,はんだ,2,9000,0.000222,222.222222,注意,推移確認
5,MELMB,コイル,12,39000,0.000308,307.692308,要確認,原因確認
6,MELMB,コネクタ,4,5000,0.000800,800.000000,重大確認,至急確認
7,WSE,Buck-IC,7,25000,0.000280,280.000000,注意,推移確認
8,WSE,はんだ,1,20000,0.000050,50.000000,良好,通常監視
9,WSE,コイル,9,22000,0.000409,409.090909,要確認,原因確認
10,WSE,コネクタ,1,6000,0.000167,166.666667,注意,推移確認

In [16]:
df_need_check = df_summary[
    df_summary["risk_category"].isin(
        [
            "要確認",
            "重大確認"
        ]
    )
].copy()
df_need_check

,site,defect_category,total_defect_qty,total_inspeciton_qty,defect_rate,defect_ppm,risk_category,check_comment
0,GSE,Buck-IC,9,20000,0.000450,450.000000,要確認,原因確認
1,GSE,はんだ,3,8000,0.000375,375.000000,要確認,原因確認
2,GSE,コイル,28,63000,0.000444,444.444444,要確認,原因確認
3,MELMB,Buck-IC,8,20000,0.000400,400.000000,要確認,原因確認
5,MELMB,コイル,12,39000,0.000308,307.692308,要確認,原因確認
6,MELMB,コネクタ,4,5000,0.000800,800.000000,重大確認,至急確認
9,WSE,コイル,9,22000,0.000409,409.090909,要確認,原因確認

In [18]:
df_risk_count = df_summary["risk_category"].value_counts(
    sort=False
).reset_index()
df_risk_count

df_risk_count.columns = [
    "risk_category",
    "count",
]

df_risk_count

  risk_category  count
0            良好      1
1            注意      3
2           要確認      6
3          重大確認      1

In [19]:
df_report = df_summary.sort_values(
    [
        "risk_category",
        "defect_ppm",
    ],
    ascending=[
        True,
        False,
    ],
)
df_report

,site,defect_category,total_defect_qty,total_inspeciton_qty,defect_rate,defect_ppm,risk_category,check_comment
8,WSE,はんだ,1,20000,0.000050,50.000000,良好,通常監視
7,WSE,Buck-IC,7,25000,0.000280,280.000000,注意,推移確認
4,MELMB,はんだ,2,9000,0.000222,222.222222,注意,推移確認
10,WSE,コネクタ,1,6000,0.000167,166.666667,注意,推移確認
0,GSE,Buck-IC,9,20000,0.000450,450.000000,要確認,原因確認
2,GSE,コイル,28,63000,0.000444,444.444444,要確認,原因確認
9,WSE,コイル,9,22000,0.000409,409.090909,要確認,原因確認
3,MELMB,Buck-IC,8,20000,0.000400,400.000000,要確認,原因確認
1,GSE,はんだ,3,8000,0.000375,375.000000,要確認,原因確認
5,MELMB,コイル,12,39000,0.000308,307.692308,要確認,原因確認
6,MELMB,コネクタ,4,5000,0.000800,800.000000,重大確認,至急確認