In [1]:
import pandas as pd
df_log = pd.read_csv("dataset/product_log.csv")
df_log["Month"] = df_log["Date"].str[5:7].astype(int)
df_log.head()

         Date  Num Product  Month
0  2017-01-03  1.0       B      1
1  2017-01-06  2.0       B      1
2  2017-01-07  1.0       A      1
3  2017-01-11  2.0       A      1
4  2017-01-12  2.0       B      1

In [2]:
df_log_pivot = df_log.pivot_table(
    values="Num",
    index="Product",
    columns="Month",
    aggfunc="sum"
)
df_log_pivot

Month       1     2     3
Product
A         8.0  18.0  40.0
B        17.0  17.0  29.0

In [3]:
df_log.pivot_table(
    "Num",
    "Product",
    "Month",
    aggfunc="count"
)

Month    1  2  3
Product
A        4  5  8
B        8  5  6

In [4]:
df_log.pivot_table(
    values="Num",
    index="Product",
    columns="Month"
)

Month        1    2         3
Product
A        2.000  3.6  5.000000
B        2.125  3.4  4.833333

In [5]:
df_log.pivot_table(
    values="Num",
    index="Product",
    columns="Month",
    aggfunc="mean"
)

Month        1    2         3
Product
A        2.000  3.6  5.000000
B        2.125  3.4  4.833333

In [7]:
import pandas as pd
df_log = pd.read_csv("dataset/product_log.csv")
df_log["Month"] = df_log["Date"].str[5:7].astype(int)
df_log.head()

         Date  Num Product  Month
0  2017-01-03  1.0       B      1
1  2017-01-06  2.0       B      1
2  2017-01-07  1.0       A      1
3  2017-01-11  2.0       A      1
4  2017-01-12  2.0       B      1

In [9]:
df_log.pivot_table(
    values="Num",
    index="Product",
    columns="Month",
    aggfunc="sum"
)

Month       1     2     3
Product
A         8.0  18.0  40.0
B        17.0  17.0  29.0

In [10]:
df_log.pivot_table(
    values="Num",
    index="Product",
    columns="Month",
    aggfunc="count"
)

Month    1  2  3
Product
A        4  5  8
B        8  5  6

In [11]:
df_log.pivot_table(
    values="Num",
    index="Product",
    columns="Month",
    aggfunc="mean"
)

Month        1    2         3
Product
A        2.000  3.6  5.000000
B        2.125  3.4  4.833333

In [12]:
df_log.pivot_table(
    values="Num",
    index="Month",
    columns="Product",
    aggfunc="sum"
)

Product     A     B
Month
1         8.0  17.0
2        18.0  17.0
3        40.0  29.0

In [13]:
df_log.pivot_table(
    values="Num",
    index="Month",
    aggfunc="sum"
)

        Num
Month
1      25.0
2      35.0
3      69.0

In [14]:
df_log.pivot_table(
    values="Num",
    index="Product",
    columns="Month",
    aggfunc="max"
)

Month      1    2    3
Product
A        3.0  4.0  6.0
B        3.0  4.0  6.0

In [15]:
df_log.pivot_table(
    values="Num",
    index="Product",
    columns="Month",
    aggfunc="min"
)

Month      1    2    3
Product
A        1.0  2.0  4.0
B        1.0  3.0  4.0