In [1]:
import pandas as pd

df_log = pd.read_csv("dataset/product_log.csv")
df_log.head()

         Date  Num Product
0  2017-01-03  1.0       B
1  2017-01-06  2.0       B
2  2017-01-07  1.0       A
3  2017-01-11  2.0       A
4  2017-01-12  2.0       B

In [2]:
df_log_date_str57 = df_log["Date"].str[5:7]
df_log_date_str57.head()

0    01
1    01
2    01
3    01
4    01
Name: Date, dtype: object

In [4]:
df_log_date_str57_int = df_log_date_str57.astype(int)
df_log_date_str57_int.head()

0    1
1    1
2    1
3    1
4    1
Name: Date, dtype: int64

In [6]:
df_log["Month"] = df_log_date_str57_int
df_log.head()

         Date  Num Product  Month
0  2017-01-03  1.0       B      1
1  2017-01-06  2.0       B      1
2  2017-01-07  1.0       A      1
3  2017-01-11  2.0       A      1
4  2017-01-12  2.0       B      1

In [7]:
df_log = pd.read_csv("dataset/product_log.csv")

In [8]:
df_log

          Date  Num Product
0   2017-01-03  1.0       B
1   2017-01-06  2.0       B
2   2017-01-07  1.0       A
3   2017-01-11  2.0       A
4   2017-01-12  2.0       B
5   2017-01-13  3.0       B
6   2017-01-15  2.0       B
7   2017-01-18  3.0       B
8   2017-01-20  2.0       B
9   2017-01-21  2.0       A
10  2017-01-29  3.0       A
11  2017-01-30  2.0       B
12  2017-02-01  4.0       A
13  2017-02-02  3.0       B
14  2017-02-03  3.0       B
15  2017-02-05  2.0       A
16  2017-02-08  NaN       A
17  2017-02-12  3.0       B
18  2017-02-14  4.0       A
19  2017-02-16  NaN       A
20  2017-02-18  NaN       A
21  2017-02-20  4.0       B
22  2017-02-23  4.0       A
23  2017-02-24  NaN       A
24  2017-02-26  4.0       B
25  2017-02-28  4.0       A
26  2017-03-01  4.0       A
27  2017-03-04  5.0       A
28  2017-03-08  4.0       B
29  2017-03-09  5.0       A
30  2017-03-11  5.0       A
31  2017-03-16  4.0       A
32  2017-03-17  6.0       B
33  2017-03-18  5.0       B
34  2017-03-20  6.0       B
35  2017-03-21  4.0       B
36  2017-03-22  4.0       B
37  2017-03-24  6.0       A
38  2017-03-27  6.0       A
39  2017-03-28  5.0       A

In [9]:
df_log_date_str57 = df_log["Date"].str[5:7]

In [10]:
df_log_date_str57

0     01
1     01
2     01
3     01
4     01
5     01
6     01
7     01
8     01
9     01
10    01
11    01
12    02
13    02
14    02
15    02
16    02
17    02
18    02
19    02
20    02
21    02
22    02
23    02
24    02
25    02
26    03
27    03
28    03
29    03
30    03
31    03
32    03
33    03
34    03
35    03
36    03
37    03
38    03
39    03
Name: Date, dtype: object

In [11]:
df_log_date_str57_int = df_log_date_str57.astype(int)

In [12]:
df_log_date_str57

0     01
1     01
2     01
3     01
4     01
5     01
6     01
7     01
8     01
9     01
10    01
11    01
12    02
13    02
14    02
15    02
16    02
17    02
18    02
19    02
20    02
21    02
22    02
23    02
24    02
25    02
26    03
27    03
28    03
29    03
30    03
31    03
32    03
33    03
34    03
35    03
36    03
37    03
38    03
39    03
Name: Date, dtype: object

In [13]:
df_log["Month"] = df_log_date_str57_int

In [14]:
df_log.head()

         Date  Num Product  Month
0  2017-01-03  1.0       B      1
1  2017-01-06  2.0       B      1
2  2017-01-07  1.0       A      1
3  2017-01-11  2.0       A      1
4  2017-01-12  2.0       B      1

In [15]:
import pandas as pd

df_log = pd.read_csv("dataset/product_log.csv")

df_log["Day"] = df_log["Date"].str[8:10].astype(int)

In [16]:
df_log["Year"] = df_log["Date"].str[0:4].astype(int)

In [18]:
df_log.head()

         Date  Num Product  Day  Year
0  2017-01-03  1.0       B    3  2017
1  2017-01-06  2.0       B    6  2017
2  2017-01-07  1.0       A    7  2017
3  2017-01-11  2.0       A   11  2017
4  2017-01-12  2.0       B   12  2017