###### 129_4_quality_drop_duplicates_practice

In [1]:
#cell1 
import pandas as pd

In [2]:
df = pd.DataFrame(
    [
         ["D001", "J69P", "MELMB", "コイル", 1, "2026-06-01 09:00"],
        ["D002", "J69P", "WSE", "Buck-IC", 0, "2026-06-01 09:10"],
        ["D003", "310D", "GSE", "はんだ", 1, "2026-06-01 09:20"],
        ["D004", "J69P", "MELMB", "コイル", 3, "2026-06-01 09:30"],
        ["D002", "J69P", "WSE", "Buck-IC", 2, "2026-06-01 10:00"],
        ["D005", "310D", "WSE", "NTF", 0, "2026-06-01 10:10"],
        ["D006", "J69P", "GSE", "コイル", 2, "2026-06-01 10:20"],
        ["D004", "J69P", "MELMB", "コイル", 4, "2026-06-01 10:30"],
        ["D007", "310D", "MELMB", "はんだ", 1, "2026-06-01 10:40"],
    ],
    columns=[
        "defect_id",
        "project",
        "site",
        "defect_category",
        "defect_qty",
        "update_time",
    ],
)

df

  defect_id project   site defect_category  defect_qty       update_time
0      D001    J69P  MELMB             コイル           1  2026-06-01 09:00
1      D002    J69P    WSE         Buck-IC           0  2026-06-01 09:10
2      D003    310D    GSE             はんだ           1  2026-06-01 09:20
3      D004    J69P  MELMB             コイル           3  2026-06-01 09:30
4      D002    J69P    WSE         Buck-IC           2  2026-06-01 10:00
5      D005    310D    WSE             NTF           0  2026-06-01 10:10
6      D006    J69P    GSE             コイル           2  2026-06-01 10:20
7      D004    J69P  MELMB             コイル           4  2026-06-01 10:30
8      D007    310D  MELMB             はんだ           1  2026-06-01 10:40

In [3]:
df_work = df.copy()
df_work

  defect_id project   site defect_category  defect_qty       update_time
0      D001    J69P  MELMB             コイル           1  2026-06-01 09:00
1      D002    J69P    WSE         Buck-IC           0  2026-06-01 09:10
2      D003    310D    GSE             はんだ           1  2026-06-01 09:20
3      D004    J69P  MELMB             コイル           3  2026-06-01 09:30
4      D002    J69P    WSE         Buck-IC           2  2026-06-01 10:00
5      D005    310D    WSE             NTF           0  2026-06-01 10:10
6      D006    J69P    GSE             コイル           2  2026-06-01 10:20
7      D004    J69P  MELMB             コイル           4  2026-06-01 10:30
8      D007    310D  MELMB             はんだ           1  2026-06-01 10:40

In [4]:
df_work["update_time"] = pd.to_datetime(
    df_work["update_time"]
)

df_work

  defect_id project   site defect_category  defect_qty         update_time
0      D001    J69P  MELMB             コイル           1 2026-06-01 09:00:00
1      D002    J69P    WSE         Buck-IC           0 2026-06-01 09:10:00
2      D003    310D    GSE             はんだ           1 2026-06-01 09:20:00
3      D004    J69P  MELMB             コイル           3 2026-06-01 09:30:00
4      D002    J69P    WSE         Buck-IC           2 2026-06-01 10:00:00
5      D005    310D    WSE             NTF           0 2026-06-01 10:10:00
6      D006    J69P    GSE             コイル           2 2026-06-01 10:20:00
7      D004    J69P  MELMB             コイル           4 2026-06-01 10:30:00
8      D007    310D  MELMB             はんだ           1 2026-06-01 10:40:00

In [6]:
df_duplicate_check = df_work[
    df_work.duplicated(
        "defect_id",
        keep=False,
    )
].copy()
df_duplicate_check

  defect_id project   site defect_category  defect_qty         update_time
1      D002    J69P    WSE         Buck-IC           0 2026-06-01 09:10:00
3      D004    J69P  MELMB             コイル           3 2026-06-01 09:30:00
4      D002    J69P    WSE         Buck-IC           2 2026-06-01 10:00:00
7      D004    J69P  MELMB             コイル           4 2026-06-01 10:30:00

In [7]:
df_sort = df_work.sort_values(
    "update_time"
)
df_sort

  defect_id project   site defect_category  defect_qty         update_time
0      D001    J69P  MELMB             コイル           1 2026-06-01 09:00:00
1      D002    J69P    WSE         Buck-IC           0 2026-06-01 09:10:00
2      D003    310D    GSE             はんだ           1 2026-06-01 09:20:00
3      D004    J69P  MELMB             コイル           3 2026-06-01 09:30:00
4      D002    J69P    WSE         Buck-IC           2 2026-06-01 10:00:00
5      D005    310D    WSE             NTF           0 2026-06-01 10:10:00
6      D006    J69P    GSE             コイル           2 2026-06-01 10:20:00
7      D004    J69P  MELMB             コイル           4 2026-06-01 10:30:00
8      D007    310D  MELMB             はんだ           1 2026-06-01 10:40:00

In [8]:
df_result = df_sort.drop_duplicates(
    "defect_id",
    keep="last",
)
df_result

  defect_id project   site defect_category  defect_qty         update_time
0      D001    J69P  MELMB             コイル           1 2026-06-01 09:00:00
2      D003    310D    GSE             はんだ           1 2026-06-01 09:20:00
4      D002    J69P    WSE         Buck-IC           2 2026-06-01 10:00:00
5      D005    310D    WSE             NTF           0 2026-06-01 10:10:00
6      D006    J69P    GSE             コイル           2 2026-06-01 10:20:00
7      D004    J69P  MELMB             コイル           4 2026-06-01 10:30:00
8      D007    310D  MELMB             はんだ           1 2026-06-01 10:40:00

In [9]:
df_site_total = df_result.pivot_table(
    values="defect_qty",
    index="site",
    aggfunc="sum",
)
df_site_total

       defect_qty
site
GSE             3
MELMB           6
WSE             2

In [11]:
df_site_total_sort = df_site_total.sort_values(
    "defect_qty",
    ascending=False,
)

df_site_total_sort

       defect_qty
site
MELMB           6
GSE             3
WSE             2