In [1]:
import pandas as pd

df = pd.read_csv("earnings_sample.csv", index_col="日付", parse_dates=["日付"])
df

            支店名  売上（万円）
日付
2022-02-01  A支店    21.6
2022-02-01  B支店    33.9
2022-02-02  A支店    25.2
2022-02-02  B支店    39.0
2022-02-03  A支店    19.9
2022-02-03  B支店    35.1
2022-02-04  A支店    22.5
2022-02-04  B支店    41.0
2022-02-05  A支店    18.0
2022-02-05  B支店    36.2
2022-02-06  A支店    24.0
2022-02-06  B支店    38.3

In [2]:
df.resample("W")["売上（万円）"].sum()

日付
2022-02-06    354.7
Freq: W-SUN, Name: 売上（万円）, dtype: float64

In [3]:
df["売上（万円)_ビン分割"] = pd.cut(
    df["売上（万円）"],
    [0, 10, 20, 30, 40, 50],
    right=False,
)
df

            支店名  売上（万円） 売上（万円)_ビン分割
日付
2022-02-01  A支店    21.6    [20, 30)
2022-02-01  B支店    33.9    [30, 40)
2022-02-02  A支店    25.2    [20, 30)
2022-02-02  B支店    39.0    [30, 40)
2022-02-03  A支店    19.9    [10, 20)
2022-02-03  B支店    35.1    [30, 40)
2022-02-04  A支店    22.5    [20, 30)
2022-02-04  B支店    41.0    [40, 50)
2022-02-05  A支店    18.0    [10, 20)
2022-02-05  B支店    36.2    [30, 40)
2022-02-06  A支店    24.0    [20, 30)
2022-02-06  B支店    38.3    [30, 40)

In [4]:
df.groupby("支店名")["売上（万円）"].sum()

支店名
A支店    131.2
B支店    223.5
Name: 売上（万円）, dtype: float64

In [5]:
df.groupby(["支店名", "売上（万円)_ビン分割"], observed=False).size()

支店名  売上（万円)_ビン分割
A支店  [0, 10)        0
     [10, 20)       2
     [20, 30)       4
     [30, 40)       0
     [40, 50)       0
B支店  [0, 10)        0
     [10, 20)       0
     [20, 30)       0
     [30, 40)       5
     [40, 50)       1
dtype: int64

In [7]:
df.groupby(["支店名", "売上（万円)_ビン分割"], observed=False)["売上（万円）"].mean()

支店名  売上（万円)_ビン分割
A支店  [0, 10)           NaN
     [10, 20)       18.950
     [20, 30)       23.325
     [30, 40)          NaN
     [40, 50)          NaN
B支店  [0, 10)           NaN
     [10, 20)          NaN
     [20, 30)          NaN
     [30, 40)       36.500
     [40, 50)       41.000
Name: 売上（万円）, dtype: float64

In [8]:
df[df["支店名"]== "B支店"].groupby("売上（万円)_ビン分割", observed=False).size()

売上（万円)_ビン分割
[0, 10)     0
[10, 20)    0
[20, 30)    0
[30, 40)    5
[40, 50)    1
dtype: int64