###### 126-3: 列ごとに昇順／降順を変えて確認するには

In [1]:
import numpy as np
import pandas as pd

df = pd.DataFrame(
    [
        ["Alice", "国語", 87],
        ["Alice", "数学", np.nan],
        ["Bob", "国語", 65],
        ["Bob", "数学", 92],
    ],
    columns=["Name", "Subject", "Point"],
)

df.sort_values(["Name", "Point"], ascending=[True, False])

    Name Subject  Point
0  Alice      国語   87.0
1  Alice      数学    NaN
3    Bob      数学   92.0
2    Bob      国語   65.0

In [2]:
import pandas as pd
import numpy as np

df_quality = pd.DataFrame(
    [
        ["melmb", "lamp-a", 12000, 18],
        ["melmb", "lamp-b", 8500, 4],
        ["wse", "lamp-c", 10000, 25],
        ["wse", "lamp-d", 6000, 2],
        ["gse", "lamp-e", 7000, np.nan],
    ],
    columns=["site", "product", "production", "defects"],
)

df_quality["ppm"] = df_quality["defects"] / df_quality["production"] * 1000000
df_quality["ppm"] = df_quality["ppm"].round(1)

df_quality

    site product  production  defects     ppm
0  melmb  lamp-a       12000     18.0  1500.0
1  melmb  lamp-b        8500      4.0   470.6
2    wse  lamp-c       10000     25.0  2500.0
3    wse  lamp-d        6000      2.0   333.3
4    gse  lamp-e        7000      NaN     NaN

In [3]:
df_quality.sort_values(["site", "ppm"], ascending=[True, False])

    site product  production  defects     ppm
4    gse  lamp-e        7000      NaN     NaN
0  melmb  lamp-a       12000     18.0  1500.0
1  melmb  lamp-b        8500      4.0   470.6
2    wse  lamp-c       10000     25.0  2500.0
3    wse  lamp-d        6000      2.0   333.3

In [4]:
df_quality.sort_values(["site", "defects"], ascending=[True, False])

    site product  production  defects     ppm
4    gse  lamp-e        7000      NaN     NaN
0  melmb  lamp-a       12000     18.0  1500.0
1  melmb  lamp-b        8500      4.0   470.6
2    wse  lamp-c       10000     25.0  2500.0
3    wse  lamp-d        6000      2.0   333.3