###### 126-3: 列ごとに昇順／降順を変えて確認するには

In [16]:
import numpy as np
import pandas as pd

df = pd.DataFrame(
    [
        ["Alice", "国語", 87],
        ["Alice", "数学", np.nan],
        ["Bob", "国語", 65],
        ["Bob", "数学", 92],
    ],
    columns=["Name", "Subject", "Point"],
)

df.sort_values(["Name", "Point"], ascending=[True, False])

    Name Subject  Point
0  Alice      国語   87.0
1  Alice      数学    NaN
3    Bob      数学   92.0
2    Bob      国語   65.0

In [17]:
import pandas as pd
import numpy as np

df_quality = pd.DataFrame(
    [
        ["melmb", "lamp-a", 12000, 18],
        ["melmb", "lamp-b", 8500, 4],
        ["wse", "lamp-c", 10000, 25],
        ["wse", "lamp-d", 6000, 2],
        ["gse", "lamp-e", 7000, np.nan],
    ],
    columns=["site", "product", "production", "defects"],
)

df_quality["ppm"] = df_quality["defects"] / df_quality["production"] * 1000000
df_quality["ppm"] = df_quality["ppm"].round(1)

df_quality

    site product  production  defects     ppm
0  melmb  lamp-a       12000     18.0  1500.0
1  melmb  lamp-b        8500      4.0   470.6
2    wse  lamp-c       10000     25.0  2500.0
3    wse  lamp-d        6000      2.0   333.3
4    gse  lamp-e        7000      NaN     NaN

In [18]:
df_quality.sort_values(["site", "ppm"], ascending=[True, False])

    site product  production  defects     ppm
4    gse  lamp-e        7000      NaN     NaN
0  melmb  lamp-a       12000     18.0  1500.0
1  melmb  lamp-b        8500      4.0   470.6
2    wse  lamp-c       10000     25.0  2500.0
3    wse  lamp-d        6000      2.0   333.3

In [19]:
df_quality.sort_values(["site", "defects"], ascending=[True, False])

    site product  production  defects     ppm
4    gse  lamp-e        7000      NaN     NaN
0  melmb  lamp-a       12000     18.0  1500.0
1  melmb  lamp-b        8500      4.0   470.6
2    wse  lamp-c       10000     25.0  2500.0
3    wse  lamp-d        6000      2.0   333.3

###### 実務寄りの練習問題

In [20]:
import pandas as pd
import numpy as np

df_quality = pd.DataFrame(
    [
        ["2026-06-01", "MELMB", "Lamp-A", "点灯不良", 12000, 18],
        ["2026-06-01", "MELMB", "Lamp-B", "外観キズ", 8500, 4],
        ["2026-06-02", "WSE", "Lamp-C", "寸法NG", 10000, 25],
        ["2026-06-02", "WSE", "Lamp-D", "異物混入", 6000, 2],
        ["2026-06-03", "GSE", "Lamp-E", "はんだ不良", 7000, 16],
        ["2026-06-03", "GSE", "Lamp-F", "点灯不良", 9000, np.nan],
        ["2026-06-04", "ISE", "Lamp-G", "外観キズ", 11000, 6],
        ["2026-06-04", "ISE", "Lamp-H", "寸法NG", 5000, 9],
    ],
    columns=["date", "site", "product", "defect_type", "production", "defects"],
)

df_quality["ppm"] = df_quality["defects"] / df_quality["production"] * 1000000
df_quality["ppm"] = df_quality["ppm"].round(1)
print(df_quality)

df_sorted = df_quality.sort_values(
    ["site", "ppm"],
    ascending=[True, False]
)
print("----- df_sorted -----")
print(df_sorted)

df_sorted_defects = df_quality.sort_values(
    ["site", "defects"],
    ascending=[True, False]
)
print("----- df_sorted_defects -----")
print(df_sorted_defects)

         date   site product defect_type  production  defects     ppm
0  2026-06-01  MELMB  Lamp-A        点灯不良       12000     18.0  1500.0
1  2026-06-01  MELMB  Lamp-B        外観キズ        8500      4.0   470.6
2  2026-06-02    WSE  Lamp-C        寸法NG       10000     25.0  2500.0
3  2026-06-02    WSE  Lamp-D        異物混入        6000      2.0   333.3
4  2026-06-03    GSE  Lamp-E       はんだ不良        7000     16.0  2285.7
5  2026-06-03    GSE  Lamp-F        点灯不良        9000      NaN     NaN
6  2026-06-04    ISE  Lamp-G        外観キズ       11000      6.0   545.5
7  2026-06-04    ISE  Lamp-H        寸法NG        5000      9.0  1800.0
----- df_sorted -----
         date   site product defect_type  production  defects     ppm
4  2026-06-03    GSE  Lamp-E       はんだ不良        7000     16.0  2285.7
5  2026-06-03    GSE  Lamp-F        点灯不良        9000      NaN     NaN
7  2026-06-04    ISE  Lamp-H        寸法NG        5000      9.0  1800.0
6  2026-06-04    ISE  Lamp-G        外観キズ       11000      6.0   545.5
0  2026-06-01  MELMB  Lamp-A        点灯不良       12000     18.0  1500.0
1  2026-06-01  MELMB  Lamp-B        外観キズ        8500      4.0   470.6
2  2026-06-02    WSE  Lamp-C        寸法NG       10000     25.0  2500.0
3  2026-06-02    WSE  Lamp-D        異物混入        6000      2.0   333.3
----- df_sorted_defects -----
         date   site product defect_type  production  defects     ppm
4  2026-06-03    GSE  Lamp-E       はんだ不良        7000     16.0  2285.7
5  2026-06-03    GSE  Lamp-F        点灯不良        9000      NaN     NaN
7  2026-06-04    ISE  Lamp-H        寸法NG        5000      9.0  1800.0
6  2026-06-04    ISE  Lamp-G        外観キズ       11000      6.0   545.5
0  2026-06-01  MELMB  Lamp-A        点灯不良       12000     18.0  1500.0
1  2026-06-01  MELMB  Lamp-B        外観キズ        8500      4.0   470.6
2  2026-06-02    WSE  Lamp-C        寸法NG       10000     25.0  2500.0
3  2026-06-02    WSE  Lamp-D        異物混入        6000      2.0   333.3

In [21]:
# 危険ランク追加
df_sorted["危険ランク"] = np.where(
    df_sorted["ppm"] >= 2000,
    "s級",
    np.where(
        df_sorted["ppm"] >= 1000,
        "a級",
        "通常"
     )
)
print("----- 危険ランク追加 -----")
print(df_sorted)

----- 危険ランク追加 -----
         date   site product defect_type  production  defects     ppm 危険ランク
4  2026-06-03    GSE  Lamp-E       はんだ不良        7000     16.0  2285.7    s級
5  2026-06-03    GSE  Lamp-F        点灯不良        9000      NaN     NaN    通常
7  2026-06-04    ISE  Lamp-H        寸法NG        5000      9.0  1800.0    a級
6  2026-06-04    ISE  Lamp-G        外観キズ       11000      6.0   545.5    通常
0  2026-06-01  MELMB  Lamp-A        点灯不良       12000     18.0  1500.0    a級
1  2026-06-01  MELMB  Lamp-B        外観キズ        8500      4.0   470.6    通常
2  2026-06-02    WSE  Lamp-C        寸法NG       10000     25.0  2500.0    s級
3  2026-06-02    WSE  Lamp-D        異物混入        6000      2.0   333.3    通常