###### 実務演習応用版

In [1]:
import pandas as pd
import numpy as np
from pathlib import Path
import os

Path("output").mkdir(exist_ok=True)

In [7]:
df_quality = pd.DataFrame(
    [
        ["2026-05-01", "MELMB", "Lamp-A", "点灯不良", 12000, 18],
        ["2026-05-03", "MELMB", "Lamp-B", "外観キズ", 8500, 4],
        ["2026-06-01", "MELMB", "Lamp-A", "点灯不良", 11000, 30],
        ["2026-06-04", "MELMB", "Lamp-C", "寸法NG", 9000, 8],

        ["2026-05-02", "WSE", "Lamp-D", "異物混入", 10000, 25],
        ["2026-05-05", "WSE", "Lamp-E", "はんだ不良", 7000, 5],
        ["2026-06-02", "WSE", "Lamp-D", "異物混入", 9500, 10],
        ["2026-06-06", "WSE", "Lamp-F", "点灯不良", 6000, 18],

        ["2026-05-04", "GSE", "Lamp-G", "外観キズ", 8000, 2],
        ["2026-05-08", "GSE", "Lamp-H", "寸法NG", 5000, 11],
        ["2026-06-03", "GSE", "Lamp-G", "外観キズ", 9000, np.nan],
        ["2026-06-07", "GSE", "Lamp-H", "寸法NG", 5200, 3],
    ],
    columns=["date", "site", "product", "defect_type", "production", "defects"],
)

print(df_quality)
df_quality["date"].dtype

          date   site product defect_type  production  defects
0   2026-05-01  MELMB  Lamp-A        点灯不良       12000     18.0
1   2026-05-03  MELMB  Lamp-B        外観キズ        8500      4.0
2   2026-06-01  MELMB  Lamp-A        点灯不良       11000     30.0
3   2026-06-04  MELMB  Lamp-C        寸法NG        9000      8.0
4   2026-05-02    WSE  Lamp-D        異物混入       10000     25.0
5   2026-05-05    WSE  Lamp-E       はんだ不良        7000      5.0
6   2026-06-02    WSE  Lamp-D        異物混入        9500     10.0
7   2026-06-06    WSE  Lamp-F        点灯不良        6000     18.0
8   2026-05-04    GSE  Lamp-G        外観キズ        8000      2.0
9   2026-05-08    GSE  Lamp-H        寸法NG        5000     11.0
10  2026-06-03    GSE  Lamp-G        外観キズ        9000      NaN
11  2026-06-07    GSE  Lamp-H        寸法NG        5200      3.0

dtype('O')

In [8]:
#date列を日付型に変換
df_quality["date"] = pd.to_datetime(df_quality["date"])
print(df_quality)
df_quality["date"].dtype

         date   site product defect_type  production  defects
0  2026-05-01  MELMB  Lamp-A        点灯不良       12000     18.0
1  2026-05-03  MELMB  Lamp-B        外観キズ        8500      4.0
2  2026-06-01  MELMB  Lamp-A        点灯不良       11000     30.0
3  2026-06-04  MELMB  Lamp-C        寸法NG        9000      8.0
4  2026-05-02    WSE  Lamp-D        異物混入       10000     25.0
5  2026-05-05    WSE  Lamp-E       はんだ不良        7000      5.0
6  2026-06-02    WSE  Lamp-D        異物混入        9500     10.0
7  2026-06-06    WSE  Lamp-F        点灯不良        6000     18.0
8  2026-05-04    GSE  Lamp-G        外観キズ        8000      2.0
9  2026-05-08    GSE  Lamp-H        寸法NG        5000     11.0
10 2026-06-03    GSE  Lamp-G        外観キズ        9000      NaN
11 2026-06-07    GSE  Lamp-H        寸法NG        5200      3.0

dtype('<M8[ns]')

In [10]:
#month列を作成
df_quality["month"] = df_quality["date"].dt.strftime("%Y-%m")
print(df_quality)

         date   site product defect_type  production  defects    month
0  2026-05-01  MELMB  Lamp-A        点灯不良       12000     18.0  2026-05
1  2026-05-03  MELMB  Lamp-B        外観キズ        8500      4.0  2026-05
2  2026-06-01  MELMB  Lamp-A        点灯不良       11000     30.0  2026-06
3  2026-06-04  MELMB  Lamp-C        寸法NG        9000      8.0  2026-06
4  2026-05-02    WSE  Lamp-D        異物混入       10000     25.0  2026-05
5  2026-05-05    WSE  Lamp-E       はんだ不良        7000      5.0  2026-05
6  2026-06-02    WSE  Lamp-D        異物混入        9500     10.0  2026-06
7  2026-06-06    WSE  Lamp-F        点灯不良        6000     18.0  2026-06
8  2026-05-04    GSE  Lamp-G        外観キズ        8000      2.0  2026-05
9  2026-05-08    GSE  Lamp-H        寸法NG        5000     11.0  2026-05
10 2026-06-03    GSE  Lamp-G        外観キズ        9000      NaN  2026-06
11 2026-06-07    GSE  Lamp-H        寸法NG        5200      3.0  2026-06

In [13]:
df_quality["ppm"] = df_quality["defects"] / df_quality["production"] * 1000000
df_quality["ppm"] = df_quality["ppm"].round(1)

print(df_quality)

         date   site product defect_type  production  defects    month     ppm
0  2026-05-01  MELMB  Lamp-A        点灯不良       12000     18.0  2026-05  1500.0
1  2026-05-03  MELMB  Lamp-B        外観キズ        8500      4.0  2026-05   470.6
2  2026-06-01  MELMB  Lamp-A        点灯不良       11000     30.0  2026-06  2727.3
3  2026-06-04  MELMB  Lamp-C        寸法NG        9000      8.0  2026-06   888.9
4  2026-05-02    WSE  Lamp-D        異物混入       10000     25.0  2026-05  2500.0
5  2026-05-05    WSE  Lamp-E       はんだ不良        7000      5.0  2026-05   714.3
6  2026-06-02    WSE  Lamp-D        異物混入        9500     10.0  2026-06  1052.6
7  2026-06-06    WSE  Lamp-F        点灯不良        6000     18.0  2026-06  3000.0
8  2026-05-04    GSE  Lamp-G        外観キズ        8000      2.0  2026-05   250.0
9  2026-05-08    GSE  Lamp-H        寸法NG        5000     11.0  2026-05  2200.0
10 2026-06-03    GSE  Lamp-G        外観キズ        9000      NaN  2026-06     NaN
11 2026-06-07    GSE  Lamp-H        寸法NG        5200      3.0  2026-06   576.9

In [ ]:
#6危険ランクを付ける
df_quality["危険ランク"] = np.where(
    df_quality["ppm"] >= 2000,
    "s級",
    np.where(
        df_quality["ppm"] >= 1000,
        "a級",
        "通常"
    )
)
df_quality

,date,site,product,defect_type,production,defects,month,ppm,危険ランク
0,2026-05-01,MELMB,Lamp-A,点灯不良,12000,18.0,2026-05,1500.0,a級
1,2026-05-03,MELMB,Lamp-B,外観キズ,8500,4.0,2026-05,470.6,通常
2,2026-06-01,MELMB,Lamp-A,点灯不良,11000,30.0,2026-06,2727.3,s級
3,2026-06-04,MELMB,Lamp-C,寸法NG,9000,8.0,2026-06,888.9,通常
4,2026-05-02,WSE,Lamp-D,異物混入,10000,25.0,2026-05,2500.0,s級
5,2026-05-05,WSE,Lamp-E,はんだ不良,7000,5.0,2026-05,714.3,通常
6,2026-06-02,WSE,Lamp-D,異物混入,9500,10.0,2026-06,1052.6,a級
7,2026-06-06,WSE,Lamp-F,点灯不良,6000,18.0,2026-06,3000.0,s級
8,2026-05-04,GSE,Lamp-G,外観キズ,8000,2.0,2026-05,250.0,通常
9,2026-05-08,GSE,Lamp-H,寸法NG,5000,11.0,2026-05,2200.0,s級
10,2026-06-03,GSE,Lamp-G,外観キズ,9000,NaN,2026-06,NaN,通常
11,2026-06-07,GSE,Lamp-H,寸法NG,5200,3.0,2026-06,576.9,通常

In [18]:
#7：site・month・PPMで並び替え
df_sorted = df_quality.sort_values(
    ["site", "month", "ppm"],
    ascending=[True, True, False]
)

df_sorted

,date,site,product,defect_type,production,defects,month,ppm,危険ランク
9,2026-05-08,GSE,Lamp-H,寸法NG,5000,11.0,2026-05,2200.0,s級
8,2026-05-04,GSE,Lamp-G,外観キズ,8000,2.0,2026-05,250.0,通常
11,2026-06-07,GSE,Lamp-H,寸法NG,5200,3.0,2026-06,576.9,通常
10,2026-06-03,GSE,Lamp-G,外観キズ,9000,NaN,2026-06,NaN,通常
0,2026-05-01,MELMB,Lamp-A,点灯不良,12000,18.0,2026-05,1500.0,a級
1,2026-05-03,MELMB,Lamp-B,外観キズ,8500,4.0,2026-05,470.6,通常
2,2026-06-01,MELMB,Lamp-A,点灯不良,11000,30.0,2026-06,2727.3,s級
3,2026-06-04,MELMB,Lamp-C,寸法NG,9000,8.0,2026-06,888.9,通常
4,2026-05-02,WSE,Lamp-D,異物混入,10000,25.0,2026-05,2500.0,s級
5,2026-05-05,WSE,Lamp-E,はんだ不良,7000,5.0,2026-05,714.3,通常
7,2026-06-06,WSE,Lamp-F,点灯不良,6000,18.0,2026-06,3000.0,s級
6,2026-06-02,WSE,Lamp-D,異物混入,9500,10.0,2026-06,1052.6,a級

In [19]:
#8：危険データだけ抽出
df_danger = df_sorted[df_sorted["危険ランク"] != "通常"]
df_danger

,date,site,product,defect_type,production,defects,month,ppm,危険ランク
9,2026-05-08,GSE,Lamp-H,寸法NG,5000,11.0,2026-05,2200.0,s級
0,2026-05-01,MELMB,Lamp-A,点灯不良,12000,18.0,2026-05,1500.0,a級
2,2026-06-01,MELMB,Lamp-A,点灯不良,11000,30.0,2026-06,2727.3,s級
4,2026-05-02,WSE,Lamp-D,異物混入,10000,25.0,2026-05,2500.0,s級
7,2026-06-06,WSE,Lamp-F,点灯不良,6000,18.0,2026-06,3000.0,s級
6,2026-06-02,WSE,Lamp-D,異物混入,9500,10.0,2026-06,1052.6,a級

In [20]:
#9：CSV保存
df_sorted.to_csv(
    "output/quality_monthly_worst_all.csv",
    index=False,
    encoding="utf-8-sig"
)

df_danger.to_csv(
    "output/quality_monthly_worst_danger.csv",
    index=False,
    encoding="utf-8-sig"
)

In [21]:
#10：保存した危険データを確認
df_check = pd.read_csv("output/quality_monthly_worst_danger.csv")
df_check

,date,site,product,defect_type,production,defects,month,ppm,危険ランク
0,2026-05-08,GSE,Lamp-H,寸法NG,5000,11.0,2026-05,2200.0,s級
1,2026-05-01,MELMB,Lamp-A,点灯不良,12000,18.0,2026-05,1500.0,a級
2,2026-06-01,MELMB,Lamp-A,点灯不良,11000,30.0,2026-06,2727.3,s級
3,2026-05-02,WSE,Lamp-D,異物混入,10000,25.0,2026-05,2500.0,s級
4,2026-06-06,WSE,Lamp-F,点灯不良,6000,18.0,2026-06,3000.0,s級
5,2026-06-02,WSE,Lamp-D,異物混入,9500,10.0,2026-06,1052.6,a級