###### 130_4_practical_site_category_action_required.ipynb

In [11]:
import pandas as pd
pd.set_option("display.max_columns", None)

In [12]:
df_summary_sorted = pd.DataFrame(
    [
        ["GSE", "NTF", 3, 3000, 1000.000000, 1.0, "最優先"],
        ["GSE", "コイル", 2, 4000, 500.000000, 2.0, "要確認"],
        ["GSE", "CAN通信", 1, 3000, 333.333333, 3.0, "通常確認"],
        ["GSE", "Buck-IC", 1, 4000, 250.000000, 4.0, "通常確認"],
        ["MELMB", "コイル", 5, 10000, 500.000000, 1.0, "最優先"],
        ["MELMB", "Buck-IC", 2, 9000, 222.222222, 2.0, "要確認"],
        ["MELMB", "CAN通信", 1, 9000, 111.111111, 3.0, "通常確認"],
        ["MELMB", "NTF", 0, 10000, 0.000000, 4.0, "通常確認"],
        ["SUS", "NTF", 2, 8000, 250.000000, 1.0, "最優先"],
        ["SUS", "コイル", 3, 20000, 150.000000, 2.0, "要確認"],
        ["SUS", "Buck-IC", 1, 12000, 83.333333, 3.0, "通常確認"],
        ["WSE", "コイル", 5, 11000, 454.545455, 1.0, "最優先"],
        ["WSE", "Buck-IC", 2, 6000, 333.333333, 2.0, "要確認"],
        ["WSE", "NTF", 1, 5000, 200.000000, 3.0, "通常確認"],
    ],
    columns=[
        "site",
        "defect_category",
        "defect_qty_total",
        "production_qty_total",
        "defect_ppm",
        "ppm_rank",
        "priority",
    ],
)
df_summary_sorted

,site,defect_category,defect_qty_total,production_qty_total,defect_ppm,ppm_rank,priority
0,GSE,NTF,3,3000,1000.000000,1.0,最優先
1,GSE,コイル,2,4000,500.000000,2.0,要確認
2,GSE,CAN通信,1,3000,333.333333,3.0,通常確認
3,GSE,Buck-IC,1,4000,250.000000,4.0,通常確認
4,MELMB,コイル,5,10000,500.000000,1.0,最優先
5,MELMB,Buck-IC,2,9000,222.222222,2.0,要確認
6,MELMB,CAN通信,1,9000,111.111111,3.0,通常確認
7,MELMB,NTF,0,10000,0.000000,4.0,通常確認
8,SUS,NTF,2,8000,250.000000,1.0,最優先
9,SUS,コイル,3,20000,150.000000,2.0,要確認
10,SUS,Buck-IC,1,12000,83.333333,3.0,通常確認
11,WSE,コイル,5,11000,454.545455,1.0,最優先
12,WSE,Buck-IC,2,6000,333.333333,2.0,要確認
13,WSE,NTF,1,5000,200.000000,3.0,通常確認

In [13]:
df_action = df_summary_sorted.copy()
df_action

,site,defect_category,defect_qty_total,production_qty_total,defect_ppm,ppm_rank,priority
0,GSE,NTF,3,3000,1000.000000,1.0,最優先
1,GSE,コイル,2,4000,500.000000,2.0,要確認
2,GSE,CAN通信,1,3000,333.333333,3.0,通常確認
3,GSE,Buck-IC,1,4000,250.000000,4.0,通常確認
4,MELMB,コイル,5,10000,500.000000,1.0,最優先
5,MELMB,Buck-IC,2,9000,222.222222,2.0,要確認
6,MELMB,CAN通信,1,9000,111.111111,3.0,通常確認
7,MELMB,NTF,0,10000,0.000000,4.0,通常確認
8,SUS,NTF,2,8000,250.000000,1.0,最優先
9,SUS,コイル,3,20000,150.000000,2.0,要確認
10,SUS,Buck-IC,1,12000,83.333333,3.0,通常確認
11,WSE,コイル,5,11000,454.545455,1.0,最優先
12,WSE,Buck-IC,2,6000,333.333333,2.0,要確認
13,WSE,NTF,1,5000,200.000000,3.0,通常確認

In [14]:
df_action["action_required"] = "経過観察"
df_action

,site,defect_category,defect_qty_total,production_qty_total,defect_ppm,ppm_rank,priority,action_required
0,GSE,NTF,3,3000,1000.000000,1.0,最優先,経過観察
1,GSE,コイル,2,4000,500.000000,2.0,要確認,経過観察
2,GSE,CAN通信,1,3000,333.333333,3.0,通常確認,経過観察
3,GSE,Buck-IC,1,4000,250.000000,4.0,通常確認,経過観察
4,MELMB,コイル,5,10000,500.000000,1.0,最優先,経過観察
5,MELMB,Buck-IC,2,9000,222.222222,2.0,要確認,経過観察
6,MELMB,CAN通信,1,9000,111.111111,3.0,通常確認,経過観察
7,MELMB,NTF,0,10000,0.000000,4.0,通常確認,経過観察
8,SUS,NTF,2,8000,250.000000,1.0,最優先,経過観察
9,SUS,コイル,3,20000,150.000000,2.0,要確認,経過観察
10,SUS,Buck-IC,1,12000,83.333333,3.0,通常確認,経過観察
11,WSE,コイル,5,11000,454.545455,1.0,最優先,経過観察
12,WSE,Buck-IC,2,6000,333.333333,2.0,要確認,経過観察
13,WSE,NTF,1,5000,200.000000,3.0,通常確認,経過観察

In [15]:
df_action.loc[
    df_action["priority"] == "最優先",
    "action_required",
] = "要対策検討"
df_action

,site,defect_category,defect_qty_total,production_qty_total,defect_ppm,ppm_rank,priority,action_required
0,GSE,NTF,3,3000,1000.000000,1.0,最優先,要対策検討
1,GSE,コイル,2,4000,500.000000,2.0,要確認,経過観察
2,GSE,CAN通信,1,3000,333.333333,3.0,通常確認,経過観察
3,GSE,Buck-IC,1,4000,250.000000,4.0,通常確認,経過観察
4,MELMB,コイル,5,10000,500.000000,1.0,最優先,要対策検討
5,MELMB,Buck-IC,2,9000,222.222222,2.0,要確認,経過観察
6,MELMB,CAN通信,1,9000,111.111111,3.0,通常確認,経過観察
7,MELMB,NTF,0,10000,0.000000,4.0,通常確認,経過観察
8,SUS,NTF,2,8000,250.000000,1.0,最優先,要対策検討
9,SUS,コイル,3,20000,150.000000,2.0,要確認,経過観察
10,SUS,Buck-IC,1,12000,83.333333,3.0,通常確認,経過観察
11,WSE,コイル,5,11000,454.545455,1.0,最優先,要対策検討
12,WSE,Buck-IC,2,6000,333.333333,2.0,要確認,経過観察
13,WSE,NTF,1,5000,200.000000,3.0,通常確認,経過観察

In [16]:
df_action.loc[
    df_action["priority"] == "要確認",
    "action_required",
] = "傾向確認"

df_action

,site,defect_category,defect_qty_total,production_qty_total,defect_ppm,ppm_rank,priority,action_required
0,GSE,NTF,3,3000,1000.000000,1.0,最優先,要対策検討
1,GSE,コイル,2,4000,500.000000,2.0,要確認,傾向確認
2,GSE,CAN通信,1,3000,333.333333,3.0,通常確認,経過観察
3,GSE,Buck-IC,1,4000,250.000000,4.0,通常確認,経過観察
4,MELMB,コイル,5,10000,500.000000,1.0,最優先,要対策検討
5,MELMB,Buck-IC,2,9000,222.222222,2.0,要確認,傾向確認
6,MELMB,CAN通信,1,9000,111.111111,3.0,通常確認,経過観察
7,MELMB,NTF,0,10000,0.000000,4.0,通常確認,経過観察
8,SUS,NTF,2,8000,250.000000,1.0,最優先,要対策検討
9,SUS,コイル,3,20000,150.000000,2.0,要確認,傾向確認
10,SUS,Buck-IC,1,12000,83.333333,3.0,通常確認,経過観察
11,WSE,コイル,5,11000,454.545455,1.0,最優先,要対策検討
12,WSE,Buck-IC,2,6000,333.333333,2.0,要確認,傾向確認
13,WSE,NTF,1,5000,200.000000,3.0,通常確認,経過観察

In [17]:
df_action_list = df_action[
    [
        "site",
        "defect_category",
        "defect_ppm",
        "ppm_rank",
        "priority",
        "action_required",
    ]
].copy()

df_action_list

     site defect_category   defect_ppm  ppm_rank priority action_required
0     GSE             NTF  1000.000000       1.0      最優先           要対策検討
1     GSE             コイル   500.000000       2.0      要確認            傾向確認
2     GSE           CAN通信   333.333333       3.0     通常確認            経過観察
3     GSE         Buck-IC   250.000000       4.0     通常確認            経過観察
4   MELMB             コイル   500.000000       1.0      最優先           要対策検討
5   MELMB         Buck-IC   222.222222       2.0      要確認            傾向確認
6   MELMB           CAN通信   111.111111       3.0     通常確認            経過観察
7   MELMB             NTF     0.000000       4.0     通常確認            経過観察
8     SUS             NTF   250.000000       1.0      最優先           要対策検討
9     SUS             コイル   150.000000       2.0      要確認            傾向確認
10    SUS         Buck-IC    83.333333       3.0     通常確認            経過観察
11    WSE             コイル   454.545455       1.0      最優先           要対策検討
12    WSE         Buck-IC   333.333333       2.0      要確認            傾向確認
13    WSE             NTF   200.000000       3.0     通常確認            経過観察