###### 127-2: データを1列おきに取得するには

In [1]:
import pandas as pd

df = pd.DataFrame(
    [
        [100, 10, 10, 15, 15],
        [101, 7, 17, 12, 27],
        [102, 5, 22, 18, 45],
    ],
    columns=["no", "sales_a", "cum_a", "sales_b", "cum_b"],
)
df.iloc[:, 1::2]

   sales_a  sales_b
0       10       15
1        7       12
2        5       18

######　実務寄り練習問題

In [3]:
import pandas as pd
import numpy as np
from pathlib import Path

Path("output").mkdir(exist_ok=True)

In [4]:
df_quality = pd.DataFrame(
    [
        ["2026-06", "Lamp-A", 12000, 18, 10000, 25, 8000, 4],
        ["2026-06", "Lamp-B", 8500, 4, 7000, 5, 6000, 18],
        ["2026-07", "Lamp-A", 11000, 30, 9500, 10, 9000, 8],
        ["2026-07", "Lamp-C", 9000, 8, 6000, 18, 5200, 3],
    ],
    columns=[
        "month",
        "product",
        "melmb_production", "melmb_defects",
        "wse_production", "wse_defects",
        "gse_production", "gse_defects",
    ]
)

df_quality

,month,product,melmb_production,melmb_defects,wse_production,wse_defects,gse_production,gse_defects
0,2026-06,Lamp-A,12000,18,10000,25,8000,4
1,2026-06,Lamp-B,8500,4,7000,5,6000,18
2,2026-07,Lamp-A,11000,30,9500,10,9000,8
3,2026-07,Lamp-C,9000,8,6000,18,5200,3

In [5]:
df_quality.head()

,month,product,melmb_production,melmb_defects,wse_production,wse_defects,gse_production,gse_defects
0,2026-06,Lamp-A,12000,18,10000,25,8000,4
1,2026-06,Lamp-B,8500,4,7000,5,6000,18
2,2026-07,Lamp-A,11000,30,9500,10,9000,8
3,2026-07,Lamp-C,9000,8,6000,18,5200,3

In [6]:
df_quality.columns

Index(['month', 'product', 'melmb_production', 'melmb_defects',
       'wse_production', 'wse_defects', 'gse_production', 'gse_defects'],
      dtype='object')

In [10]:
df_quality.index

RangeIndex(start=0, stop=4, step=1)

In [9]:
df_quality.shape

(4, 8)

In [11]:
df_quality.iloc[0]

month               2026-06
product              Lamp-A
melmb_production      12000
melmb_defects            18
wse_production        10000
wse_defects              25
gse_production         8000
gse_defects               4
Name: 0, dtype: object

In [12]:
df_quality.iloc[0:2]

,month,product,melmb_production,melmb_defects,wse_production,wse_defects,gse_production,gse_defects
0,2026-06,Lamp-A,12000,18,10000,25,8000,4
1,2026-06,Lamp-B,8500,4,7000,5,6000,18

In [13]:
df_quality.iloc[-1]

month               2026-07
product              Lamp-C
melmb_production       9000
melmb_defects             8
wse_production         6000
wse_defects              18
gse_production         5200
gse_defects               3
Name: 3, dtype: object

In [15]:
df_quality.iloc[0, 1]

'Lamp-A'

In [16]:
df_quality.iloc[:,1]

0    Lamp-A
1    Lamp-B
2    Lamp-A
3    Lamp-C
Name: product, dtype: object

In [17]:
df_quality.iloc[:, 0:2]

     month product
0  2026-06  Lamp-A
1  2026-06  Lamp-B
2  2026-07  Lamp-A
3  2026-07  Lamp-C

In [18]:
df_quality.iloc[0:2, 0:4]

     month product  melmb_production  melmb_defects
0  2026-06  Lamp-A             12000             18
1  2026-06  Lamp-B              8500              4

In [19]:
df_quality.iloc[:, [0, 1, 2, 4, 6]]

     month product  melmb_production  wse_production  gse_production
0  2026-06  Lamp-A             12000           10000            8000
1  2026-06  Lamp-B              8500            7000            6000
2  2026-07  Lamp-A             11000            9500            9000
3  2026-07  Lamp-C              9000            6000            5200

In [20]:
for i, col in enumerate(df_quality.columns):
    print(i, col)

0 month
1 product
2 melmb_production
3 melmb_defects
4 wse_production
5 wse_defects
6 gse_production
7 gse_defects

In [21]:
df_production = df_quality.iloc[:, 2::2]
df_production

   melmb_production  wse_production  gse_production
0             12000           10000            8000
1              8500            7000            6000
2             11000            9500            9000
3              9000            6000            5200

In [22]:
df_defects = df_quality.iloc[:, 3::2]
df_defects

   melmb_defects  wse_defects  gse_defects
0             18           25            4
1              4            5           18
2             30           10            8
3              8           18            3

In [24]:
df_info = df_quality.iloc[:,0:2]
df_info

     month product
0  2026-06  Lamp-A
1  2026-06  Lamp-B
2  2026-07  Lamp-A
3  2026-07  Lamp-C

In [25]:
df_ppm = df_info.copy()
df_ppm

     month product
0  2026-06  Lamp-A
1  2026-06  Lamp-B
2  2026-07  Lamp-A
3  2026-07  Lamp-C

In [27]:
df_ppm["melmb_ppm"] = (
    df_quality["melmb_defects"] / df_quality["melmb_production"] * 1000000
).round(1)
df_ppm

     month product  melmb_ppm
0  2026-06  Lamp-A     1500.0
1  2026-06  Lamp-B      470.6
2  2026-07  Lamp-A     2727.3
3  2026-07  Lamp-C      888.9

In [28]:
df_ppm["wse_ppm"] = (
    df_quality["wse_defects"] / df_quality["wse_production"] * 1000000
).round(1)
df_ppm

     month product  melmb_ppm  wse_ppm
0  2026-06  Lamp-A     1500.0   2500.0
1  2026-06  Lamp-B      470.6    714.3
2  2026-07  Lamp-A     2727.3   1052.6
3  2026-07  Lamp-C      888.9   3000.0

In [30]:
df_ppm["gse_ppm"] = (
    df_quality["gse_defects"] / df_quality["gse_production"] * 1000000
).round(1)
df_ppm

     month product  melmb_ppm  wse_ppm  gse_ppm
0  2026-06  Lamp-A     1500.0   2500.0    500.0
1  2026-06  Lamp-B      470.6    714.3   3000.0
2  2026-07  Lamp-A     2727.3   1052.6    888.9
3  2026-07  Lamp-C      888.9   3000.0    576.9

In [32]:
df_ppm_only = df_ppm.iloc[:, 2:]
df_ppm_only

   melmb_ppm  wse_ppm  gse_ppm
0     1500.0   2500.0    500.0
1      470.6    714.3   3000.0
2     2727.3   1052.6    888.9
3      888.9   3000.0    576.9

In [33]:
df_ppm["max_ppm"] = df_ppm_only.max(axis=1)
df_ppm

     month product  melmb_ppm  wse_ppm  gse_ppm  max_ppm
0  2026-06  Lamp-A     1500.0   2500.0    500.0   2500.0
1  2026-06  Lamp-B      470.6    714.3   3000.0   3000.0
2  2026-07  Lamp-A     2727.3   1052.6    888.9   2727.3
3  2026-07  Lamp-C      888.9   3000.0    576.9   3000.0

In [34]:
df_ppm["worst_site"] = df_ppm_only.idxmax(axis=1)
df_ppm

     month product  melmb_ppm  wse_ppm  gse_ppm  max_ppm worst_site
0  2026-06  Lamp-A     1500.0   2500.0    500.0   2500.0    wse_ppm
1  2026-06  Lamp-B      470.6    714.3   3000.0   3000.0    gse_ppm
2  2026-07  Lamp-A     2727.3   1052.6    888.9   2727.3  melmb_ppm
3  2026-07  Lamp-C      888.9   3000.0    576.9   3000.0    wse_ppm

In [35]:
df_ppm["危険ランク"] = np.where(
    df_ppm["max_ppm"] >= 2500,
    "s級",
    np.where(
        df_ppm["max_ppm"] >= 1000,
        "a級",
        "通常"
    )
)
df_ppm

     month product  melmb_ppm  wse_ppm  gse_ppm  max_ppm worst_site 危険ランク
0  2026-06  Lamp-A     1500.0   2500.0    500.0   2500.0    wse_ppm    s級
1  2026-06  Lamp-B      470.6    714.3   3000.0   3000.0    gse_ppm    s級
2  2026-07  Lamp-A     2727.3   1052.6    888.9   2727.3  melmb_ppm    s級
3  2026-07  Lamp-C      888.9   3000.0    576.9   3000.0    wse_ppm    s級

In [36]:
df_ppm_sorted = df_ppm.sort_values("max_ppm", ascending=False)
df_ppm_sorted

     month product  melmb_ppm  wse_ppm  gse_ppm  max_ppm worst_site 危険ランク
1  2026-06  Lamp-B      470.6    714.3   3000.0   3000.0    gse_ppm    s級
3  2026-07  Lamp-C      888.9   3000.0    576.9   3000.0    wse_ppm    s級
2  2026-07  Lamp-A     2727.3   1052.6    888.9   2727.3  melmb_ppm    s級
0  2026-06  Lamp-A     1500.0   2500.0    500.0   2500.0    wse_ppm    s級

In [37]:
df_danger = df_ppm_sorted[df_ppm_sorted["危険ランク"] != "通常"]
df_danger

     month product  melmb_ppm  wse_ppm  gse_ppm  max_ppm worst_site 危険ランク
1  2026-06  Lamp-B      470.6    714.3   3000.0   3000.0    gse_ppm    s級
3  2026-07  Lamp-C      888.9   3000.0    576.9   3000.0    wse_ppm    s級
2  2026-07  Lamp-A     2727.3   1052.6    888.9   2727.3  melmb_ppm    s級
0  2026-06  Lamp-A     1500.0   2500.0    500.0   2500.0    wse_ppm    s級

In [38]:
df_ppm_sorted.to_csv(
    "output/ppm_quality_iloc_ppm_all.csv",
    index=False,
    encoding="utf-8-sig"
)

df_danger.to_csv(
    "output/quality_iloc_ppm_danger.csv",
    index=False,
    encoding="utf=8-sig"
)

In [39]:
df_check = pd.read_csv("output/quality_iloc_ppm_danger.csv")
df_check

     month product  melmb_ppm  wse_ppm  gse_ppm  max_ppm worst_site 危険ランク
0  2026-06  Lamp-B      470.6    714.3   3000.0   3000.0    gse_ppm    s級
1  2026-07  Lamp-C      888.9   3000.0    576.9   3000.0    wse_ppm    s級
2  2026-07  Lamp-A     2727.3   1052.6    888.9   2727.3  melmb_ppm    s級
3  2026-06  Lamp-A     1500.0   2500.0    500.0   2500.0    wse_ppm    s級