## 193-1

In [2]:
import pandas

df = pandas.read_csv("input/data.csv", encoding="shift-jis")
df.head()

       date station  temp
0  2018/9/1      札幌  19.5
1  2018/9/1      青森  21.5
2  2018/9/1      仙台  21.5
3  2018/9/1      東京  25.9
4  2018/9/1      福岡  25.5

In [3]:
df.tail(3)

           date station  temp
1497  2018/9/30      熊本  20.7
1498  2018/9/30      稚内  16.6
1499  2018/9/30      函館  17.6

In [4]:
df.slice = df.iloc[10:14]
df.slice

C:\Users\kjfar\AppData\Local\Temp\ipykernel_3524\1720088915.py:1: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  df.slice = df.iloc[10:14]

        date station  temp
10  2018/9/1      山形  20.8
11  2018/9/1      福島  21.9
12  2018/9/1      水戸  23.7
13  2018/9/1      千葉  27.5

## 「193-1: 表形式のデータを前処理しよう」 2問目

In [5]:
import pandas as pd

df = pd.read_csv("input/data.csv", encoding="Shift_JIS")

In [8]:
series_temp= df["temp"]
series_temp

0       19.5
1       21.5
2       21.5
3       25.9
4       25.5
        ...
1495    21.9
1496    21.3
1497    20.7
1498    16.6
1499    17.6
Name: temp, Length: 1500, dtype: float64

In [9]:
mean_temp = series_temp.mean()

In [10]:
mean_temp

np.float64(23.020840197693573)

In [11]:
series_filled = series_temp.fillna(mean_temp)
series_filled

0       19.5
1       21.5
2       21.5
3       25.9
4       25.5
        ...
1495    21.9
1496    21.3
1497    20.7
1498    16.6
1499    17.6
Name: temp, Length: 1500, dtype: float64

In [12]:
df.iloc[1483:1488]

           date station  temp
1483  2018/9/30      神戸  23.6
1484  2018/9/30      鳥取  19.5
1485  2018/9/30      岡山   NaN
1486  2018/9/30      松江  19.5
1487  2018/9/30      広島  20.4

In [14]:
series_temp = df["temp"]
series_temp.head()

0    19.5
1    21.5
2    21.5
3    25.9
4    25.5
Name: temp, dtype: float64

In [16]:
mean_temp = series_temp.mean()
mean_temp

np.float64(23.020840197693573)

In [17]:
series_filled = series_temp.fillna(mean_temp)
series_filled.iloc[1483:1488]

1483    23.60000
1484    19.50000
1485    23.02084
1486    19.50000
1487    20.40000
Name: temp, dtype: float64

In [18]:
df.iloc[1483:1488]

           date station  temp
1483  2018/9/30      神戸  23.6
1484  2018/9/30      鳥取  19.5
1485  2018/9/30      岡山   NaN
1486  2018/9/30      松江  19.5
1487  2018/9/30      広島  20.4

In [19]:
df["temp"] = series_filled
df.iloc[1483:1488]

           date station      temp
1483  2018/9/30      神戸  23.60000
1484  2018/9/30      鳥取  19.50000
1485  2018/9/30      岡山  23.02084
1486  2018/9/30      松江  19.50000
1487  2018/9/30      広島  20.40000

## 演習問題

In [20]:
import pandas as pd

In [21]:
df = pd.read_csv("input/quality_data.csv", encoding="Shift_JIS")

In [27]:
df.head()

       date   site  defect  production  defects
0  2026/6/1  MELMB    点灯不良       10000      3.0
1  2026/6/1    WSE    外観不良        8000      5.0
2  2026/6/1    GSE    ショート       12000      NaN
3  2026/6/1    ISE  コネクタ浮き        9000      2.0
4  2026/6/2  MELMB    点灯不良       11000      4.0

In [31]:
series_defects_num = pd.to_numeric(df["defects"], errors="coerce")
mean_defects = series_defects_num.mean()
mean_defects

np.float64(3.1)

In [32]:
import pandas

df = pandas.read_csv('input/quality_data.csv', encoding='Shift_JIS')

series_defects = df['defects']

mean_defects = series_defects.mean()

series_filled = series_defects.fillna(mean_defects)

df['defects'] = series_filled

## 実務練習問題

In [33]:
import pandas as pd
import numpy as np

In [34]:
df = pd.read_csv("input/quality_data.csv", encoding="Shift_JIS")

In [36]:
series_defects = df["defects"]
series_defects

0     3.0
1     5.0
2     NaN
3     2.0
4     4.0
5     6.0
6     1.0
7     NaN
8     2.0
9     4.0
10    3.0
11    1.0
Name: defects, dtype: float64

In [38]:
mean_defects = series_defects.mean()
mean_defects

np.float64(3.1)

In [39]:
series_filled = series_defects.fillna(mean_defects)
series_filled

0     3.0
1     5.0
2     3.1
3     2.0
4     4.0
5     6.0
6     1.0
7     3.1
8     2.0
9     4.0
10    3.0
11    1.0
Name: defects, dtype: float64

In [40]:
df["defects"] = series_filled

In [42]:
df["defects"]

0     3.0
1     5.0
2     3.1
3     2.0
4     4.0
5     6.0
6     1.0
7     3.1
8     2.0
9     4.0
10    3.0
11    1.0
Name: defects, dtype: float64

In [43]:
df["ppm"] = (df["defects"] / df["production"] * 1000000).round(1)

In [45]:
df["危険度"] = np.where(df["ppm"] >= 500, "要確認", "通常")

df_ranking = df.sort_values(by="ppm", ascending=False)
df_ranking

        date   site  defect  production  defects    ppm  危険度
5   2026/6/2    WSE    外観不良        8500      6.0  705.9  要確認
1   2026/6/1    WSE    外観不良        8000      5.0  625.0  要確認
9   2026/6/3    WSE    外観不良        8200      4.0  487.8   通常
4   2026/6/2  MELMB    点灯不良       11000      4.0  363.6   通常
7   2026/6/2    ISE  コネクタ浮き        9500      3.1  326.3   通常
0   2026/6/1  MELMB    点灯不良       10000      3.0  300.0   通常
2   2026/6/1    GSE    ショート       12000      3.1  258.3   通常
10  2026/6/3    GSE    ショート       11800      3.0  254.2   通常
3   2026/6/1    ISE  コネクタ浮き        9000      2.0  222.2   通常
8   2026/6/3  MELMB    点灯不良       10500      2.0  190.5   通常
11  2026/6/3    ISE  コネクタ浮き        9100      1.0  109.9   通常
6   2026/6/2    GSE    ショート       12500      1.0   80.0   通常