###### 129_6_practical_defect_ppm_category

In [1]:
#cell1
import pandas as pd
import numpy as np

In [2]:
df = pd.DataFrame(
    [
        ["D001", "J69P", "MELMB", "コイル", 3, 12000, "調査中"],
        ["D002", "J69P", "WSE", "Buck-IC", 5, 18000, "対策検討中"],
        ["D003", "310D", "GSE", "コイル", 12, 25000, "暫定対策済"],
        ["D004", "310D", "MELMB", "はんだ", 2, 9000, "調査中"],
        ["D005", "J69P", "GSE", "コイル", 7, 15000, "調査中"],
        ["D006", "310D", "WSE", "コネクタ", 1, 6000, "完了"],
        ["D007", "J69P", "MELMB", "Buck-IC", 8, 20000, "調査中"],
        ["D008", "310D", "GSE", "コイル", 4, 10000, "対策検討中"],
        ["D009", "J69P", "GSE", "Buck-IC", 6, 14000, "調査中"],
        ["D010", "310D", "MELMB", "コイル", 5, 16000, "暫定対策済"],
        ["D011", "J69P", "WSE", "コイル", 9, 22000, "調査中"],
        ["D012", "310D", "GSE", "はんだ", 3, 8000, "完了"],
    ],
    columns=[
        "defect_id",
        "project",
        "site",
        "defect_category",
        "defect_qty",
        "inspection_qty",
        "status",
    ],
)
df

   defect_id project   site defect_category  defect_qty  inspection_qty status
0       D001    J69P  MELMB             コイル           3           12000    調査中
1       D002    J69P    WSE         Buck-IC           5           18000  対策検討中
2       D003    310D    GSE             コイル          12           25000  暫定対策済
3       D004    310D  MELMB             はんだ           2            9000    調査中
4       D005    J69P    GSE             コイル           7           15000    調査中
5       D006    310D    WSE            コネクタ           1            6000     完了
6       D007    J69P  MELMB         Buck-IC           8           20000    調査中
7       D008    310D    GSE             コイル           4           10000  対策検討中
8       D009    J69P    GSE         Buck-IC           6           14000    調査中
9       D010    310D  MELMB             コイル           5           16000  暫定対策済
10      D011    J69P    WSE             コイル           9           22000    調査中
11      D012    310D    GSE             はんだ           3            8000     完了

In [3]:
#cell3
df_work = df.copy()
df_work

   defect_id project   site defect_category  defect_qty  inspection_qty status
0       D001    J69P  MELMB             コイル           3           12000    調査中
1       D002    J69P    WSE         Buck-IC           5           18000  対策検討中
2       D003    310D    GSE             コイル          12           25000  暫定対策済
3       D004    310D  MELMB             はんだ           2            9000    調査中
4       D005    J69P    GSE             コイル           7           15000    調査中
5       D006    310D    WSE            コネクタ           1            6000     完了
6       D007    J69P  MELMB         Buck-IC           8           20000    調査中
7       D008    310D    GSE             コイル           4           10000  対策検討中
8       D009    J69P    GSE         Buck-IC           6           14000    調査中
9       D010    310D  MELMB             コイル           5           16000  暫定対策済
10      D011    J69P    WSE             コイル           9           22000    調査中
11      D012    310D    GSE             はんだ           3            8000     完了

In [4]:
df_work["defect_rate"] =(
    df_work["defect_qty"]
    / df_work["inspection_qty"]
)
df_work

,defect_id,project,site,defect_category,defect_qty,inspection_qty,status,defect_rate
0,D001,J69P,MELMB,コイル,3,12000,調査中,0.000250
1,D002,J69P,WSE,Buck-IC,5,18000,対策検討中,0.000278
2,D003,310D,GSE,コイル,12,25000,暫定対策済,0.000480
3,D004,310D,MELMB,はんだ,2,9000,調査中,0.000222
4,D005,J69P,GSE,コイル,7,15000,調査中,0.000467
5,D006,310D,WSE,コネクタ,1,6000,完了,0.000167
6,D007,J69P,MELMB,Buck-IC,8,20000,調査中,0.000400
7,D008,310D,GSE,コイル,4,10000,対策検討中,0.000400
8,D009,J69P,GSE,Buck-IC,6,14000,調査中,0.000429
9,D010,310D,MELMB,コイル,5,16000,暫定対策済,0.000313
10,D011,J69P,WSE,コイル,9,22000,調査中,0.000409
11,D012,310D,GSE,はんだ,3,8000,完了,0.000375

In [5]:
df_work["defect_ppm"] = (
    df_work["defect_rate"] * 1000000
)
df_work

,defect_id,project,site,defect_category,defect_qty,inspection_qty,status,defect_rate,defect_ppm
0,D001,J69P,MELMB,コイル,3,12000,調査中,0.000250,250.000000
1,D002,J69P,WSE,Buck-IC,5,18000,対策検討中,0.000278,277.777778
2,D003,310D,GSE,コイル,12,25000,暫定対策済,0.000480,480.000000
3,D004,310D,MELMB,はんだ,2,9000,調査中,0.000222,222.222222
4,D005,J69P,GSE,コイル,7,15000,調査中,0.000467,466.666667
5,D006,310D,WSE,コネクタ,1,6000,完了,0.000167,166.666667
6,D007,J69P,MELMB,Buck-IC,8,20000,調査中,0.000400,400.000000
7,D008,310D,GSE,コイル,4,10000,対策検討中,0.000400,400.000000
8,D009,J69P,GSE,Buck-IC,6,14000,調査中,0.000429,428.571429
9,D010,310D,MELMB,コイル,5,16000,暫定対策済,0.000313,312.500000
10,D011,J69P,WSE,コイル,9,22000,調査中,0.000409,409.090909
11,D012,310D,GSE,はんだ,3,8000,完了,0.000375,375.000000

In [7]:
bins = [
    0,
    100,
    300,
    600,
    np.inf,
]
labels =[
    "良好",
    "注意",
    "要確認",
    "重大確認",
]

In [8]:
#cell7
df_work["risk_category"] = pd.cut(
    df_work["defect_ppm"],
    bins=bins,
    labels=labels,
    include_lowest=True,
)
df_work

,defect_id,project,site,defect_category,defect_qty,inspection_qty,status,defect_rate,defect_ppm,risk_category
0,D001,J69P,MELMB,コイル,3,12000,調査中,0.000250,250.000000,注意
1,D002,J69P,WSE,Buck-IC,5,18000,対策検討中,0.000278,277.777778,注意
2,D003,310D,GSE,コイル,12,25000,暫定対策済,0.000480,480.000000,要確認
3,D004,310D,MELMB,はんだ,2,9000,調査中,0.000222,222.222222,注意
4,D005,J69P,GSE,コイル,7,15000,調査中,0.000467,466.666667,要確認
5,D006,310D,WSE,コネクタ,1,6000,完了,0.000167,166.666667,注意
6,D007,J69P,MELMB,Buck-IC,8,20000,調査中,0.000400,400.000000,要確認
7,D008,310D,GSE,コイル,4,10000,対策検討中,0.000400,400.000000,要確認
8,D009,J69P,GSE,Buck-IC,6,14000,調査中,0.000429,428.571429,要確認
9,D010,310D,MELMB,コイル,5,16000,暫定対策済,0.000313,312.500000,要確認
10,D011,J69P,WSE,コイル,9,22000,調査中,0.000409,409.090909,要確認
11,D012,310D,GSE,はんだ,3,8000,完了,0.000375,375.000000,要確認

In [9]:
df_serious = df_work[
    df_work["risk_category"] == "重大確認"
].copy()

df_serious

Empty DataFrame
Columns: [defect_id, project, site, defect_category, defect_qty, inspection_qty, status, defect_rate, defect_ppm, risk_category]
Index: []

In [12]:
#cell9
df_risk_count = df_work["risk_category"].value_counts(
    sort=False
).reset_index()

df_risk_count.columns= [
    "risk_category",
    "count",
]

df_risk_count

  risk_category  count
0            良好      0
1            注意      4
2           要確認      8
3          重大確認      0

In [17]:
df_work["report_comment"] = "通常監視"
df_work

df_work.loc[
    df_work["risk_category"] == "注意",
    "report_comment",
] = "推移確認"
df_work

df_work.loc[
    df_work["risk_category"] == "要確認",
    "report_comment",
] = "原因確認"
df_work

df_work.loc[
    df_work["risk_category"] == "重大確認",
    "report_comment",
] = "至急確認"
df_work

,defect_id,project,site,defect_category,defect_qty,inspection_qty,status,defect_rate,defect_ppm,risk_category,report_comment
0,D001,J69P,MELMB,コイル,3,12000,調査中,0.000250,250.000000,注意,推移確認
1,D002,J69P,WSE,Buck-IC,5,18000,対策検討中,0.000278,277.777778,注意,推移確認
2,D003,310D,GSE,コイル,12,25000,暫定対策済,0.000480,480.000000,要確認,原因確認
3,D004,310D,MELMB,はんだ,2,9000,調査中,0.000222,222.222222,注意,推移確認
4,D005,J69P,GSE,コイル,7,15000,調査中,0.000467,466.666667,要確認,原因確認
5,D006,310D,WSE,コネクタ,1,6000,完了,0.000167,166.666667,注意,推移確認
6,D007,J69P,MELMB,Buck-IC,8,20000,調査中,0.000400,400.000000,要確認,原因確認
7,D008,310D,GSE,コイル,4,10000,対策検討中,0.000400,400.000000,要確認,原因確認
8,D009,J69P,GSE,Buck-IC,6,14000,調査中,0.000429,428.571429,要確認,原因確認
9,D010,310D,MELMB,コイル,5,16000,暫定対策済,0.000313,312.500000,要確認,原因確認
10,D011,J69P,WSE,コイル,9,22000,調査中,0.000409,409.090909,要確認,原因確認
11,D012,310D,GSE,はんだ,3,8000,完了,0.000375,375.000000,要確認,原因確認

In [18]:
#cell11

df_report = df_work.sort_values(
    [
        "risk_category",
        "defect_ppm",
    ],
    ascending=[
        True,
        False,
    ],
)
df_report

,defect_id,project,site,defect_category,defect_qty,inspection_qty,status,defect_rate,defect_ppm,risk_category,report_comment
1,D002,J69P,WSE,Buck-IC,5,18000,対策検討中,0.000278,277.777778,注意,推移確認
0,D001,J69P,MELMB,コイル,3,12000,調査中,0.000250,250.000000,注意,推移確認
3,D004,310D,MELMB,はんだ,2,9000,調査中,0.000222,222.222222,注意,推移確認
5,D006,310D,WSE,コネクタ,1,6000,完了,0.000167,166.666667,注意,推移確認
2,D003,310D,GSE,コイル,12,25000,暫定対策済,0.000480,480.000000,要確認,原因確認
4,D005,J69P,GSE,コイル,7,15000,調査中,0.000467,466.666667,要確認,原因確認
8,D009,J69P,GSE,Buck-IC,6,14000,調査中,0.000429,428.571429,要確認,原因確認
10,D011,J69P,WSE,コイル,9,22000,調査中,0.000409,409.090909,要確認,原因確認
6,D007,J69P,MELMB,Buck-IC,8,20000,調査中,0.000400,400.000000,要確認,原因確認
7,D008,310D,GSE,コイル,4,10000,対策検討中,0.000400,400.000000,要確認,原因確認
11,D012,310D,GSE,はんだ,3,8000,完了,0.000375,375.000000,要確認,原因確認
9,D010,310D,MELMB,コイル,5,16000,暫定対策済,0.000313,312.500000,要確認,原因確認