In [1]:
import pandas as pd

In [3]:
df_quality = pd.DataFrame(
    [
         ["2026-06", "MELMB", "Lamp-A", "不点灯", 18, "対応中", "佐藤"],
        ["2026-06", "WSE", "Lamp-B", "ちらつき", 32, "未対応", "鈴木"],
        ["2026-06", "GSE", "Lamp-C", "外観不良", 9, "完了", "田中"],
        ["2026-07", "MELMB", "Lamp-A", "不点灯", 25, "対応中", "佐藤"],
        ["2026-07", "WSE", "Lamp-B", "ショート", 45, "未対応", "鈴木"],
        ["2026-07", "GSE", "Lamp-C", "外観不良", 7, "完了", "田中"],
        ["2026-08", "MELMB", "Lamp-D", "水入り", 12, "調査中", "高橋"],
        ["2026-08", "WSE", "Lamp-B", "ちらつき", 20, "対応中", "鈴木"],
        ["2026-08", "GSE", "Lamp-C", "外観不良", 5, "完了", "田中"],
        ["2026-09", "MELMB", "Lamp-D", "水入り", 16, "調査中", "高橋"],
    ],
    columns=[
        "month",
        "site",
        "product",
        "defect_type",
        "defect_qty",
        "status",
        "owner",
    ]
)
df_quality

     month   site product defect_type  defect_qty status owner
0  2026-06  MELMB  Lamp-A         不点灯          18    対応中    佐藤
1  2026-06    WSE  Lamp-B        ちらつき          32    未対応    鈴木
2  2026-06    GSE  Lamp-C        外観不良           9     完了    田中
3  2026-07  MELMB  Lamp-A         不点灯          25    対応中    佐藤
4  2026-07    WSE  Lamp-B        ショート          45    未対応    鈴木
5  2026-07    GSE  Lamp-C        外観不良           7     完了    田中
6  2026-08  MELMB  Lamp-D         水入り          12    調査中    高橋
7  2026-08    WSE  Lamp-B        ちらつき          20    対応中    鈴木
8  2026-08    GSE  Lamp-C        外観不良           5     完了    田中
9  2026-09  MELMB  Lamp-D         水入り          16    調査中    高橋

In [4]:
df_site = df_quality[["site"]]
df_site

    site
0  MELMB
1    WSE
2    GSE
3  MELMB
4    WSE
5    GSE
6  MELMB
7    WSE
8    GSE
9  MELMB

In [5]:
df_site_master = df_site.drop_duplicates().reset_index(drop=True)
df_site_master

    site
0  MELMB
1    WSE
2    GSE

In [6]:
df_product_master = df_quality[["product"]].drop_duplicates().reset_index(drop=True)
df_product_master

  product
0  Lamp-A
1  Lamp-B
2  Lamp-C
3  Lamp-D

In [7]:
df_owner_master = df_quality[["owner"]].drop_duplicates().reset_index(drop=True)
df_owner_master

  owner
0    佐藤
1    鈴木
2    田中
3    高橋

In [9]:
df_unfinished_owner = df_quality[df_quality["status"].isin(["未対応", "調査中"])]
df_unfinished_owner

     month   site product defect_type  defect_qty status owner
1  2026-06    WSE  Lamp-B        ちらつき          32    未対応    鈴木
4  2026-07    WSE  Lamp-B        ショート          45    未対応    鈴木
6  2026-08  MELMB  Lamp-D         水入り          12    調査中    高橋
9  2026-09  MELMB  Lamp-D         水入り          16    調査中    高橋

In [10]:
df_unfinished_owner_master = df_unfinished_owner.drop_duplicates().reset_index(drop=False)
df_unfinished_owner_master

   index    month   site product defect_type  defect_qty status owner
0      1  2026-06    WSE  Lamp-B        ちらつき          32    未対応    鈴木
1      4  2026-07    WSE  Lamp-B        ショート          45    未対応    鈴木
2      6  2026-08  MELMB  Lamp-D         水入り          12    調査中    高橋
3      9  2026-09  MELMB  Lamp-D         水入り          16    調査中    高橋

In [11]:
df_unfinished_report = df_unfinished[
    [
        "month",
        "site",
        "product",
        "status",
        "owner",
    ]
]
df_unfinished_report

     month   site product status owner
1  2026-06    WSE  Lamp-B    未対応    鈴木
4  2026-07    WSE  Lamp-B    未対応    鈴木
6  2026-08  MELMB  Lamp-D    調査中    高橋
9  2026-09  MELMB  Lamp-D    調査中    高橋

In [12]:
series_owner = df_quality["owner"]
df_owner = df_quality[["owner"]]
print(type(series_owner))
print(type(df_owner))

<class 'pandas.core.series.Series'>
<class 'pandas.core.frame.DataFrame'>