###### 131_1_practical_comment_mask_stepup_question.ipynb

In [1]:
import pandas as pd

In [2]:
pd.set_option("display.max_columns", None)

In [3]:
df_defect = pd.DataFrame(
    [
        ["D-001", "SUS", "J69P", "2026/06/15にKLAK-67890で3件発生。160V条件で確認。"],
        ["D-002", "WSE", "310D", "2026/06/18にKLBC-12345で1件発生。140V検査では検出せず。"],
        ["D-003", "GSE", "J69P", "2026/06/20にPY-110相当品で2件再現。12V条件で確認。"],
        ["D-004", "MELMB", "310D", "現象再現せず。対象品番KLEE-55555は継続確認中。"],
        ["D-005", "SUS", "310D", "2026/06/25にLCM-220で5件確認。160V条件で全数検査中。"],
    ],
    columns=[
        "defect_id",
        "site",
        "model",
        "comment",
    ],
)
df_defect

  defect_id   site model                                   comment
0     D-001    SUS  J69P     2026/06/15にKLAK-67890で3件発生。160V条件で確認。
1     D-002    WSE  310D  2026/06/18にKLBC-12345で1件発生。140V検査では検出せず。
2     D-003    GSE  J69P       2026/06/20にPY-110相当品で2件再現。12V条件で確認。
3     D-004  MELMB  310D              現象再現せず。対象品番KLEE-55555は継続確認中。
4     D-005    SUS  310D     2026/06/25にLCM-220で5件確認。160V条件で全数検査中。

In [4]:
df_work = df_defect.copy()
df_work

  defect_id   site model                                   comment
0     D-001    SUS  J69P     2026/06/15にKLAK-67890で3件発生。160V条件で確認。
1     D-002    WSE  310D  2026/06/18にKLBC-12345で1件発生。140V検査では検出せず。
2     D-003    GSE  J69P       2026/06/20にPY-110相当品で2件再現。12V条件で確認。
3     D-004  MELMB  310D              現象再現せず。対象品番KLEE-55555は継続確認中。
4     D-005    SUS  310D     2026/06/25にLCM-220で5件確認。160V条件で全数検査中。

In [8]:
df_work["comment_public"] = df_work["comment"]

In [9]:
df_work["comment_public"] = df_work["comment_public"].str.replace(
    r"\d{4}/\d{2}/\d{2}",
    "[DATE]",
    regex=True
)
df_work

,defect_id,site,model,comment,comment_public
0,D-001,SUS,J69P,2026/06/15にKLAK-67890で3件発生。160V条件で確認。,[DATE]にKLAK-67890で3件発生。160V条件で確認。
1,D-002,WSE,310D,2026/06/18にKLBC-12345で1件発生。140V検査では検出せず。,[DATE]にKLBC-12345で1件発生。140V検査では検出せず。
2,D-003,GSE,J69P,2026/06/20にPY-110相当品で2件再現。12V条件で確認。,[DATE]にPY-110相当品で2件再現。12V条件で確認。
3,D-004,MELMB,310D,現象再現せず。対象品番KLEE-55555は継続確認中。,現象再現せず。対象品番KLEE-55555は継続確認中。
4,D-005,SUS,310D,2026/06/25にLCM-220で5件確認。160V条件で全数検査中。,[DATE]にLCM-220で5件確認。160V条件で全数検査中。

In [11]:
df_work["comment_public"] = df_work["comment_public"].str.replace(
    r"[A-Z]+-\d+",
    "[PART]",
    regex=True
)
df_work

,defect_id,site,model,comment,comment_public
0,D-001,SUS,J69P,2026/06/15にKLAK-67890で3件発生。160V条件で確認。,[DATE]に[PART]で3件発生。160V条件で確認。
1,D-002,WSE,310D,2026/06/18にKLBC-12345で1件発生。140V検査では検出せず。,[DATE]に[PART]で1件発生。140V検査では検出せず。
2,D-003,GSE,J69P,2026/06/20にPY-110相当品で2件再現。12V条件で確認。,[DATE]に[PART]相当品で2件再現。12V条件で確認。
3,D-004,MELMB,310D,現象再現せず。対象品番KLEE-55555は継続確認中。,現象再現せず。対象品番[PART]は継続確認中。
4,D-005,SUS,310D,2026/06/25にLCM-220で5件確認。160V条件で全数検査中。,[DATE]に[PART]で5件確認。160V条件で全数検査中。

In [12]:
df_work["comment_public"] = df_work["comment_public"].str.replace(
    r"\d+件",
    "[QTY]",
    regex=True,
)

In [13]:
df_work

,defect_id,site,model,comment,comment_public
0,D-001,SUS,J69P,2026/06/15にKLAK-67890で3件発生。160V条件で確認。,[DATE]に[PART]で[QTY]発生。160V条件で確認。
1,D-002,WSE,310D,2026/06/18にKLBC-12345で1件発生。140V検査では検出せず。,[DATE]に[PART]で[QTY]発生。140V検査では検出せず。
2,D-003,GSE,J69P,2026/06/20にPY-110相当品で2件再現。12V条件で確認。,[DATE]に[PART]相当品で[QTY]再現。12V条件で確認。
3,D-004,MELMB,310D,現象再現せず。対象品番KLEE-55555は継続確認中。,現象再現せず。対象品番[PART]は継続確認中。
4,D-005,SUS,310D,2026/06/25にLCM-220で5件確認。160V条件で全数検査中。,[DATE]に[PART]で[QTY]確認。160V条件で全数検査中。

In [14]:
df_work["comment_public"] = df_work["comment_public"].str.replace(
    r"\d+V",
    "[VOLT]",
    regex=True,
)

In [15]:
df_work

,defect_id,site,model,comment,comment_public
0,D-001,SUS,J69P,2026/06/15にKLAK-67890で3件発生。160V条件で確認。,[DATE]に[PART]で[QTY]発生。[VOLT]条件で確認。
1,D-002,WSE,310D,2026/06/18にKLBC-12345で1件発生。140V検査では検出せず。,[DATE]に[PART]で[QTY]発生。[VOLT]検査では検出せず。
2,D-003,GSE,J69P,2026/06/20にPY-110相当品で2件再現。12V条件で確認。,[DATE]に[PART]相当品で[QTY]再現。[VOLT]条件で確認。
3,D-004,MELMB,310D,現象再現せず。対象品番KLEE-55555は継続確認中。,現象再現せず。対象品番[PART]は継続確認中。
4,D-005,SUS,310D,2026/06/25にLCM-220で5件確認。160V条件で全数検査中。,[DATE]に[PART]で[QTY]確認。[VOLT]条件で全数検査中。

In [16]:
df_result = df_work[
    [
        "defect_id",
        "site",
        "model",
        "comment",
        "comment_public",
    ]
]
df_result

,defect_id,site,model,comment,comment_public
0,D-001,SUS,J69P,2026/06/15にKLAK-67890で3件発生。160V条件で確認。,[DATE]に[PART]で[QTY]発生。[VOLT]条件で確認。
1,D-002,WSE,310D,2026/06/18にKLBC-12345で1件発生。140V検査では検出せず。,[DATE]に[PART]で[QTY]発生。[VOLT]検査では検出せず。
2,D-003,GSE,J69P,2026/06/20にPY-110相当品で2件再現。12V条件で確認。,[DATE]に[PART]相当品で[QTY]再現。[VOLT]条件で確認。
3,D-004,MELMB,310D,現象再現せず。対象品番KLEE-55555は継続確認中。,現象再現せず。対象品番[PART]は継続確認中。
4,D-005,SUS,310D,2026/06/25にLCM-220で5件確認。160V条件で全数検査中。,[DATE]に[PART]で[QTY]確認。[VOLT]条件で全数検査中。