###### Practical exercises 128-4

In [1]:
import pandas as pd

In [5]:
index = pd.Index(
    [
        "LCM-A",
        "LCM-B",
        "LCM-C",
        "LCM-D",
    ],
    name="product",
)

columns = pd.Index(
    [
        "melmb",
        "wse",
        "gse",
    ],
    name="site",
)

data = [
    [18, 25, 7],
    [12, 32, 9],
    [5, 14, 31],
    [8, 11, 4],
]

df_wide = pd.DataFrame(
    data,
    index=index,
    columns=columns,
)

df_wide

site     melmb  wse  gse
product
LCM-A       18   25    7
LCM-B       12   32    9
LCM-C        5   14   31
LCM-D        8   11    4

In [10]:
df_long = df_wide.melt(
    value_name="defect_qty",
    ignore_index=False
)

print(df_long)
df_long = df_long.reset_index()
df_long

          site  defect_qty
product
LCM-A    melmb          18
LCM-B    melmb          12
LCM-C    melmb           5
LCM-D    melmb           8
LCM-A      wse          25
LCM-B      wse          32
LCM-C      wse          14
LCM-D      wse          11
LCM-A      gse           7
LCM-B      gse           9
LCM-C      gse          31
LCM-D      gse           4

   product   site  defect_qty
0    LCM-A  melmb          18
1    LCM-B  melmb          12
2    LCM-C  melmb           5
3    LCM-D  melmb           8
4    LCM-A    wse          25
5    LCM-B    wse          32
6    LCM-C    wse          14
7    LCM-D    wse          11
8    LCM-A    gse           7
9    LCM-B    gse           9
10   LCM-C    gse          31
11   LCM-D    gse           4

In [11]:
df_long_sort = df_long.sort_values(
    "defect_qty",
    ascending=False,
)
df_long_sort

   product   site  defect_qty
5    LCM-B    wse          32
10   LCM-C    gse          31
4    LCM-A    wse          25
0    LCM-A  melmb          18
6    LCM-C    wse          14
1    LCM-B  melmb          12
7    LCM-D    wse          11
9    LCM-B    gse           9
3    LCM-D  melmb           8
8    LCM-A    gse           7
2    LCM-C  melmb           5
11   LCM-D    gse           4

In [13]:
df_long_sort["check_level"] = "通常確認"
#df_long_sort

df_long_sort.loc[
    df_long_sort["defect_qty"] >= 20,
    "check_level",
] = "重点確認"

df_long_sort

   product   site  defect_qty check_level
5    LCM-B    wse          32        重点確認
10   LCM-C    gse          31        重点確認
4    LCM-A    wse          25        重点確認
0    LCM-A  melmb          18        通常確認
6    LCM-C    wse          14        通常確認
1    LCM-B  melmb          12        通常確認
7    LCM-D    wse          11        通常確認
9    LCM-B    gse           9        通常確認
3    LCM-D  melmb           8        通常確認
8    LCM-A    gse           7        通常確認
2    LCM-C  melmb           5        通常確認
11   LCM-D    gse           4        通常確認

In [14]:
df_priority = df_long_sort[
    df_long_sort["check_level"] == "重点確認"
]

df_priority

   product site  defect_qty check_level
5    LCM-B  wse          32        重点確認
10   LCM-C  gse          31        重点確認
4    LCM-A  wse          25        重点確認

In [15]:
#次はセル７から　060618 14:16