###### 130_4_practical_site_model_defect_rank

In [1]:
import pandas as pd
pd.set_option("display.max_columns", None)

In [2]:
df_defect = pd.DataFrame(
    [
        ["D001", "SUS", "J69P", "コイル", 3],
        ["D002", "SUS", "J69P", "Buck-IC", 1],
        ["D003", "SUS", "310D", "NTF", 1],
        ["D004", "WSE", "310D", "コイル", 4],
        ["D005", "WSE", "310D", "NTF", 2],
        ["D006", "WSE", "J69P", "Buck-IC", 3],
        ["D007", "GSE", "J69P", "コイル", 2],
        ["D008", "GSE", "J69P", "Buck-IC", 3],
        ["D009", "GSE", "310D", "NTF", 2],
        ["D010", "SUS", "310D", "コイル", 0],
    ],
    columns=[
        "defect_id",
        "site",
        "model",
        "defect_category",
        "defect_qty",
    ],
)

df_defect

  defect_id site model defect_category  defect_qty
0      D001  SUS  J69P             コイル           3
1      D002  SUS  J69P         Buck-IC           1
2      D003  SUS  310D             NTF           1
3      D004  WSE  310D             コイル           4
4      D005  WSE  310D             NTF           2
5      D006  WSE  J69P         Buck-IC           3
6      D007  GSE  J69P             コイル           2
7      D008  GSE  J69P         Buck-IC           3
8      D009  GSE  310D             NTF           2
9      D010  SUS  310D             コイル           0

In [3]:
df_work = df_defect.copy()
df_work

  defect_id site model defect_category  defect_qty
0      D001  SUS  J69P             コイル           3
1      D002  SUS  J69P         Buck-IC           1
2      D003  SUS  310D             NTF           1
3      D004  WSE  310D             コイル           4
4      D005  WSE  310D             NTF           2
5      D006  WSE  J69P         Buck-IC           3
6      D007  GSE  J69P             コイル           2
7      D008  GSE  J69P         Buck-IC           3
8      D009  GSE  310D             NTF           2
9      D010  SUS  310D             コイル           0

In [4]:
df_work_positive = df_work[
    df_work["defect_qty"] > 0
].copy()
df_work_positive

  defect_id site model defect_category  defect_qty
0      D001  SUS  J69P             コイル           3
1      D002  SUS  J69P         Buck-IC           1
2      D003  SUS  310D             NTF           1
3      D004  WSE  310D             コイル           4
4      D005  WSE  310D             NTF           2
5      D006  WSE  J69P         Buck-IC           3
6      D007  GSE  J69P             コイル           2
7      D008  GSE  J69P         Buck-IC           3
8      D009  GSE  310D             NTF           2

In [5]:
df_summary = df_work_positive.groupby(
    [
        "site",
        "model",
    ],
    as_index=False,
)["defect_qty"].sum()
df_summary

  site model  defect_qty
0  GSE  310D           2
1  GSE  J69P           5
2  SUS  310D           1
3  SUS  J69P           4
4  WSE  310D           6
5  WSE  J69P           3

In [ ]:
#cell 3
df_summary = df_summary.rename(
    columns={
        "defect_qty": "defect_qty_total",
    }
)
df_summary

  site model  defect_qty_total
0  GSE  310D                 2
1  GSE  J69P                 5
2  SUS  310D                 1
3  SUS  J69P                 4
4  WSE  310D                 6
5  WSE  J69P                 3

In [7]:
df_summary["defect_rank"] = df_summary.groupby("site")["defect_qty_total"].rank(
    ascending=False
)
df_summary

  site model  defect_qty_total  defect_rank
0  GSE  310D                 2          2.0
1  GSE  J69P                 5          1.0
2  SUS  310D                 1          2.0
3  SUS  J69P                 4          1.0
4  WSE  310D                 6          1.0
5  WSE  J69P                 3          2.0

In [9]:
df_summary_soreted = df_summary.sort_values(
    [
        "site",
        "defect_rank",
    ]
).reset_index(drop=True)
df_summary_soreted

  site model  defect_qty_total  defect_rank
0  GSE  J69P                 5          1.0
1  GSE  310D                 2          2.0
2  SUS  J69P                 4          1.0
3  SUS  310D                 1          2.0
4  WSE  310D                 6          1.0
5  WSE  J69P                 3          2.0