## 「125-1: CSVファイル保存時の余計な列を除くには」 1問目

In [3]:
import pandas as pd

df = pd.DataFrame(
    [
        ["Alice", "国語", 87],
        ["Alice", "数学", 72],
        ["Bob", "国語", 65],
        ["Bob", "数学", 92],
    ],
    columns=["Name", "Subject", "Point"],
)
df.to_csv("result.csv", index=False)

## 演習問題

In [4]:
import pandas as pd

df_quality = pd.DataFrame(
    [
        ["melmb", "点灯不良", 10000, 3],
        ["wse", "外観不良",  8000, 5],
        ["gse", "ショート",  12000, 1],
        ["ise", "コネクタ浮き",  9000, 2],
    ],
    columns=["site", "defect", "production", "defects"],
)

In [8]:
df_quality["ppm"] = df_quality["defects"] / df_quality["production"] * 1000000
df_quality["ppm"] = df_quality["ppm"].round(1)
df_quality.to_csv("quality_result.csv", index=False)

In [9]:
df_quality.head()

    site  defect  production  defects    ppm
0  melmb    点灯不良       10000        3  300.0
1    wse    外観不良        8000        5  625.0
2    gse    ショート       12000        1   83.3
3    ise  コネクタ浮き        9000        2  222.2

In [11]:
df_quality

    site  defect  production  defects    ppm
0  melmb    点灯不良       10000        3  300.0
1    wse    外観不良        8000        5  625.0
2    gse    ショート       12000        1   83.3
3    ise  コネクタ浮き        9000        2  222.2