## 実務演習

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.DataFrame({
     '拠点': ['MELMB', 'WSE', 'GSE', 'ISE', 'SUS', 'MELMB', 'WSE', 'GSE', 'ISE', 'SUS'],
    '製品': ['LCM', 'LCM', 'LCM', 'LCM', 'LCM', 'H/L', 'H/L', 'H/L', 'H/L', 'H/L'],
    '不具合名': ['ネジゆるみ', 'ハンダ不足', 'コネクタずれ', 'ラベル間違い', '不点灯',
              '異音', 'キズ', '水入り', '点灯ちらつき', '通信エラー'],
    '生産数': [10000, 12000, 9000, 8000, 15000, 7000, 11000, 9500, 6000, 13000],
    '不良数': [5, 12, 9, 2, 20, 1, 15, 8, 10, 6],
    '重要度': ['中', '高', '高', '低', '高', '低', '中', '高', '高', '中']
})

In [3]:
df.head()

      拠点   製品    不具合名    生産数  不良数 重要度
0  MELMB  LCM   ネジゆるみ  10000    5   中
1    WSE  LCM   ハンダ不足  12000   12   高
2    GSE  LCM  コネクタずれ   9000    9   高
3    ISE  LCM  ラベル間違い   8000    2   低
4    SUS  LCM     不点灯  15000   20   高

In [4]:
df.tail()

      拠点   製品    不具合名    生産数  不良数 重要度
5  MELMB  H/L      異音   7000    1   低
6    WSE  H/L      キズ  11000   15   中
7    GSE  H/L     水入り   9500    8   高
8    ISE  H/L  点灯ちらつき   6000   10   高
9    SUS  H/L   通信エラー  13000    6   中

In [5]:
df["拠点"]

0    MELMB
1      WSE
2      GSE
3      ISE
4      SUS
5    MELMB
6      WSE
7      GSE
8      ISE
9      SUS
Name: 拠点, dtype: str

In [6]:
df["拠点"].unique()

<ArrowStringArray>
['MELMB', 'WSE', 'GSE', 'ISE', 'SUS']
Length: 5, dtype: str

In [7]:
df["ppm"] = df["不良数"] / df["生産数"] * 1000000
df["ppm"] = df["ppm"].round(1)
df.head()

      拠点   製品    不具合名    生産数  不良数 重要度     ppm
0  MELMB  LCM   ネジゆるみ  10000    5   中   500.0
1    WSE  LCM   ハンダ不足  12000   12   高  1000.0
2    GSE  LCM  コネクタずれ   9000    9   高  1000.0
3    ISE  LCM  ラベル間違い   8000    2   低   250.0
4    SUS  LCM     不点灯  15000   20   高  1333.3

In [9]:
df_wse = df[df["拠点"] == "WSE"]
df_wse

    拠点   製品   不具合名    生産数  不良数 重要度     ppm
1  WSE  LCM  ハンダ不足  12000   12   高  1000.0
6  WSE  H/L     キズ  11000   15   中  1363.6

In [10]:
defect_ranking = df_wse.loc[:, ["拠点", "製品", "不具合名", "不良数", "ppm", "重要度"]]
defect_ranking

    拠点   製品   不具合名  不良数     ppm 重要度
1  WSE  LCM  ハンダ不足   12  1000.0   高
6  WSE  H/L     キズ   15  1363.6   中

In [12]:
df["危険度"] = np.where(df["ppm"] >= 1000, "危険モンスター", "通常モンスター")
df.sort_values(by="ppm", ascending=False).head(10)

      拠点   製品    不具合名    生産数  不良数 重要度     ppm      危険度
8    ISE  H/L  点灯ちらつき   6000   10   高  1666.7  危険モンスター
6    WSE  H/L      キズ  11000   15   中  1363.6  危険モンスター
4    SUS  LCM     不点灯  15000   20   高  1333.3  危険モンスター
1    WSE  LCM   ハンダ不足  12000   12   高  1000.0  危険モンスター
2    GSE  LCM  コネクタずれ   9000    9   高  1000.0  危険モンスター
7    GSE  H/L     水入り   9500    8   高   842.1  通常モンスター
0  MELMB  LCM   ネジゆるみ  10000    5   中   500.0  通常モンスター
9    SUS  H/L   通信エラー  13000    6   中   461.5  通常モンスター
3    ISE  LCM  ラベル間違い   8000    2   低   250.0  通常モンスター
5  MELMB  H/L      異音   7000    1   低   142.9  通常モンスター

##  演習問題

In [13]:
import pandas as pd
import numpy as np

In [14]:
df = pd.DataFrame({
    '拠点': ['MELMB', 'WSE', 'GSE', 'ISE', 'SUS', 'MELMB', 'WSE', 'GSE', 'ISE', 'SUS'],
    '製品': ['LCM', 'LCM', 'LCM', 'LCM', 'LCM', 'H/L', 'H/L', 'H/L', 'H/L', 'H/L'],
    '不具合名': ['ネジゆるみ', 'ハンダ不足', 'コネクタずれ', 'ラベル間違い', '不点灯',
              '異音', 'キズ', '水入り', '点灯ちらつき', '通信エラー'],
    '生産数': [10000, 12000, 9000, 8000, 15000, 7000, 11000, 9500, 6000, 13000],
    '不良数': [5, 12, 9, 2, 20, 1, 15, 8, 10, 6],
    '重要度': ['中', '高', '高', '低', '高', '低', '中', '高', '高', '中']
})

In [15]:
df.head()

      拠点   製品    不具合名    生産数  不良数 重要度
0  MELMB  LCM   ネジゆるみ  10000    5   中
1    WSE  LCM   ハンダ不足  12000   12   高
2    GSE  LCM  コネクタずれ   9000    9   高
3    ISE  LCM  ラベル間違い   8000    2   低
4    SUS  LCM     不点灯  15000   20   高

In [16]:
df.tail()

      拠点   製品    不具合名    生産数  不良数 重要度
5  MELMB  H/L      異音   7000    1   低
6    WSE  H/L      キズ  11000   15   中
7    GSE  H/L     水入り   9500    8   高
8    ISE  H/L  点灯ちらつき   6000   10   高
9    SUS  H/L   通信エラー  13000    6   中

In [17]:
df["拠点"].unique()

<ArrowStringArray>
['MELMB', 'WSE', 'GSE', 'ISE', 'SUS']
Length: 5, dtype: str

In [19]:
df["ppm"] = df["不良数"] / df["生産数"] * 1000000
df["ppm"] = df["ppm"].round(1)
df["ppm"]

0     500.0
1    1000.0
2    1000.0
3     250.0
4    1333.3
5     142.9
6    1363.6
7     842.1
8    1666.7
9     461.5
Name: ppm, dtype: float64

In [21]:
df_gse = df[df["拠点"] == "GSE"]
df_gse.head()

    拠点   製品    不具合名   生産数  不良数 重要度     ppm
2  GSE  LCM  コネクタずれ  9000    9   高  1000.0
7  GSE  H/L     水入り  9500    8   高   842.1

In [22]:
defect_ranking = df_gse.loc[:, ["拠点", "製品", "不具合名", "不良数", "ppm", "重要度"]]
defect_ranking

    拠点   製品    不具合名  不良数     ppm 重要度
2  GSE  LCM  コネクタずれ    9  1000.0   高
7  GSE  H/L     水入り    8   842.1   高

In [23]:
defect_ranking = defect_ranking.sort_values(by="ppm", ascending=False)
defect_ranking

    拠点   製品    不具合名  不良数     ppm 重要度
2  GSE  LCM  コネクタずれ    9  1000.0   高
7  GSE  H/L     水入り    8   842.1   高

In [24]:
df["危険度"] = np.where(df["ppm"] >= 1000, "危険モンスター", "通常モンスター")
df.sort_values(by="ppm", ascending=False).head(10)

      拠点   製品    不具合名    生産数  不良数 重要度     ppm      危険度
8    ISE  H/L  点灯ちらつき   6000   10   高  1666.7  危険モンスター
6    WSE  H/L      キズ  11000   15   中  1363.6  危険モンスター
4    SUS  LCM     不点灯  15000   20   高  1333.3  危険モンスター
1    WSE  LCM   ハンダ不足  12000   12   高  1000.0  危険モンスター
2    GSE  LCM  コネクタずれ   9000    9   高  1000.0  危険モンスター
7    GSE  H/L     水入り   9500    8   高   842.1  通常モンスター
0  MELMB  LCM   ネジゆるみ  10000    5   中   500.0  通常モンスター
9    SUS  H/L   通信エラー  13000    6   中   461.5  通常モンスター
3    ISE  LCM  ラベル間違い   8000    2   低   250.0  通常モンスター
5  MELMB  H/L      異音   7000    1   低   142.9  通常モンスター

In [25]:
df_ise = df[df["拠点"] == "ISE"]

In [27]:
ise_ranking = df_ise.loc[:, ["拠点", "製品", "不具合名", "ppm", "重要度"]]
ise_ranking = ise_ranking.sort_values(by="ppm", ascending=False)
ise_ranking.head()

    拠点   製品    不具合名     ppm 重要度
8  ISE  H/L  点灯ちらつき  1666.7   高
3  ISE  LCM  ラベル間違い   250.0   低