## 「190-2: pandasの使い方を学ぼう」 3問目

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("./input/ramen-ratings.csv")
df.head()

,Review #,Brand,Variety,Style,Country,Stars,Top Ten
0,2580,New Touch,T's Restaurant Tantanmen,Cup,Japan,3.75,NaN
1,2579,Just Way,Noodles Spicy Hot Sesame Spicy Hot Sesame Guan...,Pack,Taiwan,1,NaN
2,2578,Nissin,Cup Noodles Chicken Vegetable,Cup,USA,2.25,NaN
3,2577,Wei Lih,GGE Ramen Snack Tomato Flavor,Pack,Taiwan,2.75,NaN
4,2576,Ching's Secret,Singapore Curry,Pack,India,3.75,NaN

In [3]:
df.tail()

,Review #,Brand,Variety,Style,Country,Stars,Top Ten
2575,5,Vifon,"Hu Tiu Nam Vang [""Phnom Penh"" style] Asian Sty...",Bowl,Vietnam,3.5,NaN
2576,4,Wai Wai,Oriental Style Instant Noodles,Pack,Thailand,1,NaN
2577,3,Wai Wai,Tom Yum Shrimp,Pack,Thailand,2,NaN
2578,2,Wai Wai,Tom Yum Chili Flavor,Pack,Thailand,2,NaN
2579,1,Westbrae,Miso Ramen,Pack,USA,0.5,NaN

In [5]:
df["Country"].unique()

<ArrowStringArray>
[        'Japan',        'Taiwan',           'USA',         'India',
   'South Korea',     'Singapore',      'Thailand',     'Hong Kong',
       'Vietnam',         'Ghana',      'Malaysia',     'Indonesia',
         'China',       'Nigeria',       'Germany',       'Hungary',
        'Mexico',          'Fiji',     'Australia',      'Pakistan',
    'Bangladesh',        'Canada',         'Nepal',        'Brazil',
            'UK',       'Myanmar',   'Netherlands', 'United States',
      'Cambodia',       'Finland',       'Sarawak',   'Philippines',
        'Sweden',      'Colombia',       'Estonia',       'Holland',
        'Poland',         'Dubai']
Length: 38, dtype: str

In [7]:
df_jpn = df[df["Country"] == "Japan"]
df_jpn.head()

,Review #,Brand,Variety,Style,Country,Stars,Top Ten
0,2580,New Touch,T's Restaurant Tantanmen,Cup,Japan,3.75,NaN
6,2574,Acecook,Spice Deli Tantan Men With Cilantro,Cup,Japan,4,NaN
7,2573,Ikeda Shoku,Nabeyaki Kitsune Udon,Tray,Japan,3.75,NaN
8,2572,Ripe'n'Dry,Hokkaido Soy Sauce Ramen,Pack,Japan,0.25,NaN
13,2567,Nissin,Deka Buto Kimchi Pork Flavor,Bowl,Japan,4.5,NaN

In [10]:
variety_stars = df_jpn.loc[:, ["Brand", "Variety", "Stars"]]
variety_stars.head()

          Brand                              Variety Stars
0     New Touch            T's Restaurant Tantanmen   3.75
6       Acecook  Spice Deli Tantan Men With Cilantro     4
7   Ikeda Shoku                Nabeyaki Kitsune Udon  3.75
8    Ripe'n'Dry             Hokkaido Soy Sauce Ramen  0.25
13       Nissin         Deka Buto Kimchi Pork Flavor   4.5

In [11]:
variety_stars.tail()

                Brand                                      Variety Stars
2554           Nissin        Soba Noodles With Mayo Mustard Squirt     4
2555           Nissin                     Demae Ramen Spicy Flavor     3
2556           Nissin  Demae Ramen Spicy Seafood With Chili Pepper     2
2567  Sapporo Ichiban                                    Chow Mein     5
2568  Sapporo Ichiban                                Shrimp Flavor   2.5

In [12]:
variety_stars = variety_stars.sort_values(by="Stars", ascending=False)
variety_stars.head()

      Brand                               Variety Stars
447  Nissin           Kimchi Chikin Ramen Donburi  5.00
454  Nissin                Mennippon Oumi Chanpon  5.00
585  Nissin  Cup Noodle Big Cheese Mexican Chilli  5.00
385  Nissin             Gyorai Inaniwa Chuka Soba   5.0
581  Nissin                            Curry Udon   5.0

In [ ]:
## 演習問題

In [13]:
import pandas as pd


df_quality = pd.DataFrame({
    "拠点": ["melmb", "wse", "gse", "ise", "sus", "melmb", "wse"],
    "不具合名": ["ねじゆるみ", "はんだ不足", "コネクタずれ", "ラベル間違い", "不点灯", "異音", "キズ"],
    "カテゴリ": ["組立", "はんだ", "部品", "表示", "電気", "機構", "外観"],
    "ppm": [500, 1000, 1000, 250, 1333, 143, 1364]
})

In [14]:
df_quality.head()

      拠点    不具合名 カテゴリ   ppm
0  melmb   ねじゆるみ   組立   500
1    wse   はんだ不足  はんだ  1000
2    gse  コネクタずれ   部品  1000
3    ise  ラベル間違い   表示   250
4    sus     不点灯   電気  1333

In [15]:
df_quality["拠点"].unique()

<ArrowStringArray>
['melmb', 'wse', 'gse', 'ise', 'sus']
Length: 5, dtype: str

In [16]:
df_wse = df_quality[df_quality["拠点"] == "wse"]
df_wse.head()

    拠点   不具合名 カテゴリ   ppm
1  wse  はんだ不足  はんだ  1000
6  wse     キズ   外観  1364

In [17]:
defect_ppm = df_quality.loc[:, ["不具合名", "カテゴリ", "ppm"]]
defect_ppm.head()

     不具合名 カテゴリ   ppm
0   ねじゆるみ   組立   500
1   はんだ不足  はんだ  1000
2  コネクタずれ   部品  1000
3  ラベル間違い   表示   250
4     不点灯   電気  1333

In [18]:
defect_ppm = defect_ppm.sort_values(by="ppm", ascending=False)

In [19]:
defect_ppm.head()

     不具合名 カテゴリ   ppm
6      キズ   外観  1364
4     不点灯   電気  1333
1   はんだ不足  はんだ  1000
2  コネクタずれ   部品  1000
0   ねじゆるみ   組立   500

In [20]:
df_melmb = df_quality[df_quality["拠点"] == "melmb"]
df_melmb.head()

      拠点   不具合名 カテゴリ  ppm
0  melmb  ねじゆるみ   組立  500
5  melmb     異音   機構  143

In [21]:
defect_ppm = df_quality.loc[:, ["不具合名", "カテゴリ", "ppm"]]

In [22]:
defect_ppm.head()

     不具合名 カテゴリ   ppm
0   ねじゆるみ   組立   500
1   はんだ不足  はんだ  1000
2  コネクタずれ   部品  1000
3  ラベル間違い   表示   250
4     不点灯   電気  1333

In [23]:
defect_ppm = defect_ppm.sort_values(by="ppm", ascending=False)

In [24]:
defect_ppm

     不具合名 カテゴリ   ppm
6      キズ   外観  1364
4     不点灯   電気  1333
1   はんだ不足  はんだ  1000
2  コネクタずれ   部品  1000
0   ねじゆるみ   組立   500
3  ラベル間違い   表示   250
5      異音   機構   143