In [1]:
import pandas as pd

df = pd.read_csv("./input/python_workshop.csv")
df.head()

,イベント名,開催日,会場,参加者数
0,GAE (Go/Python) もくもく勉強会 in 横浜タネマキ vol.56,2018-08-19,タネマキ,6
1,【上級】論文輪読&実装会 強化学習 DQN 2018/8/19,2018-08-19,(株)HCI 本社工場 2F 会議室,10
2,人工知能を使ったリアルタイム物体検出でIoTを実践するハンズオン,2018-08-19,江東区産業会館,5
3,『Pythonによるクローラー＆スクレイピング入門』読書会 #01,2018-08-19,蕨市民会館（303会議室）,0
4,機械学習を始めるためのpythonデータ分析実践（機械学習モデル構築）,2018-08-19,スキルアップビデオテクノロジーズ,7

In [2]:
df.tail()

,イベント名,開催日,会場,参加者数
293,Python勉強会（numpy 、Ansible、囲碁AI）,2018-07-01,未来会議室,7
294,【名古屋開催】【学生限定】初心者歓迎！PythonでBotを作ってみよう！,2018-07-01,ヤフー株式会社 名古屋オフィス,26
295,Tokyo Quantopian User Group Vol.04 商品先物を学ぼう,2018-07-01,株式会社Smart Trade,15
296,【未経験者・初心者向け】Python+Jupyterで学ぶプログラミングの基礎 #6,2018-07-01,水道橋駅周辺,6
297,機械学習を始めるためのpythonデータ分析実践（機械学習直前）,2018-07-01,スキルアップビデオテクノロジーズ,9

In [3]:
df[:10]

,イベント名,開催日,会場,参加者数
0,GAE (Go/Python) もくもく勉強会 in 横浜タネマキ vol.56,2018-08-19,タネマキ,6
1,【上級】論文輪読&実装会 強化学習 DQN 2018/8/19,2018-08-19,(株)HCI 本社工場 2F 会議室,10
2,人工知能を使ったリアルタイム物体検出でIoTを実践するハンズオン,2018-08-19,江東区産業会館,5
3,『Pythonによるクローラー＆スクレイピング入門』読書会 #01,2018-08-19,蕨市民会館（303会議室）,0
4,機械学習を始めるためのpythonデータ分析実践（機械学習モデル構築）,2018-08-19,スキルアップビデオテクノロジーズ,7
5,塩尻MLもくもく会 #07,2018-08-18,市民交流センターえんぱーく 2F 会議室203,7
6,Python機械学習勉強会in新潟Restart,2018-08-18,Prototype Cafe,25
7,PyCPA第3回勉強会,2018-08-18,colieto～コリエット～,8
8,【8月期 基礎数学シリーズ】機械学習・深層学習のための線形代数,2018-08-18,スキルアップビデオテクノロジーズ,0
9,【eLV】ICTを支える「考え方」シリーズ：S05-A物理学の考え方 (時空・ベクトル・テン...,2018-08-18,株式会社CRE-CO,5

In [4]:
df[20:25]

,イベント名,開催日,会場,参加者数
20,朝活Python 簡単スクレイピング（後編） in 秋葉原（秋葉原スクエア）,2018-08-17,【秋葉原/浅草橋】秋葉原スクエア403号室,12
21,夜活Python Webスクレイピング前編（0816） in 池袋,2018-08-16,池袋サンシャインシティ tully's coffee アルパ店,5
22,量子化学計算集中合宿２！OpenFermion+Cirqを一日中触る,2018-08-16,MDR株式会社,19
23,朝活Python 簡単スクレイピング（前編） in 秋葉原（秋葉原スクエア）,2018-08-16,【秋葉原/浅草橋】秋葉原スクエア403号室,8
24,【神田に移転！】Pythonアルゴリズム勉強会,2018-08-15,株式会社Smart Trade,18

In [5]:
df.loc[0:10, ["イベント名", "参加者数"]]

                                                イベント名  参加者数
0            GAE (Go/Python) もくもく勉強会 in 横浜タネマキ vol.56     6
1                     【上級】論文輪読&実装会 強化学習 DQN 2018/8/19    10
2                    人工知能を使ったリアルタイム物体検出でIoTを実践するハンズオン     5
3                   『Pythonによるクローラー＆スクレイピング入門』読書会 #01     0
4                 機械学習を始めるためのpythonデータ分析実践（機械学習モデル構築）     7
5                                       塩尻MLもくもく会 #07     7
6                            Python機械学習勉強会in新潟Restart    25
7                                         PyCPA第3回勉強会     8
8                     【8月期 基礎数学シリーズ】機械学習・深層学習のための線形代数     0
9   【eLV】ICTを支える「考え方」シリーズ：S05-A物理学の考え方 (時空・ベクトル・テン...     5
10                                    fin-pyもくもく会 #18    14

In [6]:
df.iloc[0:10, [0, 3]]

                                               イベント名  参加者数
0           GAE (Go/Python) もくもく勉強会 in 横浜タネマキ vol.56     6
1                    【上級】論文輪読&実装会 強化学習 DQN 2018/8/19    10
2                   人工知能を使ったリアルタイム物体検出でIoTを実践するハンズオン     5
3                  『Pythonによるクローラー＆スクレイピング入門』読書会 #01     0
4                機械学習を始めるためのpythonデータ分析実践（機械学習モデル構築）     7
5                                      塩尻MLもくもく会 #07     7
6                           Python機械学習勉強会in新潟Restart    25
7                                        PyCPA第3回勉強会     8
8                    【8月期 基礎数学シリーズ】機械学習・深層学習のための線形代数     0
9  【eLV】ICTを支える「考え方」シリーズ：S05-A物理学の考え方 (時空・ベクトル・テン...     5