## 190-2: pandasの使い方を学ぼう

In [2]:
import pandas as pd
import numpy as np

ser = pd.Series([10, 20, 30, 40])
ser

0    10
1    20
2    30
3    40
dtype: int64

In [3]:
df_list = pd.DataFrame([
    [10, "a", True],
    [20, "b", False],
    [30, "c", False],
    [40, "d", True]
])
df_list

    0  1      2
0  10  a   True
1  20  b  False
2  30  c  False
3  40  d   True

In [4]:
df_np = pd.DataFrame(np.arange(100).reshape(25, 4))
df_np.head()

    0   1   2   3
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15
4  16  17  18  19

In [5]:
df_np.tail()

     0   1   2   3
20  80  81  82  83
21  84  85  86  87
22  88  89  90  91
23  92  93  94  95
24  96  97  98  99

In [6]:
df_dict = pd.DataFrame({"A": [10, 20, 30, 40], "B":[100, 200, 300, 400]})
df_dict

    A    B
0  10  100
1  20  200
2  30  300
3  40  400

In [9]:
df_csv = pd.read_csv("./input/pycon_jp.csv")
df_csv.head()

,イベント名,開催日,会場,参加者数
0,PyCon JP 2017,2017-09-08,早稲田大学西早稲田キャンパス63号館,616
1,PyCon JP 2016,2016-09-21,早稲田大学西早稲田キャンパス63号館,656
2,PyCon JP 2015,2015-10-10,東京国際交流館プラザ平成/Tokyo International Exchange Cent...,542
3,PyCon JP 2014,2014-09-13,東京国際交流館プラザ平成/Tokyo International Exchange Cent...,485
4,PyCon APAC 2013 in Japan,2013-09-14,Kogakuin University / 工学院大学,402

In [10]:
df_csv.columns = ["Title", "Date", "Venue", "Participants"]
df_csv

,Title,Date,Venue,Participants
0,PyCon JP 2017,2017-09-08,早稲田大学西早稲田キャンパス63号館,616
1,PyCon JP 2016,2016-09-21,早稲田大学西早稲田キャンパス63号館,656
2,PyCon JP 2015,2015-10-10,東京国際交流館プラザ平成/Tokyo International Exchange Cent...,542
3,PyCon JP 2014,2014-09-13,東京国際交流館プラザ平成/Tokyo International Exchange Cent...,485
4,PyCon APAC 2013 in Japan,2013-09-14,Kogakuin University / 工学院大学,402
5,PyCon JP 2012,2012-09-15,産業技術大学院大学 / Advanced Institute of Industrial T...,400

## 演習問題

In [11]:
import pandas as pd

df_quality = pd.DataFrame({
    "site": ["melmb", "wse", "gse", "ise"],
    "production": [10000, 20000, 9000, 8000],
    "defects": [4, 12, 9, 2]
})

df_quality

    site  production  defects
0  melmb       10000        4
1    wse       20000       12
2    gse        9000        9
3    ise        8000        2

## 演習問題２

In [13]:
import pandas as pd

df_quality = pd.DataFrame({
    "site": ["melmb", "wse", "gse", "ise"],
    "production": [10000, 12000, 9000, 8000],
    "defects": [5, 1, 9, 2]
})

df_quality["ppm"] = (df_quality["defects"] / df_quality["production"] * 1000000).round(1)

df_quality

    site  production  defects     ppm
0  melmb       10000        5   500.0
1    wse       12000        1    83.3
2    gse        9000        9  1000.0
3    ise        8000        2   250.0