In [29]:
import pandas as pd
df = pd.read_csv("dataset/calories.csv", parse_dates=["日時"])
df.head()

                   日時  種別   カロリー   スキップ   備考
0 2022-03-01 07:15:18  朝食  180.0  False  NaN
1 2022-03-01 12:22:00  昼食    1.0  False  NaN
2 2022-03-01 16:15:00  間食   81.0  False  NaN
3 2022-03-01 20:23:00  夕食  450.0  False  NaN
4 2022-03-02 07:15:18  朝食  220.0  False  NaN

In [30]:
df_select_na = df[df["カロリー"].isna()]
df_select_na

                    日時  種別  カロリー   スキップ     備考
45 2022-03-14 07:15:18  朝食   NaN  False     寝坊
60 2022-03-18 12:22:00  昼食   NaN  False  急ぎで軽食
89 2022-03-26 20:23:00  夕食   NaN  False    飲み会

In [31]:
df_select_low = df[df["カロリー"] < 5]
df_select_low

                   日時  種別  カロリー   スキップ   備考
1 2022-03-01 12:22:00  昼食   1.0  False  NaN

In [32]:
df= df[~(df["カロリー"].isna() & (df["スキップ"] == False))]
df

                     日時  種別   カロリー   スキップ   備考
0   2022-03-01 07:15:18  朝食  180.0  False  NaN
1   2022-03-01 12:22:00  昼食    1.0  False  NaN
2   2022-03-01 16:15:00  間食   81.0  False  NaN
3   2022-03-01 20:23:00  夕食  450.0  False  NaN
4   2022-03-02 07:15:18  朝食  220.0  False  NaN
..                  ...  ..    ...    ...  ...
104 2022-03-30 20:23:00  夕食  700.0  False  NaN
105 2022-03-31 07:15:18  朝食  540.0  False  NaN
106 2022-03-31 12:22:00  昼食  700.0  False  NaN
107 2022-03-31 16:15:00  間食  183.0  False  NaN
108 2022-03-31 20:23:00  夕食  610.0  False  NaN

[106 rows x 5 columns]

In [33]:
mean_lunch = df[(df["種別"] == "昼食") & (df["カロリー"] > 1)]["カロリー"].mean()
mean_lunch

np.float64(611.1851851851852)

In [34]:
df.loc[df["カロリー"] == 1, "カロリー"] = mean_lunch
df

                     日時  種別        カロリー   スキップ   備考
0   2022-03-01 07:15:18  朝食  180.000000  False  NaN
1   2022-03-01 12:22:00  昼食  611.185185  False  NaN
2   2022-03-01 16:15:00  間食   81.000000  False  NaN
3   2022-03-01 20:23:00  夕食  450.000000  False  NaN
4   2022-03-02 07:15:18  朝食  220.000000  False  NaN
..                  ...  ..         ...    ...  ...
104 2022-03-30 20:23:00  夕食  700.000000  False  NaN
105 2022-03-31 07:15:18  朝食  540.000000  False  NaN
106 2022-03-31 12:22:00  昼食  700.000000  False  NaN
107 2022-03-31 16:15:00  間食  183.000000  False  NaN
108 2022-03-31 20:23:00  夕食  610.000000  False  NaN

[106 rows x 5 columns]

In [35]:
df.loc[23, :]

日時      2022-03-07 16:15:00
種別                       間食
カロリー                  100.0
スキップ                  False
備考                      NaN
Name: 23, dtype: object

In [ ]:
df.loc[36, :]

KeyError: 45

In [ ]:
49 in df.index, 98 in df.index

(True, True)