In [30]:
import pandas as pd

#step2で作成したcsvを読み込む
df = pd.read_csv(
    "dataset/calories.csv",
    parse_dates=["日時"]
)
df.head()

                   日時  種別   カロリー   スキップ   備考
0 2022-03-01 07:15:18  朝食  180.0  False  NaN
1 2022-03-01 12:22:00  昼食    1.0  False  NaN
2 2022-03-01 16:15:00  間食   81.0  False  NaN
3 2022-03-01 20:23:00  夕食  450.0  False  NaN
4 2022-03-02 07:15:18  朝食  220.0  False  NaN

In [31]:
# resampleを使うため、日時をインデックスにする
df = df.set_index("日時")
df.head()

                     種別   カロリー   スキップ   備考
日時
2022-03-01 07:15:18  朝食  180.0  False  NaN
2022-03-01 12:22:00  昼食    1.0  False  NaN
2022-03-01 16:15:00  間食   81.0  False  NaN
2022-03-01 20:23:00  夕食  450.0  False  NaN
2022-03-02 07:15:18  朝食  220.0  False  NaN

In [32]:
summary_df = df.resample("D")[["カロリー", "スキップ"]].sum()
summary_df.head()

              カロリー  スキップ
日時
2022-03-01   712.0     0
2022-03-02   920.0     0
2022-03-03  1130.0     0
2022-03-04  1235.0     0
2022-03-05  1220.0     0

In [33]:
summary_df = summary_df.rename(
    columns= {"カロリー": "合計カロリー", "スキップ": "スキップ件数"}
)
summary_df.head()

            合計カロリー  スキップ件数
日時
2022-03-01   712.0       0
2022-03-02   920.0       0
2022-03-03  1130.0       0
2022-03-04  1235.0       0
2022-03-05  1220.0       0

In [34]:
names = df["種別"].unique()
names

<StringArray>
['朝食', '昼食', '間食', '夕食']
Length: 4, dtype: str

In [35]:
for category in names:
    selected_df= df[df["種別"] == category]
    summary_df[category] = selected_df.resample("D")["カロリー"].sum()
summary_df.head()

            合計カロリー  スキップ件数     朝食     昼食    間食     夕食
日時
2022-03-01   712.0       0  180.0    1.0  81.0  450.0
2022-03-02   920.0       0  220.0  220.0   0.0  480.0
2022-03-03  1130.0       0  260.0  280.0  90.0  500.0
2022-03-04  1235.0       0  300.0  320.0  95.0  520.0
2022-03-05  1220.0       0  320.0  360.0   0.0  540.0

In [36]:
def is_ok(sr):
    result_morning = sr["朝食"] >= 400
    result_lunch = sr["昼食"] >= 400
    result_dinner = sr["夕食"] >= 400
    result_all = (1500 <= sr["合計カロリー"]) & (sr["合計カロリー"] <= 2100)

    result_sr = (sr["スキップ件数"] >= 1) | (
        result_morning & result_lunch & result_dinner & result_all
    )
    return result_sr

In [37]:
summary_df["デイリー目標OK"] = summary_df.apply(is_ok, axis=1)
summary_df.head()

            合計カロリー  スキップ件数     朝食     昼食    間食     夕食  デイリー目標OK
日時
2022-03-01   712.0       0  180.0    1.0  81.0  450.0     False
2022-03-02   920.0       0  220.0  220.0   0.0  480.0     False
2022-03-03  1130.0       0  260.0  280.0  90.0  500.0     False
2022-03-04  1235.0       0  300.0  320.0  95.0  520.0     False
2022-03-05  1220.0       0  320.0  360.0   0.0  540.0     False

In [38]:
summary_df.index.name = "日付"
summary_df.head()

            合計カロリー  スキップ件数     朝食     昼食    間食     夕食  デイリー目標OK
日付
2022-03-01   712.0       0  180.0    1.0  81.0  450.0     False
2022-03-02   920.0       0  220.0  220.0   0.0  480.0     False
2022-03-03  1130.0       0  260.0  280.0  90.0  500.0     False
2022-03-04  1235.0       0  300.0  320.0  95.0  520.0     False
2022-03-05  1220.0       0  320.0  360.0   0.0  540.0     False

In [39]:
import pandas as pd
df = pd.read_csv("dataset/calories.csv", parse_dates=["日時"])
df.head()

                   日時  種別   カロリー   スキップ   備考
0 2022-03-01 07:15:18  朝食  180.0  False  NaN
1 2022-03-01 12:22:00  昼食    1.0  False  NaN
2 2022-03-01 16:15:00  間食   81.0  False  NaN
3 2022-03-01 20:23:00  夕食  450.0  False  NaN
4 2022-03-02 07:15:18  朝食  220.0  False  NaN

In [40]:
df = df.set_index("日時")
df.head()

                     種別   カロリー   スキップ   備考
日時
2022-03-01 07:15:18  朝食  180.0  False  NaN
2022-03-01 12:22:00  昼食    1.0  False  NaN
2022-03-01 16:15:00  間食   81.0  False  NaN
2022-03-01 20:23:00  夕食  450.0  False  NaN
2022-03-02 07:15:18  朝食  220.0  False  NaN

In [41]:
summary_df = df.resample("D")[["カロリー", "スキップ"]].sum()
summary_df.head()

              カロリー  スキップ
日時
2022-03-01   712.0     0
2022-03-02   920.0     0
2022-03-03  1130.0     0
2022-03-04  1235.0     0
2022-03-05  1220.0     0

In [42]:
summary_df = summary_df.rename(
    columns={"カロリー": "合計カロリー", "スキップ": "スキップ件数"}
)
summary_df.head()

            合計カロリー  スキップ件数
日時
2022-03-01   712.0       0
2022-03-02   920.0       0
2022-03-03  1130.0       0
2022-03-04  1235.0       0
2022-03-05  1220.0       0

In [43]:
names = df["種別"].unique()
names

<StringArray>
['朝食', '昼食', '間食', '夕食']
Length: 4, dtype: str

In [44]:
names = df["種別"].unique()
names

<StringArray>
['朝食', '昼食', '間食', '夕食']
Length: 4, dtype: str

In [45]:
for category in names:
    selected_df = df[df["種別"] == category]
    summary_df[category] = selected_df.resample("D")["カロリー"].sum()
summary_df.head()

            合計カロリー  スキップ件数     朝食     昼食    間食     夕食
日時
2022-03-01   712.0       0  180.0    1.0  81.0  450.0
2022-03-02   920.0       0  220.0  220.0   0.0  480.0
2022-03-03  1130.0       0  260.0  280.0  90.0  500.0
2022-03-04  1235.0       0  300.0  320.0  95.0  520.0
2022-03-05  1220.0       0  320.0  360.0   0.0  540.0

In [47]:
def is_ok(sr):
    result_morning = sr["朝食"] >= 400
    result_lunch = sr["昼食"] >= 400
    result_dinner = sr["夕食"] >= 400
    result_all = (1500 <= sr["合計カロリー"]) & (sr["合計カロリー"] <= 2100)

    result_sr = (sr["スキップ件数"] >= 1) | (
        result_morning & result_lunch & result_dinner & result_all  
    )
    return result_sr
summary_df["デイリー目標OK"] = summary_df.apply(is_ok, axis=1)
summary_df.head()

            合計カロリー  スキップ件数     朝食     昼食    間食     夕食  デイリー目標OK
日時
2022-03-01   712.0       0  180.0    1.0  81.0  450.0     False
2022-03-02   920.0       0  220.0  220.0   0.0  480.0     False
2022-03-03  1130.0       0  260.0  280.0  90.0  500.0     False
2022-03-04  1235.0       0  300.0  320.0  95.0  520.0     False
2022-03-05  1220.0       0  320.0  360.0   0.0  540.0     False

In [48]:
summary_df.index.name = "日付"
summary_df.head()

            合計カロリー  スキップ件数     朝食     昼食    間食     夕食  デイリー目標OK
日付
2022-03-01   712.0       0  180.0    1.0  81.0  450.0     False
2022-03-02   920.0       0  220.0  220.0   0.0  480.0     False
2022-03-03  1130.0       0  260.0  280.0  90.0  500.0     False
2022-03-04  1235.0       0  300.0  320.0  95.0  520.0     False
2022-03-05  1220.0       0  320.0  360.0   0.0  540.0     False