In [51]:
import pandas as pd
df = pd.read_csv("dataset/calories.csv", parse_dates=["日付"]
)
df.head()

                   日付  種別   カロリー   スキップ   備考
0 2022-03-01 07:15:18  朝食  180.0  False  NaN
1 2022-03-01 12:22:00  昼食    1.0  False  NaN
2 2022-03-01 16:15:00  間食   81.0  False  NaN
3 2022-03-01 20:23:00  夕食  450.0  False  NaN
4 2022-03-02 07:15:18  朝食  220.0  False  NaN

In [52]:
df[df["カロリー"].isna()]

                    日付  種別  カロリー   スキップ     備考
45 2022-03-14 07:15:18  朝食   NaN  False     寝坊
60 2022-03-18 12:22:00  昼食   NaN  False  急ぎで軽食
89 2022-03-26 20:23:00  夕食   NaN  False    飲み会

In [53]:
df[df["カロリー"] < 5]

                   日付  種別  カロリー   スキップ   備考
1 2022-03-01 12:22:00  昼食   1.0  False  NaN

In [54]:
df = df[~(df["カロリー"] < 5)]
df

                     日付  種別   カロリー   スキップ     備考
0   2022-03-01 07:15:18  朝食  180.0  False    NaN
2   2022-03-01 16:15:00  間食   81.0  False    NaN
3   2022-03-01 20:23:00  夕食  450.0  False    NaN
4   2022-03-02 07:15:18  朝食  220.0  False    NaN
5   2022-03-02 12:22:00  昼食  220.0  False  会議で遅め
..                  ...  ..    ...    ...    ...
104 2022-03-30 20:23:00  夕食  700.0  False    NaN
105 2022-03-31 07:15:18  朝食  540.0  False    NaN
106 2022-03-31 12:22:00  昼食  700.0  False    NaN
107 2022-03-31 16:15:00  間食  183.0  False    NaN
108 2022-03-31 20:23:00  夕食  610.0  False    NaN

[108 rows x 5 columns]

In [55]:
mean_lunch = df.loc[
    (df["種別"] == "昼食") & (df["カロリー"] > 1),
    "カロリー"
].mean()
mean_lunch

np.float64(611.1851851851852)

In [56]:
df.loc[
    (df["種別"] == "昼食") & (df["カロリー"].isna()),
    "カロリー"
] = mean_lunch
df.head()

                   日付  種別   カロリー   スキップ     備考
0 2022-03-01 07:15:18  朝食  180.0  False    NaN
2 2022-03-01 16:15:00  間食   81.0  False    NaN
3 2022-03-01 20:23:00  夕食  450.0  False    NaN
4 2022-03-02 07:15:18  朝食  220.0  False    NaN
5 2022-03-02 12:22:00  昼食  220.0  False  会議で遅め

In [57]:
df = df.set_index("日付")
df.head()

                     種別   カロリー   スキップ     備考
日付
2022-03-01 07:15:18  朝食  180.0  False    NaN
2022-03-01 16:15:00  間食   81.0  False    NaN
2022-03-01 20:23:00  夕食  450.0  False    NaN
2022-03-02 07:15:18  朝食  220.0  False    NaN
2022-03-02 12:22:00  昼食  220.0  False  会議で遅め

In [58]:
daily_total = df["カロリー"].resample("D").sum().to_frame()
daily_total.head()

              カロリー
日付
2022-03-01   711.0
2022-03-02   920.0
2022-03-03  1130.0
2022-03-04  1235.0
2022-03-05  1220.0

In [59]:
meal_types = df["種別"].unique()
meal_types

<StringArray>
['朝食', '間食', '夕食', '昼食']
Length: 4, dtype: str

In [60]:
for meal in meal_types:
    daily_total[meal] = df.loc[df["種別"] == meal, "カロリー"].resample("D").sum()
daily_total.head()

              カロリー     朝食    間食     夕食     昼食
日付
2022-03-01   711.0  180.0  81.0  450.0    NaN
2022-03-02   920.0  220.0   0.0  480.0  220.0
2022-03-03  1130.0  260.0  90.0  500.0  280.0
2022-03-04  1235.0  300.0  95.0  520.0  320.0
2022-03-05  1220.0  320.0   0.0  540.0  360.0

In [61]:
daily_total = daily_total.fillna(0)
daily_total

                   カロリー     朝食     間食      夕食           昼食
日付
2022-03-01   711.000000  180.0   81.0   450.0     0.000000
2022-03-02   920.000000  220.0    0.0   480.0   220.000000
2022-03-03  1130.000000  260.0   90.0   500.0   280.000000
2022-03-04  1235.000000  300.0   95.0   520.0   320.000000
2022-03-05  1220.000000  320.0    0.0   540.0   360.000000
2022-03-06  1060.000000    0.0  100.0   560.0   400.000000
2022-03-07  1404.000000  340.0  100.0   564.0   400.000000
2022-03-08   920.000000  340.0    0.0   580.0     0.000000
2022-03-09  1490.000000  360.0  100.0   600.0   430.000000
2022-03-10  1580.000000  380.0  110.0   620.0   470.000000
2022-03-11   920.000000  400.0    0.0     0.0   520.000000
2022-03-12  1728.000000  420.0  120.0   628.0   560.000000
2022-03-13  1781.000000  440.0  130.0   632.0   579.000000
2022-03-14  1212.000000    0.0    0.0   632.0   580.000000
2022-03-15  1870.000000  460.0  140.0   650.0   620.000000
2022-03-16  1980.000000  480.0  160.0   680.0   660.000000
2022-03-17  1900.000000  480.0    0.0   720.0   700.000000
2022-03-18  2031.185185  500.0  160.0   760.0   611.185185
2022-03-19  2220.000000  520.0  160.0   800.0   740.000000
2022-03-20  1586.000000    0.0    0.0   835.0   751.000000
2022-03-21  1545.000000  540.0  170.0   835.0     0.000000
2022-03-22  2312.000000  540.0  180.0   840.0   752.000000
2022-03-23  2180.000000  540.0    0.0   860.0   780.000000
2022-03-24  2440.000000  540.0  180.0   900.0   820.000000
2022-03-25  2520.000000  540.0  180.0   940.0   860.000000
2022-03-26  1440.000000  540.0    0.0     0.0   900.000000
2022-03-27  2640.000000  540.0  180.0   980.0   940.000000
2022-03-28  2720.000000  540.0  180.0  1000.0  1000.000000
2022-03-29  2213.000000  540.0    0.0  1053.0   620.000000
2022-03-30  1960.000000  540.0  180.0   700.0   540.000000
2022-03-31  2033.000000  540.0  183.0   610.0   700.000000

In [62]:
daily_total = daily_total.rename(columns={"カロリー": "合計カロリー"})
daily_total

                 合計カロリー     朝食     間食      夕食           昼食
日付
2022-03-01   711.000000  180.0   81.0   450.0     0.000000
2022-03-02   920.000000  220.0    0.0   480.0   220.000000
2022-03-03  1130.000000  260.0   90.0   500.0   280.000000
2022-03-04  1235.000000  300.0   95.0   520.0   320.000000
2022-03-05  1220.000000  320.0    0.0   540.0   360.000000
2022-03-06  1060.000000    0.0  100.0   560.0   400.000000
2022-03-07  1404.000000  340.0  100.0   564.0   400.000000
2022-03-08   920.000000  340.0    0.0   580.0     0.000000
2022-03-09  1490.000000  360.0  100.0   600.0   430.000000
2022-03-10  1580.000000  380.0  110.0   620.0   470.000000
2022-03-11   920.000000  400.0    0.0     0.0   520.000000
2022-03-12  1728.000000  420.0  120.0   628.0   560.000000
2022-03-13  1781.000000  440.0  130.0   632.0   579.000000
2022-03-14  1212.000000    0.0    0.0   632.0   580.000000
2022-03-15  1870.000000  460.0  140.0   650.0   620.000000
2022-03-16  1980.000000  480.0  160.0   680.0   660.000000
2022-03-17  1900.000000  480.0    0.0   720.0   700.000000
2022-03-18  2031.185185  500.0  160.0   760.0   611.185185
2022-03-19  2220.000000  520.0  160.0   800.0   740.000000
2022-03-20  1586.000000    0.0    0.0   835.0   751.000000
2022-03-21  1545.000000  540.0  170.0   835.0     0.000000
2022-03-22  2312.000000  540.0  180.0   840.0   752.000000
2022-03-23  2180.000000  540.0    0.0   860.0   780.000000
2022-03-24  2440.000000  540.0  180.0   900.0   820.000000
2022-03-25  2520.000000  540.0  180.0   940.0   860.000000
2022-03-26  1440.000000  540.0    0.0     0.0   900.000000
2022-03-27  2640.000000  540.0  180.0   980.0   940.000000
2022-03-28  2720.000000  540.0  180.0  1000.0  1000.000000
2022-03-29  2213.000000  540.0    0.0  1053.0   620.000000
2022-03-30  1960.000000  540.0  180.0   700.0   540.000000
2022-03-31  2033.000000  540.0  183.0   610.0   700.000000

In [63]:
weekly_total = df["カロリー"].resample("W").sum().to_frame()
weekly_total

                    カロリー
日付
2022-03-06   6276.000000
2022-03-13   9823.000000
2022-03-20  12799.185185
2022-03-27  15077.000000
2022-04-03   8926.000000

In [64]:
mean_dinner = df.loc[
    (df["種別"] == "夕食") & (df["カロリー"] > 1),
    "カロリー"
].mean()
mean_dinner

np.float64(705.8275862068965)

In [65]:
selected_meals = ["朝食", "夕食"]
daily_small = df["カロリー"].resample("D").sum().to_frame()

for meal in selected_meals:
    daily_small[meal] = df.loc[df["種別"] == meal, "カロリー"].resample("D").sum()

daily_small = daily_small.fillna(0)
daily_small

                   カロリー     朝食      夕食
日付
2022-03-01   711.000000  180.0   450.0
2022-03-02   920.000000  220.0   480.0
2022-03-03  1130.000000  260.0   500.0
2022-03-04  1235.000000  300.0   520.0
2022-03-05  1220.000000  320.0   540.0
2022-03-06  1060.000000    0.0   560.0
2022-03-07  1404.000000  340.0   564.0
2022-03-08   920.000000  340.0   580.0
2022-03-09  1490.000000  360.0   600.0
2022-03-10  1580.000000  380.0   620.0
2022-03-11   920.000000  400.0     0.0
2022-03-12  1728.000000  420.0   628.0
2022-03-13  1781.000000  440.0   632.0
2022-03-14  1212.000000    0.0   632.0
2022-03-15  1870.000000  460.0   650.0
2022-03-16  1980.000000  480.0   680.0
2022-03-17  1900.000000  480.0   720.0
2022-03-18  2031.185185  500.0   760.0
2022-03-19  2220.000000  520.0   800.0
2022-03-20  1586.000000    0.0   835.0
2022-03-21  1545.000000  540.0   835.0
2022-03-22  2312.000000  540.0   840.0
2022-03-23  2180.000000  540.0   860.0
2022-03-24  2440.000000  540.0   900.0
2022-03-25  2520.000000  540.0   940.0
2022-03-26  1440.000000  540.0     0.0
2022-03-27  2640.000000  540.0   980.0
2022-03-28  2720.000000  540.0  1000.0
2022-03-29  2213.000000  540.0  1053.0
2022-03-30  1960.000000  540.0   700.0
2022-03-31  2033.000000  540.0   610.0

In [66]:
daily_total = daily_total.fillna(0).astype(int)
daily_total

            合計カロリー   朝食   間食    夕食    昼食
日付
2022-03-01     711  180   81   450     0
2022-03-02     920  220    0   480   220
2022-03-03    1130  260   90   500   280
2022-03-04    1235  300   95   520   320
2022-03-05    1220  320    0   540   360
2022-03-06    1060    0  100   560   400
2022-03-07    1404  340  100   564   400
2022-03-08     920  340    0   580     0
2022-03-09    1490  360  100   600   430
2022-03-10    1580  380  110   620   470
2022-03-11     920  400    0     0   520
2022-03-12    1728  420  120   628   560
2022-03-13    1781  440  130   632   579
2022-03-14    1212    0    0   632   580
2022-03-15    1870  460  140   650   620
2022-03-16    1980  480  160   680   660
2022-03-17    1900  480    0   720   700
2022-03-18    2031  500  160   760   611
2022-03-19    2220  520  160   800   740
2022-03-20    1586    0    0   835   751
2022-03-21    1545  540  170   835     0
2022-03-22    2312  540  180   840   752
2022-03-23    2180  540    0   860   780
2022-03-24    2440  540  180   900   820
2022-03-25    2520  540  180   940   860
2022-03-26    1440  540    0     0   900
2022-03-27    2640  540  180   980   940
2022-03-28    2720  540  180  1000  1000
2022-03-29    2213  540    0  1053   620
2022-03-30    1960  540  180   700   540
2022-03-31    2033  540  183   610   700