In [2]:
import pandas as pd
df = pd.read_csv("dataset/calories.csv", parse_dates=["日時"])
df.head()

                   日時  種別   カロリー   スキップ   備考
0 2022-03-01 07:15:18  朝食  180.0  False  NaN
1 2022-03-01 12:22:00  昼食    1.0  False  NaN
2 2022-03-01 16:15:00  間食   81.0  False  NaN
3 2022-03-01 20:23:00  夕食  450.0  False  NaN
4 2022-03-02 07:15:18  朝食  220.0  False  NaN

In [3]:
df_shape = df.shape
df_shape

(109, 5)

In [4]:
na_count = df.isna().sum()
na_count

日時        0
種別        0
カロリー      3
スキップ      0
備考      104
dtype: int64

In [9]:
category_values = df["種別"].unique()
category_values

<StringArray>
['朝食', '昼食', '間食', '夕食']
Length: 4, dtype: str

In [10]:
df_group_desc = df.groupby("種別")["カロリー"].describe()
df_group_desc

    count        mean         std    min    25%    50%     75%     max
種別
夕食   29.0  705.827586  167.811771  450.0  580.0  650.0  835.00  1053.0
昼食   28.0  589.392857  234.172829    1.0  422.5  600.0  751.25  1000.0
朝食   28.0  440.714286  111.883821  180.0  355.0  480.0  540.00   540.0
間食   21.0  141.857143   37.203878   81.0  100.0  160.0  180.00   183.0

In [11]:
df.sort_values("カロリー").head(9)

                    日時  種別   カロリー   スキップ   備考
1  2022-03-01 12:22:00  昼食    1.0  False  NaN
2  2022-03-01 16:15:00  間食   81.0  False  NaN
9  2022-03-03 16:15:00  間食   90.0  False  NaN
13 2022-03-04 16:15:00  間食   95.0  False  NaN
23 2022-03-07 16:15:00  間食  100.0  False  NaN
29 2022-03-09 16:15:00  間食  100.0  False  NaN
19 2022-03-06 16:15:00  間食  100.0  False  NaN
33 2022-03-10 16:15:00  間食  110.0  False  NaN
39 2022-03-12 16:15:00  間食  120.0  False  NaN

In [12]:
df.sort_values("カロリー", ascending=False).head()

                     日時  種別    カロリー   スキップ   備考
100 2022-03-29 20:23:00  夕食  1053.0  False  NaN
95  2022-03-28 12:22:00  昼食  1000.0  False  NaN
97  2022-03-28 20:23:00  夕食  1000.0  False  NaN
93  2022-03-27 20:23:00  夕食   980.0  False  NaN
91  2022-03-27 12:22:00  昼食   940.0  False  NaN

In [14]:
print("【df_shape】")
print(df_shape)
print()

print("【na_count】")
print(na_count)
print()

print("【category_values】")
print(category_values)
print()

print("【df_group_desc】")
print(df_group_desc)

【df_shape】
(109, 5)

【na_count】
日時        0
種別        0
カロリー      3
スキップ      0
備考      104
dtype: int64

【category_values】
<StringArray>
['朝食', '昼食', '間食', '夕食']
Length: 4, dtype: str

【df_group_desc】
    count        mean         std    min    25%    50%     75%     max
種別
夕食   29.0  705.827586  167.811771  450.0  580.0  650.0  835.00  1053.0
昼食   28.0  589.392857  234.172829    1.0  422.5  600.0  751.25  1000.0
朝食   28.0  440.714286  111.883821  180.0  355.0  480.0  540.00   540.0
間食   21.0  141.857143   37.203878   81.0  100.0  160.0  180.00   183.0

In [15]:
df["種別"].value_counts()

種別
夕食    30
朝食    29
昼食    29
間食    21
Name: count, dtype: int64

In [16]:
df["カロリー"].describe()

count     106.000000
mean      493.311321
std       255.871373
min         1.000000
25%       285.000000
50%       540.000000
75%       645.500000
max      1053.000000
Name: カロリー, dtype: float64

In [19]:
df[df["日時"].isna()]

Empty DataFrame
Columns: [日時, 種別, カロリー, スキップ, 備考]
Index: []

In [21]:
df[df["カロリー"] < 200]

                     日時  種別   カロリー   スキップ   備考
0   2022-03-01 07:15:18  朝食  180.0  False  NaN
1   2022-03-01 12:22:00  昼食    1.0  False  NaN
2   2022-03-01 16:15:00  間食   81.0  False  NaN
9   2022-03-03 16:15:00  間食   90.0  False  NaN
13  2022-03-04 16:15:00  間食   95.0  False  NaN
19  2022-03-06 16:15:00  間食  100.0  False  NaN
23  2022-03-07 16:15:00  間食  100.0  False  NaN
29  2022-03-09 16:15:00  間食  100.0  False  NaN
33  2022-03-10 16:15:00  間食  110.0  False  NaN
39  2022-03-12 16:15:00  間食  120.0  False  NaN
43  2022-03-13 16:15:00  間食  130.0  False  NaN
50  2022-03-15 16:15:00  間食  140.0  False  NaN
54  2022-03-16 16:15:00  間食  160.0  False  NaN
61  2022-03-18 16:15:00  間食  160.0  False  NaN
65  2022-03-19 16:15:00  間食  160.0  False  NaN
70  2022-03-21 16:15:00  間食  170.0  False  NaN
74  2022-03-22 16:15:00  間食  180.0  False  NaN
81  2022-03-24 16:15:00  間食  180.0  False  NaN
85  2022-03-25 16:15:00  間食  180.0  False  NaN
92  2022-03-27 16:15:00  間食  180.0  False  NaN
96  2022-03-28 16:15:00  間食  180.0  False  NaN
103 2022-03-30 16:15:00  間食  180.0  False  NaN
107 2022-03-31 16:15:00  間食  183.0  False  NaN

In [22]:
df.groupby("種別")["カロリー"].mean()

種別
夕食    705.827586
昼食    589.392857
朝食    440.714286
間食    141.857143
Name: カロリー, dtype: float64