###### *132_1_datetime_convert_basic_answer.ipynb*

In [1]:
import pandas as pd
pd.set_option("display.max_columns", None)

In [2]:
df = pd.read_csv("dataset/study_log_dirty.csv")
df

   id user_name subject             start_at               end_at
0   1     Alice      数学     2021/12/31 13:01     2021/12/31 13:31
1   2     Alice      情報  2021-12-31 13:50:08  2021-12-31 14:28:10
2   3       Bob      国語      20211231 232230      20211231 234221

In [3]:
df.dtypes

id           int64
user_name      str
subject        str
start_at       str
end_at         str
dtype: object

In [4]:
df["start_at"] = pd.to_datetime(
    df["start_at"],
    format="mixed",
)
df

   id user_name subject            start_at               end_at
0   1     Alice      数学 2021-12-31 13:01:00     2021/12/31 13:31
1   2     Alice      情報 2021-12-31 13:50:08  2021-12-31 14:28:10
2   3       Bob      国語 2021-12-31 23:22:30      20211231 234221

In [7]:
df["end_at"] = pd.to_datetime(
    df["end_at"],
    format="mixed",
)
df

   id user_name subject            start_at              end_at
0   1     Alice      数学 2021-12-31 13:01:00 2021-12-31 13:31:00
1   2     Alice      情報 2021-12-31 13:50:08 2021-12-31 14:28:10
2   3       Bob      国語 2021-12-31 23:22:30 2021-12-31 23:42:21

In [8]:
df.dtypes

id                    int64
user_name               str
subject                 str
start_at     datetime64[us]
end_at       datetime64[us]
dtype: object

In [9]:
df["start_at"] = pd.to_datetime(
    df["start_at"],
    format="mixed",
    errors="coerce",
)

In [10]:
df["end_at"] = pd.to_datetime(
    df["end_at"],
    format="mixed",
    errors="corece",
)

In [11]:
df["study_minutes"] = (
    df["end_at"] - df["start_at"]
).dt.total_seconds() / 60

In [12]:
df

   id user_name subject            start_at              end_at  study_minutes
0   1     Alice      数学 2021-12-31 13:01:00 2021-12-31 13:31:00      30.000000
1   2     Alice      情報 2021-12-31 13:50:08 2021-12-31 14:28:10      38.033333
2   3       Bob      国語 2021-12-31 23:22:30 2021-12-31 23:42:21      19.850000

In [14]:
df["study_minutes"] = df["study_minutes"].round(0).astype(int)

In [15]:
df

,id,user_name,subject,start_at,end_at,study_minutes,stury_minutes
0,1,Alice,数学,2021-12-31 13:01:00,2021-12-31 13:31:00,30,30
1,2,Alice,情報,2021-12-31 13:50:08,2021-12-31 14:28:10,38,38
2,3,Bob,国語,2021-12-31 23:22:30,2021-12-31 23:42:21,20,20

In [16]:
df.drop(columns=["stury_minutes"], inplace=True)

In [17]:
df

   id user_name subject            start_at              end_at  study_minutes
0   1     Alice      数学 2021-12-31 13:01:00 2021-12-31 13:31:00             30
1   2     Alice      情報 2021-12-31 13:50:08 2021-12-31 14:28:10             38
2   3       Bob      国語 2021-12-31 23:22:30 2021-12-31 23:42:21             20

In [18]:
df.columns

Index(['id', 'user_name', 'subject', 'start_at', 'end_at', 'study_minutes'], dtype='str')

In [19]:
df["start_date"] = df["start_at"].dt.date

In [20]:
df

,id,user_name,subject,start_at,end_at,study_minutes,start_date
0,1,Alice,数学,2021-12-31 13:01:00,2021-12-31 13:31:00,30,2021-12-31
1,2,Alice,情報,2021-12-31 13:50:08,2021-12-31 14:28:10,38,2021-12-31
2,3,Bob,国語,2021-12-31 23:22:30,2021-12-31 23:42:21,20,2021-12-31

In [21]:
df["start_month"] = df["start_at"].dt.to_period("M").astype(str)

In [22]:
df

,id,user_name,subject,start_at,end_at,study_minutes,start_date,start_month
0,1,Alice,数学,2021-12-31 13:01:00,2021-12-31 13:31:00,30,2021-12-31,2021-12
1,2,Alice,情報,2021-12-31 13:50:08,2021-12-31 14:28:10,38,2021-12-31,2021-12
2,3,Bob,国語,2021-12-31 23:22:30,2021-12-31 23:42:21,20,2021-12-31,2021-12

In [23]:
df_summary = df.groupby(
    ["start_month", "subject"],
    as_index=False,
)["study_minutes"].sum()

In [24]:
df_summary

  start_month subject  study_minutes
0     2021-12      国語             20
1     2021-12      情報             38
2     2021-12      数学             30