###### 129_5_add_top3_rank

In [1]:
#cell1
import pandas as pd

In [3]:
df = pd.DataFrame(
    [
        ["Alice", "国語", 92],
        ["Alice", "数学", 72],
        ["Bob", "国語", 65],
        ["Bob", "数学", 92],
    ],
    columns=[
        "Name",
        "Subject",
        "Point",
    ],
)
df

    Name Subject  Point
0  Alice      国語     92
1  Alice      数学     72
2    Bob      国語     65
3    Bob      数学     92

In [4]:
#cell3
top3_index = df["Point"].nlargest(3).index
top3_index

Index([0, 3, 1], dtype='int64')

In [5]:
df.loc[
    top3_index,
    "Rank",
] = [
    1,
    2,
    3,
]
df

    Name Subject  Point  Rank
0  Alice      国語     92   1.0
1  Alice      数学     72   3.0
2    Bob      国語     65   NaN
3    Bob      数学     92   2.0