###### 128_4_melt_wide_to_long

In [4]:
import pandas as pd

In [5]:
index = pd.Index(["Alice", "Bob"], name="Name")
columns = pd.Index(["国語", "数学"], name="Subject")
data = [[80, 72,], [65, 92]]

df = pd.DataFrame(data, index=index, columns=columns)
df

Subject  国語  数学
Name
Alice    80  72
Bob      65  92

In [7]:
dfm = df.melt(value_name="Point", ignore_index=False)
dfm

      Subject  Point
Name
Alice      国語     80
Bob        国語     65
Alice      数学     72
Bob        数学     92

In [8]:
df_result = dfm.reset_index()
df_result

    Name Subject  Point
0  Alice      国語     80
1    Bob      国語     65
2  Alice      数学     72
3    Bob      数学     92