###### 129_3_quality_fill_from_other_column_practice

In [1]:
#cell1
import numpy as np
import pandas as pd

In [2]:
df = pd.DataFrame(
    [
        ["D001", "J69P", "MELMB", "L250601-A", "コイル", 1, np.nan, 300],
        ["D002", "J69P", "WSE", "L250601-B", "Buck-IC", 2, 2, 280],
        ["D003", "310D", "GSE", "L250602-C", "はんだ", 1, np.nan, 250],
        ["D004", "J69P", "MELMB", "L250603-D", "コイル", 3, 4, 310],
        ["D005", "310D", "WSE", "L250604-E", "NTF", 0, np.nan, 260],
        ["D006", "J69P", "GSE", "L250605-F", "コイル", 2, np.nan, 290],
        ["D007", "310D", "MELMB", "L250606-G", "はんだ", 1, 1, 240],
        ["D008", "J69P", "WSE", "L250607-H", "Buck-IC", 1, np.nan, 270],
    ],
    columns=[
        "defect_id",
        "project",
        "site",
        "lot_no",
        "defect_category",
        "first_report_defect_qty",
        "confirmed_defect_qty",
        "inspection_qty",
    ],
)
df

,defect_id,project,site,lot_no,defect_category,first_report_defect_qty,confirmed_defect_qty,inspection_qty
0,D001,J69P,MELMB,L250601-A,コイル,1,NaN,300
1,D002,J69P,WSE,L250601-B,Buck-IC,2,2.0,280
2,D003,310D,GSE,L250602-C,はんだ,1,NaN,250
3,D004,J69P,MELMB,L250603-D,コイル,3,4.0,310
4,D005,310D,WSE,L250604-E,NTF,0,NaN,260
5,D006,J69P,GSE,L250605-F,コイル,2,NaN,290
6,D007,310D,MELMB,L250606-G,はんだ,1,1.0,240
7,D008,J69P,WSE,L250607-H,Buck-IC,1,NaN,270

In [3]:
#cell3
df_work = df.copy()
df_work

,defect_id,project,site,lot_no,defect_category,first_report_defect_qty,confirmed_defect_qty,inspection_qty
0,D001,J69P,MELMB,L250601-A,コイル,1,NaN,300
1,D002,J69P,WSE,L250601-B,Buck-IC,2,2.0,280
2,D003,310D,GSE,L250602-C,はんだ,1,NaN,250
3,D004,J69P,MELMB,L250603-D,コイル,3,4.0,310
4,D005,310D,WSE,L250604-E,NTF,0,NaN,260
5,D006,J69P,GSE,L250605-F,コイル,2,NaN,290
6,D007,310D,MELMB,L250606-G,はんだ,1,1.0,240
7,D008,J69P,WSE,L250607-H,Buck-IC,1,NaN,270

In [4]:
df_work["confirmed_defect_qty_filled"] = df_work["confirmed_defect_qty"].fillna(
    df_work["first_report_defect_qty"]
)
df_work

,defect_id,project,site,lot_no,defect_category,first_report_defect_qty,confirmed_defect_qty,inspection_qty,confirmed_defect_qty_filled
0,D001,J69P,MELMB,L250601-A,コイル,1,NaN,300,1.0
1,D002,J69P,WSE,L250601-B,Buck-IC,2,2.0,280,2.0
2,D003,310D,GSE,L250602-C,はんだ,1,NaN,250,1.0
3,D004,J69P,MELMB,L250603-D,コイル,3,4.0,310,4.0
4,D005,310D,WSE,L250604-E,NTF,0,NaN,260,0.0
5,D006,J69P,GSE,L250605-F,コイル,2,NaN,290,2.0
6,D007,310D,MELMB,L250606-G,はんだ,1,1.0,240,1.0
7,D008,J69P,WSE,L250607-H,Buck-IC,1,NaN,270,1.0

In [5]:
#cell5
df_check_fill = df_work[
    [
        "defect_id",
        "project",
        "site",
        "defect_category",
        "first_report_defect_qty",
        "confirmed_defect_qty",
        "confirmed_defect_qty_filled",
    ]
].copy()

df_check_fill

,defect_id,project,site,defect_category,first_report_defect_qty,confirmed_defect_qty,confirmed_defect_qty_filled
0,D001,J69P,MELMB,コイル,1,NaN,1.0
1,D002,J69P,WSE,Buck-IC,2,2.0,2.0
2,D003,310D,GSE,はんだ,1,NaN,1.0
3,D004,J69P,MELMB,コイル,3,4.0,4.0
4,D005,310D,WSE,NTF,0,NaN,0.0
5,D006,J69P,GSE,コイル,2,NaN,2.0
6,D007,310D,MELMB,はんだ,1,1.0,1.0
7,D008,J69P,WSE,Buck-IC,1,NaN,1.0

In [7]:
df_work["defect_rate"] = (
    df_work["confirmed_defect_qty_filled"] / df_work["inspection_qty"]
)
df_work

,defect_id,project,site,lot_no,defect_category,first_report_defect_qty,confirmed_defect_qty,inspection_qty,confirmed_defect_qty_filled,defect_rate
0,D001,J69P,MELMB,L250601-A,コイル,1,NaN,300,1.0,0.003333
1,D002,J69P,WSE,L250601-B,Buck-IC,2,2.0,280,2.0,0.007143
2,D003,310D,GSE,L250602-C,はんだ,1,NaN,250,1.0,0.004000
3,D004,J69P,MELMB,L250603-D,コイル,3,4.0,310,4.0,0.012903
4,D005,310D,WSE,L250604-E,NTF,0,NaN,260,0.0,0.000000
5,D006,J69P,GSE,L250605-F,コイル,2,NaN,290,2.0,0.006897
6,D007,310D,MELMB,L250606-G,はんだ,1,1.0,240,1.0,0.004167
7,D008,J69P,WSE,L250607-H,Buck-IC,1,NaN,270,1.0,0.003704

In [8]:
df_rate_sort = df_work.sort_values(
    "defect_rate",
    ascending=False,
)
df_rate_sort

,defect_id,project,site,lot_no,defect_category,first_report_defect_qty,confirmed_defect_qty,inspection_qty,confirmed_defect_qty_filled,defect_rate
3,D004,J69P,MELMB,L250603-D,コイル,3,4.0,310,4.0,0.012903
1,D002,J69P,WSE,L250601-B,Buck-IC,2,2.0,280,2.0,0.007143
5,D006,J69P,GSE,L250605-F,コイル,2,NaN,290,2.0,0.006897
6,D007,310D,MELMB,L250606-G,はんだ,1,1.0,240,1.0,0.004167
2,D003,310D,GSE,L250602-C,はんだ,1,NaN,250,1.0,0.004000
7,D008,J69P,WSE,L250607-H,Buck-IC,1,NaN,270,1.0,0.003704
0,D001,J69P,MELMB,L250601-A,コイル,1,NaN,300,1.0,0.003333
4,D005,310D,WSE,L250604-E,NTF,0,NaN,260,0.0,0.000000

In [9]:
#cell7

df_rate_sort = df_work.sort_values(
    "defect_rate",
    ascending=False,
)
df_rate_sort

,defect_id,project,site,lot_no,defect_category,first_report_defect_qty,confirmed_defect_qty,inspection_qty,confirmed_defect_qty_filled,defect_rate
3,D004,J69P,MELMB,L250603-D,コイル,3,4.0,310,4.0,0.012903
1,D002,J69P,WSE,L250601-B,Buck-IC,2,2.0,280,2.0,0.007143
5,D006,J69P,GSE,L250605-F,コイル,2,NaN,290,2.0,0.006897
6,D007,310D,MELMB,L250606-G,はんだ,1,1.0,240,1.0,0.004167
2,D003,310D,GSE,L250602-C,はんだ,1,NaN,250,1.0,0.004000
7,D008,J69P,WSE,L250607-H,Buck-IC,1,NaN,270,1.0,0.003704
0,D001,J69P,MELMB,L250601-A,コイル,1,NaN,300,1.0,0.003333
4,D005,310D,WSE,L250604-E,NTF,0,NaN,260,0.0,0.000000

In [10]:
df_work["check_result"] = "通常"

df_work.loc[
    df_work["defect_rate"] > 0.005,
    "check_result",
] = "要確認"

df_work

,defect_id,project,site,lot_no,defect_category,first_report_defect_qty,confirmed_defect_qty,inspection_qty,confirmed_defect_qty_filled,defect_rate,check_result
0,D001,J69P,MELMB,L250601-A,コイル,1,NaN,300,1.0,0.003333,通常
1,D002,J69P,WSE,L250601-B,Buck-IC,2,2.0,280,2.0,0.007143,要確認
2,D003,310D,GSE,L250602-C,はんだ,1,NaN,250,1.0,0.004000,通常
3,D004,J69P,MELMB,L250603-D,コイル,3,4.0,310,4.0,0.012903,要確認
4,D005,310D,WSE,L250604-E,NTF,0,NaN,260,0.0,0.000000,通常
5,D006,J69P,GSE,L250605-F,コイル,2,NaN,290,2.0,0.006897,要確認
6,D007,310D,MELMB,L250606-G,はんだ,1,1.0,240,1.0,0.004167,通常
7,D008,J69P,WSE,L250607-H,Buck-IC,1,NaN,270,1.0,0.003704,通常

In [11]:
df_need_check = df_work[
    df_work["check_result"] == "要確認"
].copy()
df_need_check

,defect_id,project,site,lot_no,defect_category,first_report_defect_qty,confirmed_defect_qty,inspection_qty,confirmed_defect_qty_filled,defect_rate,check_result
1,D002,J69P,WSE,L250601-B,Buck-IC,2,2.0,280,2.0,0.007143,要確認
3,D004,J69P,MELMB,L250603-D,コイル,3,4.0,310,4.0,0.012903,要確認
5,D006,J69P,GSE,L250605-F,コイル,2,NaN,290,2.0,0.006897,要確認