###### フォルダー名：128_3_quality_pivot_total_check_practice
###### ファイル名：quality_pivot_total_check_practice.ipynb

In [5]:
import pandas as pd

In [6]:
df_total_sort = pd.DataFrame(
    [
        [12, 32, 9, 53],
        [18, 25, 7, 50],
        [8, 11, 4, 23],
    ],
    columns=[
        "melmb",
        "wse",
        "gse",
        "total",
    ],
    index=[
        "LCM-B",
        "LCM-A",
        "LCM-D",
    ],
)
df_total_sort

       melmb  wse  gse  total
LCM-B     12   32    9     53
LCM-A     18   25    7     50
LCM-D      8   11    4     23

In [7]:
df_total_sort["check_level"] = "通常確認"
df_total_sort

       melmb  wse  gse  total check_level
LCM-B     12   32    9     53        通常確認
LCM-A     18   25    7     50        通常確認
LCM-D      8   11    4     23        通常確認

In [10]:
df_total_sort.loc[df_total_sort["total"] >= 40, "check_level"] = "重点確認"
df_total_sort

       melmb  wse  gse  total check_level comment
LCM-B     12   32    9     53        重点確認    通常監視
LCM-A     18   25    7     50        重点確認    通常監視
LCM-D      8   11    4     23        通常確認    通常監視

In [9]:
df_total_sort["comment"] = "通常監視"
df_total_sort

       melmb  wse  gse  total check_level comment
LCM-B     12   32    9     53        重点確認    通常監視
LCM-A     18   25    7     50        重点確認    通常監視
LCM-D      8   11    4     23        通常確認    通常監視

In [11]:
df_total_sort.loc[df_total_sort["check_level"] == "重点確認", "comment"] = "原因調査を優先"
df_total_sort

       melmb  wse  gse  total check_level  comment
LCM-B     12   32    9     53        重点確認  原因調査を優先
LCM-A     18   25    7     50        重点確認  原因調査を優先
LCM-D      8   11    4     23        通常確認     通常監視