###### 129_5_quality_group_top3_rank_practice

In [1]:
#cell 1
import pandas as pd

In [2]:
#cell 2
df = pd.DataFrame(
    [
        ["D001", "J69P", "MELMB", "コイル", 3, "調査中"],
        ["D002", "J69P", "WSE", "Buck-IC", 5, "対策検討中"],
        ["D003", "310D", "GSE", "コイル", 12, "暫定対策済"],
        ["D004", "310D", "MELMB", "はんだ", 2, "調査中"],
        ["D005", "J69P", "GSE", "コイル", 7, "調査中"],
        ["D006", "310D", "WSE", "コネクタ", 1, "完了"],
        ["D007", "J69P", "MELMB", "Buck-IC", 8, "調査中"],
        ["D008", "310D", "GSE", "コイル", 4, "対策検討中"],
        ["D009", "J69P", "GSE", "Buck-IC", 6, "調査中"],
        ["D010", "310D", "MELMB", "コイル", 5, "暫定対策済"],
        ["D011", "J69P", "WSE", "コイル", 9, "調査中"],
        ["D012", "310D", "GSE", "はんだ", 3, "完了"],
    ],
    columns=[
        "defect_id",
        "project",
        "site",
        "defect_category",
        "defect_qty",
        "status",
    ],
)
df

   defect_id project   site defect_category  defect_qty status
0       D001    J69P  MELMB             コイル           3    調査中
1       D002    J69P    WSE         Buck-IC           5  対策検討中
2       D003    310D    GSE             コイル          12  暫定対策済
3       D004    310D  MELMB             はんだ           2    調査中
4       D005    J69P    GSE             コイル           7    調査中
5       D006    310D    WSE            コネクタ           1     完了
6       D007    J69P  MELMB         Buck-IC           8    調査中
7       D008    310D    GSE             コイル           4  対策検討中
8       D009    J69P    GSE         Buck-IC           6    調査中
9       D010    310D  MELMB             コイル           5  暫定対策済
10      D011    J69P    WSE             コイル           9    調査中
11      D012    310D    GSE             はんだ           3     完了

In [3]:
#cell3
df_work = df.copy()
df_work

   defect_id project   site defect_category  defect_qty status
0       D001    J69P  MELMB             コイル           3    調査中
1       D002    J69P    WSE         Buck-IC           5  対策検討中
2       D003    310D    GSE             コイル          12  暫定対策済
3       D004    310D  MELMB             はんだ           2    調査中
4       D005    J69P    GSE             コイル           7    調査中
5       D006    310D    WSE            コネクタ           1     完了
6       D007    J69P  MELMB         Buck-IC           8    調査中
7       D008    310D    GSE             コイル           4  対策検討中
8       D009    J69P    GSE         Buck-IC           6    調査中
9       D010    310D  MELMB             コイル           5  暫定対策済
10      D011    J69P    WSE             コイル           9    調査中
11      D012    310D    GSE             はんだ           3     完了

In [ ]:
#cell 4
df_summary = df_work.groupby(
    [
        "site",
        "defect_category",
    ],
    as_index=False,
)["defect_qty"].sum()
df_summary

    site defect_category  defect_qty
0    GSE         Buck-IC           6
1    GSE             はんだ           3
2    GSE             コイル          23
3  MELMB         Buck-IC           8
4  MELMB             はんだ           2
5  MELMB             コイル           8
6    WSE         Buck-IC           5
7    WSE             コイル           9
8    WSE            コネクタ           1

In [5]:
#cell 5
df_summary = df_summary.rename(
    columns={
        "defect_qty": "total_defect_qty",
    }
)
df_summary

    site defect_category  total_defect_qty
0    GSE         Buck-IC                 6
1    GSE             はんだ                 3
2    GSE             コイル                23
3  MELMB         Buck-IC                 8
4  MELMB             はんだ                 2
5  MELMB             コイル                 8
6    WSE         Buck-IC                 5
7    WSE             コイル                 9
8    WSE            コネクタ                 1

In [7]:
#cell 6
top3_index = df_summary["total_defect_qty"].nlargest(3).index
top3_index

Index([2, 7, 3], dtype='int64')

In [8]:
#cell 7
df_summary.loc[
    top3_index,
    "priority_rank",
] = [
    1,
    2,
    3,
]
df_summary

    site defect_category  total_defect_qty  priority_rank
0    GSE         Buck-IC                 6            NaN
1    GSE             はんだ                 3            NaN
2    GSE             コイル                23            1.0
3  MELMB         Buck-IC                 8            3.0
4  MELMB             はんだ                 2            NaN
5  MELMB             コイル                 8            NaN
6    WSE         Buck-IC                 5            NaN
7    WSE             コイル                 9            2.0
8    WSE            コネクタ                 1            NaN

In [9]:
#cell 8
df_summary["priority_flag"] = "通常確認"

df_summary.loc[
    df_summary["priority_rank"].notna(),
    "priority_flag",
] = "重点確認"

df_summary

    site defect_category  total_defect_qty  priority_rank priority_flag
0    GSE         Buck-IC                 6            NaN          通常確認
1    GSE             はんだ                 3            NaN          通常確認
2    GSE             コイル                23            1.0          重点確認
3  MELMB         Buck-IC                 8            3.0          重点確認
4  MELMB             はんだ                 2            NaN          通常確認
5  MELMB             コイル                 8            NaN          通常確認
6    WSE         Buck-IC                 5            NaN          通常確認
7    WSE             コイル                 9            2.0          重点確認
8    WSE            コネクタ                 1            NaN          通常確認

In [11]:
#cell9

df_summary_sort = df_summary.sort_values(
    [
        "priority_rank",
        "total_defect_qty",
    ],
    ascending=[
        True,
        False,
    ],
)

df_summary_sort

    site defect_category  total_defect_qty  priority_rank priority_flag
2    GSE             コイル                23            1.0          重点確認
7    WSE             コイル                 9            2.0          重点確認
3  MELMB         Buck-IC                 8            3.0          重点確認
5  MELMB             コイル                 8            NaN          通常確認
0    GSE         Buck-IC                 6            NaN          通常確認
6    WSE         Buck-IC                 5            NaN          通常確認
1    GSE             はんだ                 3            NaN          通常確認
4  MELMB             はんだ                 2            NaN          通常確認
8    WSE            コネクタ                 1            NaN          通常確認

In [12]:
#cell10
df_priority = df_summary_sort[
    df_summary_sort["priority_flag"] == "重点確認"
].copy()
df_priority

    site defect_category  total_defect_qty  priority_rank priority_flag
2    GSE             コイル                23            1.0          重点確認
7    WSE             コイル                 9            2.0          重点確認
3  MELMB         Buck-IC                 8            3.0          重点確認

In [13]:
#cell 11
df_count_summary = pd.DataFrame(
    [
        ["集計後の組み合わせ数", len(df_summary)],
        ["重点確認件数", len(df_priority)],
        ["通常確認件数", len(df_summary) - len(df_priority)],
    ],
    columns=[
        "確認項目",
        "件数",
    ],
)
df_count_summary

         確認項目  件数
0  集計後の組み合わせ数   9
1      重点確認件数   3
2      通常確認件数   6