###### 131_3_practical_exclude_reason_answer.ipynb

In [2]:
import pandas as pd

In [3]:
pd.set_option("display.max_columns", None)

In [4]:
df_defect = pd.read_csv("dataset/defect_comment_reason.csv")
df_defect

   defect_id   site model occ_month defect_category                 comment
0       D001    SUS  J69P   2026-04             NTF      市場返却品を確認したが不具合再現せず
1       D002    SUS  J69P   2026-04         Buck-IC  TEST登録：Buck-IC焼損確認用データ
2       D003    WSE  310D   2026-05            Coil         コイル内部に鉄粉噛み込みを確認
3       D004    GSE  310D   2026-05            Coil            サンプル評価用として登録
4       D005  MELMB  J69P   2026-06             NTF          現品確認の結果、症状再現せず
5       D006    WSE  310D   2026-06            Coil            重複登録のため集計対象外
6       D007    SUS  J69P   2026-06         Buck-IC     Buck-ICのHS-FET損傷を確認
7       D008    GSE  310D   2026-06            Coil        確認用：検査条件変更前の仮データ
8       D009  MELMB  310D   2026-07            Coil        160Vインパルス検査で異常検出
9       D010    SUS  J69P   2026-07             NTF          test memo only
10      D011    WSE  310D   2026-07            Coil            転記ミスのため再登録予定
11      D012  MELMB  J69P   2026-07         Buck-IC       Buck-IC再発疑いとして調査中

In [5]:
#cell4
df_defect["exclude_reason"] = ""
df_defect

,defect_id,site,model,occ_month,defect_category,comment,exclude_reason
0,D001,SUS,J69P,2026-04,NTF,市場返却品を確認したが不具合再現せず,
1,D002,SUS,J69P,2026-04,Buck-IC,TEST登録：Buck-IC焼損確認用データ,
2,D003,WSE,310D,2026-05,Coil,コイル内部に鉄粉噛み込みを確認,
3,D004,GSE,310D,2026-05,Coil,サンプル評価用として登録,
4,D005,MELMB,J69P,2026-06,NTF,現品確認の結果、症状再現せず,
5,D006,WSE,310D,2026-06,Coil,重複登録のため集計対象外,
6,D007,SUS,J69P,2026-06,Buck-IC,Buck-ICのHS-FET損傷を確認,
7,D008,GSE,310D,2026-06,Coil,確認用：検査条件変更前の仮データ,
8,D009,MELMB,310D,2026-07,Coil,160Vインパルス検査で異常検出,
9,D010,SUS,J69P,2026-07,NTF,test memo only,
10,D011,WSE,310D,2026-07,Coil,転記ミスのため再登録予定,
11,D012,MELMB,J69P,2026-07,Buck-IC,Buck-IC再発疑いとして調査中,

In [6]:
df_defect.loc[
    df_defect["comment"].str.contains(
        "TEST",
        case=False,
        na=False,
    )
    & (df_defect["exclude_reason"] == ""),
    "exclude_reason",
] = "TESTデータ"
df_defect

,defect_id,site,model,occ_month,defect_category,comment,exclude_reason
0,D001,SUS,J69P,2026-04,NTF,市場返却品を確認したが不具合再現せず,
1,D002,SUS,J69P,2026-04,Buck-IC,TEST登録：Buck-IC焼損確認用データ,TESTデータ
2,D003,WSE,310D,2026-05,Coil,コイル内部に鉄粉噛み込みを確認,
3,D004,GSE,310D,2026-05,Coil,サンプル評価用として登録,
4,D005,MELMB,J69P,2026-06,NTF,現品確認の結果、症状再現せず,
5,D006,WSE,310D,2026-06,Coil,重複登録のため集計対象外,
6,D007,SUS,J69P,2026-06,Buck-IC,Buck-ICのHS-FET損傷を確認,
7,D008,GSE,310D,2026-06,Coil,確認用：検査条件変更前の仮データ,
8,D009,MELMB,310D,2026-07,Coil,160Vインパルス検査で異常検出,
9,D010,SUS,J69P,2026-07,NTF,test memo only,TESTデータ
10,D011,WSE,310D,2026-07,Coil,転記ミスのため再登録予定,
11,D012,MELMB,J69P,2026-07,Buck-IC,Buck-IC再発疑いとして調査中,

In [8]:
#cell6

df_defect.loc[
    df_defect["comment"].str.contains(
        "確認用",
        na=False,
    )
    & (df_defect["exclude_reason"] == ""),
    "exclude_reason",
] = "確認用データ"
df_defect

,defect_id,site,model,occ_month,defect_category,comment,exclude_reason
0,D001,SUS,J69P,2026-04,NTF,市場返却品を確認したが不具合再現せず,
1,D002,SUS,J69P,2026-04,Buck-IC,TEST登録：Buck-IC焼損確認用データ,TESTデータ
2,D003,WSE,310D,2026-05,Coil,コイル内部に鉄粉噛み込みを確認,
3,D004,GSE,310D,2026-05,Coil,サンプル評価用として登録,
4,D005,MELMB,J69P,2026-06,NTF,現品確認の結果、症状再現せず,
5,D006,WSE,310D,2026-06,Coil,重複登録のため集計対象外,
6,D007,SUS,J69P,2026-06,Buck-IC,Buck-ICのHS-FET損傷を確認,
7,D008,GSE,310D,2026-06,Coil,確認用：検査条件変更前の仮データ,確認用データ
8,D009,MELMB,310D,2026-07,Coil,160Vインパルス検査で異常検出,
9,D010,SUS,J69P,2026-07,NTF,test memo only,TESTデータ
10,D011,WSE,310D,2026-07,Coil,転記ミスのため再登録予定,
11,D012,MELMB,J69P,2026-07,Buck-IC,Buck-IC再発疑いとして調査中,

In [10]:
df_defect.loc[
    df_defect["comment"].str.contains(
    "サンプル",
    na=False,
    )
    & (df_defect["exclude_reason"] == ""),
    "exclude_reason"
] = "サンプル評価"
df_defect

,defect_id,site,model,occ_month,defect_category,comment,exclude_reason
0,D001,SUS,J69P,2026-04,NTF,市場返却品を確認したが不具合再現せず,
1,D002,SUS,J69P,2026-04,Buck-IC,TEST登録：Buck-IC焼損確認用データ,TESTデータ
2,D003,WSE,310D,2026-05,Coil,コイル内部に鉄粉噛み込みを確認,
3,D004,GSE,310D,2026-05,Coil,サンプル評価用として登録,サンプル評価
4,D005,MELMB,J69P,2026-06,NTF,現品確認の結果、症状再現せず,
5,D006,WSE,310D,2026-06,Coil,重複登録のため集計対象外,
6,D007,SUS,J69P,2026-06,Buck-IC,Buck-ICのHS-FET損傷を確認,
7,D008,GSE,310D,2026-06,Coil,確認用：検査条件変更前の仮データ,確認用データ
8,D009,MELMB,310D,2026-07,Coil,160Vインパルス検査で異常検出,
9,D010,SUS,J69P,2026-07,NTF,test memo only,TESTデータ
10,D011,WSE,310D,2026-07,Coil,転記ミスのため再登録予定,
11,D012,MELMB,J69P,2026-07,Buck-IC,Buck-IC再発疑いとして調査中,

In [11]:
#cell8
df_defect.loc[
    df_defect["comment"].str.contains(
        "重複",
        na=False,
    )
    & (df_defect["exclude_reason"] == ""),
    "exclude_reason",
] = "重複登録"
df_defect

,defect_id,site,model,occ_month,defect_category,comment,exclude_reason
0,D001,SUS,J69P,2026-04,NTF,市場返却品を確認したが不具合再現せず,
1,D002,SUS,J69P,2026-04,Buck-IC,TEST登録：Buck-IC焼損確認用データ,TESTデータ
2,D003,WSE,310D,2026-05,Coil,コイル内部に鉄粉噛み込みを確認,
3,D004,GSE,310D,2026-05,Coil,サンプル評価用として登録,サンプル評価
4,D005,MELMB,J69P,2026-06,NTF,現品確認の結果、症状再現せず,
5,D006,WSE,310D,2026-06,Coil,重複登録のため集計対象外,重複登録
6,D007,SUS,J69P,2026-06,Buck-IC,Buck-ICのHS-FET損傷を確認,
7,D008,GSE,310D,2026-06,Coil,確認用：検査条件変更前の仮データ,確認用データ
8,D009,MELMB,310D,2026-07,Coil,160Vインパルス検査で異常検出,
9,D010,SUS,J69P,2026-07,NTF,test memo only,TESTデータ
10,D011,WSE,310D,2026-07,Coil,転記ミスのため再登録予定,
11,D012,MELMB,J69P,2026-07,Buck-IC,Buck-IC再発疑いとして調査中,

In [14]:
df_defect.loc[
    df_defect["comment"].str.contains(
        "転記ミス",
        na=False,
    )
    & (df_defect["exclude_reason"] == ""),
    "exclude_reason",
] = "転記ミス"
df_defect

,defect_id,site,model,occ_month,defect_category,comment,exclude_reason
0,D001,SUS,J69P,2026-04,NTF,市場返却品を確認したが不具合再現せず,
1,D002,SUS,J69P,2026-04,Buck-IC,TEST登録：Buck-IC焼損確認用データ,TESTデータ
2,D003,WSE,310D,2026-05,Coil,コイル内部に鉄粉噛み込みを確認,
3,D004,GSE,310D,2026-05,Coil,サンプル評価用として登録,サンプル評価
4,D005,MELMB,J69P,2026-06,NTF,現品確認の結果、症状再現せず,
5,D006,WSE,310D,2026-06,Coil,重複登録のため集計対象外,重複登録
6,D007,SUS,J69P,2026-06,Buck-IC,Buck-ICのHS-FET損傷を確認,
7,D008,GSE,310D,2026-06,Coil,確認用：検査条件変更前の仮データ,確認用データ
8,D009,MELMB,310D,2026-07,Coil,160Vインパルス検査で異常検出,
9,D010,SUS,J69P,2026-07,NTF,test memo only,TESTデータ
10,D011,WSE,310D,2026-07,Coil,転記ミスのため再登録予定,転記ミス
11,D012,MELMB,J69P,2026-07,Buck-IC,Buck-IC再発疑いとして調査中,

In [15]:
df_actual = df_defect[
    df_defect["exclude_reason"] == ""
].copy()

df_actual

,defect_id,site,model,occ_month,defect_category,comment,exclude_reason
0,D001,SUS,J69P,2026-04,NTF,市場返却品を確認したが不具合再現せず,
2,D003,WSE,310D,2026-05,Coil,コイル内部に鉄粉噛み込みを確認,
4,D005,MELMB,J69P,2026-06,NTF,現品確認の結果、症状再現せず,
6,D007,SUS,J69P,2026-06,Buck-IC,Buck-ICのHS-FET損傷を確認,
8,D009,MELMB,310D,2026-07,Coil,160Vインパルス検査で異常検出,
11,D012,MELMB,J69P,2026-07,Buck-IC,Buck-IC再発疑いとして調査中,

In [17]:
df_excluded = df_defect[
    df_defect["exclude_reason"] != ""
].copy()
df_excluded

,defect_id,site,model,occ_month,defect_category,comment,exclude_reason
1,D002,SUS,J69P,2026-04,Buck-IC,TEST登録：Buck-IC焼損確認用データ,TESTデータ
3,D004,GSE,310D,2026-05,Coil,サンプル評価用として登録,サンプル評価
5,D006,WSE,310D,2026-06,Coil,重複登録のため集計対象外,重複登録
7,D008,GSE,310D,2026-06,Coil,確認用：検査条件変更前の仮データ,確認用データ
9,D010,SUS,J69P,2026-07,NTF,test memo only,TESTデータ
10,D011,WSE,310D,2026-07,Coil,転記ミスのため再登録予定,転記ミス

In [21]:
df_site_count = df_actual.groupby(
    "site",
    as_index=False,
)["defect_id"].count()

df_site_count

df_site_count = df_site_count.rename(
    columns={
        "defect_id": "actual_count",
    }
)
df_site_count

df_site_count = df_site_count.sort_values(
    ["actual_count", "site"],
    ascending=[False, True],
).reset_index(drop=True)

df_site_count

    site  actual_count
0  MELMB             3
1    SUS             2
2    WSE             1

In [25]:
df_reason_count = df_excluded.groupby(
    "exclude_reason",
    as_index=False,
)["defect_id"].count()
df_reason_count

df_reason_count = df_reason_count.rename(
    columns={
        "defect_id": "count",
    }
)
df_reason_count

df_reason_count = df_reason_count.sort_values(
    ["count","exclude_reason"],
    ascending=[False, True],
).reset_index(drop=True)

df_reason_count

  exclude_reason  count
0        TESTデータ      2
1         サンプル評価      1
2         確認用データ      1
3           転記ミス      1
4           重複登録      1