###### 129_4_drop_duplicates_basic

In [2]:
import pandas as pd

In [3]:
df = pd.DataFrame(
    [
        ["Alice", "国語", 87],
        ["Alice", "数学", 0],
        ["Bob", "国語", 65],
        ["Bob", "数学", 92],
        ["Alice", "数学", 72],
    ],
    columns=["Name", "Subject", "Point"],
)
df

    Name Subject  Point
0  Alice      国語     87
1  Alice      数学      0
2    Bob      国語     65
3    Bob      数学     92
4  Alice      数学     72

In [4]:
df_result = df.drop_duplicates(
    ["Name", "Subject"],
    keep="last",
)
df_result

    Name Subject  Point
0  Alice      国語     87
2    Bob      国語     65
3    Bob      数学     92
4  Alice      数学     72