In [1]:
import pandas as pd
df = pd.read_csv('dataset/fitness.csv', parse_dates=["開始日時"])
df.head()

                 開始日時     分   カテゴリー          コメント
0 2022-04-01 06:49:36   6.1   ストレッチ           NaN
1 2022-04-01 12:31:23  15.1     筋トレ           NaN
2 2022-04-01 18:32:54  18.4  ウォーキング     途中で蕁麻疹が出た
3 2022-04-02 06:21:42   9.6   ストレッチ           NaN
4 2022-04-02 12:16:24   4.2   ストレッチ  昨日の筋肉痛が残っている

In [2]:
df.shape

(62, 4)

In [3]:
df.isna().sum()

開始日時      0
分         1
カテゴリー     3
コメント     60
dtype: int64

In [4]:
df["カテゴリー"].unique()

array(['ストレッチ', '筋トレ', 'ウォーキング', nan], dtype=object)

In [5]:
df["分"].describe()

count     61.000000
mean      39.581967
std       89.137745
min        0.300000
25%        6.800000
50%       15.100000
75%       41.200000
max      681.200000
Name: 分, dtype: float64

In [6]:
df.sort_values("分").head()

                  開始日時    分   カテゴリー          コメント
49 2022-04-26 18:01:32  0.3  ウォーキング           NaN
15 2022-04-07 17:47:48  0.5     筋トレ           NaN
22 2022-04-13 06:41:36  4.0   ストレッチ           NaN
4  2022-04-02 12:16:24  4.2   ストレッチ  昨日の筋肉痛が残っている
30 2022-04-17 06:35:12  4.4   ストレッチ           NaN

In [7]:
df.sort_values("分", ascending=False).head())

SyntaxError: unmatched ')' (57882315.py, line 1)

In [8]:
df.sort_values("分", ascending=False).head()

                  開始日時      分   カテゴリー コメント
10 2022-04-05 06:19:36  681.2   ストレッチ  NaN
20 2022-04-11 06:23:54  123.4   ストレッチ  NaN
5  2022-04-02 13:01:12  123.2  ウォーキング  NaN
55 2022-04-29 08:24:57  121.6  ウォーキング  NaN
29 2022-04-16 18:08:36  113.1  ウォーキング  NaN

In [9]:
df.groupby("カテゴリー")["分"].describe()

        count       mean         std  min     25%    50%     75%    max
カテゴリー
ウォーキング   15.0  58.346667   37.325707  0.3  33.550  49.60  77.600  123.2
ストレッチ    29.0  34.148276  126.320238  4.0   6.000   6.90   8.000  681.2
筋トレ      14.0  34.785714   14.808618  0.5  29.975  35.25  42.325   63.4

In [11]:
import pandas as pd
df = pd.read_csv("dataset/fitness.csv", parse_dates=["開始日時"])
df.tail()

                  開始日時     分   カテゴリー コメント
57 2022-04-30 19:11:11  30.5     筋トレ  NaN
58 2022-04-10 18:00:00   NaN  ウォーキング  NaN
59 2022-04-12 18:00:00  25.0     NaN  NaN
60 2022-04-18 07:00:00  15.0     NaN  NaN
61 2022-04-27 07:30:00  22.0     NaN  NaN

In [12]:
df.shape

(62, 4)

In [13]:
df.isna().sum()

開始日時      0
分         1
カテゴリー     3
コメント     60
dtype: int64

In [14]:
df["カテゴリー"].unique()

array(['ストレッチ', '筋トレ', 'ウォーキング', nan], dtype=object)

In [15]:
df["カテゴリー"].value_counts()

カテゴリー
ストレッチ     29
ウォーキング    16
筋トレ       14
Name: count, dtype: int64

In [16]:
df["分"].describe()

count     61.000000
mean      39.581967
std       89.137745
min        0.300000
25%        6.800000
50%       15.100000
75%       41.200000
max      681.200000
Name: 分, dtype: float64

In [17]:
df.sort_values("分").head()

                  開始日時    分   カテゴリー          コメント
49 2022-04-26 18:01:32  0.3  ウォーキング           NaN
15 2022-04-07 17:47:48  0.5     筋トレ           NaN
22 2022-04-13 06:41:36  4.0   ストレッチ           NaN
4  2022-04-02 12:16:24  4.2   ストレッチ  昨日の筋肉痛が残っている
30 2022-04-17 06:35:12  4.4   ストレッチ           NaN

In [18]:
df.sort_values("分", ascending=False).head()

                  開始日時      分   カテゴリー コメント
10 2022-04-05 06:19:36  681.2   ストレッチ  NaN
20 2022-04-11 06:23:54  123.4   ストレッチ  NaN
5  2022-04-02 13:01:12  123.2  ウォーキング  NaN
55 2022-04-29 08:24:57  121.6  ウォーキング  NaN
29 2022-04-16 18:08:36  113.1  ウォーキング  NaN

In [19]:
df["カテゴリー"].unique()

array(['ストレッチ', '筋トレ', 'ウォーキング', nan], dtype=object)

In [20]:
df.groupby("カテゴリー")["分"].mean()

カテゴリー
ウォーキング    58.346667
ストレッチ     34.148276
筋トレ       34.785714
Name: 分, dtype: float64

In [21]:
df.groupby("カテゴリー")["分"].sum()

カテゴリー
ウォーキング    875.2
ストレッチ     990.3
筋トレ       487.0
Name: 分, dtype: float64

In [22]:
df.groupby("カテゴリー")["分"].count()

カテゴリー
ウォーキング    15
ストレッチ     29
筋トレ       14
Name: 分, dtype: int64