In [14]:
import pandas as pd

df = pd.read_csv("dataset/fitness.csv", parse_dates=["開始日時"])
df.head()

                 開始日時     分   カテゴリー          コメント
0 2022-04-01 06:49:36   6.1   ストレッチ           NaN
1 2022-04-01 12:31:23  15.1     筋トレ           NaN
2 2022-04-01 18:32:54  18.4  ウォーキング     途中で蕁麻疹が出た
3 2022-04-02 06:21:42   9.6   ストレッチ           NaN
4 2022-04-02 12:16:24   4.2   ストレッチ  昨日の筋肉痛が残っている

In [15]:
df[df["分"].isna() | df["カテゴリー"].isna()]

                  開始日時     分   カテゴリー コメント
58 2022-04-10 18:00:00   NaN  ウォーキング  NaN
59 2022-04-12 18:00:00  25.0     NaN  NaN
60 2022-04-18 07:00:00  15.0     NaN  NaN
61 2022-04-27 07:30:00  22.0     NaN  NaN

In [16]:
df = df[~(df["分"].isna() | df["カテゴリー"].isna())]
df.shape

(58, 4)

In [17]:
df =df[df["分"] >= 1]
df.shape

(56, 4)

In [18]:
df[df["カテゴリー"] == "ストレッチ"].sort_values("分", ascending=False).head()

                  開始日時      分  カテゴリー コメント
10 2022-04-05 06:19:36  681.2  ストレッチ  NaN
20 2022-04-11 06:23:54  123.4  ストレッチ  NaN
54 2022-04-29 06:07:06   10.3  ストレッチ  NaN
26 2022-04-15 06:28:41   10.2  ストレッチ  NaN
3  2022-04-02 06:21:42    9.6  ストレッチ  NaN

In [20]:
stretch_df = df[(df["カテゴリー"] == "ストレッチ") & (df["分"] < 30)]
stretch_df.head()

                 開始日時    分  カテゴリー          コメント
0 2022-04-01 06:49:36  6.1  ストレッチ           NaN
3 2022-04-02 06:21:42  9.6  ストレッチ           NaN
4 2022-04-02 12:16:24  4.2  ストレッチ  昨日の筋肉痛が残っている
6 2022-04-03 07:02:11  7.4  ストレッチ           NaN
8 2022-04-04 06:33:12  6.8  ストレッチ           NaN

In [21]:
valid_stretch_mean = stretch_df["分"].mean()
valid_stretch_mean

np.float64(6.877777777777777)

In [24]:
df.loc[(df["カテゴリー"] == "ストレッチ") & (df["分"] >= 30), "分"] = valid_stretch_mean

In [25]:
df[df["開始日時"] == "2022-04-05 06:19:36"]

                  開始日時         分  カテゴリー コメント
10 2022-04-05 06:19:36  6.877778  ストレッチ  NaN

In [26]:
df.groupby("カテゴリー")["分"].describe()

        count       mean        std   min    25%        50%   75%    max
カテゴリー
ウォーキング   14.0  62.492857  34.966830  18.4  35.95  50.300000  78.9  123.2
ストレッチ    29.0   6.877778   1.573289   4.0   6.00   6.877778   7.6   10.3
筋トレ      13.0  37.423077  11.492400  15.1  30.50  36.500000  42.7   63.4

In [28]:
import pandas as pd
df = pd.read_csv("dataset/fitness.csv", parse_dates=["開始日時"])
df.head()

                 開始日時     分   カテゴリー          コメント
0 2022-04-01 06:49:36   6.1   ストレッチ           NaN
1 2022-04-01 12:31:23  15.1     筋トレ           NaN
2 2022-04-01 18:32:54  18.4  ウォーキング     途中で蕁麻疹が出た
3 2022-04-02 06:21:42   9.6   ストレッチ           NaN
4 2022-04-02 12:16:24   4.2   ストレッチ  昨日の筋肉痛が残っている

In [31]:
df[df["分"].isna() | df["カテゴリー"].isna()]

                  開始日時     分   カテゴリー コメント
58 2022-04-10 18:00:00   NaN  ウォーキング  NaN
59 2022-04-12 18:00:00  25.0     NaN  NaN
60 2022-04-18 07:00:00  15.0     NaN  NaN
61 2022-04-27 07:30:00  22.0     NaN  NaN

In [34]:
df  = df[~(df["分"].isna() | df["カテゴリー"].isna())]
df.shape

(58, 4)

In [35]:
df = df[df["分"] >= 1]
df.shape

(56, 4)

In [40]:
df[df["カテゴリー"] == "ストレッチ"].sort_values("分", ascending=False).head()

                  開始日時      分  カテゴリー コメント
10 2022-04-05 06:19:36  681.2  ストレッチ  NaN
20 2022-04-11 06:23:54  123.4  ストレッチ  NaN
54 2022-04-29 06:07:06   10.3  ストレッチ  NaN
26 2022-04-15 06:28:41   10.2  ストレッチ  NaN
3  2022-04-02 06:21:42    9.6  ストレッチ  NaN

In [44]:
stretch_df = df[(df["カテゴリー"] == "ストレッチ") & (df["分"] < 30)]
stretch_df.head()

                 開始日時    分  カテゴリー          コメント
0 2022-04-01 06:49:36  6.1  ストレッチ           NaN
3 2022-04-02 06:21:42  9.6  ストレッチ           NaN
4 2022-04-02 12:16:24  4.2  ストレッチ  昨日の筋肉痛が残っている
6 2022-04-03 07:02:11  7.4  ストレッチ           NaN
8 2022-04-04 06:33:12  6.8  ストレッチ           NaN

In [45]:
valid_stretch_mean = stretch_df["分"].mean()

In [46]:
valid_stretch_mean

np.float64(6.877777777777777)

In [49]:
df.loc[(df["カテゴリー"] == "ストレッチ") & (df["分"] >= 30), "分"] = valid_stretch_mean

In [52]:
df.groupby("カテゴリー")["分"].describe()

        count       mean        std   min    25%        50%   75%    max
カテゴリー
ウォーキング   14.0  62.492857  34.966830  18.4  35.95  50.300000  78.9  123.2
ストレッチ    29.0   6.877778   1.573289   4.0   6.00   6.877778   7.6   10.3
筋トレ      13.0  37.423077  11.492400  15.1  30.50  36.500000  42.7   63.4

In [55]:
df[df["分"].isna()]

Empty DataFrame
Columns: [開始日時, 分, カテゴリー, コメント]
Index: []

In [59]:
df[df["カテゴリー"] == "金トレ"].sort_values("分", ascending=False).head()

Empty DataFrame
Columns: [開始日時, 分, カテゴリー, コメント]
Index: []