In [2]:
import pandas as pd
df = pd.read_csv("dataset/fitness_after.csv", index_col=0, parse_dates=["開始日時"])
df.head()

                 開始日時     分   カテゴリー          コメント
0 2022-04-01 06:49:36   6.1   ストレッチ           NaN
1 2022-04-01 12:31:23  15.1     筋トレ           NaN
2 2022-04-01 18:32:54  18.4  ウォーキング     途中で蕁麻疹が出た
3 2022-04-02 06:21:42   9.6   ストレッチ           NaN
4 2022-04-02 12:16:24   4.2   ストレッチ  昨日の筋肉痛が残っている

In [3]:
df = df.set_index("開始日時")
df.head()

                        分   カテゴリー          コメント
開始日時
2022-04-01 06:49:36   6.1   ストレッチ           NaN
2022-04-01 12:31:23  15.1     筋トレ           NaN
2022-04-01 18:32:54  18.4  ウォーキング     途中で蕁麻疹が出た
2022-04-02 06:21:42   9.6   ストレッチ           NaN
2022-04-02 12:16:24   4.2   ストレッチ  昨日の筋肉痛が残っている

In [4]:
summary_sr = df.resample("D")["分"].sum()
summary_df = summary_sr.to_frame()
summary_df.head()

               分
開始日時
2022-04-01  39.6
2022-04-02  66.2
2022-04-03  53.8
2022-04-04  41.0
2022-04-05   7.5

In [5]:
names = df["カテゴリー"].unique()
names

array(['ストレッチ', '筋トレ', 'ウォーキング'], dtype=object)

In [6]:
for category in names:
    selected_df = df[df["カテゴリー"] == category]
    summary_df[category] = selected_df.resample("D")["分"].sum()
summary_df.head()

               分  ストレッチ   筋トレ  ウォーキング
開始日時
2022-04-01  39.6    6.1  15.1    18.4
2022-04-02  66.2   13.8  20.0    32.4
2022-04-03  53.8   10.4  17.8    25.6
2022-04-04  41.0   11.7  29.3     0.0
2022-04-05   7.5    7.5   0.0     0.0

In [7]:
summary_df.tail()

                分  ストレッチ   筋トレ  ウォーキング
開始日時
2022-04-26   70.5    5.0   0.0    65.5
2022-04-27   46.4   13.5  32.9     0.0
2022-04-28   56.7    5.0  36.7    15.0
2022-04-29  131.9   10.3   NaN   121.6
2022-04-30    7.6    7.6   NaN     NaN

In [8]:
summary_df.loc[summary_df["筋トレ"].isna(), "筋トレ"] = 0
summary_df.loc[summary_df["ウォーキング"].isna(), "ウォーキング"] = 0
summary_df.tail()

                分  ストレッチ   筋トレ  ウォーキング
開始日時
2022-04-26   70.5    5.0   0.0    65.5
2022-04-27   46.4   13.5  32.9     0.0
2022-04-28   56.7    5.0  36.7    15.0
2022-04-29  131.9   10.3   0.0   121.6
2022-04-30    7.6    7.6   0.0     0.0

In [9]:
def is_ok(sr):
    return (sr["ストレッチ"] >= 5) & (sr["分"] >=45)
new_sr = summary_df.apply(is_ok, axis=1)
new_sr.head()

開始日時
2022-04-01    False
2022-04-02     True
2022-04-03     True
2022-04-04    False
2022-04-05    False
Freq: D, dtype: bool

In [10]:
summary_df["デイリー目標OK"] = new_sr
summary_df.head()

               分  ストレッチ   筋トレ  ウォーキング  デイリー目標OK
開始日時
2022-04-01  39.6    6.1  15.1    18.4     False
2022-04-02  66.2   13.8  20.0    32.4      True
2022-04-03  53.8   10.4  17.8    25.6      True
2022-04-04  41.0   11.7  29.3     0.0     False
2022-04-05   7.5    7.5   0.0     0.0     False

In [12]:
summary_df.index.name = "日付"
summary_df = summary_df.rename(columns={"分": "合計(分)", })
summary_df.head()

            合計(分)  ストレッチ   筋トレ  ウォーキング  デイリー目標OK
日付
2022-04-01   39.6    6.1  15.1    18.4     False
2022-04-02   66.2   13.8  20.0    32.4      True
2022-04-03   53.8   10.4  17.8    25.6      True
2022-04-04   41.0   11.7  29.3     0.0     False
2022-04-05    7.5    7.5   0.0     0.0     False