###### 131_1_practical_comment_mask_answer.ipynb

In [1]:
import pandas as pd

In [2]:
pd.set_option("display.max_columns", None)

In [3]:
df_defect = pd.DataFrame(
    [
        ["D-001", "SUS", "J69P", "6月にLCM-220で3件発生。1000台中3台で確認。"],
        ["D-002", "WSE", "310D", "2026/06/15にNo.5ラインで1件発生。"],
        ["D-003", "GSE", "J69P", "PY-110相当品で2回再現。電圧12V条件で確認。"],
        ["D-004", "MELMB", "310D", "現象再現せず。コメント内に数字なし。"],
        ["D-005", "SUS", "310D", "Lot202606-Aで5件確認。検査機160V条件で検出。"],
    ],
    columns=[
        "defect_id",
        "site",
        "model",
        "comment",
    ],
)
df_defect

  defect_id   site model                         comment
0     D-001    SUS  J69P    6月にLCM-220で3件発生。1000台中3台で確認。
1     D-002    WSE  310D        2026/06/15にNo.5ラインで1件発生。
2     D-003    GSE  J69P      PY-110相当品で2回再現。電圧12V条件で確認。
3     D-004  MELMB  310D              現象再現せず。コメント内に数字なし。
4     D-005    SUS  310D  Lot202606-Aで5件確認。検査機160V条件で検出。

In [4]:
df_work = df_defect.copy()

In [5]:
df_work

  defect_id   site model                         comment
0     D-001    SUS  J69P    6月にLCM-220で3件発生。1000台中3台で確認。
1     D-002    WSE  310D        2026/06/15にNo.5ラインで1件発生。
2     D-003    GSE  J69P      PY-110相当品で2回再現。電圧12V条件で確認。
3     D-004  MELMB  310D              現象再現せず。コメント内に数字なし。
4     D-005    SUS  310D  Lot202606-Aで5件確認。検査機160V条件で検出。

In [8]:
df_work["comment_public"] = df_work["comment"].str.replace(
    r"\d+",
    "#",
    regex=True,
)
df_work

,defect_id,site,model,comment,comment_public
0,D-001,SUS,J69P,6月にLCM-220で3件発生。1000台中3台で確認。,#月にLCM-#で#件発生。#台中#台で確認。
1,D-002,WSE,310D,2026/06/15にNo.5ラインで1件発生。,#/#/#にNo.#ラインで#件発生。
2,D-003,GSE,J69P,PY-110相当品で2回再現。電圧12V条件で確認。,PY-#相当品で#回再現。電圧#V条件で確認。
3,D-004,MELMB,310D,現象再現せず。コメント内に数字なし。,現象再現せず。コメント内に数字なし。
4,D-005,SUS,310D,Lot202606-Aで5件確認。検査機160V条件で検出。,Lot#-Aで#件確認。検査機#V条件で検出。

In [9]:
df_result = df_work[
    [
        "defect_id",
        "site",
        "model",
        "comment",
        "comment_public",
    ]
]
df_result

,defect_id,site,model,comment,comment_public
0,D-001,SUS,J69P,6月にLCM-220で3件発生。1000台中3台で確認。,#月にLCM-#で#件発生。#台中#台で確認。
1,D-002,WSE,310D,2026/06/15にNo.5ラインで1件発生。,#/#/#にNo.#ラインで#件発生。
2,D-003,GSE,J69P,PY-110相当品で2回再現。電圧12V条件で確認。,PY-#相当品で#回再現。電圧#V条件で確認。
3,D-004,MELMB,310D,現象再現せず。コメント内に数字なし。,現象再現せず。コメント内に数字なし。
4,D-005,SUS,310D,Lot202606-Aで5件確認。検査機160V条件で検出。,Lot#-Aで#件確認。検査機#V条件で検出。