In [7]:
import pandas as pd

In [8]:
df = pd.read_excel("input/exam.xlsx")

In [9]:
df[:4]

       名前  クラス  クラブ       実施月  科目
0     NaN  NaN  NaN       NaN  数学
1  松原　勇二郎    A  弓道部  201905.0  93
2  松原 勇二郎    A  弓道部  201908.0  69
3  吉澤 あきの    A  NaN  201905.0  71

In [10]:
df = pd.read_excel("input/exam.xlsx", header=1)
df[:4]

  Unnamed: 0 Unnamed: 1 Unnamed: 2  Unnamed: 3  数学
0     松原　勇二郎          A        弓道部      201905  93
1     松原 勇二郎          A        弓道部      201908  69
2     吉澤 あきの          A        NaN      201905  71
3     吉澤 あきの          A        NaN      201908  76

In [11]:
names = ["名前", "クラス", "クラブ", "実施月", "数学"]
df = pd.read_excel("input/exam.xlsx", header=1, names=names)
df[:4]

       名前 クラス  クラブ     実施月  数学
0  松原　勇二郎   A  弓道部  201905  93
1  松原 勇二郎   A  弓道部  201908  69
2  吉澤 あきの   A  NaN  201905  71
3  吉澤 あきの   A  NaN  201908  76