In [1]:
import pandas as pd

In [2]:
names = ["名前", "クラス", "クラブ", "実施月", "数学"]
df = pd.read_excel("input/exam.xlsx", header=1, names=names)
df[:4]

       名前 クラス  クラブ     実施月  数学
0  松原　勇二郎   A  弓道部  201905  93
1  松原 勇二郎   A  弓道部  201908  69
2  吉澤 あきの   A  NaN  201905  71
3  吉澤 あきの   A  NaN  201908  76

In [4]:
len(df["名前"].unique())

69

In [5]:
df["名前"] = df["名前"].str.replace("\u3000", " ", regex=False)

In [6]:
df[:4]

       名前 クラス  クラブ     実施月  数学
0  松原 勇二郎   A  弓道部  201905  93
1  松原 勇二郎   A  弓道部  201908  69
2  吉澤 あきの   A  NaN  201905  71
3  吉澤 あきの   A  NaN  201908  76

In [8]:
len(df["名前"].unique())

57

In [9]:
df["名前"] = df["名前"].str.replace("\u3000", " ", regex=False)
df["名前"].unique()[:5]

array(['松原 勇二郎', '吉澤 あきの', '平山 詩', '茂木 聖香', '澤田 佐千子'], dtype=object)